### ISSUE TITLE
Remove all attachments

### ISSUE THREAD

**Issue by playinteractive** [swiftmailer/swiftmailer#1001]
Hi,

Is there some way to remove all attachments from the $message?

Thanks

**Comment by sstok** [comment]
You can use the detach method https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Mime/SimpleMessage.php#L547 for this. But note that everything in the message is an attachment (including the body text itself).

You can have a look at https://github.com/rollerworks-graveyard/RollerworksMailBundle/blob/master/src/Rollerworks/Bundle/MailBundle/Decorator/AttachmentDecorator.php (project is end of life and properly doesn't work anymore but it should give you an idea how to work with attachments).

**Comment by playinteractive** [comment]
Hi sstok, thanks for your response, could you give us an example of this?

I attach the files this way:

$message->attach(Swift_Attachment::fromPath($file)->setFilename($new_filename));

Cheers!
