### ISSUE TITLE
Get path of attachment

### ISSUE THREAD

**Issue by iluuu1994** [swiftmailer/swiftmailer#1004]
We're currently spooling our emails and flushing it every 5 minutes. If the email has an attachment and that attachment is in our **tmp** folder we want to delete it. To find out where the path is stored we have to access the `body` of the `Swift_Mime_Attachment`.

Unfortunately, the `getBody` accessor automatically returns the result from the stream instead of returning the actual body instance.

https://github.com/swiftmailer/swiftmailer/blob/c4b87383073bc4aee7b3c9a9626cceb3f71803aa/lib/classes/Swift/Mime/SimpleMimeEntity.php#L359

Therefore we have to use the reflection API to get the actual body instance so we can extract the path of the file.

```php
$reflectionProperty = new \ReflectionProperty(\Swift_Mime_SimpleMimeEntity::class, '_body');
$reflectionProperty->setAccessible(true);
$byteStream = $reflectionProperty->getValue($attachment);

if ($byteStream instanceof \Swift_ByteStream_FileByteStream) {
    $path = $byteStream->getPath();
    // ...
}
```

I suggest implementing one of these options:

1. Add a `$readStream = true` parameter that can be set to `false`
2. A new getter that returns the `_body` directly

I can create a pull request. Any feedback?

| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| RFC?                | yes
| How used?           | Standalone
| Swiftmailer version | v5.4.8
| PHP version         | 7.0

**Comment by iluuu1994** [comment]
@fabpot Are you interested in this at all? If not I'll close this issue.

**Comment by iluuu1994** [comment]
This project should really have better support. I mean, how long does responding with a one liner take?

**Comment by kafene** [comment]
I'm trying to do this right now for logging purposes. Looks like I'm going to have to resort to reflection.

**Comment by parth391** [comment]
@fabpot This new feature request has due open for a long time. Please have a look at the ticket and pull request [1341](https://github.com/swiftmailer/swiftmailer/pull/1341).
