### ISSUE TITLE
The site documentation is unavailable

### ISSUE THREAD

**Issue by FinesseRus** [swiftmailer/swiftmailer#1008]
Both the link in [the repository readme](https://github.com/swiftmailer/swiftmailer) and the «documentation» link on [the site](https://swiftmailer.symfony.com) point to a 404 error page.

![2017-10-08 15 25 47](https://user-images.githubusercontent.com/9006227/31314180-04f193ee-ac3d-11e7-9939-dcd39abb00b5.png)

**Comment by Rotzbua** [comment]
https://swiftmailer.symfony.com/ works for me

**Comment by FinesseRus** [comment]
@Rotzbua Yes, the site works but there is [a 404 error](https://swiftmailer.symfony.com/docs/introduction.html) instead of the documentation on the site.

**Comment by Valkeru** [comment]
```
valkeru@valkeru-supcomp:~ [0 ✓] $ curl -IL https://swiftmailer.symfony.com/docs/introduction.html
HTTP/1.1 404 Not Found
Cache-Control: no-cache
Content-Type: text/html; charset=UTF-8
Date: Sun, 08 Oct 2017 05:09:41 GMT
X-Correlation-Id: hbyuyvx3djoiqv4zh6o3znlb
X-Sensiocloud-Cache: MISS
X-Sensiocloud-Cluster: ism4mega7wpx6-master-7rqtwti
X-Sensiocloud-Processor: ji7dtgjzh7xkw425ntkt5sr6me
X-Sensiocloud-Router: oaeikbbkwwyxwl3vacgi6sviqy
```

**Comment by Rotzbua** [comment]
As alternative:
Use the source of the website: https://github.com/swiftmailer/swiftmailer/tree/master/doc
Or for older versions the waybackmachine: https://archive.org/web/

**Comment by fabpot** [comment]
fixed now
