### ISSUE TITLE
Syntax Error unexpected '?' in EsmtpTransport.php on line 211

### ISSUE THREAD

**Issue by Omnea13** [swiftmailer/swiftmailer#1010]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| How used?           | Standalone
| Swiftmailer version | ^6.0
| PHP version         |  7.0.15

### Observed behaviour
**i use swift mailer for sending pdf by email used composer to download it, but it shows a syntax error in getSourceIp function:**
 syntax error, unexpected '?' in vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php on line 211

### Expected behaviour
it should send email with pdf attached (mpdf)
### Example
the code i used:
```

$transport = new Swift_SmtpTransport('localhost', 25);
$mailer = new Swift_Mailer($transport);
$attachment = new Swift_Attachment($content, 'filename.pdf', 'application/pdf');
$message = (new Swift_Message('Email subject'))
	->setFrom(['sender email' => 'sender name'])
	->setTo(['reciever email' => 'reciever name'])
	->setBody($msgBody) //msgBody html message
	->attach($attachment) //pdf attached
	;
$result = $mailer->send($message);

```

**Comment by xabbuh** [comment]
Are you sure that you got this error when using PHP 7? The null coalescing operator used on line 211 (see https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Transport/EsmtpTransport.php#L211) was introduced with PHP 7.0 (see http://php.net/manual/de/migration70.new-features.php#migration70.new-features.null-coalesce-op and https://3v4l.org/nCAW4).

**Comment by Omnea13** [comment]
Thanks for answering.
i found  that PHP version on my server is PHP 5 while on my local PHP 7,
is there a version of swiftMailer that supports PHP 5 ?

**Comment by xabbuh** [comment]
Swiftmailer 5 is still compatible with PHP 5.

**Comment by Omnea13** [comment]
thanks alot @xabbuh
