### ISSUE TITLE
PHP version support?

### ISSUE THREAD

**Issue by benkeen** [swiftmailer/swiftmailer#1011]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| RFC?                | ?
| How used?           | 
| Swiftmailer version | ?
| PHP version         | 5.3

What version of the script is compatible with PHP 5.3? I can't seem to find it in the documentation - it says the current release requires 7.0 but nothing about earlier versions. 

Thanks!

**Comment by benkeen** [comment]
Never mind - I found it by examining the composer.json files for each version. All the best.

**Comment by xabbuh** [comment]
@benkeen Note that you can also see this information on [packagist.org](https://packagist.org/packages/swiftmailer/swiftmailer) which might be more comfortable than switching between branches/tags on GitHub.

**Comment by benkeen** [comment]
@xabbuh - ah, much more convenient. Thanks very much!
