### ISSUE TITLE
SWIFTMAILER behind a proxy

### ISSUE THREAD

**Issue by zakioo** [swiftmailer/swiftmailer#1013]
Wich parameter should i use to specify that my webserver using swiftmailer is behind a proxy ?

**Comment by c960657** [comment]
You may need `Swift_Transport_AbstractSmtpTransport::setLocalDomain()`, if `$_SERVER['SERVER_NAME']` does not contain a public IP/hostname.

Apart from that, Swift Mailer does not need any special configuration when working behind an HTTP proxy.
