### ISSUE TITLE
Not working with php 5.6

### ISSUE THREAD

**Issue by ak868308** [swiftmailer/swiftmailer#1014]
PHP Parse Error 'yii\base\ErrorException' with message 'syntax error, unexpected '?'' 

in /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php:496

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

Here is the problem. This line is not working with php 5.6 I think
**return $priority ?? 3;**

**Comment by Rotzbua** [comment]
latest Swiftmailer do not work with old php versions <7.0 ....

**Comment by bboyzchecken** [comment]
me get This issue too :(

**Comment by xabbuh** [comment]
@bboyzchecken Which PHP version and which version of Swiftmailer do you use?

**Comment by bboyzchecken** [comment]
@xabbuh 5.6 && 7.0 My host can run both of version ,my issue is some people can send a mail but some people can't send a mail,on android are working but IOS some people can't send a mail

**Comment by bboyzchecken** [comment]
Here some Code

`<?php
require_once 'vendor/autoload.php';



// Create the Transport
$transport = (new Swift_SmtpTransport('mail', 25))
    ->setUsername('')
    ->setPassword('');

// Create the Mailer using your created Transport
$mailer = new Swift_Mailer($transport);

// Create a message
$message = (new Swift_Message('Name : ' . $_POST['fullname'] . 'Leave a Messages'))
    ->setFrom([$_POST['email_callback'] => $_POST['fullname']])
    ->setTo([email@email' => 'SYSTEM'])
    ->setBody($_POST['messages']);
$message->setContentType("text/html");
// Send the message
if ($mailer->send($message)) {
    ?>
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2 class="text-center">thank you for contact us</h2>
                <a href="index.html" class="btn btn-warning text-center">BackHOME</a>
            </div>
        </div>
    </div>
    <?php
} else {
    ?>
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2 class="text-center"> Can not send email</h2>
                <a href="index.html" class="btn btn-warning text-center">Back HOME</a>
            </div>
        </div>
    </div>
    <?php
}
?>`

**Comment by netbrothers-tr** [comment]
IMHO it's not a problem with swiftmailer but with the Yii framework. The dependencies there (in the application templates) do not seem to be consistent.

**Comment by MuhammadimYusoff** [comment]
So what can be done? is there any swiftmailer that support 5.6 or php <7.0?

**Comment by MuhammadimYusoff** [comment]
Okay I ve just done it.

just change the command line to earlier version:

composer require "swiftmailer/swiftmailer:^5.4.12"

from this web I choose the version on the right bottom side, v5.4.12.

https://packagist.org/packages/swiftmailer/swiftmailer#v6.0.0
