### ISSUE TITLE
Reply Back To email using SwiftMailer

### ISSUE THREAD

**Issue by AneebImamdin** [swiftmailer/swiftmailer#1017]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| RFC?                | yes/no
| How used?           | Standalone/Symfony/3party
| Swiftmailer version | ~5.3
| PHP version         | 7.0.10

### Observed behaviour
I used the library to send the emails to some specific email addresses. It works fine.

### Expected behaviour
I want to reply back to email. Can it be done using this library ? I read the documentation but could not find anything related to this .

**Comment by FinesseRus** [comment]
You can't. To do it you need to do some things by yourself:

1. Use another library to connect to an inbox by IMAP or POP and read a message you want to reply.
2. Parse the message data (from, subject, body) and insert it to a SwiftMailer message to make a reply message.
3. Send the reply message using SwiftMailer.
