### ISSUE TITLE
problem download swiftmailer with composer on drupal 8  

### ISSUE THREAD

**Issue by anibalsoul** [swiftmailer/swiftmailer#1019]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes/no
| RFC?                | yes/no
| How used?           | Standalone/Symfony/3party
| Swiftmailer version | ^6.0
| PHP version         | x.y.z

I make a website with drupal 8 and i need Swiftmailer but when i try to download the library with composer it's not working could anyone tell me why?

C:\Users\Ahmoho\Sites\devdesktop\asso2>composer require swiftmailer/swiftmailer
Using version ^6.0 for swiftmailer/swiftmailer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for egulias/email-validator (installed at 1.2.14, required as ^1.2) -> satisfiable by egulias/email-validator[1.2.14].
- swiftmailer/swiftmailer 6.0.x-dev requires egulias/email-validator ~2.0 -> satisfiable by egulias/email-validator[2.0.x-dev].
- swiftmailer/swiftmailer v6.0.0 requires egulias/email-validator ~2.0 -> satisfiable by egulias/email-validator[2.0.x-dev].
- swiftmailer/swiftmailer v6.0.1 requires egulias/email-validator ~2.0 -> satisfiable by egulias/email-validator[2.0.x-dev].
- swiftmailer/swiftmailer v6.0.2 requires egulias/email-validator ~2.0 -> satisfiable by egulias/email-validator[2.0.x-dev].
- Conclusion: don't install egulias/email-validator 2.0.x-dev
- Installation request for swiftmailer/swiftmailer ^6.0 -> satisfiable by swiftmailer/swiftmailer[6.0.x-dev, v6.0.0, v6.0.1, v6.0.2].

Installation failed, reverting ./composer.json to its original content.

**Comment by dahousecat** [comment]
The instructions to install swiftmailer simply say to run:

`composer require swiftmailer/swiftmailer`

Doing this results in the error OP posted.

We are not depending on any version of email validator. I don't even want email-validator - I just want to install swift mailer.

**Comment by xabbuh** [comment]
Please show the output of `composer show` before installing Swiftmailer.

**Comment by Rotzbua** [comment]
As mentioned in https://github.com/swiftmailer/swiftmailer/issues/1019#issuecomment-346026792

your drupal 8 require egulias/email-validator `1.x`
swiftmailer 6 require egulias/email-validator `2.x`

Version 2 can not be installed while version 1 is installed. Nothing else tells you the log in your fist post.

So conclusion: drupal 8 and swiftmailer 6 can not be used in one composer environment.

**Comment by dahousecat** [comment]
I ran `composer show` and it did indeed have the line:

`egulias/email-validator               1.2.14`

This was not in my composer.json, but upon further inspection was in the [composer.json in the core of Drupal](http://cgit.drupalcode.org/drupal/tree/core/composer.json). 

Until [this is updated](https://www.drupal.org/project/drupal/issues/2755401) the only solution appears to be to install an older version of swift mailer.

Looking at the [packagist page](https://packagist.org/packages/swiftmailer/swiftmailer#v5.4.8) the last (non dev) version without a requirement for version 2 of egulias/email-validator is 5.4.8 so running:

`composer require swiftmailer/swiftmailer:5.4.8`

Installed swiftmailer fine.

This has actually been reported as [an issue on the swiftmailer Drupal module issue queue](https://www.drupal.org/project/swiftmailer/issues/2891884) and I've made [a request](https://www.drupal.org/project/swiftmailer/issues/2891884#comment-12413500) that these instructions are included in the module readme file as to not catch more people out.
