### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by collinspamba** [swiftmailer/swiftmailer#1022]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | 3party
| Swiftmailer version | 6.0.3
| PHP version         | 5.6.32

### Observed behaviour
Parse error: syntax error, unexpected '?' in ../swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php on line 211

**Comment by Rotzbua** [comment]
No Bug.

> Swift Mailer is a component based mailing solution for **PHP 7**.

https://github.com/swiftmailer/swiftmailer/blob/master/README
