### ISSUE TITLE
Call to undefined method Swift_Transport_EsmtpTransport::newInstance()

### ISSUE THREAD

**Issue by john-dgi** [swiftmailer/swiftmailer#1029]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Standalone
| Swiftmailer version |6.0.2
| PHP version         | 7.2.0

### Observed behaviour

gets: Call to undefined method Swift_Transport_EsmtpTransport::newInstance()

### Expected behaviour

want to know why method not found

### Example
$transport = Swift_Transport_EsmtpTransport::newInstance('gmail-smtp-in.l.google.com', 587, 'tls') 
		->setStreamOptions(array('ssl' => array(
			'verify_peer' => false,
			'verify_peer_name' => false,
			'allow_self_signed' => true
		 )));

**Comment by Rotzbua** [comment]
Function is removed in 6.x https://github.com/swiftmailer/swiftmailer/blob/master/CHANGES
you have to change your code, see doc.
