### ISSUE TITLE
Expected response code 250 but got code "550", with message "550 5.7.60 SMTP; Client does not have permissions to send as this sender [MW2PR1901MB2155.namprd19.prod.outlook.com]

### ISSUE THREAD

**Issue by LakshmanKatragadda** [swiftmailer/swiftmailer#1030]
How used?           Laravel 
Swiftmailer version  v5.4.8
PHP version        v7.1.11

**### Observed behaviour**

Expected response code 250 but got code "550", with message "550 5.7.60 SMTP; Client does not have permissions to send as this sender [MW2PR1901MB2155.namprd19.prod.outlook.com]

**### Expected behaviour**

Mail should sent 

### Example

MAIL_DRIVER=smtp
MAIL_HOST=smtp.office365.com
MAIL_PORT=587
MAIL_USERNAME=****
MAIL_PASSWORD=******
MAIL_ENCRYPTION=tls

**Comment by Rotzbua** [comment]
Swiftm. works correctly. It is a microsoft problem.

Your acc do not have the perm. or you try something incorrect, eg. faking mail.

As smtp tells you:
> Client does not have permissions to send as this sender

**Comment by Rotzbua** [comment]
https://www.google.com/search?q=550+5.7.60+SMTP%3B+Client+does+not+have+permissions+to+send+as+this+sender
