### ISSUE TITLE
Wrong validation on attachments IDs.

### ISSUE THREAD

**Issue by ivopetkov** [swiftmailer/swiftmailer#1035]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | yes
| How used?           | Standalone
| Swiftmailer version | 6.0.2
| PHP version         | 7.1.0

### Observed behavior
When calling `->setId('file1.jpg')` on Swift_Attachment I got the following exception:
`Swift_RfcComplianceException: Invalid ID given <file1.jpg>`
Using `->setId('file1.jpg@example.com')` seems to work. I found an email validation for this value and I don't think this is in the specs.

### Expected behavior
`->setId('file1.jpg')` on Swift_Attachment should work.

### Example
$attachment = \Swift_Attachment::fromPath('/path/to/file1.jpg');
$attachment->setId('file1.jpg');

**Comment by Rotzbua** [comment]
Which rfc mention a content-id scheme which allow `file1.jpg` ?

Quick search tells me: `content-id    = url-addr-spec`
https://www.ietf.org/rfc/rfc2392.txt

**Comment by fabpot** [comment]
Closing as there is no more feedback from the reporter.
