### ISSUE TITLE
syntax error, unexpected '?'

### ISSUE THREAD

**Issue by abdulmanan7** [swiftmailer/swiftmailer#1036]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes

I got error every time i send mail 
Reference 
https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Mime/SimpleMessage.php
Function
`getPriority()`

```
 public function getPriority()
    {
        list($priority) = sscanf($this->getHeaderFieldModel('X-Priority'),
            '%[1-5]'
            );
 
        return $priority ?? 3;
    }
```

**Comment by xabbuh** [comment]
It looks like you are trying to use a Swiftmailer version that requires PHP 7 with PHP 5.

**Comment by abdulmanan7** [comment]
Exactly you are right .
Thanks
