### ISSUE TITLE
Error Parse EsmtpTransport.php on line 211

### ISSUE THREAD

**Issue by Flasker99** [swiftmailer/swiftmailer#1041]
Hello guys,

I need i help.

Parse error: syntax error, unexpected '?' in /home/seasonch/public_html/swiftmailer-master/lib/classes/Swift/Transport/EsmtpTransport.php on line 211

i have this configuration

<?php

require_once 'swiftmailer-master/lib/swift_required.php';

// Create the Transport
$transport = (new Swift_SmtpTransport('smtp.live.com', 25))
    ->setUsername('marcelo_bett@hotmail.com')
    ->setPassword('*******')
;

// Create the Mailer using your created Transport
$mailer = new Swift_Mailer($transport);

// Create a message
$message = (new Swift_Message('Wonderful Subject'))
->setFrom(['flasker99@gmail.com' => 'John Doe'])
->setTo(['marcelo_bett@hotmail.com', 'info@marcelobettencourt.pt' => 'A name'])
->setBody('Here is the message itself')
;

// Send the message
$result = $mailer->send($message);

?>

**Comment by fabpot** [comment]
This version of Swiftmailer needs PHP 7. Use an older version if you don't have PHP 7.
