### ISSUE TITLE
Please remove square brackets from $_domain on Swift_Transport_AbstractSmtpTransport

### ISSUE THREAD

**Issue by tarikhagustia** [swiftmailer/swiftmailer#1043]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| RFC?                | No
| How used?           | 3party
| Swiftmailer version | Latest
| PHP version         | 7.0

Hello, can you change default $_domain without `[ ]` ? because when using default domain, the email cannot receive by some users like google mail users.

thankyou

**Comment by tomzx** [comment]
What makes you say that the email cannot be received by some users like Google mail?

According to the [current implementation](https://github.com/swiftmailer/swiftmailer/blob/v6.0.2/lib/classes/Swift/Transport/AbstractSmtpTransport.php#L57-L58) which follows [RFC 5321, section 4.1.3](https://tools.ietf.org/html/rfc5321#section-4.1.3), ip v4/v6 addresses are supposed to be within brackets.

Thus, it seems it might either be an issue with your server configuration (Google rejecting your emails because you haven't setup SPF for instance).

**Comment by whfamily2006** [comment]
Mail sending works when I call using `\Artisan::call()` the command from a controller. So, the email is being sent if I use a browser, but not from command line.

**Comment by tarikhagustia** [comment]
If you are using laravel under 5.5 you need to upgrade swift mailer from 5.x to 6.x

**Comment by whfamily2006** [comment]
@tarikhagustia is this possible that we install swift mailer separately in our project using our project composer.json file and there is no conflict with laravel used version? 

I am using laravel v5.3.

**Comment by tarikhagustia** [comment]
@whfamily2006 you cannot upgrade swiftmailer from composer.json beacause laravel 5.3 need swiftmailer/swiftmailer: ~5.4. you must add some function in you Mail Listener if you using Mail Event.

try this on `build()` method

`
$mailTransport = app()->make('mailer')->getSwiftMailer()->getTransport();
       if ($mailTransport instanceof \Swift_SmtpTransport) {
           /** @var \Swift_SmtpTransport $mailTransport */
           $mailTransport->setLocalDomain('127.0.0.1');
       }
`

**Comment by tarikhagustia** [comment]
try to put that code before `Mail::send`, otherwise you should using artisan make mail `php artisan make:mail` see this link [https://laravel.com/docs/5.3/mail#generating-mailables](url).

on `setLocalDomain` you should pass your domain name in production

**Comment by whfamily2006** [comment]
@tarikhagustia this not worked for me, here is my code. 
```
$mailTransport = app()->make('mailer')->getSwiftMailer()->getTransport();
	if ($mailTransport instanceof \Swift_SmtpTransport) {
		$mailTransport->setLocalDomain(env('APP_URL'));
}

$this->line( "Start notify on fail");		
Mail::send('email-view',   ['data' => $params], function($message){
	$message->from( env('NOTIFICATION_EMAIL'), 'Company' )
		->to( env('whfamily2006@gmail.com') )
		->subject( 'Subject of my emal' );
});
$this->line( "Finish notify on fail");
```

**Comment by tarikhagustia** [comment]
@whfamily2006 try to use this package [https://github.com/oprudkyi/laravel-mail-logger](url) to debug your SMTP connection. run in browser and cli mode  and see what different between them.
