### ISSUE TITLE
Symfony dependacy injection not found Swift Mailert

### ISSUE THREAD

**Issue by vladanzivanovic** [swiftmailer/swiftmailer#1051]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | yes/no
| How used?           | Symfony
| Swiftmailer version | x.y.z
| PHP version         | 5.6.30

### Observed behaviour

Hi, 
suddenly I got this while sending the email. The path should be "/var/www/clients/client1/web10/web/", but what I can figure it's trying to load from "/var/www/clients/client1/web8/web".

I can't solve this. Could you help me with this bug

Warning: file_exists(): open_basedir restriction in effect. File(/var/www/clients/client1/web10/web/vendor/swiftmailer/swiftmailer/lib/classes/Swift/SmtpTransport.php) is not within the allowed path(s): (/var/www/clients/client1/web8/web:/var/www/clients/client1/web8/private:/var/www/clients/client1/web8/tmp:/var/www/dev.lea-shoes.com/web:/srv/www/dev.lea-shoes.com/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin:/dev/random:/dev/urandom) in /var/www/clients/client1/web10/web/vendor/swiftmailer/swiftmailer/lib/classes/Swift.php on line 52

**Comment by tomzx** [comment]
Looks like your configuration of PHP might have changed, more specifically take a look at http://php.net/manual/en/ini.core.php#ini.open-basedir.

This seems to be unrelated to swiftmailer but to your PHP configuration.

**Comment by fabpot** [comment]
Closing as there is no more feedback from the reporter.
