### ISSUE TITLE
Error sending mail to TLSv1.1 / TLSv1.2 mailserver

### ISSUE THREAD

**Issue by rtuk** [swiftmailer/swiftmailer#1052]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | 3party (Laravel)
| Swiftmailer version | 6.0.2
| PHP version         | 7.1..12

### Observed behaviour
Sending email with TLS encryption to SMTP server with TLSv1.0 disabled does not work

### Expected behaviour
Sending email with TLS encryption to SMTP server with TLSv1.0 disabled works

### Example
Use a smtp server with TLSv1.0 disabled

[file with the code that makes this impossible](https://github.com/swiftmailer/swiftmailer/blob/v6.0.2/lib/classes/Swift/Transport/StreamBuffer.php)

On line 94 STREAM_CRYPTO_METHOD_TLS_CLIENT is used, this is explicitly only TLSv1.0
Solution should probably be to introduce more encryptions options say SSL, TLS, TLSv1.1, TLSv1.2
and use the correct STREAM_CRYPTO_METHOD based on this selection

**Comment by Rotzbua** [comment]
I reported this a while ago: #933
Quick fix: #935

**Comment by fabpot** [comment]
closing as a duplicate
