### ISSUE TITLE
[BUG] Incompatible use of dynamic environment variables for encryption

### ISSUE THREAD

**Issue by homersimpsons** [swiftmailer/swiftmailer#1054]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Symfony
| Swiftmailer version | 5.4.9
| PHP version         | 7.1.11
| Symfony version | 3.4.4

### Observed behaviour
I this issue:
```Incompatible use of dynamic environment variables "MAILER_ENCRYPTION" found in parameters.```

### Expected behaviour
Nothing (According to the [doc](http://symfony.com/doc/3.4/reference/configuration/swiftmailer.html))

> The following options can be set via environment variables using the %env()% syntax: url, transport, username, password, host, port, timeout, source_ip, local_domain, ***encryption***, auth_mode

### Example
Just set 
```parameters.mailer_encryption: '%env(MAILER_ENCRYPTION)%'```
and
```swiftmailer.encryption: "%mailer_encryption%"```

(I don't know if the problem is in the doc or in SwiftMailer)
Thank you for this bundle 🥇

**Comment by Rotzbua** [comment]
Wrong place. Bundle can be found here: https://github.com/symfony/swiftmailer-bundle

**Comment by homersimpsons** [comment]
Okay, opened an issue there then :) Thank you
