### ISSUE TITLE
app.ERROR: Exception occurred while flushing email queue: Connection could not be established with host smtp.gmail.com

### ISSUE THREAD

**Issue by juliettelofaro** [swiftmailer/swiftmailer#1055]
I looked on every forum for an answer. So here is the problem :

I know my method to send mails works, my teacher did it on his computer and make it run in commandline (he doesn't use WAMP or any server). And i get the emails well on gmail. Now that i try the exact same code as him i don't get the mails. I use WAMP server. 
We tried to figured it out together but after a few hours nothings seems to work. My parameters.yml, config.yml and config_dev.yml are good. I put the Version 7 for PhP, changed nothing. Here is what i put in php.init : 

[mail function]
; For Win32 only.
; http://php.net/smtp
SMTP = smtp.gmail.com
; http://php.net/smtp-port
smtp_port = 465

changed nothing as well. I tried differents mail adresses, i enabled   less secure applications in gmail. I turned off avast. nothing..!
Should I use a plugin? Enable an extension in WAMP ? Put the website online ? 
thanks in advance

**Comment by tomzx** [comment]
This isn't related to swiftmailer. It seems that either you have no internet connection, or something is preventing your computer from accessing Gmail's servers (smtp.gmail.com).

Looking on google for `Connection could not be established with host`, there's a lot of entries on the topic, and more specifically in relation with swiftmailer. In all cases, it doesn't have to do with the library but either with the computer configuration or PHP's configuration. You'll have to provide more details, there should be the reason why it failed (connection refused, timed out, etc.) at the end of the error string.

```
Connection could not be established with host smtp.gmail.com [Connection timed out #110]
Connection could not be established with host smtp.gmail.com [Connection refused #111]
```

**Comment by juliettelofaro** [comment]
hey tomz thanks for the answer i find the solution : in config.yml i have
to add  "allow_self_signed: true" !

Il 3 feb 2018 11:15 PM, "tomzx" <notifications@github.com> ha scritto:

**Comment by MubeenTahirCheema** [comment]
we have configured our email server some times if the server is not responding due to any reason 
send() returns status 1 as email is been sent then after some time it gives exception
when i had saved it in db that email sent
