### ISSUE TITLE
syntax error, unexpected '?' in ..... \lib\classes\Swift\Mime\SimpleMessage.php on line 490

### ISSUE THREAD

**Issue by wbockhh** [swiftmailer/swiftmailer#1057]
Hello,
created according the guide on 
http://wiki.selfhtml.org/wiki/PHP/Tutorials/Formmailer-Advanced 
a contact-form.
Settings are:
 ... 
$Transport0 = Swift_MailTransport::newInstance(); 
$Transport = Swift_SmtpTransport::newInstance('mail.xyz.org',587,'tls' ) ->setUsername("mailadresse@xyz.org") 
->setPassword("secret") ; 
$mailer = Swift_Mailer::newInstance($Transport); 
...
Got the following error-message: 
syntax error, unexpected '?' in ..... \lib\classes\Swift\Mime\SimpleMessage.php on line 490

Can you help, how to settle this problem??
Thanks for your assistance in advance!

Regards

Wolfgang

**Comment by fabpot** [comment]
Apparently, you are not using PHP 7. Use an older version of Swiftmailer if you are using PHP 5.
