### ISSUE TITLE
Duplicated dots while using Sendmail transport in -t mode

### ISSUE THREAD

**Issue by kiler129** [swiftmailer/swiftmailer#1058]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Standalone/Symfony
| Swiftmailer version | 6.0.2
| PHP version         | 7.1.14
| PHP build  | `7.1.14-1+ubuntu17.10.1+deb.sury.org+1 (cli) (built: Feb  9 2018 09:34:03) ( NTS )`

### Observed behavior
Sending e-mail with line longer than 76 characters where dot is present as a 76th character produces duplicated dot while using Sendmail transport in `-t` mode.

SwiftMailer sends this raw payload to `sendmail` binary (I replaced some of the characters with dummy ones, but the length itself was preserved):
```
Message-ID: <c0233cb0dd6209286260d35e865e8a66@swift.generated>
Date: Thu, 22 Feb 2018 14:17:37 -0500
Subject: Test Email
From: xxxxxxxxxx@ccccc.com
To: aaaa.aaaaaaaaa@bbbbbbbb.com
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable
X-Origin-Id: c0233cb0dd6209286260d35e865e8a66@swift.generated
X-Mailer: XXXXX

http://example.tld/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=
..html
```

This problem is not present while working in `-bs` mode.

### Expected behavior
It looks like SwifMailer uses SMTP encoding in `-t` mode in the same way as it does for `-bs`. From what I see it's wrong. You can use `-i` flag but this is more a hack than a solution. While using `-t` mode alone dots should not be duplicated.

Problem is isolated to sendmail transport - SMTP itself is not affected by this.

### Example
```php
<?php

$sendmailTransport = new \Swift_SendmailTransport('/usr/sbin/sendmail -t');
$swift = new \Swift_Mailer($sendmailTransport);

$message = new \Swift_Message();
$message
    ->setFrom('xxxxxxxxxx@ccccc.com')
    ->addTo('aaaa.aaaaaaaaa@bbbbbbbb.com')
    ->setSubject('Test Email')
    ->setBody('http://example.tld/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.html', 'text/html')
;

echo $swift->send($message) . "\n";
```

**Comment by c960657** [comment]
Which Sendmail variant/clone are you using? AFAICT from reading the [source code for Postfix](https://github.com/vdukhovni/postfix/blob/master/postfix/src/sendmail/sendmail.c), dot-stuffing (the practice of adding an extra `.` at beginning of lines that begin with `.`) is not really supported in this mode, so there is no way to send an email with a line containing only `.` when using Postfix in `-t` mode.

[As mentioned in the inline documentation](https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Transport/SendmailTransport.php#L54), it is highly recommended to use `-i` together with `-t`.

**Comment by jannschu** [comment]
Had similar problems, found the issue  after reading the source and spotting this line:

https://github.com/swiftmailer/swiftmailer/blob/23e9ffaf6e8c716bce31bde1be708a405b1fbdf9/lib/classes/Swift/Transport/SendmailTransport.php#L120

I think this does not replace lines containing only a dot (as intended), but every line beginning with a dot.
