### ISSUE TITLE
Deconstruct a Swift_Message

### ISSUE THREAD

**Issue by rsantellan** [swiftmailer/swiftmailer#1072]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| RFC?                | no
| How used?           | Symfony 1.5
| Swiftmailer version | 5.4.9
| PHP version         | 7.1.15

### Change
It is possible to retrieve the basic information of the message with simple methods.
What I'm looking is after I created a Swift_Message take out the data for example:
- to
- cc
- bcc
- body
- attachments

**Comment by tomzx** [comment]
* to `$message->getTo()`
* cc `$message->getCc()`
* bcc `$message->getBcc()`
* body `$message->getBody()`
* attachments `$message->getChildren()`
