### ISSUE TITLE
Signed mail to bcc is not valid

### ISSUE THREAD

**Issue by CarstenKarbach** [swiftmailer/swiftmailer#1073]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Standalone
| Swiftmailer version | master, 6.2.1, 6.0.2, 5.4.9
| PHP version         | 7.1.5, 7.3.8

### Observed behaviour

I am trying to send a signed mail to a normal receiver (to) and to a Bcc receiver in a single mail. The message to the normal receiver is sent correctly. The message to Bcc contains an invalid content-type. This leads to an empty body displayed for the Bcc receiver.

### Expected behaviour

The message should be sent to the normal receiver (to) and to the Bcc receiver correctly. The problem seems to be caused by the Content-Type being set to "multipart/signed" in the mail to Bcc where Content-Type "text/plain" is expected. It looks like the message object is modified during the first sent, which causes the second sent mail to fail. If I leave the $toMail empty, the mail sent to Bcc is valid.

### Example

```php
<?php

$toMail = 'testmail@testmail.com';
$bccMail = 'testmail2@testmail.com';

$mail = (new Swift_Message())
->setFrom($toMail)
->setTo($toMail);

$mail->addBcc($bccMail);

$smimeSigner = new Swift_Signers_SMimeSigner();
$smimeSigner->setSignCertificate('certlocation',array('certlocation', 'password'));
$mail->attachSigner($smimeSigner);

$mail->setBody('Test body', 'text/plain');

$mailer = new Swift_Mailer(new Swift_SendmailTransport());
$mailer->send($mail);
?>
```

**Comment by TenMediaBln** [comment]
Same here. Any solution so far?

**Comment by CarstenKarbach** [comment]
This problem persists also for version v6.2.1.

**Comment by AlexH269** [comment]
I'm hitting the same issue.

**Comment by linushstge** [comment]
Still not valid in [6.2.5](https://github.com/swiftmailer/swiftmailer/releases/tag/v6.2.5)
