### ISSUE TITLE
getmypid() issue when sending email on shared hosting where its disabled

### ISSUE THREAD

**Issue by gathecageorge** [swiftmailer/swiftmailer#1075]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Standalone/Yii2
| Swiftmailer version | 5.x
| PHP version         | 5.6

### Observed behaviour
When sending email and the getmypid() function is disabled for example in a shared server, an exception is thrown and email not sent.

### Expected behaviour
It should be able to send the email even when getmypid() is disabled.

**Comment by Rotzbua** [comment]
Swiftmailer version 5.x is out of support.
getmypid is not used in 6.x, but you cant upgrade because it uses php7x -> you can not use swiftmailer
