### ISSUE TITLE
Process could not be started [The system cannot find the path specified. ]

### ISSUE THREAD

**Issue by chuksdsilent** [swiftmailer/swiftmailer#1080]
Am Using laravel
env

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=465
MAIL_USERNAME=******
MAIL_PASSWORD=********
MAIL_ENCRYPTION=tls

controller
 public function sendEmail(Request $request){
            Mail::to('chuksdsilent@gmail.com')->send(new Mailtrap()); 
            return response()->json(['message' => 'Request completed']);
 }

Swift_TransportException: Process could not be started [The system cannot find the path specified.
] in file C:\xampp\htdocs\tranxavApi\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php on line 299
Stack trace:
  1. Swift_TransportException-&gt;() C:\xampp\htdocs\tranxavApi\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php:299
  2. Swift_Transport_StreamBuffer-&gt;establishProcessConnection() C:\xampp\htdocs\tranxavApi\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php:58
  3. Swift_Transport_StreamBuffer-&gt;initialize() C:\xampp\htdocs\tranxavApi\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php:126
  4. Swift_Transport_AbstractSmtpTransport-&gt;start() C:\xampp\htdocs\tranxavApi\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\SendmailTransport.php:52
  5. Swift_Transport_SendmailTransport-&gt;start() C:\xampp\htdocs\tranxavApi\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mailer.php:67
  6. Swift_Mailer-&gt;send() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php:451
  7. Illuminate\Mail\Mailer-&gt;sendSwiftMessage() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php:235
  8. Illuminate\Mail\Mailer-&gt;send() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:221
  9. Illuminate\Support\Facades\Facade-&gt;__callStatic() C:\xampp\htdocs\tranxavApi\app\Http\Controllers\APIController.php:120
 10. App\Http\Controllers\APIController-&gt;sendEmail() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
 11. call_user_func_array() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
 12. Illuminate\Routing\Controller-&gt;callAction() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php:45
 13. Illuminate\Routing\ControllerDispatcher-&gt;dispatch() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Route.php:212
 14. Illuminate\Routing\Route-&gt;runController() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Route.php:169
 15. Illuminate\Routing\Route-&gt;run() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Router.php:658
 16. Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
 17. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php:41
 18. Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
 19. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 20. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php:57
 21. Illuminate\Routing\Middleware\ThrottleRequests-&gt;handle() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
 22. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 23. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:102
 24. Illuminate\Pipeline\Pipeline-&gt;then() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Router.php:660
 25. Illuminate\Routing\Router-&gt;runRouteWithinStack() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Router.php:635
 26. Illuminate\Routing\Router-&gt;runRoute() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Router.php:601
 27. Illuminate\Routing\Router-&gt;dispatchToRoute() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Router.php:590
 28. Illuminate\Routing\Router-&gt;dispatch() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:176
 29. Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
 30. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\xampp\htdocs\tranxavApi\vendor\fideloper\proxy\src\TrustProxies.php:56
 31. Fideloper\Proxy\TrustProxies-&gt;handle() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
 32. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 33. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:30
 34. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
 35. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 36. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:30
 37. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
 38. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 39. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php:27
 40. Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
 41. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 42. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php:46
 43. Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode-&gt;handle() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
 44. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
 45. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:102
 46. Illuminate\Pipeline\Pipeline-&gt;then() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:151
 47. Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter() C:\xampp\htdocs\tranxavApi\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:116
 48. Illuminate\Foundation\Http\Kernel-&gt;handle() C:\xampp\htdocs\tranxavApi\public\index.php:55

**Comment by tomzx** [comment]
Given you are on Windows and it appears that the default command is possibly `'/usr/sbin/sendmail -bs'`, then it is likely that the following method is failing because it cannot find sendmail. I'd suggest using the `mail` or `sendmail` drivers instead.

https://github.com/swiftmailer/swiftmailer/blob/c63b07e0968134b9bc522c16c521d38be0fabbb3/lib/classes/Swift/Transport/StreamBuffer.php#L283-L301

**Comment by payalord** [comment]
@tomzx 
> I'd suggest using the `mail` or `log` drivers.

This not working too. But yeah looks like this problem because of windows.

**Comment by slinstj** [comment]
Hi guys... Any workaround for this problem? Same problem here. Thnx

**Comment by tobiasgraeber** [comment]
Same error here! Any suggestions to fix this?

**Comment by slinstj** [comment]
I had this same problem and I couldn't find the reason since native php
mail function was working fine. So, I made a new component for my Yii2
project and removed SwiftMailer (at least till we have some senseful
information or a fix here). 👍🏼

Em ter, 21 de ago de 2018 03:20, Tobias Gräber <notifications@github.com>
escreveu:

**Comment by NahawandAli** [comment]
Hi, 
I have solved this issue by updating my windows.

**Comment by 9555643857** [comment]
same problem laravel 5.7

**Comment by 9555643857** [comment]
![mail](https://user-images.githubusercontent.com/17945452/53394192-74f38380-39c4-11e9-9ee9-92fe08f62e4b.PNG)

**Comment by Rajesh4307** [comment]
Same Error???

**Comment by Rajesh4307** [comment]
![image](https://user-images.githubusercontent.com/46595535/54526791-d8f2e180-499d-11e9-9614-9e845b8da6ff.png)

**Comment by codepopular** [comment]
i'm fetching same error in my website 
www.codepopular.com

**Comment by fazalhakim426** [comment]
i have the same problem.Any solution? please

**Comment by masoudashams** [comment]
same error

**Comment by dwainbeck** [comment]
I think the solution here is to update swiftmailer to version 6 or higher but I can't find instructions on how to do that.

**Comment by henrypandales** [comment]
any solution??

**Comment by JayenKB** [comment]
same error...
any solution?

**Comment by Rajesh4307** [comment]
whats error ??

**Comment by hamzakhan17826** [comment]
This is the php mailer issue. when i use smtp credential in localhost then it gave me error.
