### ISSUE TITLE
Swift Mailer session closed after xx hours

### ISSUE THREAD

**Issue by ychakroun** [swiftmailer/swiftmailer#1082]
When i'm executing command take several minutes few minutes, and i have an email sending at the bottom of the script, swift mailer work perfectly, but if the process take hours, i got this error:

[Swift_TransportException]                                                   
  Expected response code 250 but got code "451", with message "451 4.4.2 Time  
  out - closing connection. l131sm7924836wmb.36 - gsmtp 

Any idea please?
I'm using Symfony 3.2

Thanks

**Comment by tomzx** [comment]
Can you give a code snippet example to show how you use swift mailer?

Normally, I'd expect the connection to the remote server to be opened only for the duration of sending the email, then it is closed. If it times out, either the remote server is purposefully timing out your connections, or you are keeping the connection to that server open for too long.

**Comment by c960657** [comment]
[Swift_Transport::ping()](https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Transport.php#L35) might be helpful to you.

**Comment by fabpot** [comment]
Closing as there is no more activities.
