### ISSUE TITLE
Local Domains with example-.local cause "Invalid ID given" error

### ISSUE THREAD

**Issue by stevelandis** [swiftmailer/swiftmailer#1084]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Yii2
| Swiftmailer version | x.y.z
| PHP version         |7

### Observed behaviour
My local domains have a -.  http://example-.local.  
This causes an error in swiftmail.
Invalid ID given <cba811606712193a0d9729937af34e04@example-.local>

### Expected behaviour
mime_deps.php should not allow dash.  Line 16    ->asValue(!empty($_SERVER['SERVER_NAME']) && preg_replace('/(?:^\[)?[a-zA-Z0-9:\]_]+\.?/', '', $_SERVER['SERVER_NAME']) === '' ? $_SERVER['SERVER_NAME'] : 'swift.generated')

### Example
SERVER_NAME = example-.local and try sending an email.

**Comment by tomzx** [comment]
Given [RFC 1035 section #2.3.1](https://tools.ietf.org/html/rfc1035#section-2.3.1), it would seem that a label (or more specifically in this case, a subdomain of `local`) should not end with an hyphen.

> The labels must follow the rules for ARPANET host names.  They must start with a letter, end with a letter or digit, and have as interior characters only letters, digits, and hyphen.  There are also some restrictions on the length.  Labels must be 63 characters or less.

**Comment by stevelandis** [comment]
If domain is invalid it should return "swift.generated" ?
