### ISSUE TITLE
Swift_RFC ComplianceException' with message. Address in mailbox given does not comply with RFC 2822.3.6.2.

### ISSUE THREAD

**Issue by jamesyeobh** [swiftmailer/swiftmailer#1086]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| RFC?                | yes
| How used?           | Standalone
| Swiftmailer version | x.y.z
| PHP version         | x.y.z

### Observed behaviour

The code supposed to send out bulk emails to all users. But error showed:
'Swift_RFC ComplianceException' with message. Address in mailbox given does not comply with RFC 2822.3.6.2.

### Expected behaviour

The code supposedto send bulk emails based on the email addresses entered in a form
![swiftmailerphp]
(https://user-images.githubusercontent.com/38290271/39965000-5e120748-56c3-11e8-87e6-e7329bbe698d.JPG)

### Example

<?php
	
	require_once '/vendor/swiftmailer-5.x/lib/swift_required.php';
	function send_mail($recipient, $subject="", $message="") {
		if (strpos($recipient, ",") !== true) {
			$recipient = preg_split("/[,]+/", $recipient);
		}
		$transport = (new Swift_SmtpTransport('in-v3.mailjet.com', 25))
		  ->setUsername('53b0742d1ff9e724fcc22a69fe05a70a')
		  ->setPassword('1475a1a4fabaf09c3bbf87c9192f03aa');
		$mailer = new Swift_Mailer($transport);
		
		$message = (new Swift_Message($subject))
			->setFrom(['jamesyeobh@gmail.com' => 'Webmaster'])
			//->setTo([$recipient]) //Recipients
			->setTo($recipient) //Recipients

			//Recipients
			->setBody($message); //Bodymessage
			
		if ($mailer->send($message) > 0) {
		  return 1;
		return 0;
	}
	}
?>

**Comment by Rotzbua** [comment]
> Swiftmailer version | x.y.z
> PHP version | x.y.z

??

**Comment by fabpot** [comment]
Closing as Github is only used for bugs and feature requests. You should use StackOverflow for support instead. Thanks for your understanding.
