### ISSUE TITLE
Lack of documentation for new features in 4.1.1

### ISSUE THREAD

**Issue by arena94** [swiftmailer/swiftmailer#109]
- Any information about 'Swift_Transport_NullTransport' &
  'Swift_Transport_SpoolTransport' is welcomed + code samples
- Any information about RedirectingPlugin and ImpersonatePlugin is
  welcomed + code samples

**Comment by RinkAttendant6** [comment]
Yes I agree. I think `Swift_NullTransport` is what I'm supposed to be using for the transport in my DI container in my test environment (CI or even PHPUnit in general) but there's no documentation on it :confused:
