### ISSUE TITLE
How many maximum email addresses can be passed in Bcc using array

### ISSUE THREAD

**Issue by freejobpoint** [swiftmailer/swiftmailer#1093]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| RFC?                | no
| How used?           | Symfony
| Swiftmailer version | 5.4.0
| PHP version         | 7.1

### Observed behaviour

I have approximately 4500 subscribers. I need to send newsletter to them. My hosting providers allows only 500 emails per hour. I am trying to do like this.
*$mailer = new Swift_Mailer($transport);
$msg = (new Swift_Message('TEST MESSAGE'))
  ->setFrom(['admin@xyz.com' => 'XYZ'])
  ->setTo(['care@XYZ.com'])
  ->setBcc($loe)
  ->setBody($message,'text/html');
$fr = $mailer->send($msg);  

Where $loe is an Array of 500 emails. I will put this file in cron job and execute it every hour. So email will be sent to 500 subscribers. When I pass 500 emails in setBcc() function. It does not work. Please guide.

**Comment by tomzx** [comment]
How do you observe that it does not work? Is there an exception/error logged?

**Comment by freejobpoint** [comment]
Swift_TransportException: Expected response code 250 but got code "421", too many messages.

**Comment by tomzx** [comment]
That is likely your hosting provider SMTP server telling you you are trying to send too many emails at once. Consider that if `$loe` size is 500, you are effectively sending 501 emails (to + 500 bcc).

I'd suggest you try sending a lot less emails per hour/batch, or you switch SMTP provider (use something like AWS SES for instance).
