### ISSUE TITLE
Sending multiple emails causing connection timeout with tcp://smtp.office365.com:587 

### ISSUE THREAD

**Issue by yervandakopyan** [swiftmailer/swiftmailer#1094]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | ?
| How used?           | laravel 5.3
| Swiftmailer version | x.y.z
| PHP version         | 5.6.4

Im using laravel and swiftmailer to send out emails via cron. I know microsoft has a limitation of 30 emails per minute so i have a sleep in between for every 30 emails to wait 60 seconds before continuing to do the rest. All seems to work fine for about 400 emails or so then suddenly i get the following error:

exception 'Swift_TransportException' with message 'Connection to tcp://smtp.office365.com:587 Timed Out'

Does anyone know what may cause this or if there is any limitation in swiftmailer that i am unaware of. I contacted microsoft and it says it looks fine on their end and they dont see any issues.

My settings are as follows:
MAIL_DRIVER=smtp
MAIL_HOST=smtp.office365.com
MAIL_PORT=587
MAIL_ENCRYPTION=tls

I know settings are ok because it does send it for about 400 of it or so.

**Comment by ImageProjector** [comment]
I brought mine down to 13 a minute and that seemed to work for a while, but it still times out occasionally. I switched to using mailgun for large volumes.

**Comment by yervandakopyan** [comment]
Ya im thinking of switching as well
