### ISSUE TITLE
afterEhlo function doesn't throw correct message

### ISSUE THREAD

**Issue by gitstashgithub** [swiftmailer/swiftmailer#1095]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Laravel5.5
| Swiftmailer version | 6.0.2
| PHP version         | 7.1.3

### Observed behaviour
In `vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php` file `afterEhlo` function, if authentication fails it always throw error message 'Failed to authenticate on SMTP server with username $usename using $count possible authenticators'. The error message from mail server is caught in $authenticator->authenticate() function but never passes here. 

Therefore, no matter the error is caused by wrong password or is caused two step authentication is enabled, the error messages are the same.

**Comment by fabpot** [comment]
Can you have a look at #1096? I've not tested it yet but I think it fixes your issue.

**Comment by gitstashgithub** [comment]
Thank you, it looks like exactly what I asked for.
