### ISSUE TITLE
No IDN encoder found (install the intl extension or the true/punycode package

### ISSUE THREAD

**Issue by m144** [swiftmailer/swiftmailer#1100]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | laravel
| Swiftmailer version |  6.1.0
| PHP version         | 7.0.30

When upgrading swiftmailer version from 6.0.2 to 6.1.0 , I get the following error when trying to send an email:
exception: "Swift_SwiftException"
file:"vendor/swiftmailer/swiftmailer/lib/classes/Swift/AddressEncoder/IdnAddressEncoder.php"
line:64
message: "No IDN encoder found (install the intl extension or the true/punycode package"

This is the first time it happened after using this package for a long time.

I think the correct way to solve this is to make the php extension ext-intl or the package true/punycode a requirement, not only a suggestion, in composer.json

(When installing the true/punycode package the issue was solved)

**Comment by c960657** [comment]
Which email address are you trying to send to? Can you post the full stack trace?

The exception thrown by `Swift_AddressEncoder_IdnAddressEncoder` is a subclass of `Swift_RfcComplianceException`. `Swift_RfcComplianceException` is also thrown if you are trying to send to a malformed email address, so you probably want to catch it in any case, unless you have validated the addresses in advance.

**Comment by m144** [comment]
All validations are done before sending, and I have been sending to the same email address I sent before with success. 
I know this is meant to solve a problem with utf-8 characters in the email address, but I have none in my addresses.
Here is the stack trace:
```
{
    "message": "No IDN encoder found (install the intl extension or the true/punycode package",
    "exception": "Swift_SwiftException",
    "file": "vendor/swiftmailer/swiftmailer/lib/classes/Swift/AddressEncoder/IdnAddressEncoder.php",
    "line": 64,
    "trace": [
        {
            "file": "vendor/swiftmailer/swiftmailer/lib/classes/Swift/AddressEncoder/IdnAddressEncoder.php",
            "line": 43,
            "function": "idnToAscii",
            "class": "Swift_AddressEncoder_IdnAddressEncoder",
            "type": "->"
        },
        {
            "file": "vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/IdentificationHeader.php",
            "line": 164,
            "function": "encodeString",
            "class": "Swift_AddressEncoder_IdnAddressEncoder",
            "type": "->"
        },
        {
            "file": "vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php",
            "line": 426,
            "function": "getFieldBody",
            "class": "Swift_Mime_Headers_IdentificationHeader",
            "type": "->"
        },
        {
            "file": "vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php",
            "line": 169,
            "function": "toTokens",
            "class": "Swift_Mime_Headers_AbstractHeader",
            "type": "->"
        },
        {
            "file": "vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderSet.php",
            "line": 310,
            "function": "toString",
            "class": "Swift_Mime_Headers_AbstractHeader",
            "type": "->"
        },
        {
            "file": "vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php",
            "line": 466,
            "function": "toString",
            "class": "Swift_Mime_SimpleHeaderSet",
            "type": "->"
        },
        {
            "file": "vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php",
            "line": 576,
            "function": "toString",
            "class": "Swift_Mime_SimpleMimeEntity",
            "type": "->"
        },
        {
            "file": "vendor/swiftmailer/swiftmailer/lib/classes/Swift/Message.php",
            "line": 142,
            "function": "toString",
            "class": "Swift_Mime_SimpleMessage",
            "type": "->"
        },
        {
            "file": "vendor/laravel/framework/src/Illuminate/Mail/Transport/MandrillTransport.php",
            "line": 48,
            "function": "toString",
            "class": "Swift_Message",
            "type": "->"
        },
        {
            "file": "vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php",
            "line": 70,
            "function": "send",
            "class": "Illuminate\\Mail\\Transport\\MandrillTransport",
            "type": "->"
        },
        {
            "file": "vendor/laravel/framework/src/Illuminate/Mail/Mailer.php",
            "line": 451,
            "function": "send",
            "class": "Swift_Mailer",
            "type": "->"
        },
        {
            "file": "vendor/laravel/framework/src/Illuminate/Mail/Mailer.php",
            "line": 235,
            "function": "sendSwiftMessage",
            "class": "Illuminate\\Mail\\Mailer",
            "type": "->"
        },
        {
            "file": "vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php",
            "line": 64,
            "function": "send",
            "class": "Illuminate\\Mail\\Mailer",
            "type": "->"
        },
        {
            //the rest is app-specific
        }
    ]
}
```

**Comment by c960657** [comment]
Sorry, my bad. We do infact require an encoder to be present even for emails that do not contain UTF-8 characters. I'll make a fix later today.

**Comment by stemis** [comment]
I have the same issue. also laravel install.

After running composer update our testsuite fails.

Since the new version this error comes up:
` No IDN encoder found (install the intl extension or the true/punycode package at /vendor/swiftmailer/swiftmailer/lib/classes/Swift/AddressEncoder/IdnAddressEncoder.php:64)`

We went from swiftmailer/swiftmailer (v6.0.2 => v6.1.0):

**Comment by AlexanderPoellmann** [comment]
Same here after updating from 6.0.2 to 6.1.0. Thanks @c960657 for fixing that ;-)

**Comment by pablorsk** [comment]
Thanks @c960657 

Temporal fix (in Laravel, for example) :wrench: 
```json
{
    "require": {
        "laravel/framework": "5.6.*",
        "swiftmailer/swiftmailer": "6.0.*",
         "...": "..."
     },
     "...": "..."
}
```

**Comment by mrisholgabeid** [comment]
Hi all,

I am having some trouble with the Swiftmailer package but I am unsure if it related to a known issue or something. Also, I am a complete beginner with this, so I may not be able to provide you the information you need if you to support, if you request using jargon :).

I downloaded the Windows Composer installer (from getcomposer.org) and I successfully installed in on my computer. I then ran the command (cd (to my project directory) composer require swiftmailer/swiftmailer @stable) to download swiftmailer, and after it finished, there were some things that are listed as missing - please see below:

swymfony/polyfill-intl-idn suggests installing ext-intl (For best performance)
egulias/email-validator suggests installing ext-intl (PHP Internationalization Libraries are required to use the SpoofChecking validation)
swiftmailer/swiftmailer suggests installing ext-intl (Needed to support internationalized email addresses)
swiftmailer/swiftmailer suggests installing true/punycode (Needed to support internationalized email addresses, if ext-intl is not installed) 

I tried to run a test to check if the Swift class was available using an if statement, and I always get the response as true. However, when I try to instantiate a method to compose my email - such as **Swift_Message::newInstance()**, I get an error saying: **Call to undefined method Swift_Message::newInstance()**.

**In case this might be useful, please note that this has happened to me twice with 2 different devices: Dell Latitue E5470 running Windows 7 Enterprise & Surface Pro 4 running Windows 10**

Can you please help me resolve this issue? Is there that I am doing wrong? Is there support somewhere that can show me how to correctly and efficiently use Swiftmailer? I need to learn how to create HTML5 emails, with attachments and be able to send those to more than one recipient.

Please let me know if there is any other information that I can provide that could help to resolve this issue.

Thank you in advance.
