### ISSUE TITLE
mailer not working, no matter what

### ISSUE THREAD

**Issue by rvanuden** [swiftmailer/swiftmailer#1104]
### Expected behaviour
I am using swift in a theme (html) and it is quite straightforward to setup the mailing form.

THere are only a few parameters that i have to change but the form never works, i tried all possible combinations:

my hoster info:

Outgoing servername: mailout.one.com
Port en encription:
- 587 with STARTTLS (aanbevolen)
- 465 with TLS
- 25 with STARTTLS or none

I use:

$emailMethod                = 'smtp'; // REQUIRED value. Options: 'smtp' , 'phpmail' (phpmail does nothing, no errors neither)

$outgoingServerAddress      = 'mailout.one.com'; // Consult your hosting provider.
$outgoingServerPort         = '465';                  // Options: '587' , '25' - Consult your hosting provider.
$outgoingServerSecurity     = 'tls';                 // Options: 'ssl' , 'tls' , null - Consult your hosting provider.

Then my credentials:

sendingAccountUsername     = 'info@bbdenoever.be';
$sendingAccountPassword     = 'mypassword';

// Recipient (To:) Details  - Change this to the email details of who will receive all the emails from the website.
$recipientEmail             = 'roger@etserv.be'; // REQUIRED value. (testemail)
$recipientName              = 'B&B Den Oever';             // REQUIRED value.

one of the errors i get now with this info is: Backend fetch failed after a while

any ideas?

**Comment by Rotzbua** [comment]
> any ideas?

Yes, complete your environment information.

**Comment by rvanuden** [comment]
ok...but forgive me for being a noob, what do you mean by that?

**Comment by Rotzbua** [comment]
| Q                   | A
| ------------------- | -----
| How used?           | Standalone/Symfony/3party
| Swiftmailer version | x.y.z
| PHP version         | x.y.z

**Comment by rvanuden** [comment]
ah ok, sorry for that

* 3rd party (but no response there)
* PHP Version 7.0.29
* Swift mailer version: no idea it is integrated in the html foundry editor and it works on another hosting but not this one although i did exactly the same thing. The developers do not respond so thos forum is my last resort to get it working. I tried to check all swift mailer files bu no date there

**Comment by fabpot** [comment]
Closing as Github is only used for bugs and feature requests. You should use StackOverflow for support instead. Thanks for your understanding.
