### ISSUE TITLE
5.4.10 have a bug

### ISSUE THREAD

**Issue by Isites** [swiftmailer/swiftmailer#1111]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    |no
| RFC?                | no
| How used?           | Standalone/Symfony/3party
| Swiftmailer version | v5.4.10
| PHP version         | php5.5

### Example

in v5.4.10 composer.js support tls1.1 and tls1.2 but STREAM_CRYPTO_METHOD_TLSv1_0_CLIENT,
    STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT and
    STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT added in php 5.6
so, 
**`"php": ">=5.3.3" -> "php": ">=5.6.0"
`**

**Comment by fabpot** [comment]
Can you make a pull request that defines those constants if they don't exist (use 0 as a value in that case)?

**Comment by Isites** [comment]
I think it is not a good way.
I have tried a simple example, it's not succeed, it depends on php version

```php
$stream = stream_socket_client("google.com:443", $errno, $errstr, 30);

echo PHP_VERSION . "\n";

$supportTls = PHP_VERSION > '5.6' ? STREAM_CRYPTO_METHOD_TLSv1_0_CLIENT | STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT | STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT : STREAM_CRYPTO_METHOD_TLS_CLIENT;

$res = stream_socket_enable_crypto($stream, true, $supportTls);

var_dump($res);
```

This can support different versions

![image](https://user-images.githubusercontent.com/8931156/43408191-42046fa0-9453-11e8-9ccb-0fea099be875.png)

I will submit a pull request later.
