### ISSUE TITLE
v5.4.11 StreamBuffer has an invalid property

### ISSUE THREAD

**Issue by troymccabe** [swiftmailer/swiftmailer#1113]
`StreamBuffer::stream` does not exist in 5.4.11, but `StreamBuffer::_stream` does. This tag needs to be fixed. https://github.com/swiftmailer/swiftmailer/blob/v5.4.11/lib/classes/Swift/Transport/StreamBuffer.php#L103

| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Standalone
| Swiftmailer version | 5.4.11
| PHP version         | 7.1

### Observed behaviour
```
Fatal error: Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined property: Swift_Transport_StreamBuffer::$stream in <snip>/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:103
Stack trace:
#0 <snip>/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(313): Swift_Transport_StreamBuffer->startTLS()
#1 <snip>/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(118): Swift_Transport_EsmtpTransport->_doHeloCommand()
#2 <snip>/vendor/swiftmailer/swiftmailer/lib/classes/Swift/MemorySpool.php(83): Swift_Transport_AbstractSmtpTransport->start()
#3 <snip>/vendor/symfony/swiftmailer-bundle/EventListener/EmailSenderListener.php(61): Swift_MemorySpool->flushQueue(Object(Swift_Transport_Es in <snip>/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 103
```

### Expected behaviour
Not that ☝

### Example
We use SES, so it communicates over TLS: `$container->get('mailer')->send($message);`

**Comment by xabbuh** [comment]
You need to update to 5.4.12 where this was already fixed (see d96063e9e57b3b2f67de6e465cc5353c29612fe8).
