### ISSUE TITLE
Bogus HELO [127.0.0.1]

### ISSUE THREAD

**Issue by leenooks** [swiftmailer/swiftmailer#1115]
I'm having a problem with sending email via Laravel using the SMTP transport.

I cannot figure out how to change the HELO domain that SwiftMailer is using. I can see that there is a function there to set it setLocalDomain(), however, it seems to get called with 127.0.0.1 (which is a hard coded default).

| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| How used?           | via Laravel Mail::to()->send() 
| Swiftmailer version | 6.0.2
| PHP version         | 7.2.1

### Observed behaviour
SMTP server rejects outbound mail with `bogus HELO name used: [127.0.0.1]`

### Expected behaviour
I want to set (or Swift) to use the domain from the hostname and/or $_SERVER['SERVER_NAME'] (which are both fully qualified).

**Comment by sstok** [comment]
`setLocalDomain` seems to be working correctly, can you verify this method is called in the Laravel layer that handles this configuration? I don't think this a problem with Swiftmailer itself.

**Comment by leenooks** [comment]
I'll check in Laravel - but shouldnt the default be derived from the hostname or the $_SERVER['SERVER_NAME'] not 127.0.0.1?

**Comment by leenooks** [comment]
So I'm looking for more help on this problem. I couldnt get swiftmailer working in Laravel and used SSMTP instead on the localhost instead of an SMTP connection to a remote server.

Today, I was looking at changing from owncloud to nextcloud - and I discovered nextcloud is failing for the same reason - and its using Swift 6.1.3. Owncloud however works without any problem, and it's using 5.4.12 - so something changed between those releases?

**Comment by WouterFlorijn** [comment]
I'm having the same problem (I think). It occurs when queueing email notifications and then sending them using `queue:work` from a separate container (I'm running Kubernetes).

The strange thing is that the queue worker is fine for a few hours until suddenly it generates this exception:

> Swift_TransportException
> Connection to tcp://smtp.sendgrid.net:587 Timed Out

And from then on, it will generate the same exception every minute. In the stack trace I can see the 127.0.0.1 being using in the HELO call, which triggers the timeout.

This is very hard to debug and I would love some ideas on this issue.

**Comment by leenooks** [comment]
I'm not completely sure your "timeout" issue is the same as my issue - where I was seeing the SMTP server (sendmail), reject the outgoing email with `bogus HELO name used: [127.0.0.1]`.

My resolution was to give the container a FQDN hostname, since I discovered 127.0.0.1 is used if the container doesnt have one.
