### ISSUE TITLE
Mail is not sent everytime

### ISSUE THREAD

**Issue by hasmukhmistry13** [swiftmailer/swiftmailer#1121]
Smtp details which we use are correct, for host **smtp.office365.com** mail is not sent every time.

Sometimes this error is generated,
Fatal error: Uncaught Swift_TransportException: Failed to authenticate on SMTP server with username "XXX" using 2 possible authenticators in vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php on line 181

### Observed behaviour
Sometimes with the same details, emails are sent.

### Expected behaviour
It should send an email every time.

Can you please tell me what should I do?

**Comment by fabpot** [comment]
I'm sorry but we are only using the GitHub repository to discuss bugs and new features. For this kind of questions about using Swiftmailer, please use any StackOverflow.

Thanks!
