### ISSUE TITLE
Office 365 delivering email to To: recipients multiple times when Bcc: set

### ISSUE THREAD

**Issue by tmey2016** [swiftmailer/swiftmailer#1132]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Standalone
| Swiftmailer version | 5.4.12 and 6.1.3
| PHP version         | 5.6.37 and 7.2.2

### Observed behavior

Address an outgoing email with one To: and one Bcc recipient. Two copies of the message will be delivered to the To: recipient.

This is a recent change (just this week for our business account users) to the way the Microsoft Office 365 SMTP system responds to Swiftmailer when it sends messages with Bcc recipients. Microsoft may not be following the standards, but they are big enough that I assume we should be aware of this issue. My company is likely not the only one experiencing this problem.

### Expected behaviour
Deliver only one copy of the message to the To: recipient.

### Example
```php
        $transport = (new Swift_SmtpTransport(
            'smtp.office365.com',
            587,
            'tls'
        ))
          ->setUsername($sender)
          ->setPassword($password)
          ->setTimeout(600);

        // Create the Mailer using your created Transport
        $mailer = new Swift_Mailer($transport);
        $msg = (new Swift_Message($subject))
          ->setFrom([$sender => $senderName])
          ->setTo($to)
          ->setBody($message)
          ->setBcc($bcc);
        
$mailer->send($msg);
```

### Applicable Swiftmailer code

When a message has Bcc recipients, it sends separate smtp messages: one to all of the non-bcc recipients then one to each bcc recipient. An email with one To and three Bcc will cause Swiftmailer to send four smtp messages.

With Office 365, I commented out sendTo() and the message was still delivered to the To: recipient.

/lib/classes/Swift/Transport/AbstractSmtpTransport.php

function send
```php
        $tos = array_merge($to, $cc);
        $bcc = (array) $message->getBcc();

        $message->setBcc([]);

        try {
            $sent += $this->sendTo($message, $reversePath, $tos, $failedRecipients);
            $sent += $this->sendBcc($message, $reversePath, $bcc, $failedRecipients);
        } finally {
            $message->setBcc($bcc);
        }
```

```php
    /** Send a message to the given To: recipients */
    private function sendTo(Swift_Mime_SimpleMessage $message, $reversePath, array $to, array &$failedRecipients)
    {
        if (empty($to)) {
            return 0;
        }

        return $this->doMailTransaction($message, $reversePath, array_keys($to),
            $failedRecipients);
    }

    /** Send a message to all Bcc: recipients */
    private function sendBcc(Swift_Mime_SimpleMessage $message, $reversePath, array $bcc, array &$failedRecipients)
    {
        $sent = 0;
        foreach ($bcc as $forwardPath => $name) {
            $message->setBcc([$forwardPath => $name]);
            $sent += $this->doMailTransaction(
                $message, $reversePath, [$forwardPath], $failedRecipients
                );
        }

        return $sent;
    }
```

### Research into server behavior

Office 365 for some unknown reason (I could find no notice or documentation on this) has decided to deliver SMTP mail based on the message headers rather than just the RCPT TO envelope. I debugged the SMTP communication and confirmed that when Swiftmailer hands off a message RCPT TO: Person A which contains a header To: Person B, Microsoft will deliver the message to both Person A and Person B.

### Solution

I looked into the code of zend-mail, another popular PHP mail library. They strip the Bcc header from the message just before sending (so the "blind" header is not included), but otherwise, they do not do anything special with Bcc recipients. It is all sent as a single message with all of the RCPT TO. 

Our company makes extensive use of Bcc so we were scrambling to fix the problem. We replaced Swiftmailer with zend-mail and it fixed all problems. Therefore their implementation seems to be compatible with the recent Office 365.

I do not know the purpose behind Swiftmailer's current implementation, but I see no reason not to remove sendBcc altogether, strip the Bcc header, but include the Bcc recipients in the RCPT TO for sendTo(). 

I have not contributed to Swiftmailer before, so maybe a lead developer can provide feedback on whether this approach is something they want to consider.

Thanks. I hope my findings can save people a lot of stress in dealing with this issue.

**Comment by jaudette** [comment]
I have not put as much effort into this issue, but i noticed that when i add a CC to a message and send it with Office365 smtp server, the message gets sent twice.

**Comment by aristos32** [comment]
I confirm same issue with BCC. We had to switch to PHPMailer to solve it.
Will this be fixed?

**Comment by tmey2016** [comment]
Some other very recent Office365 changes I have run into that people may be facing:

1. custom message headers starting with x- are removed before delivery (I switched to using a data- attribute in a span tag in the html to store meta data)

2. text/plain alternative part is removed before imap delivery IF the recipient is an Office365 user

3. when sending a text/calendar;method=REQUEST part, the To: in the envelope is ignored and the email is delivered to everyone listed as a meeting attendee.

I'll look into submitting a pull request for the bcc issue.

**Comment by mazraara** [comment]
I have the same issue with BCC when using Office 365.  Any workaround?
