### ISSUE TITLE
Can't Authenticate With App Password on Gmail

### ISSUE THREAD

**Issue by jsl303** [swiftmailer/swiftmailer#1138]
This particular gmail account has two step authentication enabled, so I generated an app password.
$transport = (new Swift_SmtpTransport('smtp.gmail.com', 465, 'ssl'))
->setUsername('user_email@gmail.com')
->setPassword('app_password');
However, I get this error:

PHP Fatal error:  Uncaught Swift_TransportException: Failed to authenticate on SMTP server with username "email@gmail.com" using 3 possible authenticators. Authenticator LOGIN returned Swift_TransportException: Expected response code 235 but got code "534", with message "<https://accounts.google.com/signin/continue?sarp=1&scc=1...>
Please log in via your web browser and then try again.
Learn more at https://support.google.com/mail/answer/78754
.../vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:457
Stack trace: #0 .../vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php on line 191

**Comment by Rotzbua** [comment]
Just look at that what you wrote:

>  Learn more at https://support.google.com/mail/answer/78754
