### ISSUE TITLE
Cannot set maxLineLength on header with special character

### ISSUE THREAD

**Issue by robinmoisson** [swiftmailer/swiftmailer#1141]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Symfony
| Swiftmailer version | 5.4.9
| PHP version         | 7.0.32

### Observed behaviour
I am trying to set a custom maxLineLength for my subject header (as a workaround for https://github.com/swiftmailer/swiftmailer/issues/601). 

I'm trying to set it to 998 to get it all on one line, if the subject doesn't contain any special character then it work as expected. If it does contain any special character my custom maxLineLength is overridden and is set to 76 characters, causing it to be split on multiple lines.

The place where it is overridden is https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Mime/Headers/AbstractHeader.php#L278.

Why is there this forceful override here ? 

### Expected behaviour
I expect my custom maxLineLength to be taken into account whether there is a special character in my header or not.

### Example

    $subject = 'éLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt';
    $message = new \Swift_Message();
    $message->setSubject( $subject );
    $message->getHeaders()->get( 'Subject' )->setMaxLineLength( 998 );
    echo $message->toString(); // will show the Subject header broken on 2 lines

If you remove the leading `é` from the subject, the subject header is using the custom maxLineLength and displays on one line.

**Comment by nothing3618** [comment]
Here is a workaround:
$message->setSubject( '=?UTF-8?B?'.$subject.'?=' );

**Comment by p1ratrulezzz** [comment]
Check \Swift_Mime_Headers_AbstractHeader::getTokenAsEncodedWord()

if has a hardcoded value 75 for checking an offset. And this issue can't be solved until this magic constant is replaced by maxLineLength in every place it is used.

So, as recommended, use the workaround from the previous comment or here is another example:

```php
mb_internal_encoding('UTF-8');
$transfer_encoding = $message->getHeaders()->get('content-tranfser-encoding')->getValue() == 'quoted-printable' ? 'Q' : 'B';
$encoded = mb_encode_mimeheader($subject, 'UTF-8', $transfer_encoding, null, strlen('Subject: '));
$message->setSubject($encoded);
```
