### ISSUE TITLE
return $priority ?? 3; php 7.2

### ISSUE THREAD

**Issue by sergmoro1** [swiftmailer/swiftmailer#1145]
PHP Parse Error 'yii\base\ErrorException' with message 'syntax error, unexpected '?''

in /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php:490

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

Here is the problem. 
return $priority ?? 3;

My PHP version is

php -v
PHP 7.2.12-1+ubuntu14.04.1+deb.sury.org+1 (cli) (built: Nov 12 2018 10:58:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.12-1+ubuntu14.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by xabbuh** [comment]
Did you see the error when executing your application on the command line or during an HTTP request? Note that the PHP version used to serve HTTP requests is not necessarily the same as the one used on the CLI.

**Comment by sergmoro1** [comment]
You are right. They are different. Thanks.
