### ISSUE TITLE
A small typo inside the documentation

### ISSUE THREAD

**Issue by abelardolg** [swiftmailer/swiftmailer#1147]
Hi, 
This is a small typo inside your documentation. Is not an issue neither a bug.

**WHERE**: https://swiftmailer.symfony.com/docs/messages.html#setting-to-recipients
**WHAT**: 
![image](https://user-images.githubusercontent.com/22522883/48935048-88dfa300-ef06-11e8-9c5a-2326fc8dc1b2.png)

I think you have duplicated this text
Best regards.

| Q                   | A
| ------------------- | -----
| Bug report?         | /no
| Feature request?    |/no
| RFC?                | /no
| How used?           | /Symfony/
| Swiftmailer version | x.y.z
| PHP version         | x.y.z

### Observed behaviour

Not code related.

### Example

Go to this page:  https://swiftmailer.symfony.com/docs/messages.html#setting-to-recipients

**Comment by fabpot** [comment]
fixed in b80d74f2e88cd40b56adc58804a07a59ac30dc47
