### ISSUE TITLE
The checksum verification of the file failed

### ISSUE THREAD

**Issue by TuningYourCode** [swiftmailer/swiftmailer#1151]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Standalone
| Swiftmailer version | 5.4.8
| PHP version         | 7.1.24

### Observed behaviour
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 1 install, 0 updates, 0 removals
  - Installing swiftmailer/swiftmailer (v5.4.8): Downloading (100%)    Failed to download swiftmailer/swiftmailer from dist: The checksum verification of the file failed (downloaded from https://api.github.com/repos/swiftmailer/swiftmailer/zipball/9a06dc570a036
7850280eefd3f1dc2da45aef517)
    Now trying to download from source
  - Installing swiftmailer/swiftmailer (v5.4.8): Cloning 9a06dc570a

### Expected behaviour
  - Installing swiftmailer/swiftmailer (v5.4.8): Downloading (100%)

**Comment by TuningYourCode** [comment]
I know that this is an old version but would be cool if somebody could fix the checksum for the zip-file.

**Comment by Rotzbua** [comment]
Not a problem of this library. Seems a bug in composer or github.

**Comment by TuningYourCode** [comment]
It's reproduceable as it occurs everytime even if i completly destory my vagrant maschine and rebuild the application.
So no composer cache at client side at least. I'm not sure where or which checksum composer uses to compare it. Hopefully somebody knows more about the process or which checksum composer uses.

**Comment by Rotzbua** [comment]
Cant reproduce your problem. If you use `.lock` maybe this file is damaged.

My test:
---------

composer file:
```json
{
    "name": "root/phpteest",
    "require": {
        "swiftmailer/swiftmailer": "5.4.8"
    }
}
```

Output:

```
[...]
Would you like to install dependencies now [yes]? yes
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing swiftmailer/swiftmailer (v5.4.8): Downloading (100%)         
Writing lock file
Generating autoload files
```

> PHP 7.2.9-1 (cli) (built: Aug 19 2018 06:56:13) ( NTS )


composer.lock part
```json
            "name": "swiftmailer/swiftmailer",
            "version": "v5.4.8",
            "source": {
                "type": "git",
                "url": "https://github.com/swiftmailer/swiftmailer.git",
                "reference": "9a06dc570a0367850280eefd3f1dc2da45aef517"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/swiftmailer/swiftmailer/zipball/9$
                "reference": "9a06dc570a0367850280eefd3f1dc2da45aef517",
                "shasum": ""
            },
```

**Comment by TuningYourCode** [comment]
totally forget about composer.lock

Sorry & thank you for your hint 👍
