### ISSUE TITLE
Swift_TransportException: Failed to authenticate on SMTP server with username "xxx@xxxx.com" using 2 possible authenticators

### ISSUE THREAD

**Issue by LakshmanKatragadda** [swiftmailer/swiftmailer#1152]
Bug report?         yes
How used?           Laravel  5.4.28
Swiftmailer version 5.4.8
PHP version       7.1.11

I config outlook smtp details in laravel  with tls and port 587 . i getting Swift_TransportException . i am able login outlook with those credentials.

**Comment by conroymulti** [comment]
I can;t get Swift Mailer to connect to either Gmail server or Website Hosting Server even my hosting support guy (Inmotion Hosting) spent 30 minutes on the phone with me trying to fix the issue. 

I would like  if someone replied please.
