### ISSUE TITLE
 Notice: Undefined property: Swift_Transport_StreamBuffer::$_sequence 

### ISSUE THREAD

**Issue by perodriguezl** [swiftmailer/swiftmailer#1155]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Standalone
| Swiftmailer version | 4.1.1
| PHP version         | 5.6.35

### Observed behaviour
trying to: $transporter = \Swift_SmtpTransport::newInstance(xxxx.com', 465, 'ssl')
 Notice: Undefined property: Swift_Transport_StreamBuffer::$_sequence in /app/vendor/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php line 244 (500 Internal Server Error)

### Expected behaviour
it should not fire that

**Comment by fabpot** [comment]
Closing as version 4.1 of Swiftmailer is not maintained anymore. Please, upgrade.
