### ISSUE TITLE
SMTPUTF8 support in a Symfony project

### ISSUE THREAD

**Issue by julienfalque** [swiftmailer/swiftmailer#1159]
I am using Swiftmailer (6.3.1) in a Symfony project and am trying to enable SMTPUTF8 support (implemented in #1056). I couldn't find a setting for that in the Swiftmailer bundle so I wrote a compiler pass that injects `SmtpUtf8Handler` and `Utf8AddressEncoder` into `EsmtpTransport` as described in the documentation but this doesn't seem to be sufficient. When creating the `Message` instance, it uses a Swiftmailer internal dependency container which has hardcoded references to the `IdnAddressEncoder`:

https://github.com/swiftmailer/swiftmailer/blob/e8c3ed713d199760c1730fb89a38cefe7f54c4ae/lib/dependency_maps/transport_deps.php#L10-L18

https://github.com/swiftmailer/swiftmailer/blob/e8c3ed713d199760c1730fb89a38cefe7f54c4ae/lib/dependency_maps/mime_deps.php#L64-L72

How can I make sure the internal Swiftmailer dependency container also references `Utf8AddressEncoder` instead of `IdnAddressEncoder`?

**Comment by arena94** [comment]
with the same code, i tried to send a mail to trucmuche@toto.com with gmail as smtp server : (failed)

Here is what i have from the Swift_Plugins_Loggers_ArrayLogger (see attached)

[Swift_Plugins_Loggers_ArrayLogger.txt](https://github.com/swiftmailer/swiftmailer/files/2762290/Swift_Plugins_Loggers_ArrayLogger.txt)

fyi, i am also using this

`$this->message->setEncoder( Swift_DependencyContainer::getInstance()->lookup('mime.qpcontentencoder') );`

Hope this help !

**Comment by arena94** [comment]
When i remove those lines,

`
	$smtpUtf8 = new Swift_Transport_Esmtp_SmtpUtf8Handler();
	$conn->setExtensionHandlers( [$smtpUtf8] );
	$utf8Encoder = new Swift_AddressEncoder_Utf8AddressEncoder();
	$conn->setAddressEncoder( $utf8Encoder );

`

I successfully send my mail to trucmuche@toto.com

**Comment by arena94** [comment]
Continuing my investigations

as noticed in the Swift_Plugins_Loggers_ArrayLogger.txt (see above)
```$conn->setExtensionHandlers( [$smtpUtf8] );```
is properly held.

but i am still in doubt for 
```$conn->setAddressEncoder( $utf8Encoder );```

in  class **Swift_Transport_AbstractSmtpTransport**, there are two functions :

- setAddressEncoder
- getAddressEncoder : can't find a call to this function in all swiftmailer code

**Comment by arena94** [comment]
So this morning i decided to make it work :

**Test One**
create a new class refering to new dependencies : 

`class Swift_SmtpUtf8Transport extends Swift_Transport_EsmtpTransport
{
    public function __construct($host = 'localhost', $port = 25, $encryption = null)
    {
        call_user_func_array(
            [$this, 'Swift_Transport_EsmtpTransport::__construct'],
            Swift_DependencyContainer::getInstance()
                ->createDependenciesFor('transport.smtputf8')
            );
        $this->setHost($host);
        $this->setPort($port);
        $this->setEncryption($encryption);
    }
}`

and create the correspondig dependency (hereunder source diff) :+1: 
[old_new_diff_step1.txt](https://github.com/swiftmailer/swiftmailer/files/2763985/old_new_diff_step1.txt)

and send a mail to  θσερ@εχαμπλε.ψομ 

Same error :

`PHP Fatal error:  Uncaught Swift_AddressEncoderException: Non-ASCII characters not supported in local-part in \Swift\AddressEncoder\IdnAddressEncoder.php:41`

**Test Two:** 

Just for that test changed mime_deps (hereunder source diff)
[old_new_diff_step2.txt](https://github.com/swiftmailer/swiftmailer/files/2763992/old_new_diff_step2.txt)

and send a mail to  θσερ@εχαμπλε.ψομ (still with gmail as a smtp server)

and .... IT WORKS !!!!

**Comment by arena94** [comment]
Content of my gmail sent box :

![ingreek](https://user-images.githubusercontent.com/1025411/51247835-9194a880-198e-11e9-8ade-4e1260a9df85.png)

;-)

**Comment by arena94** [comment]
@fabpot any (good) advice on this thread ?

**Comment by PascalJonassonDV** [comment]
Hey @julienfalque .

Did you find any solution for this?

BR

**Comment by julienfalque** [comment]
No, I didn't investigate the issue since I submitted it.
