### ISSUE TITLE
Attachment serialization size

### ISSUE THREAD

**Issue by jnvsor** [swiftmailer/swiftmailer#1172]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Standalone
| Swiftmailer version | 6.1.3
| PHP version         | 7.3

A serialized empty message object is 12677 bytes long, but a serialized empty attachment object is 48169 bytes long, ballooning any message object with an attachment in it. (Not to mention multiple)

This is because by default the entire list of 986 known mimetypes from `/lib/mime_types.php` is added to attachments as a private property, which is only used in `setFile` to determine the mimetype from the extension...

This seems similar to #103 and should be fixable the same way: By moving this into a static property. This lowers the size of a `Swift_Attachment` to 7959 bytes.

### Example
```php
<?php

include 'vendor/autoload.php';

echo strlen(serialize(new Swift_Message())).PHP_EOL;
echo strlen(serialize(new Swift_Attachment())).PHP_EOL;
```

**Comment by fabpot** [comment]
We are well aware of the size of the serialized messages. Unfortunately, nothing we can do easily. I've tried several times. The good news is that I've taken that into account when designing Symfony Mailer, which is a replacement for Swiftmailer.
