### ISSUE TITLE
option to Shuffle $directoryIterator in flushQueue

### ISSUE THREAD

**Issue by pety-dc** [swiftmailer/swiftmailer#1175]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| RFC?                | no
| How used?           | Symfony
| Swiftmailer version | x.y.z
| PHP version         | x.y.z

### Observed behaviour
swiftmailer/swiftmailer/blob/master/lib/classes/Swift/FileSpool.php::flushQueue() method reads contents of spool path sequentionally.

### Expected behaviour
Please add an option to shuffle the $directoryIterator array so that parallel send processes don't pick up spool files from each other.

**Comment by edwh** [comment]
I'd find this useful too.  At the moment I only run one flushQueue instance, but this can be very slot to clear a backlog, so I'd like to run multiple - but there's no point if they are all trampling on each other's feet.
