### ISSUE TITLE
TLS/STARTTLS Self-Signed Certificate in 4.1.3

### ISSUE THREAD

**Issue by Amagali** [swiftmailer/swiftmailer#1178]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| RFC?                | no
| How used?           | Symfony1.4
| Swiftmailer version | 4.1.3
| PHP version         | 5.4

### Observed behaviour
Want to send emails from TLS, port 25 with self signed certificates and get the following error:

Connection could not be established with host [Unable to find the socket transport "starttls" - did you forget to enable it when you configured PHP? #835125409]

OpenSSL is working and tried connect from the server and it connects.

### Expected behaviour
Send emails with self-signed certificate.

### Example
mailer:
    class: sfMailer
    param:
      delivery_strategy:  realtime
      delivery_address:   user@mail.com
      transport:
        class: Swift_SmtpTransport
        param:
          host:       x.x.x.x
          port:       25
          encryption: ~
          username:   user@mail.com
          password:   pass
          streamOptions:
            ssl:
                allow_self_signed: true
                verify_peer: false
                local_cert: "/etc/ssl/certificate.cer"
                local_pk: "/etc/ssl/certificate.key"

Got this configuration. 

Hello. I know I have to go to Stackoverflow for troubleshoot but I don't get any help there.

https://stackoverflow.com/questions/54923629/symfony-1-4-sfmailer-configure-tls-self-signed-certificate-unable-to-find-the

Any help would be appreciated. Thank you.

**Comment by xywf221** [comment]
@Amagali Hi Amagali, I met this problem before, and then I read the source code carefully and found that the error came from the SMTP server. You should ask the service provider if they support TLS.

**Comment by Amagali** [comment]
@xywf221 Hi! Thank you for your answer. So, do you think my setup is correct? I suppose to add anything else in my code apart from above?

**Comment by xywf221** [comment]
I'm sorry to see your reply now, I saw your question, but I never used ' Symfony ', I don't know if you're configured correctly, but I recommend that you use mailbox Client connection tests, such as Outlook (:]. Or use the following code to test whether your mailbox provider's SSL is available
```php
<?php
$su = 'test-subject';
$ge = 'xxx@xx.com';
$co = 'i am a test email';
send_mail($su, $ge, $co);

function send_mail($subject, $getter, $content)
{
    $https['ssl']['verify_peer'] = FALSE;
    $https['ssl']['verify_peer_name'] = FALSE;
    $result = false;
    $username = '';
    $password = '';
    $transport = Swift_SmtpTransport::newInstance('smtp.163.com', 465, 'ssl')
        ->setUsername($username)
        ->setPassword($password)
        ->setStreamOptions($https);
    $mailer = Swift_Mailer::newInstance($transport);
    $message = Swift_Message::newInstance($subject)
        ->setFrom(array($username => 'x Project'))
        ->setTo($getter)
        ->setBody($content);
    $result = $mailer->send($message);
    $success = $result ? 0 : 1;
    return $result;
}
```

**Comment by xywf221** [comment]
> @xywf221 Hi! Thank you for your answer. So, do you think my setup is correct? Am I supposed to add anything else in my code apart from above?
> 
> Email provider says that TLS is enabled through port 25, I asked them to open 587 but it seems they cannot do that.

I'm sorry to see your reply now, I saw your question, but I never used ' Symfony ', I don't know if you're configured correctly, but I recommend that you use mailbox Client connection tests, such as Outlook (:]. Or use the following code to test whether your mailbox provider's SSL is available
```php
<?php
$su = 'test-subject';
$ge = 'xxx@xx.com';
$co = 'i am a test email';
send_mail($su, $ge, $co);

function send_mail($subject, $getter, $content)
{
    $https['ssl']['verify_peer'] = FALSE;
    $https['ssl']['verify_peer_name'] = FALSE;
    $result = false;
    $username = '';
    $password = '';
    $transport = Swift_SmtpTransport::newInstance('smtp.163.com', 465, 'ssl')
        ->setUsername($username)
        ->setPassword($password)
        ->setStreamOptions($https);
    $mailer = Swift_Mailer::newInstance($transport);
    $message = Swift_Message::newInstance($subject)
        ->setFrom(array($username => 'x Project'))
        ->setTo($getter)
        ->setBody($content);
    $result = $mailer->send($message);
    $success = $result ? 0 : 1;
    return $result;
}
```
