### ISSUE TITLE
Need rcpt command

### ISSUE THREAD

**Issue by jknigga** [swiftmailer/swiftmailer#1181]
| Q                   | A
| ------------------- | -----
| Bug report?         | Yes
| Feature request?    | No
| RFC?                | No
| How used?           | Symfony
| Swiftmailer version | 3.2.5
| PHP version         | 7.2.8

### Observed behaviour
Trying to send mail, getting the following error:
Uncaught PHP Exception Swift_TransportException: "Expected response code 354 but got code "503", with message "503 5.5.2 Need rcpt command [mail.server.com]

It would appear that the RCPT command never gets sent to the server.

### Expected behaviour
The mail should send successfully.

### Example
In my trouble shooting, I sidestepped Symfony and I lifted the code directly from the [docs](https://swiftmailer.symfony.com/docs/sending.html#transport-types) and I was still getting the error:

> // Create the Transport
> $transport = (new Swift_SmtpTransport('smtp.example.org', 25))
> ->setUsername('your username')
> ->setPassword('your password')
> ;
> 
> /*
> You could alternatively use a different transport such as Sendmail:
> 
> // Sendmail
> $transport = new Swift_SendmailTransport('/usr/sbin/sendmail -bs');
> */
> 
> // Create the Mailer using your created Transport
> $mailer = new Swift_Mailer($transport);
> 
> // Create a message
> $message = (new Swift_Message('Wonderful Subject'))
>   ->setFrom(['john@doe.com' => 'John Doe'])
>   ->setTo(['receiver@domain.org', 'other@domain.org' => 'A name'])
>   ->setBody('Here is the message itself')
>   ;
> 
> // Send the message
> $result = $mailer->send($message);

**Comment by bhulsman** [comment]
@jknigga Did you find a solution for this?

**Comment by jknigga** [comment]
@bhulsman Nope, I never did.

**Comment by gadget60** [comment]
I've had the same error message here. Turned out it actually was a relaying issue - unfortunately the exception is thrown on "503 5.5.2 Need rcpt command", while the previous answer "550 5.7.1 Unable to relay" has been ignored. This lead me on a wrong path for quite a while. Here's a tcp dump:

![image](https://user-images.githubusercontent.com/23076771/57459051-c34dba00-7272-11e9-80e8-cd2042b9573e.png)

Hope this helps anyone...

**Comment by groovenectar** [comment]
Is this related to #1240 ? I am experiencing the same issue:

`Expected response code 354 but got code "503", with message "503 5.5.2 Need rcpt command "`
