### ISSUE TITLE
Missing @throws from docblocks that throw exceptions

### ISSUE THREAD

**Issue by jpswade** [swiftmailer/swiftmailer#1183]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | yes
| How used?           | -
| Swiftmailer version | master
| PHP version         | -

### Observed behaviour
The send() functions and functions that consume it do not document in the DocBlock that they throw errors.

### Expected behaviour
There should be `@throws` in the docblock for functions that throw exceptions.

### Example

For example, here's the throw:

https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Transport/AbstractSmtpTransport.php#L195

Yet the docblock does not contain an `@throws` property.

**Comment by fabpot** [comment]
We do  not document all possible exceptions in the phpdocs.

**Comment by jpswade** [comment]
> We do not document all possible exceptions in the phpdocs.

Why not?

> This tag is used to present in your documentation which error COULD occur and under which circumstances. It is RECOMMENDED to provide a description that describes the reason an exception is thrown.
>
>It is also RECOMMENDED that this tag occurs for every occurrance of an exception, even if it has the same type. By documenting every occurance a detailed view is created and the consumer knows for which errors to check.

~ https://docs.phpdoc.org/references/phpdoc/tags/throws.html
