### ISSUE TITLE
6.2.0 - Call to a member function getReaderFor()

### ISSUE THREAD

**Issue by PhilETaylor** [swiftmailer/swiftmailer#1184]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           |Symfony
| Swiftmailer version | v6.2.0
| swiftmailer-bundle | v3.2.4
| PHP version         | 7.3.3

### Observed behaviour

Error: `Error: Call to a member function getReaderFor() on null`

from 

https://github.com/swiftmailer/swiftmailer/blob/c64ebb091bc9a4a7d8c4e81aae570d4fe759c026/lib/classes/Swift/CharacterStream/CharacterStream.php#L213

```
Error: Call to a member function getReaderFor() on null
#28 vendor/swiftmailer/swiftmailer/lib/classes/Swift/CharacterStream/CharacterStream.php(213): write
#27 vendor/swiftmailer/swiftmailer/lib/classes/Swift/CharacterStream/CharacterStream.php(136): importString
#26 vendor/swiftmailer/swiftmailer/lib/classes/Swift/Encoder/QpEncoder.php(177): encodeString
#25 vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/HeaderEncoder/QpHeaderEncoder.php(62): encodeString
#24 vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php(356): getTokenAsEncodedWord
#23 vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php(276): encodeWords
#22 vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/UnstructuredHeader.php(103): getFieldBody
#21 vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderSet.php(309): toString
#20 vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(529): toByteStream
#19 vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(601): toByteStream
#18 vendor/swiftmailer/swiftmailer/lib/classes/Swift/Message.php(162): toByteStream
#17 vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(398): streamMessage
#16 vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(500): doMailTransaction
#15 vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(516): sendTo
#14 vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): send
#13 vendor/snc/redis-bundle/SwiftMailer/RedisSpool.php(85): flushQueue
#12 vendor/symfony/swiftmailer-bundle/Command/SendEmailCommand.php(115): recoverSpool
#11 vendor/symfony/swiftmailer-bundle/Command/SendEmailCommand.php(86): processMailer
#10 vendor/symfony/swiftmailer-bundle/Command/SendEmailCommand.php(65): execute
#9 vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): run
#8 vendor/jmose/command-scheduler-bundle/Command/ExecuteCommand.php(236): executeCommand
#7 vendor/jmose/command-scheduler-bundle/Command/ExecuteCommand.php(150): execute
#6 vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): run
#5 vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(978): doRunCommand
#4 vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(86): doRunCommand
#3 vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(255): doRun
#2 vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(74): doRun
#1 vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): run
#0 bin/console(31): null
```

### Example

My app runs `php bin/console s:s:s` every min to flush the queue of emails, once a week Im obviously sending to someone with some crazy chars in the body of the email (A domain name with these chars in it`ø æ`) and I get the above fatal error/stack trace. 

This has only recently happened. Maybe after upgrading to 6.2.0 which has deprecated Swift_CharacterStream_NgCharacterStream in the changelog.

**Comment by PhilETaylor** [comment]
I have been trying to replicate this issue but failed to replicate it :( 

```
<?php

// composer.json
/*
{
    "require": {
        "swiftmailer/swiftmailer": "^6.2",
        "twig/twig": "^2.7"
    }
}
 */
error_reporting(E_ALL);
ini_set('display_errors',1);

require_once 'vendor/autoload.php';

$loader = new \Twig\Loader\ArrayLoader([
    'index' => 'Hello {{ name }}!',
]);
$twig = new \Twig\Environment($loader);

// Create the Transport
// use Mailhog with docker:
// docker run -p 8025:8025 -p 1025:1025 mailhog/mailhog
$transport = (new Swift_SmtpTransport('127.0.0.1', 1025));

// Create the Mailer using your created Transport
$mailer = new Swift_Mailer($transport);

// Create a message
$message = (new Swift_Message('http://nørregaardtræpleje.dk/'))
    ->setFrom(['john@nørregaardtræpleje.dk' => 'John Doe'])
    ->setTo(['receiver@nørregaardtræpleje.dk', 'other@nørregaardtræpleje.dk' => 'A name'])
    ->setBody($twig->render('index', ['name' => 'http://nørregaardtræpleje.dk/']), 'text/html')
    ->addPart($twig->render('index', ['name' => 'http://nørregaardtræpleje.dk/']), 'text/plain')

;

// Send the message
$result = $mailer->send($message);
```

**Comment by PhilETaylor** [comment]
I just built a complete Symfony 4 framework app to test this, I still cannot replicate it :( 

Any ideas why I might have this issue in production anyone?

**Comment by PhilETaylor** [comment]
I have now been unable to replicate this anywhere else other than my production platform on the live servers. 

I even spent hours replicating my whole production stack locally (Docker, PHP 7.3.3 Symfony 3.4) last night, and I was unable to replicate this issue.  I'm concerned because the issue relates to something that was changed in 6.2.0, but if I cannot replicate it then I cannot expect you to fix an imaginary issue. 

I'll leave this issue open for a week, to see if anyone else has this issue, or if the maintainers can comment what they might think the root cause is, and if not then we can close and Ill just accept it as "one of those things".

**Comment by za4me** [comment]
Have the same issue on locale but in beta everything is okay.

**Comment by PhilETaylor** [comment]
My production/live system just gave the same error today 

` Error: Call to a member function getReaderFor() on null`

on processing the string `http://nørregaardtræpleje.dk/` in an email, but again I have been unable to reproduce in any test builds I make. :-(

**Comment by andreiciceu** [comment]
Happend to me in production to, failed to replicate on live.
Temp fix, reverted to version 6.1.3 of swiftmailer/swiftmailer

**Comment by fabpot** [comment]
I've reverted the change and released 6.2.2. Hopefully, this will fix this issue.

**Comment by jacekkarczmarczyk** [comment]
@fabpot The problem was (at least in my case) that that change you've reverted changed the format of serialized mails, so mails queued before the change were not possible to unserialize with the new version. That was definitely a breaking change, so I'm not sure how it is covered in unit tests but the format of serialized mails should in patch or minor releases

**Comment by PhilETaylor** [comment]
Yes I had that both on upgrading and on the 6.2.2 revert version. The serialization of the emails into a redis based queue were different between the versions, and I had to delete the swiftmailer redis queue manually on upgrade/downgrade thus losing any mails in the queue. Therefore this was a b/c breaking change initially, and on the revert of the feature. 

I still never got to the bottom of the root issues with encoding, and its not returned since 6.2.2
