### ISSUE TITLE
Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in C:\xampp\htdocs\test\form.php on line 10

### ISSUE THREAD

**Issue by BustedSLS** [swiftmailer/swiftmailer#1185]
.....
    if ($_POST['password'] == $_POST['confirmpassword']){

        $username = mysqli->real_escape_string($_POST['username']);
        $email = $mysqli->real_escape_string($_POST['email']);
        $password = md5($_POST['password']); //md5 hash password security
        $avatar_path = $mysqli->real_escape_string('images/'.$_FILES['avatar']['name']);

.....

can you help me

**Comment by xabbuh** [comment]
You are missing a `$` in front of `mysql` on the first line.
