### ISSUE TITLE
Domain Key Signer Documentation is Wrong

### ISSUE THREAD

**Issue by ElyBob** [swiftmailer/swiftmailer#1189]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
 Feature request?    | no

### Observed behavior
at https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Signers/DomainKeySigner.php#L238 it says defaults to sha256, however sha256 is not mentioned anywhere else in the class nor implemented. AND it defaults to sha1 see: https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Signers/DomainKeySigner.php#L44

This is throwing a violation in Veracode as being a risky cryptographic approach.

### Expected behaviour
documentation matches behavior either default sha1 in docs, or implement default sha256 behavior.

### Example
see links in description..

**Comment by Rotzbua** [comment]
You should use dkim. Domainkeys are outdated.

**Comment by tuxedobob** [comment]
DKIM is not mentioned anywhere in the swiftmalier documentation.
