### ISSUE TITLE
phpdoc of Swift_Mailer::send() does not mention thrown exception

### ISSUE THREAD

**Issue by AlexHaaniWink** [swiftmailer/swiftmailer#1193]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| RFC?                | yes
| How used?           | 3party
| Swiftmailer version | 5.4.8

The documentation does mention that a `Swift_TransportException` can be thrown. But shouldn't the phpdoc of `\Swift_Mailer::send()` then also mention that it can throw an exception?

**Comment by fabpot** [comment]
We're not adding all possible exception everywhere.
