### ISSUE TITLE
Feature request: Receiving messages

### ISSUE THREAD

**Issue by abelardolg** [swiftmailer/swiftmailer#1194]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| RFC?                | no
| How used?           | Symfony/
| Swiftmailer version | Symfony CLI version v4.4.4
| PHP version         | 7.3.1

### Example

Now, Swiftmailer only sends mails...but it hasn't got any method to receive ones.

Regards.

**Comment by fabpot** [comment]
That's something very different and won't be added to Swiftmailer.
