### ISSUE TITLE
Fortify Swiftmailer Privacy Violation in PopBeforeSmtpPlugin.php

### ISSUE THREAD

**Issue by Rohit272** [swiftmailer/swiftmailer#1195]
Hi,

Fortify scan is throwing critical issue in vendor/swiftmailer/swiftmailer/lib/classes/Swift/Plugins/
PopBeforeSmtpPlugin.php, , line 213 (Privacy Violation).

Sink: fwrite()
Enclosing Method: command()
File: vendor/swiftmailer/swiftmailer/lib/classes/Swift/Plugins/PopBeforeSmtpPlugin.php:213
Taint Flags: PRIVATE

Is there any workaround or fix that can be applied here. Could this be taken care in the future versions .

Thanks

**Comment by laharshah** [comment]
@fabpot , So what is a resolution to the issue? Can you please provide some information on it! Thank you!
