### ISSUE TITLE
Add snapshot test for serialized mails format

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [swiftmailer/swiftmailer#1197]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| RFC?                | no
| How used?           | -
| Swiftmailer version | 6.2.1
| PHP version         | any

This change https://github.com/swiftmailer/swiftmailer/commit/f62331c8fe0d6ebfa15e72b77ad8a02b67a545dd (and corresponding one) appeared to be the breaking change as due to changed names of used classes the format of serialized mails also changed making impossible to read mails that were created earlier (FileSpool in version 6.2.0 queued mails, and then the next version of SwiftMailer tried to send them)

Adding a simple snapshot test would help to avoid such problems in the future

**Comment by fabpot** [comment]
Sorry for the issue. Nothing we can anymore. So, closing.
