### ISSUE TITLE
ErrorException: fwrite(): SSL operation failed with code 1. OpenSSL Error messages: error:140D00CF:SSL routines:SSL_write:protocol is shutdown in laravel/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:231

### ISSUE THREAD

**Issue by doubleyolk** [swiftmailer/swiftmailer#1212]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | yes/no
| How used?           | Laravel
| Swiftmailer version |Default came in laravel
| PHP version         | 7.3

### Observed behaviour
While sending concurrent emails through queued jobs  getting this exception resulting failure of the job and failure of the email delivery

### Expected behaviour
Email should be sent

**Comment by victoretibr** [comment]
This issue when trying to send email campaigns with Mautic + Amazon SES

**Comment by sawmurai** [comment]
@victoretibr Have you found a solution? We experience the same issue

**Comment by dschiffel** [comment]
@victoretibr @sawmurai @doubleyolk  Working for me now... after disabling ssl for swiftmailer
```
    stream_options:
        ssl:
            verify_peer: false
            verify_peer_name: false
```

**Comment by robschaefer** [comment]
@dschiffel 

i just woke up to this error :-)  can you tell me what file those stream_options need to go into?

Thanks!

**Comment by jimmyorpheus** [comment]
Having the same issue with swiftmailer 6.2.3.
I am requesting to reopen this issue, since in many cases disabling ssl is not an option.

**Comment by aldotopciu** [comment]
Same issue here.

**Comment by dokicro** [comment]
Same issue here. Following
