### ISSUE TITLE
 PHP Warning:  fwrite(): SSL operation failed with code 1. OpenSSL Error messages: error:1409E10F:SSL routines:ssl3_write_bytes:bad length in /var/www/mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 240

### ISSUE THREAD

**Issue by victoretibr** [swiftmailer/swiftmailer#1213]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | yes/no
| How used?           | Mautic
| Swiftmailer version | Default came in Mautic
| PHP version         | 7.2.19

### Observed behaviour
While sending concurrent emails through queued jobs getting this exception resulting failure of the job and failure of the email delivery

### Expected behaviour
Email should be sent

### Example
php app/console mautic:emails:send

**Comment by victoretibr** [comment]
php app/console mautic:emails:send

                                                                                                          
  [Swift_TransportException]                                                                                    
  Expected response code 250 but got code "451", with message "451 4.4.2 Timeout waiting for data from client.  
  "                                                                                                             
                                                                                                              
PHP Warning:  fwrite(): SSL: Broken pipe in /var/www/mautic/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 240

**Comment by Isitar** [comment]
any updates on this issue?

**Comment by dschiffel** [comment]
same problem! any updates on this issue?

**Comment by dschiffel** [comment]
@victoretibr @Isitar  Working for me now... after disabling ssl for swiftmailer
```
    stream_options:
        ssl:
            verify_peer: false
            verify_peer_name: false
```

**Comment by deepkesh26** [comment]
I was getting the same error for ssl://gateway.push.apple.com:2195. It is working for a sandbox mode but not for production mode. So I have restarted the apache server and it works

**Comment by kaistaerk** [comment]
i have the same problem. does anyone has any suggestion?

**Comment by oktaykalfa** [comment]
having the same problem. any solution?

**Comment by japo32** [comment]
We encountered this issue today. Why was this issue closed @fabpot ?

**Comment by Isitar** [comment]
in our case the issue occoured only when sending many mails, we ended up doing batch-processing for this application and resolved the issue this way

**Comment by japo32** [comment]
> in our case the issue occoured only when sending many mails, we ended up doing batch-processing for this application and resolved the issue this way

it's a good workaround, but doesn't really fix the issue. :(
How many emails did you make each batch to make it work @Isitar ?

**Comment by Isitar** [comment]
The batch size is 10, then we wait for 1 second
