### ISSUE TITLE
Handling iso-2022-jp encoding for base64

### ISSUE THREAD

**Issue by ganchiku** [swiftmailer/swiftmailer#122]
Header encoding for base64 does not work in JIS code (iso-2022-jp).
base64_encode is working properly, but splitting 76 characters cannot handle after encoding. To do this, we have to check each character to encode to base64.
The easiest way to solve this is using mb_encode_mimeheader, but the usage of mb_encode_mimeheader is not very clean, since we always have to set mb_internal_encoding before calling mb_encode_mimeheader. And after using it, re-set the mb_internal_encoding again.

Also, I would like to mention using iconv functions or mbstring functions. iconv functions cannot handle some Japanese texts, so we have to check the existence of mbstring earlier than iconv functions.

Actually, I'm working with this right now, and will pull request when it finished.

**Comment by jchook** [comment]
For others with this problem, [symfony/mime](https://github.com/symfony/mime/blob/c4457ae2453d8d2a10b15fc4adefea517131047a/Encoder/Base64MimeHeaderEncoder.php#L32) uses the `mb_encode_mimeheader()` as ganchiku described.
