### ISSUE TITLE
SMTP Validation before Mail Sent

### ISSUE THREAD

**Issue by admin9039** [swiftmailer/swiftmailer#1223]
How we check smtp validation before mail in swiftmailer.

**Comment by TheDigitalOrchard** [comment]
I'd love to know this, too!

I've run into problems such as the FROM header containing parentheses and I think these are not valid without being escaped. If we had a way to validate before sending, these types of problems could be identified and corrected early.

**Comment by davereid** [comment]
I could also use this feature to help add some additional monitoring to a site to know if there are any issues with our SMTP server.

**Comment by davereid** [comment]
I found this useful too: https://laracasts.com/discuss/channels/general-discussion/check-smtp-connection
