### ISSUE TITLE
Remove proc_open

### ISSUE THREAD

**Issue by Starlette** [swiftmailer/swiftmailer#1224]
Can I use this without having to use proc_open ?

**Comment by TheDigitalOrchard** [comment]
Docs say that the proc_* functions are required.

StreamBuffer requires `proc_open()` and `proc_close()`.

What is the reason you want to avoid using these functions? Your hosting environment? If so, my best recommendation is change providers. Take control of your hosting environment. Don't let your hosting company restrict what you can do with your sites.
