### ISSUE TITLE
exception 'Swift_TransportException' with message 'Failed to authenticate SMTP server" using 2 possible authenticators

### ISSUE THREAD

**Issue by amrithadevadiga** [swiftmailer/swiftmailer#1228]
I am using google apps paid service to send emails from my domain. simply routing emails sent from my server through gmail smtp.
using swiftmailer.org script to do so.
It was working fine till last month, but suddenly it started giving this error.

Fatal error: Uncaught exception 'Swift_TransportException' with message 'Failed to authenticate on SMTP server with username "myem...@gmail.com" using 2 possible authenticators' in /home/cultures/public_html/swift/lib/classes/Swift/Transport/Esmtp/AuthHandler.php 

is there any other way I can send emails to my clients inbox other than gmail.?? please suggest only free one I already paid google and Ns thing is now stopped working.

I used this belowlink to test but didnt work
https://stackoverflow.com/questions/57373133/why-im-getting-swift-transportexception-unable-to-connect-with-tls-encryption

**Comment by faltrock-abone** [comment]
Same problem, but with Office365 / Microsoft. Trying to see if there is some security setting, but no luck so far.
