### ISSUE TITLE
Enhancement: Support SMTP keywords RET, ENVID, NOTIFY, ORCPT

### ISSUE THREAD

**Issue by ThomasLandauer** [swiftmailer/swiftmailer#126]
Hi,

please make it possible to hand these commands over to the SMTP server:
MAIL FROM: me@home.com RET=full ENVID=12345
RCPT TO: somebody@example.com NOTIFY=success,delay,failure ORCPT=rfc822;somebody@example.com

As far as I can tell, that's the purpose of the functions getMailParams() and getRcptParams() - however, they are not really implemented yet :-(

I'd be willing to contribute, if you can give me a hint as to where to start ;-)

Thanks!!

**Comment by hm122** [comment]
+1 for DSN feature

**Comment by nabab** [comment]
+1 for DSN feature

**Comment by DeanWard** [comment]
Did anything ever happen with this?
