### ISSUE TITLE
The function setReplyTo() does not work

### ISSUE THREAD

**Issue by ciitelecom** [swiftmailer/swiftmailer#1262]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Standalone
| Swiftmailer version | 6.2-dev
| PHP version         | 7.3.6

### Observed behaviour
When setting "replyTo" with setReplyTo() or addReplyTo() methods, the header "Reply-To" is not present in the mail.
Example:
Subject: Subject of the mail
From: "Name of the sender" <sender@mydomain.com>
To: user@otherdomain.com

### Expected behaviour
Example:
Subject: Subject of the mail
From: "Name of the sender" <sender@mydomain.com>
Reply-To: contact@mydomain.com
To: user@otherdomain.com

### Example
addReplyTo("contact@mydomain.com") produces this warning:
PHP Warning:  Illegal string offset 'contact@mydomain.com' in swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php on line 243
PHP Warning:  preg_split() expects parameter 2 to be string, array given in swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php on line 312

setReplyTo(array("contact@mydomain.com")) 
OR
setReplyTo(array("contact@mydomain.com" => "")) 
OR
setReplyTo("contact@mydomain.com") 
OR
setReplyTo("contact@mydomain.com", "") 

In fact, addReplyTo() calls setReplyTo() which calls other methods giving always an array as second parameter.
It finishs with a PHP Warning because preg_split() expects to receive a string in the second parameter "$string", but in the case of setReplyTo() method it receives an array.
So the header "Reply-To" is not set in the mail which is really a problem for us.

Solution found modifying the method "getEncodableWordTokens" in the file "swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php":

`
protected function getEncodableWordTokens($string)
{
    $tokens = [];

    $encodedToken = '';
    if(!empty($string)) {
        if(is_array($string)) {
            $arrayKeys = array_keys($string);
            if(is_array($arrayKeys) && count($arrayKeys) > 0) {
                $string = array_shift($arrayKeys);
            }
        }
        // Split at all whitespace boundaries
        foreach (preg_split('~(?=[\t ])~', $string) as $token) {
            if ($this->tokenNeedsEncoding($token)) {
                $encodedToken .= $token;
            } else {
                if (strlen($encodedToken) > 0) {
                    $tokens[] = $encodedToken;
                    $encodedToken = '';
                }
                $tokens[] = $token;
            }
        }
        if (strlen($encodedToken)) {
            $tokens[] = $encodedToken;
        }
    }

    return $tokens;
}
`

**Comment by leftdevel** [comment]
I'm facing a similar issue. I use gmail, and I can see the "reply-to" header in the raw email text, but for some reason the gmail app will ignore this header and will reply automatically to the "from" address. 

It seems this used to work before, but not anymore. It could be a client issue rather than this library. Thoughts?
