### ISSUE TITLE
syntax error, unexpected '->' (T_OBJECT_OPERATOR)

### ISSUE THREAD

**Issue by Ravindrakumara** [swiftmailer/swiftmailer#1268]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| RFC?                | yes/no
| How used?           | Standalone/Symfony/3party
| Swiftmailer version | x.y.z
| PHP version         | x.y.z

**Comment by xabbuh** [comment]
Please provide more information about your issue. How can one reproduce it? Which Swiftmailer and PHP version do you use? What is the stack trace for this error?
