### ISSUE TITLE
Don't know how to handle the case when connection is refused by a mail server.

### ISSUE THREAD

**Issue by Arkasian** [swiftmailer/swiftmailer#1269]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Symfony
| Swiftmailer version | 3.0
| PHP version         | 7.3.16

### Observed behaviour

My code just uses:  *send($message, $errors);*
There are 3 mail addresses set as receipents, correctly set to headers as "To".
Each receipent should receive just a 1 message, so in a summary: there are 3 messages to be sent.
Even that the connection is refused(just because there is not mail server on localhost) method send() returns 1 as a result... why?
### Expected behaviour

It should allow to handle Connection refused error, or return this as a string message in $errors array.
### Example

Because by default, SwiftMailer uses SpoolTransport, which implements Transport interface on its own, there is no place in StackTrace to handle an exception thrown by StreamBuffer then AbstractSmtpTransport, just because the AbstractSmtpTransport is not in the same trace as the SpoolTransport instance: one __do not__ inherit after the second one.
Thus, I suggest to throw it higher so the users can handle it on their own or to pass the information in $errors array.

P.S: I guess I may be wrong, and please correct me if I am mistaken, thus if so, I am very sorry about wasting your time.

**Comment by cluster28** [comment]
Hi @Arkasian i'm looking for the same solution. There's no way to check if there's any problem with the server. I found that [https://swiftmailer.symfony.com/docs/plugins.html#logger-plugin](https://swiftmailer.symfony.com/docs/plugins.html#logger-plugin) but I still don't know how to use it and if it's what we're looking for.

**Comment by Arkasian** [comment]
Sure, it can help sysops because it will log all problems with server from all around the SwiftMailer, but for us, I guess it has no real usage, as we want to avoid parsing logs to receive just as simple information as that the connection was refused or something. In my opinion they should just pass that information somehow higher in errors array or just leave the exception for user to be caught.

**Comment by cluster28** [comment]
I'm using Symfony so i could feedback the errors via Slack with [swiftmailer-bundle](https://github.com/symfony/swiftmailer-bundle/blob/master/EventListener/EmailSenderListener.php#L64)

**Comment by Arkasian** [comment]
Tell me more about it, I don't know that, and I am using Symfony too. 3.4/4.4 with SwiftMailer.

**Comment by cluster28** [comment]
Hi @Arkasian:

Do you have this configuration in swiftmailer declaration?

`spool:          { type: memory }`

If true the mails are sent at the end of the request so Symfony use this [listener](https://github.com/symfony/swiftmailer-bundle/blob/master/EventListener/EmailSenderListener.php) to send.

I had this configuration in my project but I removed it and I refactored the code to send mails directly when [send](https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Mailer.php#L59) method is called. This way if it fails an Exception is thrown and you can handler the error. 

In my case i send this error to slack with [monolog](https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/Configuration.php#L225). I both cases you can send the error to slack.

Hope this helps you.

**Comment by Arkasian** [comment]
As far as I remember there is such configuration done in my project. I have to try it out. Thanks for a clue @cluster28 . I will get back to you if it will work for me too.
