### ISSUE TITLE
Expected response code 220 but got an empty response

### ISSUE THREAD

**Issue by AdrianCarreno** [swiftmailer/swiftmailer#1271]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| RFC?                | no
| How used?           | Symfony
| Swiftmailer version | 6.2.1
| PHP version         | 7.3.14

### Observed behaviour
I use Swiftmailer in Laravel to send messages to a mailgun server. It worked fine for the last 6 months, but lately I've been encountering errors regarding an empty response. Googling returns answers to what I think is a similar problem ("Expected response code 220 but got code "", with message ") but as the message is not the same, I don't know if it's the exact same error and the solutions don't help me. As far as I know Laravel is using TLS as I haven't changed that setting.
I can't replicate the error, we send almost 100 mails daily and just a few return this error. Haven't figured out what fails.
### Expected behaviour
The mail should be consistent in succeeding or failing, but it only occurs sometimes.

### Example
Can't reproduce.

### Logs
Attached an example log
[laravel-2020-04-06.log](https://github.com/swiftmailer/swiftmailer/files/4440186/laravel-2020-04-06.log)

Is the problem related to my coding, my mail provider or is it just the package? The problem is happening on a server **in production** so I don't want to update just for the sake of it.

**Comment by alexpgates** [comment]
@AdrianCarreno +1
I'm experiencing the same. I've seen an uptick after upgrading to Laravel 7. I can't reliably replicate the error, either. 

Have you made any progress finding a solution?

Are you using a queue system to send your mail? I'm using Horizon.
