### ISSUE TITLE
Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients

### ISSUE THREAD

**Issue by rhlsingh001** [swiftmailer/swiftmailer#1274]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| RFC?                | yes/no
| How used?           | Standalone/Symfony/3party
| Swiftmailer version | x.y.z
| PHP version         | x.y.z

**Comment by oyenet1** [comment]
1. ![WhatsApp Image 2021-06-03 at 00 35 50 (1)](https://user-images.githubusercontent.com/55518926/125195743-e7402800-e24e-11eb-8dc2-29d3d53bcb7f.jpeg)
