### ISSUE TITLE
The Documentation is bad.

### ISSUE THREAD

**Issue by tuxedobob** [swiftmailer/swiftmailer#1278]
I'm sorry to say this, but the documentation for Swift Mailer is bad.

I'm currently trying to figure out whether it's possible for Swift Mailer to send emails with DKIM headers. There are references to it. Whispers across the web in places like https://stackoverflow.com/questions/31591078/. But that page references a class called Swift_Signers_DKIMSigner which is found nowhere in Swift Mailer's documentation. It mentions Swift_SignedMessage, also found nowhere in the documentation.

If this feature is part of the default Swift Mailer installation, and not provided via a plugin or a forked version, what version of Swift Mailer is it available in? For that matter, what is the current version of Swift Mailer? I have an old version from pre-Composer days. The "recommended" way to install Swiftmailer is via composer. Is there any other way? Is the project officially "Swift Mailer" (as it is in most of the documentation) or "Swiftmailer" (as it is in the Installation section)?

I realize it's a very peculiar sort of person who actually enjoys writing documentation, but it does a disservice to the people who work and have worked on the project for the documentation to be so lacking, as I'm sure Swift Mailer has features that many people don't even know exist or don't know how to use. Why spend all that effort implementing a feature only to have nearly nobody use it?

**Comment by zord1k** [comment]
Take any version you like: https://github.com/swiftmailer/swiftmailer/tags

**Comment by malohtie** [comment]
documentation not bad it very bad
