### ISSUE TITLE
Autoloading, Namespacing, etc.

### ISSUE THREAD

**Issue by oojacoboo** [swiftmailer/swiftmailer#1280]
Are these any intentions to update this lib so it's not such a hack job in terms of autoloading/lazy-loading, namespacing, etc?

I'm running into an issue now that appears to be preloading related and an issue due to lazy-loading.  I really don't see the benefit of lazy-loading with preload capabilities.  Maybe 10 years ago it made sense.

Also, namespacing would be great, in addition to class names that aren't underscored.

**Comment by oojacoboo** [comment]
Having to explicitly call

`\Swift::autoload('Swift_Mime_Attachment');`

in our autoloading logic. Otherwise, I get the error: `Too few arguments to function Swift_Mime_Attachment::__construct(), 0 passed`.  I've already read about other getting similar errors.

All of this is because of the autoloading situation going on with Swiftmailer.  It really need to be refactored to conform to some standards.

**Comment by fabpot** [comment]
The good news is that the work has already been done. The "modern" successor of Swiftmailer is Symfony Mailer, which is derived from Swiftmailer and supports more features (like using third(party providers).

https://symfony.com/doc/current/components/mailer.html
