### ISSUE TITLE
Unable to send SSL/TLS smtp emails from Laravel 7

### ISSUE THREAD

**Issue by chilio** [swiftmailer/swiftmailer#1286]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | yes
| How used?           | Laravel 7
| Swiftmailer version | 6.2.3
| PHP version         | 7.4.5

### Observed behaviour
`Swift_TransportException
Connection could not be established with host ... :stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed`

### Expected behaviour
Working -> I think there was a breaking change in underlying libs and used encryption methods, cause I have systems where it is working with the exactly same swiftmailer version.

### Example to reproduce
1. Install latest Laravel 7.
2. Create proper configs and mails.
3. Try to send email with port 587 and tls enabled. Error:
`stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed`
4. Try to send email with port 465 and ssl enabled. Error:
`Connection could not be established with host ... :stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed`

### Please note that:
1. Configs are 100% validated and I can send emails from many different systems, but not using this library.
2. I've tried different smtp mailing vendors and the results are identical.

**Comment by aikutto** [comment]
Is there any solution or workaround?

**Comment by ionasrobert** [comment]
This works

`MAIL_MAILER=**sendmail** 

MAIL_HOST=server.domain.com

MAIL_PORT=465

MAIL_USERNAME=office@domain.com

MAIL_PASSWORD=29390399393#@

MAIL_ENCRYPTION=SSL

MAIL_FROM_ADDRESS=office@domain.com

MAIL_FROM_NAME="${APP_NAME}"`

**Comment by chilio** [comment]
@fabpot why close? Issue is not solved....

**Comment by LucasSequeira** [comment]
Hi! can you resolved? i have this problem with laravel 7

**Comment by chilio** [comment]
Hi @LucasSequeira unfortunately not. I was hoping to get solution here, but it seems op @fabpot  is not interested.

**Comment by LucasSequeira** [comment]
@chilio :S 

when i can use phpmailer in laravel 7. it works for me.

https://packagist.org/packages/phpmailer/phpmailer

good luck bro!

**Comment by davorpeic** [comment]
Also having issues with live server and L7
