### ISSUE TITLE
Too many files in /tmp directory

### ISSUE THREAD

**Issue by mankowitz** [swiftmailer/swiftmailer#1287]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| RFC?                | yes
| How used?           | Symfony (Laravel)
| Swiftmailer version | 6.2.3
| PHP version         | 7.4.1

### Observed behaviour
creates many files (>1700) in /tmp directory

### Expected behaviour
occasionally remove unneeded files, or at least help me identify which files may be removed

### Example
Use Laravel to send mail; reboot server only rarely

**Comment by valerio-bozzolan** [comment]
I would like to help but I cannot reproduce.

Can you inspect one of these temporary files to discover if they are really created/related to/by swiftmailer?

**Comment by Kwaadpepper** [comment]
It happens when using queue:work.
This is because these files are remove using  __destruct in swiftmailer

And it is not trigerred when using queue:work but it works when using queue:listen

**Comment by mfn** [comment]
> It happens when using queue:work.

This triggered my curiosity but I'm using horizon actually and have non such files in `/tmp`

Btw, that's the naming pattern of these files? Maybe they're located somewhere else I'm not aware of.

I found https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/ByteStream/TemporaryFileByteStream.php#L39

which uses the name from https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/ByteStream/TemporaryFileByteStream.php#L18

I couldn't find anything on my systems related to `FileByteStream`; but is that the name pattern you're seeing?

---
and more curious: why would it work with horizon in my case.

Horizon gets restarted a few but at least once a day in my case; maybe this than triggers the destruct calls. But: I'm sending lots-o-mails and even before a potential restart, I see nothing 🤷‍♀️

**Comment by Kwaadpepper** [comment]
We have this issue on one of our project. With laravel with supervisor.

It creates folders like ```06eec2faff68397e5659dcf74ef407f6/body``` with the mail body in it.

**Comment by mankowitz** [comment]
AFAIK, rebooting the machine cleans out the /tmp directory in most unix flavors, which may explain why @mfn is not seeing so many files. My files are of the same formant as described by @Kwaadpepper. I am using Laravel 8 and also using supervisor to run queue:work

**Comment by mfn** [comment]
The machines are not rebooted in my case. I mean, yes _eventually_. The last time roughly a month ago but we're sending out north of 100k emails / day, so if there would be temporary files, they would be there.

Note: I'm using it also as part of Laravel 8.40.0 and swiftmailer v6.2.7 and horizon 5.7.6, also using supervisor but only for `artisan horizon` to run

**Comment by Kwaadpepper** [comment]
The servers in my case are also not rebooted too often. So /temp is not cleared. We had an uptime of more 200 days. However I for e the temp folder to be in Laravel storage/too and make a scheduled job to clean old folders of more than few hours. But this is not so efficient.
As I said before with queue:listen folders are destructed when sent. 
What is the main difference between listen and work ?

**Comment by mfn** [comment]
>  What is the main difference between listen and work ?

https://laravel.com/docs/8.x/queues#the-queue-work-command
> Note that once the queue:work command has started, it will continue to run until it is manually stopped or you close your terminal:
…
> When using the queue:listen command, you don't have to manually restart the worker when you want to reload your updated code or reset the application state; however, this command is significantly less efficient than the queue:work command

I guess that explains it.

I'd argue that `queue:listen` is useful for local dev mostly.

**Comment by Kwaadpepper** [comment]
How ever _destruct is never called with queue:work. I guess because the object is kept in memory? So the files aren't removed which is an issue.
Even queue:work is suited for production it has this side effect which is problematic.

**Comment by Kwaadpepper** [comment]
Just made an issue ticket on laravel framework, maybe someone there would have an idea ?

**Comment by Vusys** [comment]
I've had a similar issue with a different library, but same root cause. As a crappy work around, I put `rm -rf /tmp/*.bin` in the server's crontab.

**Comment by Vusys** [comment]
It was a different library - but one that also left behind files in `/tmp` because the destructor was not being called. In my case, I was able to schedule a time to clean them without impacting the application. But you could potentially use `find` to get files older than X minutes and delete them.

**Comment by Kwaadpepper** [comment]
@Vusys this is the only workaround that I could think of. However how could you be sure swift mailer has sent the mail and therefore the temp file can be deleted ? I mean with another condition than 'older than' on the system file.

**Comment by Vusys** [comment]
Without digging into Swift, it's hard to say. My understanding is that the files are used to store data about a single email, so surely after the email has been sent, the temporary file left behind is redundant. 

Personally I would experiment with deleting files older than 5 minutes and see if it has any adverse effect on the application. It seems like the simplest option.

I did take a brief look at Swift and Laravel's mailer, and I have no idea if this will work, but you could try using the after callback to forget the mailer, which should dereference the Swift mailer object and thus call the `__destruct` method. Something like:

```php
\Illuminate\Support\Facades\Queue::after(function (\Illuminate\Queue\Events\JobProcessed $event) {
    if($event->job->getName() === 'mail'){
        app(\Illuminate\Mail\MailManager::class)->forgetMailers();
    }            
});
```

**Comment by Kwaadpepper** [comment]
@Vusys oh this seems like a good option ! I'll experiment that Asap !
Indeed removing the file after 5 minutes could be the solution, but I'm not it is good for any transport type. I did not take enough time to experiment and I'm not familiar enough with swift mail.

I mean, if the file is generated and if there was some kind of delay in SMTP case for example. would swift mailer take a try after some time using the already generated temp file ?

I cannot make my experiments on production of course, so I would need to take some time just to be sure.

Any way thank you for your last tip !
