### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by ivose** [swiftmailer/swiftmailer#1288]
Parse error: syntax error, unexpected '?' in /home/way/public_html/ud/_app/libs/swiftmailer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php on line 490
My windows xampp localhost does not display the error. And in a server throw cpanel displays it.

| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| RFC?                | yes/no
| How used?           | Standalone/Symfony/3party
| Swiftmailer version | x.y.z
| PHP version         | x.y.z

**Comment by ivose** [comment]
The line has to be like  return isset($priority) ? $priority : 3; In a new version is a line return $priority ?? 3;. "??", maybe "?:".

**Comment by ivose** [comment]
Again i found from about 20 places this "??" instead of "? :". If a new version of php supports such syntax, then and older php versions. Then i'd like recomment to take this to use after some years. It's causes bigger problems.

**Comment by xabbuh** [comment]
It looks like you need to fix your server to use a PHP version higher than or equal to 7.2.5 as defined in Swiftmailer's `composer.json` file.

**Comment by ivose** [comment]
Good suggestion. If i change to higher version, then the bigger website has many-many errors, including "deprecated" messages. At current time i removed the swiftmailer and took another mailing code - PHPMailer. Anoter thing that i don't understant, why projects (including your swiftmailer) must contain many hundreds or even thousands files. It cause difficulties to uploading and repairing. Codes must to be possible "lightwaigt" possible few files.

**Comment by xabbuh** [comment]
I am glad that you were able to find a library that serves your needs. Could you please close this issue then as it does not look like there is anything to be done in Swiftmailer. :)
