### ISSUE TITLE
Do not depend on composer

### ISSUE THREAD

**Issue by robo2bobo** [swiftmailer/swiftmailer#1296]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| RFC?                | no
| How used?           | Standalone
| Swiftmailer version | 6.2.3
| PHP version         | 7.2.24

### Observed behaviour
Swiftmailer appears to offer the ability to run standalone without composer, unfortunately **this is not true**. If we try to use Swiftmailer as-is then we end up with the following error:

PHP Fatal error:  Uncaught ReflectionException: Class Egulias\EmailValidator\EmailValidator does not exist

Unfortunately, Egulias\EmailValidator has a heavy dependency/requirement on composer, thus Swiftmailer becomes dependent on composer by proxy.

### Expected behaviour
For those who don't want or can't use composer, due to various corporate restrictions or other issues with composer, we'd like to be able to use Swiftmailer easily without composer.

### Proposal
In my limited tests, I found that the dependencies on polyfill packages are ok and have no extra requirements and can be easily installed without composer. So the only real problem is with Egulias\EmailValidator. Our proposal, is to check for the existence of the Egulias\EmailValidator pacakge and if its not available then use a simple fallback function.

We prefer a usable Swiftmailer without composer, even if some features are missing.

Thank you.

**Comment by fabpot** [comment]
Recent versions of Swiftmailer needs Composer. I don't see anything in the docs that says it can be used standalone (can you tell me where you read this?). In any case, we won't support using Swiftmailer without Composer, so I'm closing this issue.

**Comment by robo2bobo** [comment]
In the introduction page it says that composer is the "recommended way".. not the only way. Ok, maybe I'm being pedantic :)

But honestly, please give this another chance, it feels like it should be an easy thing to implement and give the opportunity to Swiftmailer to run easily on more systems. For example, when EmailValidator is not available, to use PHP's native [data filtering](https://www.php.net/manual/en/book.filter.php)?

PS:
I made things work by simply loading the required classes manually:

```php
require_once 'assets/doctrinelexer/AbstractLexer.php';
require_once 'assets/emailvalidator/Validation/EmailValidation.php';
require_once 'assets/emailvalidator/Validation/RFCValidation.php';
require_once 'assets/emailvalidator/Parser/Parser.php';
require_once 'assets/emailvalidator/Parser/DomainPart.php';
require_once 'assets/emailvalidator/Parser/LocalPart.php';
require_once 'assets/emailvalidator/Warning/Warning.php';
require_once 'assets/emailvalidator/Warning/LocalTooLong.php';
require_once 'assets/emailvalidator/EmailLexer.php';
require_once 'assets/emailvalidator/EmailParser.php';
require_once 'assets/emailvalidator/EmailValidator.php';
require_once 'assets/swift/swift_required.php';
```

**Comment by xabbuh** [comment]
IMO that's not worth the effort. Composer is the way to go nowadays. By not adopting it for Swiftmailer you will only postpone issues you likely run into later when trying to use other libraries (for example the Symfony Mailer component which I would recommend to use instead of Swiftmailer).

**Comment by robo2bobo** [comment]
Composer will never be allowed within the corporate environments that I'm involved in, eventually something that absolutely requires composer will be replaced by another project that does not require composer. There are multiple reasons, all of them have to do with security and stability.

**Comment by dbrumann** [comment]
If composer is not allowed in your corporate environments you might want to consider using [private packagist](https://packagist.com/). I don't think you can reasonably expect open source maintainers to cater to your specific needs. If you want to replace it by an alternative that does not use composer or write and maintain the functionality yourself, you are free to do so.
