### ISSUE TITLE
Laravel Swift Mailer Error   [2020-10-13 23:18:41] local.ERROR: Expected response code 354 but got code "250", with message "250 Accepted " {"exception":"[object] (Swift_TransportException(code: 250): Expected response code 354 but got code \"250\", with message \"250 Accepted

### ISSUE THREAD

**Issue by RajbirSehrawat** [swiftmailer/swiftmailer#1300]
**I am using Swift Mailer with Laravel Version 7.0 and on server when sending email using Corn Job. This give below error.I make a lot of R&D to resolve this error. But There is no solution find for this on Internet.**

**This is the Error** 

[2020-10-13 23:18:41] local.ERROR: Expected response code 354 but got code "250", with message "250 Accepted
" {"exception":"[object] (Swift_TransportException(code: 250): Expected response code 354 but got code \"250\", with message \"250 Accepted
\" at /data/servercenter/public_html/servercenter.xyz/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:457)
[stacktrace]
#0 /data/servercenter/public_html/servercenter.xyz/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode('250 Accepted\
\
', Array)
#1 /data/servercenter/public_html/servercenter.xyz/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('DATA\
\
', Array, Array, false, NULL)
#2 /data/servercenter/public_html/servercenter.xyz/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(390): Swift_Transport_EsmtpTransport->executeCommand('DATA\
\
', Array, Array)

| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | yes/no
| How used?           | Laravel
| Swiftmailer version | 6.2-dev
| PHP version         | 7.3

**Comment by fabpot** [comment]
I'm sorry but we are only using the GitHub repository to discuss bugs and new features. For this kind of questions about using Swiftmailer, please use any StackOverflow.

Thanks!
