### ISSUE TITLE
PSR-4 autoload

### ISSUE THREAD

**Issue by Jeckerson** [swiftmailer/swiftmailer#1304]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| RFC?                | no
| How used?           | 3party
| Swiftmailer version | latest
| PHP version         | latest

### Observed behaviour
Any plans to adapt for PSR-4 compliance? Phan (code analyzer) has problems to detect the library's classes...

### Expected behaviour
Be PSR-4 compliant.

**Comment by fabpot** [comment]
You should probably use Symfony Mailer then. It's the "modern" version of Swiftmailer.
