### ISSUE TITLE
How does swiftmail use a proxy to send mail

### ISSUE THREAD

**Issue by waimaolang** [swiftmailer/swiftmailer#1305]
$opts = array('smtp' => array(
            'proxy' => 'tcp://49.89.103.159:4236',
            'request_fulluri'=>true,
        ),
            'http' => array(
                'proxy' => 'tcp://49.89.103.159:4236',
                'request_fulluri'=>true,

            )
        );

        $transport = (new Swift_SmtpTransport($params->smtpServer, $params->smtpPort, $params->smtpSSL))->
        setUsername($params->sendMailAccount)->
        setPassword($params->password)->setStreamOptions($opts);

According to my example, proxy cannot be used. What should I do

**Comment by DaPoHou** [comment]
I had the same problem.

**Comment by pablosebastianr** [comment]
Anyone able to solve this ? I have the same issue.
