### ISSUE TITLE
Laravel Error Class 'Swift_StreamFilters_StringReplacementFilter' not found

### ISSUE THREAD

**Issue by JimB14** [swiftmailer/swiftmailer#1306]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Laravel
| Swiftmailer version | 6.2.3
| PHP version         | 7.4.9

### Observed behaviour
Mail code stalls and then throws an error.
Error Class 'Swift_StreamFilters_StringReplacementFilter' not found

Swift_StreamFilters_StringReplacementFilterFactory::createFilter
vendor/swiftmailer/swiftmailer/lib/classes/Swift/StreamFilters/StringReplacementFilterFactory.php:40

Line 40: 
```
$this->filters[$search][$replace] = new Swift_StreamFilters_StringReplacementFilter($search, $replace);
```

### Expected behaviour
Send email (works fine on local machine with Mailtrap).
```
Mail::to('myemail@gmail.com')
                ->send(new ContactForm($data));
```
I replaced this code with PHP mail code to rule out host server. It works.
```
$to = 'myemail@gmail.com';
$subject = "Email Subject";
            
$message = 'Dear Jim <br>';
$message .= "Let me know if this email reaches you.<br><br>";
$message .= "Regards,<br>";
            
$headers = "MIME-Version: 1.0" . "\r\n";
$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
            
$headers .= 'From: <website>' . "\r\n";
$headers .= 'Cc: anotheremail@gmail.com' . "\r\n";
            
if (mail($to,$subject,$message,$headers)) {
     echo "Success";
} else {
    echo "Failure";
}            
```

### Example
To see error, submit form:  https://bitbizpro.com/contacts/create

**Comment by xabbuh** [comment]
This looks like an issue with autoloading on your end. The class does exist here: https://github.com/swiftmailer/swiftmailer/blob/149cfdf118b169f7840bbe3ef0d4bc795d1780c9/lib/classes/Swift/StreamFilters/StringReplacementFilter.php

**Comment by JimB14** [comment]
Hi Christian,

Thanks for your reply. I am new to Laravel and SwiftMailer, and have never
reported an issue on Github.

I think that this error has resulted from an error or errors in uploading
the project.

I am reuploading it again and expect it to work as it does on my local
machine.

I will let you know.

If there's anything that I'm supposed to do when I know that the issue is
no issue after all, please let me know.



Jim Burns, M.A.
Web Developer
Elite Pro Bark.com
https://jburns.dev
jim.burns14@gmail.com
904-219-9057 (mobile)


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by JimB14** [comment]
Error the result of file upload errors to host server.
