### ISSUE TITLE
'Address in mailbox given ['.$address.'] does not comply with RFC 2822, 3.6.2.'

### ISSUE THREAD

**Issue by shyenhau** [swiftmailer/swiftmailer#1308]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| RFC?                | yes
| How used?           | Symfony/3party
| Swiftmailer version | 6.0
| PHP version         | 7.4.9

### Observed behaviour

Unable to send the email with my php code

### Expected behaviour

able to send the verification mail to my gmail

### Example

<?php

require_once 'vendor/autoload.php';
require_once 'config/constants.php';

// Create the Transport
$transport = (new Swift_SmtpTransport('smtp.gmail.com', 465,'ssl'))
  ->setUsername(EMAIL)
  ->setPassword(PASSWORD);

// Create the Mailer using your created Transport
$mailer = new Swift_Mailer($transport);

function sendVerificationEmail($userEmail,$token)
{
	global $mailer; //to make this mailer object to be available use inside the function

	$body='<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Verify email</title>
</head>

<body>

 <div class="wrapper">
     <p>
         Thank you for signing up on our website.Please click on the link below
         to verify your email.
     </p>
     <a href="http://localhost/UserRegistration/index.php?token=' . $token . '">
         Verify your email address
     </a>
 </div>

</body>
</html>';

	// Create a message
	$message = (new Swift_Message('Verify your email address'))
	  ->setFrom(EMAIL)
	  ->setTo($userEmail)
	  ->setBody($body,'text/html'); 

	// Send the message
	$result = $mailer->send($message);

}

**Comment by vpArth** [comment]
Have same issue with dash in the email address, like a-b@gmail.com
While it can be not compliant with some RFC, it is real client email address. It should be able to send email on it.

How can I disable this assertion(w/o monkey patching of vendor scripts)?
