### ISSUE TITLE
[doc / question] Meaning of $encryption = "ssl" vs. "tls"

### ISSUE THREAD

**Issue by heidemn-faro** [swiftmailer/swiftmailer#1329]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes (extending documentation)
| RFC?                | no
| How used?           | Standalone, but in a Symfony app
| Swiftmailer version | 6.2.3 (same in current master)
| PHP version         | 7.3

### Observed behaviour
From the code in `Swift_SmtpTransport` and `Swift_Transport_EsmtpTransport`, I understand that that
`Swift_SmtpTransport::__construct` allows one of `$encryption = null | "ssl" | "tls"`.

Can you please explain what the difference between "ssl" and "tls" is?
I'm only guessing, it could be:
1. "ssl" = SSLv3, "tls" = TLSv1 or later
2. "ssl" = SMTPS, "tls" = SMTP + STARTTLS

### Expected behaviour
The parameter should be documented.

### Example

```php
    /**
     * @param string $host
     * @param int    $port
     * @param string $encryption    // - put explanation here -
     */
    public function __construct($host = 'localhost', $port = 25, $encryption = null)
```

Thanks :-)

**Comment by heidemn** [comment]
Okay found it: https://github.com/swiftmailer/swiftmailer/issues/545
