### ISSUE TITLE
Make TLS arguments configurable / allow self-signed certificates for TLS connections

### ISSUE THREAD

**Issue by MaximeDelwaulle** [swiftmailer/swiftmailer#1337]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| RFC?                | no
| How used?           | with Laravel
| Swiftmailer version | 6.0
| PHP version         | 8.0

### Observed behaviour
Currently, it is not possible to use self-signed certificates for TLS connections.

This ticket just represents https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Transport/StreamBuffer.php#L93, which says:
> TODO make tls arguments configurable

### Expected behaviour
A fix would allow making the TLS arguments configurable, thus making it possible to allow self-signed certificates.

### Example
Use a self-signed certificate for your SMTP server and try to send a mail.

**Comment by jesuer** [comment]
I have also encountered this problem, not only office365, but also Gmail mailbox cannot be connected. It always prompts: Unable to connect with TLS encryption. The version of swiftmailer I am currently using is v6.2.7.

**Comment by jesuer** [comment]
Hello,Have you solved this problem?
