### ISSUE TITLE
slash is normal ?

### ISSUE THREAD

**Issue by Liderdomofon** [swiftmailer/swiftmailer#1339]
https://github.com/swiftmailer/swiftmailer/blob/23e9ffaf6e8c716bce31bde1be708a405b1fbdf9/lib/classes/Swift/Mime/SimpleMessage.php#L209

**Comment by mfn** [comment]
Yes, [LMGTFY](https://www.google.com/search?hl=en&q=php%20backslash%20before%20functions)

**Comment by Liderdomofon** [comment]
thanks!
