### ISSUE TITLE
fwrite(): SSL operation failed with code 1 when emails sent using queue

### ISSUE THREAD

**Issue by PaddyLock** [swiftmailer/swiftmailer#1343]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | yes/no
| How used?           | Laravel 8, Supervisor, Redis queue
| Swiftmailer version | 6.2.5
| PHP version         | 7.4.15

### Observed behaviour
The emails are added to a redis queue in AWS.
The redis queue is run using Supervisor
The queue is run but the job fails and end up in failed_jobs database table with the following error

`ErrorException: fwrite(): SSL operation failed with code 1. OpenSSL Error messages:
error:1420C0CF:SSL routines:ssl_write_internal:protocol is shutdown in /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:223`

Strangely the emails were sending for a while when first configured but then suddenly stopped working.

It could be something to do with SMTP connections lasting too long? does it need to force a reconnection?

### Expected behaviour
The email should be sent

### Example
Create a redis cluster in AWS elasticache and use as QUEUE_CONNECTION in Laravel

supervisor config:

`[program:laravel-worker-emails]
process_name=%(program_name)s_%(process_num)02d
command=sudo php /var/www/html/artisan queue:work redis --queue=emails --sleep=3 --tries=3
autostart=true
autorestart=true
user=ubuntu
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/shared/storage/logs/worker-emails.log`

send emails using ->onQueue('emails')

It seems like this issue was around before but never resolved? - https://github.com/swiftmailer/swiftmailer/issues/1212

**Comment by nixprosoft** [comment]
Same issue with version 6.2.3 on my project was episodic:

```
ErrorException: fwrite(): SSL operation failed with code 1. OpenSSL Error messages: error:1420C0CF:SSL routines:ssl_write_internal:protocol is shutdown in /var/www/new/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:231
```

**Comment by nameless-ross** [comment]
+1

**Comment by dokicro** [comment]
I overcame the issue by sending one email every 5 seconds from the queue...
