### ISSUE TITLE
SMTP connection don't get properly closed when one of email address violates the RFC

### ISSUE THREAD

**Issue by Magomogo** [swiftmailer/swiftmailer#1346]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Standalone
| Swiftmailer version | v6.2.7
| PHP version         | 7.3.27

### Observed behaviour
SMTP connection don't get closed when "TO" email addresses contain invalid email address together with a good one. The script hangs and exits because of a timeout (in 5 minutes in my case)

### Expected behaviour
Bad address should be listed among `$failedRecipients` array, email should be sent to good addressees.

### Example

This script reproduces the issue:

```php
$mailer = new \Swift_Mailer(new \Swift_SendmailTransport('/usr/sbin/sendmail -bs'));
$mailer->registerPlugin(new Swift_Plugins_LoggerPlugin(new Swift_Plugins_Loggers_EchoLogger(false)));

$message = new \Swift_Message;
$message->setFrom('maxim@example.com');
$message->setTo([
    'müller@example.com', // RFC violation!
    'maxim@example.com'
]);
$mailer->send($message);
```

The output:

```txt
> php reproduce.php
++ Starting Swift_SendmailTransport
<< 220 hostname.local ESMTP

>> HELO [127.0.0.1]

<< 250 hostname.local

++ Swift_SendmailTransport started
>> MAIL FROM:<maxim@example.com>

<< 250 2.1.0 Ok

>> RCPT TO:<maxim@example.com>

<< 250 2.1.5 Ok

>> DATA

<< 354 End data with <CR><LF>.<CR><LF>

++ Stopping Swift_SendmailTransport
>> QUIT

<< 421 4.4.2 hostname.local Error: timeout exceeded

!! Expected response code 221 but got code "421", with message "421 4.4.2 hostname.local Error: timeout exceeded
" (code: 421)
!! Expected response code 221 but got code "421", with message "421 4.4.2 hostname.local Error: timeout exceeded
"
Log data:
 (code: 421)
++ Swift_SendmailTransport stopped
```

The reason of this behavior is here: https://github.com/swiftmailer/swiftmailer/blob/15f7faf8508e04471f666633addacf54c0ab5933/lib/classes/Swift/Transport/AbstractSmtpTransport.php#L498-L502

Method `streamMessage()` explodes with `Swift_AddressEncoderException` that didn't handled well causing DATA command to be not terminated properly.

**Comment by robertoibarra** [comment]
Same issue, using Laravel, sample code:

```
       foreach ($emails as $email){
              try {
                     Mail::to($email) //first email address of the loop has an RFC violation
                         ->send(new FolderStatus());
                 } catch (\Exception $e) {
                      //Trigger error
                 }
      }
```

When the $email is invalid, no exception is thrown right away and it actually falsely appears that the email was correctly sent. The issue is that even if the next $email of the loop is correct you get the error: _Expected response code 250 but got an empty response_

I am getting an Exception on the $email + 1 item, but the error was actually generated on the previous loop because the $email address was incorrect and when the $email + 1 loop tries to send the email, the SMTP stream is broken and of course there is no response from the smtp server.
