### ISSUE TITLE
PHP 8 errors on new DateTimeImmutable()

### ISSUE THREAD

**Issue by bellwether-thomas** [swiftmailer/swiftmailer#1356]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Standalone
| Swiftmailer version | 6.3.0
| PHP version         | 8.0.10

### Observed behaviour
Error thrown due to new DateTimeImmutable() being empty. Has optional parameters in PHP 8, but in order for this to work in our software at least, we had to provide it default values for both parameters.

### Expected behaviour
Have default parameters.

### Example
Try to send email using PHP 8

**Comment by fabpot** [comment]
That looks suspicious as that's not what the docs describe: https://www.php.net/manual/en/datetimeimmutable.construct.php both parameters are optional.

**Comment by bellwether-thomas** [comment]
It might be something else in our software which is setting the default timezone, or something along those lines. I just know that making that change, resolved the PHP 8 error we're encountering. 

Just providing it these default values is all the change is:
$this->setDate(new DateTimeImmutable('now', new DateTimeZone('UTC')));

**Comment by fabpot** [comment]
I'm going to close as the current is valid PHP.
