### ISSUE TITLE
beforeSendPerformed event is called twice with memory spool

### ISSUE THREAD

**Issue by craue** [swiftmailer/swiftmailer#139]
Using the memory spool added in d44b7fcc4c2abcc4e305672adb29833bab520fae, `beforeSendPerformed` of a `Swift_Events_SendListener` is called twice.

**Comment by craue** [comment]
I'm also having this issue with file spool (using the current version 5.4.0). The event is triggered the 1st time when generating the mail and storing it in a file, then the 2nd time when it's actually sent. I'm using this event to append some footer text to each mail, which is unfortunately done twice.

@fabpot: It's a rather old issue. Do you even consider this to be a bug (which will be fixed) or do I need to make up a workaround?

**Comment by craue** [comment]
The status is `RESULT_PENDING` in both invokations, so I don't see a way to distinguish between spooling and sending.

**Comment by chris-testing-github** [comment]
I concur with @craue, in the beforeSendPerformed method the status is RESULT_PENDING in both instances so there is no way to differentiate. 
I'm using a custom plugin with beforeSendPerformed to emogrify an email before it's sent. Unfortunately because of this (bug?) the process is happening twice and characters are encoded twice leading to undesirable characters.

**Comment by fabpot** [comment]
Anyone willing to submit a PR?

**Comment by rmznpydn** [comment]
I have the same problem and do I have an existing solution?

**Comment by samdjstevens** [comment]
I am also experiencing this issue - would an acceptable fix be changing the event target that is dispatched from `beforeSendPerformed` to say `beforeSpoolPerformed` (and similar for `sendPerformed`) or would this be a BC?

**Comment by anyx** [comment]
Do anyone knows how to avoid this issue now?

**Comment by appaydin** [comment]
> Do anyone knows how to avoid this issue now?

Look, maybe it helps https://github.com/appaydin/pd-mailer/blob/master/SwiftMailer/SendListener.php

**Comment by kiwidood** [comment]
I came across this issue today, the easiest solution I found was to create an array with the key/or value of $message->getId() and checking against that before doing anything with the message. Not sure if it's fool proof, or if it would work in all use cases but maybe this will help someone.
