### ISSUE TITLE
Feature Request: Default email address for Swift_Mailer

### ISSUE THREAD

**Issue by naitsirch** [swiftmailer/swiftmailer#142]
Hi,

it would be a nice feature if it would be possible to set a **default email address** to the **Swift_Mailer** instance. Because in many use cases you have the same sender email address in every email and you always have to set the same sender email address to the message instances. Better would be to set a default sender email to the mailer  once (in Symfony2 the Mailer is managed globally in the whole application, for example) and if the message does not have its own sender email the default email address is used.

What do you think?

I am using Swift-4.1.3

**Comment by dirkluijk** [comment]
I 'm sorry to bump this old feature request, but a :+1: from me!

**Comment by robinvdvleuten** [comment]
This would be so nice to have 🎉

**Comment by FinesseRus** [comment]
If you need to set a default sender you can use this plugin: [Swift Mailer Defaults Plugin](https://github.com/FinesseRus/SwiftMailerDefaultsPlugin)
