### ISSUE TITLE
cant set custom boundary on nested parts

### ISSUE THREAD

**Issue by mcauser** [swiftmailer/swiftmailer#166]
When I try to set my own custom boundary it works fine until I attach a base64 encoded file (pdf).
When I attach the content type "multipart/alternative" is nested inside a "multipart/mixed" and I am unable to set the inner boundary to a custom value.

Shouldn't the nested boundary be the same as the parent boundary?

<?php
$swiftMessage = Swift_Message::newInstance()
    ->setSubject( "test subject" )
    ->setFrom( array( "mike@example.com" => "mike" ) )
    ->setTo( array( "mike@example.com" => "mike" ) )
    ->setBoundary( "this_is_sparta" )
;
$swiftMessage->setBody( "<b>i am the html part</b>", 'text/html', 'UTF-8' );
$swiftMessage->addPart( "i am the text part", 'text/plain', 'UTF-8' );
$swiftMessage->attach( Swift_Attachment::fromPath( "/var/www/test.pdf", 'application/pdf' ) );
echo $swiftMessage->toString();
?>

As demonstrated here:

Without attachment:
http://pastebin.com/0tMAKfWx

With attachment:
http://pastebin.com/LADUgsNC

**Comment by TuningYourCode** [comment]
Having the same issue. Quiet a problem if you want to do (blackbox) tests.
