### ISSUE TITLE
Swift_Image produces MIME-type multipart/related instead of multipart/alternative

### ISSUE THREAD

**Issue by ThomasLandauer** [swiftmailer/swiftmailer#184]
When embedding an image like said in the docs:
$message->embed(Swift_Image::fromPath('http://site.tld/logo.png'))
the outcomming message has a top MIME-type of multipart/related. Should be multipart/alternative, since the text-only version is still being sent along with the HTML-version.

**Comment by fabpot** [comment]
I'm closing this issue as it's going to be fixed by Symfony Mailer/Mime, which will replace Swiftmailer eventually.
