### ISSUE TITLE
setId() not working

### ISSUE THREAD

**Issue by ghost** [swiftmailer/swiftmailer#198]
The following code does not work. I am running this from the command line and in CLI mode `$_SERVER['SERVER_NAME']` is not set so SwiftMailer is generating an id `x.y@swift.generated`. 

```
$mail = \Swift_Message::newInstance($subject(), $body(), $contentType, $charset);
$mail->setTo($toEmail());
$mail->setFrom($fromEmail());
echo $mail->getId(); // generated by the constructor
$mail->setId('x@y');
$mail->send();
```

Note that `$mail->getId()` seems to work, but when the message is sent, the originally generated `Message-ID` is present

**Comment by Yamakasi** [comment]
Can it be that this is also the issue on the latest version ? I'm struggeling setting my own ID and can only add one. setId() doesn't do a thing and only the original server ID is visible.
