### ISSUE TITLE
problem using Swiftmailer on a Symfony2 contact form

### ISSUE THREAD

**Issue by barryj** [swiftmailer/swiftmailer#200]
Hi

I have set up a contact form on my Symfony2 website http://www.needasecretchef.com/ and it is set to send the details via email to a gmail account
This works on my computer through localhost, but now that I have uploaded the site to the server the form fails when I hit the submit button and gives the following message:

Connection could not be established with host smtp.gmail.com [Connection timed out #110]
500 Internal Server Error - Swift_TransportException

in /home/content/63/9209863/html/secretchef/vendor/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php at line 266
1. $this->_stream = @stream_socket_client($host.':'.$this->_params['port'], $errno, $errstr, $timeout, STREAM_CLIENT_CONNECT, stream_context_create($options));
2. if (false === $this->_stream)
3. {
4. throw new Swift_TransportException(
5. 'Connection could not be established with host ' . $this->_params['host'] .
6. ' [' . $errstr . ' #' . $errno . ']'
7. );

I actually want to change the email address to the one provided by the Godaddy server which runs through smtp, but the only documentation I can find helps you to set up only through Gmail.

The settings in my current parameters.ini file are as follows, but as I said this only works through localhost and not when on the Godaddy server:

mailer_transport="gmail"
mailer_encryption="ssl"
mailer_auth_mode="login"
mailer_host="smtp.gmail.com"
mailer_user="myemail@gmail.com"
mailer_password="mypassword"
locale="en"

Hopefully somebody can help with this.

Many thanks in advance

Barry

**Comment by rkyrimbao** [comment]
@barryj follow-up to this may I know your swift mailer configuration for godaddy?
