### ISSUE TITLE
Content types messed up 

### ISSUE THREAD

**Issue by ghost** [swiftmailer/swiftmailer#204]
We are a happy user of the Swift classes and send over 10 million emails per month but lately we are having a strange issue.  it seems that some users are getting to see the content of the mail as is. I mean: they get to see all the content parts, bounderies, ...

this seems to be originating in the content-Type of the main message headers. Normally it's multipart/alternative but in these cases it's 
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0

if i send exactly the same mail to me, the content types are as bellow and everything is OK (the html part is shown & the text mail is there in the source but nothing more)
Content-Type: multipart/alternative;
    boundary="_=_swift_v4_13385564924fc8c04c67a3d_=_"
Content-Transfer-Encoding: base64

This is our code:
require_once '../v2/tools/' . SWIFT_VERSION . '/lib/swift_required.php';
Swift_Preferences::getInstance()->setCharset('utf-8');
Swift_Preferences::getInstance()->setCacheType('array');

$transport = Swift_SendmailTransport::newInstance();
$transport->setLocalDomain(SET_URL);
$mailer = Swift_Mailer::newInstance($transport);

$message = Swift_Message::newInstance();
$message->setSubject($this_headers['Subject']);
$message->setBody($html, 'text/html');
$message->addPart($text, 'text/plain');

$message->setEncoder(new Swift_Mime_ContentEncoder_Base64ContentEncoder());

... set return path, to, from, replyto

$mailer->send($message);

**Comment by lamoni** [comment]
Running into this issue.  Any ideas?

**Comment by sstok** [comment]
If anyone can create a script that will reproduce this it will help with debugging.
Or the exact message (including all headers) (e-mailaddres blanked of course ;)) that is displayed malformed.

I may have an idea whats wrong but I need something to confirm it.

**Comment by xdecock** [comment]
Probably due to the magic that transform text/plain to text/alternative
when you add part text/html :-/

Might be something to drop on 6.0
Le 21 mars 2015 09:17, "Sebastiaan Stok" <notifications@github.com> a écrit
:

**Comment by lamoni** [comment]
I'm running into it on Laravel 4.2 (using Swift-5.4.0).

I don't truly understand what's going on with the MIME settings (or any of the content, actually.  Need to read up on how the email headers actually work), but I run into it by just trying to send plain/text mail to a certain server (if I CC myself on the email going to that server, my outlook shows it as fine, but the server spits out errors):

Below is a excerpt from the email that the server is receiving:

    --_=_swift_v4_1426919623_eeb6dc64257b0a30dd6b37446044b477_=_
    Content-Type: text/plain; charset=utf-8
    Content-Transfer-Encoding: quoted-printable
     
    Email body here

The boundary and the content-type are, for some reason, showing up in the email message.

The code I'm using to send in Laravel is:

```php
        return \Mail::send(
            $viewPath,
            $viewParams,
            function($message) use ($to, $subject, $cc, $fromEmail)
            {

                $message->to($to)
                        ->subject($subject)
                        ->cc($cc)
                        ->from($fromEmail);

            }
        );
```

I can get the errorenous email content to show up in Outlook if I try to add a text-header:

```php
        return \Mail::send(
            $viewPath,
            $viewParams,
            function($message) use ($to, $subject, $cc, $fromEmail)
            {

                $message->to($to)
                        ->subject($subject)
                        ->cc($cc)
                        ->from($fromEmail)
                        ->getHeaders()->addTextHeader('Content-Type', 'text/plain; charset="ISO-8859-1"');

            }
        );
```

**Comment by xdecock** [comment]
Seems the issue is the charset you should use a setCharset the header is
not parsed and it will mess up with qpencoder

Le sam. 21 mars 2015 09:32, Lamoni Finlayson <notifications@github.com> a
écrit :
