### ISSUE TITLE
problems with mail() transport and safe_mode

### ISSUE THREAD

**Issue by Raven24** [swiftmailer/swiftmailer#238]
(I know, `safe_mode` is deprecated and horrible anyway, but with some hosted webspaces, there is nothing you can do about it...)

In `lib/classes/Swift/Transport/SimpleMailInvoker.php` the mail() method looks like this:

``` php
    public function mail($to, $subject, $body, $headers = null, $extraParams = null)
    {
        if (!ini_get('safe_mode')) {
            return @mail($to, $subject, $body, $headers, $extraParams);
        } else {
            return @mail($to, $subject, $body, $headers);
        }
    }
```

I ran into a problem there: `ini_get()`

> Note: When querying boolean values
> 
> A boolean ini value of off will be returned as an empty string or "0" while a boolean ini value of on will be returned as "1". The function can also return the literal string of INI value. 

So in case this returns a string, e.g. "Off", this makes the condition behave wrongly, and fail (silently), since `safe_mode` does not allow for the additional parameter.

**Comment by fabpot** [comment]
`ini_get` always returns an int, so it should work fine.
