### ISSUE TITLE
SwiftMailer thinks that emails with two or more dots inside are invalid, but they didn't

### ISSUE THREAD

**Issue by DyaGa** [swiftmailer/swiftmailer#239]
SwiftMailer throws an error like:

```
PHP Fatal error: Uncaught exception 'Swift_RfcComplianceException' with message 'Address in mailbox given [den...4ik@mail.ru] does not comply with RFC 2822, 3.6.2.'
```
for next emails:
```
a..azfar@mail.ru
den...4ik@mail.ru
```

But this emails are valid. For example, `a..azfar@mail.ru` is the same as `aazfar@mail.ru` (without dots).

p.s. I'm not English speaking, so there could be some spelling errors. sorry for this.

**Comment by swplzj** [comment]
mr.name.dept@...sch.org is OK???
