### ISSUE TITLE
Cannot forward message as attachment

### ISSUE THREAD

**Issue by dinamic** [swiftmailer/swiftmailer#258]
In one of our projects, a webmail, there's the standard functionality for the user to be able to forward a given message as attachment.

I find impossible to do this only by using SwiftMailer.

While using Swift_Attachment is okay for regular uses, it cannot handle the message/rfc822 spec. An example of why it can't do it is that it has to have two Content-Type headers:
- one for the mime part of the email
  
  ```
  Content-Type: message/rfc822;
    name="=?UTF-8?B?0JzQsNC70LrQviDQutC40YDQuNC70LjRhtCwLmVtbA==?="
  ```
- one for the forwarded message
  
  ```
  Content-Type: text/plain; charset=utf-8
  ```

Also the headers of the forwarded message has to be separated from the mime-part headers with one empty line.

I've tried using Swift_Message, since the Swift_Message::attach() method requires an implementation of the Swift_Mime_MimeEntity interface and it's one. Unfortunately, this did not worked as well.

It seem to me like we need another class which would combine the Swift_Message and Swift_Attachment, so we can specify the attachment filename. It can default to the message subject, but we have to be able to change it. An example class name might be Swift_Message_Rfc822.

**Comment by lyoshenka** [comment]
Did you guys make any progress on this? I'm trying to do the same thing @dinamic was talking about, any help would be appreciated.

**Comment by howtomakeaturn** [comment]
+1

**Comment by fabpot** [comment]
I'm closing this issue as it's going to be fixed by Symfony Mailer/Mime, which will replace Swiftmailer eventually.

**Comment by dinamic** [comment]
Thanks for the update, @fabpot!

I am troubled that the github page about the Mime component says it is an experimental one. This raises a flag for me. Should we keep this issue open until we have the component proven?

**Comment by ikarol** [comment]
Seems like forcing encoder to use 8bit( or 7bit) does the thing
According to my tests, such message could also be retrieved by IMAP from "attachments section"
`$swiftAttachment->setEncoder(new \Swift_Mime_ContentEncoder_PlainContentEncoder('8bit'));`

**Comment by carakas** [comment]
Encoder 8 bit solved the issue for me
