### ISSUE TITLE
Encoding problem in swiftmailer 4.2.2

### ISSUE THREAD

**Issue by khrizt** [swiftmailer/swiftmailer#293]
Sending emails to french users I've found what seems to be a bug, the é character is not encoded correctly using the QPHeaderEncoder class and appears empty in the client email's subject.

The charset is defined to UTF-8 in the preferences and the text is also UTF-8, but changing for test purposes the QPHeaderEncoder encoding function to use quoted_printable_encode function the subject is encoded correctly.

Here is the code I'm using.

``` php
$message = Swift_Message::newInstance()

// set encoding in 8 bit
->setEncoder(Swift_Encoding::get8BitEncoding())

// Give the message a subject
->setSubject($subject)

// Set the From address with an associative array
->setFrom(array($from => $niceFrom))

// Set the To addresses with an associative array
->setTo(array($to)) ;
```

**Comment by fyrye** [comment]
What's the output from:

```php
echo $message->toString();
```

**Comment by xdecock** [comment]
Do you use a mix of iso-8859-1 / iso-8859-15 / utf-8 character encoding ?

It's usually the culprit
