### ISSUE TITLE
SwiftMailer/classes/Swift/Transport/StreamBuffer.php:234 - fwrite(): send of 8192 bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by savgoran** [swiftmailer/swiftmailer#307]
File: SwiftMailer/classes/Swift/Transport/StreamBuffer.php
Line: 234
Method: fwrite()

Array

```
  [0] => Resource id #1558
  [1] => MAIL FROM: <noreply@datingbackend.com>
```

MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com
MAIL FROM: noreply@datingbackend.com

**Comment by alterphp** [comment]
No, I use a version of Swift with mentionned commit and get the same issue. I don't know if it comes from SwiftMailer or from execution context....

**Comment by xdecock** [comment]
Are you using ssl? Or do you use long running scripts?

**Comment by alterphp** [comment]
That was a long running script, so ... a contextual issue. SMTP socket was time outed.
