### ISSUE TITLE
Some issues with the file spool when messages fail

### ISSUE THREAD

**Issue by bicpi** [swiftmailer/swiftmailer#311]
Recently I encountered some difficulties with the file spool feature (in conjunction with SwiftmailerBundle's `SendEmailCommand` command). This was also my topic on the KnpUniversity Q&A day and my question was analysed in depth at https://knpuniversity.com/screencast/question-answer-day/swiftmailer-spooling. The solution was a workaround and I'm currently helping myself with a similar approach.

But nonetheless I think the `Swift_FileSpool` may need some improvements:
1. What is the reason for `Swift_FileSpool`'s attributes `$_path` and `$_retryLimit` being declared as `private`? To implement my workaround in a customized child class I was struggling with overriding some methods (`recover()` and `flushQueue()`) because I have no  access to these properties. So I had to copy all the coode down to my child class. I could not use an independent class because SwiftmailerBundle's `SendEmailCommand` command requires an `Swift_FileSpool` instance.
2. `Swift_FileSpool::flushQueue()`: I'm using Amazons SES service via SMTP. When sending out thousands of mails every day it is likely to sometimes receive a permanent  SMTP error for some reasons (e.g. _recepient blacklisted_ or _sender not verified_). This causes `$transport->send()` to throw an `Swift_TransportException` which is not catched and kills the remaining sendouts. There are four problems with this:
   - You won't get informed about the sent mails before the error (`$count` variable)
   - You won't get informed about what mail has failed
   - No more mails are sent after the error, but it seems that we could recover from an error for a particular mail - all the mails afterwards could be ok and would not need to wait for  the next queue flush.
   - Supposed to flush the queue every minute via cron and supposed to use the default interval for recovery (15 minutes): As soon as more than 15 messages with permanent errors have accumulated in the spool directory - no email at all will be sent any more. This is because the first failed message recovers afters 15 minutes and fails again with the sending process completely aborted. One minute later it's the same with the second message and so on.  

In my workaround I've created a customized child class of `Swift_FileSpool`. I'm catching  `Swift_TransportException`s for the `$transport->send()` call in `flushQueue()` to continue with the "good"  messages in the same process - currently not beeing able to log that. To get rid of permanently failing messages I've added a second parameter `$recoverLimit=3` to the `recover()` method. It is used to indicate how many attempts for recovery should be made. All spooled message files are removed after `$recoverLimit*$timeout` seconds.

I'm not really happy with my temporary solution and I also don't want to create a second cron job for cleaning up things. I think the `Swift_FileSpool` could be improved to handle message failures but I'm not to deep in the code to find the right approach. But I would really like to help improving the process if someone can point me in the right direction. For issue 1) I could create a PR.

Thank you,
Philipp

**Comment by TiGR** [comment]
@bicpi BTW, you could still extend `Swift_FileSpool`, just redeclare these private fields and their setters (don't forget to call original setters if you are going to use some of original code that relies on them) - and that's enough.

But anyway, I also had to create some kind of failsave file spool, and I also had to struggle with these private fields. Is there really any reason for having them private?

**Comment by stof** [comment]
@TiGR anything which is protected must be taken into account for backward compatibility. this is why this is private: it makes the maintenance of the project a lot simpler.
