### ISSUE TITLE
Expected response code 250 but got code "421", with message "421 Timeout waiting for data from client.

### ISSUE THREAD

**Issue by pmoubed** [swiftmailer/swiftmailer#330]
When using with AWS, it throws the exception below:

Expected response code 250 but got code "421", with message "421 Timeout waiting for data from client.

**Comment by errogaht** [comment]
i have the same. Any ideas?

**Comment by errogaht** [comment]
$transport->stop(), $transport->start() . fixed

**Comment by terox** [comment]
@errogaht This should be taked be carefully. If you put it in a loop, message queue or something similar the sender provider could be lock your IP, account or take similar actions. Be careful!
