### ISSUE TITLE
Swift_TransportException: Expected response code 250 but got code "", with message ""

### ISSUE THREAD

**Issue by arnaugm** [swiftmailer/swiftmailer#331]
Suddenly I started to have this error very frequently in my Symfony 2.1 applications. In the tests I run in jenkins it happens every 4-5 times I run the tests. The application running in the production server is giving this error too as it's reflected in the logs. And it is not a matter of sending tons of emails, just after sending 3 or 4 the error appears. Then you have to wait a bit until it works again.

As it's quite random it's impossible to know exactly at what point I started to get the error, but checking the commits, I don't see any change in the composer.lock file for long, so no changes in the bundles, and I haven't touched any package in the ubuntu server.

I updated "symfony/swiftmailer-bundle" respecting the composer.lock file of Symfony 2.1 which says "2.1.*" and the bundle was updated to the version 2.1.11. Swiftmailer itself didn't change and the installed version is 4.2.2.
The error persists.

I read something about being php's old version fault but I didn't get what was considered old. The server is using PHP 5.3.10-1ubuntu3.6.

As the error message is empty I really don't have any clue on what is going on.

**Comment by hufeng903** [comment]
i use this in yii2 . get this error :Swift_TransportException

Expected response code 250 but got code "", with message "",who can help me？

**Comment by vinoVINI1** [comment]
i got  error  while  trying to send  email   anyone  can  plz  help to  shot out this issues 
Expected response code 250 but got code "530", with message "530-5.5.1 Authentication Required. Learn more at 530 5.5.1 https://support.google.com/mail/?p=WantAuthError w72-v6sm80663446pfa.26 - gsmtp "
