### ISSUE TITLE
Quoted printable encoding line wraps every 76 characters, not after 76 on a line

### ISSUE THREAD

**Issue by jamesrgrinter** [swiftmailer/swiftmailer#334]
The QP encoding seems to be a bit too agressive, when it comes to line wrapping, and I can't find an existing issue logged for this.

My observation is that it's line-wrapping every n (n=72?) characters, rather than after n characters on a given line (where it puts the '=' character, before the LF)

Here's what it's sending out for the first few lines of one of my emails. Some of these line break decisions are clearly unnecessary:

    <HTML>
    
     <HEAD>
      <META HTTP-EQUIV=3D"content-type" CONTENT=3D"text/h=
    tml;charset=3DISO-8859-1">
      <TITLE></TITLE>
      <STYLE TYPE=3D"text/css"=
    >
    a {
        text-decoration: none;
        color:           #5be201;
    }
    =
    
    a:hover  {
        text-decoration: underline;
    }
    
    body, td, p, .text=
    , #body_style {
        font-family: Verdana, Geneva, Helvetica, Arial, sans-=
    serif;
        font-size:   10px;
        color: #ffffff;
        background-colo=
    r:  #1d1d1b;
    }

This is with Swiftmailer 5.0.0, I think,

    $ cat vendor/swiftmailer/swiftmailer/VERSION 
    Swift-5.0.0

coming via the symfony/swiftmailer-bundle 2.2.*, if that helps ('"swiftmailer/swiftmailer": ">=4.2.0,<5.1-dev",')

executing with a self-built php 5.4.15, on OS x.

**Comment by c960657** [comment]
A PR has been created for this issue:
#622 Only add soft line break when necessary
