### ISSUE TITLE
Diffrent Message-ID

### ISSUE THREAD

**Issue by Lechus** [swiftmailer/swiftmailer#335]
Why there is not the same message-id in e-mail send by swiftmailer?

[code]
 $message = Swift_Message::newInstance('Faktura')
..
$msgId = $message->getHeaders()->get('Message-ID');
 $numSent = $mailer->send($message, $failures);
[/code]

$msgId->toString() != Message-id in the e-mail.
fbc3aee9d948b44052e96b83390e6074@domain.pl != d580f5adeafd1fe354369ee67e57062f@domain.pl

**Comment by nenadalm** [comment]
messageId is changed in the end of ```send``` method
https://github.com/swiftmailer/swiftmailer/blob/12a6329c24d08fb97bcf10128365757f845dc140/lib/classes/Swift/Transport/AbstractSmtpTransport.php#L197
as for me - this is very confusing behaviour. it would be better to change the id at the beginning if it has to be changed in the method somewhere (as usually if I want to store some data about the message - I want to do that after I send it - so I'll probably care about messageId after I send the message and first thing which come to my mind is to call ```$message->getId()``` If I want to know id of the sent message)
