### ISSUE TITLE
Sending an email having a name with a parentheses - example: Scott Motte (Dev) - fails to escape the parentheses causing them to not be displayed in gmail.

### ISSUE THREAD

**Issue by motdotla** [swiftmailer/swiftmailer#339]
To repeat do the following.

```php
$mail = new Swift_Message();
$mail->setTo('recipient@gmail.com', 'Recipient (bla bla)');
$mail->setFrom('sender@test.com', 'Sender');
$mail->setSubject('Test email');
$mail->setBody('<html><body><h3>Hello</h3></body></html>', 'text/html');
sfContext::getInstance()->getMailer()->send($mail);
```

The gmail user will receive the email, but the name will be set as `Recipient` instead of `Recipient (bla bla)`.

If you inspect the raw email, it will look like this:

```
Recipient (bla bla) <recipient@gmail.com>
```

Gmail would expect it to be escaped like the following in order to display the (bla bla) part.

```
Recipient \(bla bla\) <recipient@gmail.com>
```

The fix actually exists here:

http://stackoverflow.com/questions/17240387/in-symfony-1-4-using-swiftmailer-setto-with-parentheses-in-name-breaks-message

The gist of the answer is that the name needs to be encoded.

```php
public function setTo($addresses, $name = null)
{
  // if $name is set, encode it
  if(isset($name))
  {
    $name = $this->encodeName($name);
  }

  // if $addresses is an non numeric array (email => name), encode each name.
  if(is_array($addresses) && array_keys($addresses) !== range(0, count($addresses) - 1))
  {
    foreach($addresses as $key => $value)
    {
      $addresses[$key] = $this->encodeName($value);;
    }
  }

  if (!is_array($addresses) && isset($name))
  {
    $addresses = array($addresses => $name);
  }

  if (!$this->_setHeaderFieldModel('To', (array) $addresses))
  {
    $this->getHeaders()->addMailboxHeader('To', (array) $addresses);
  }
  return $this;
}

/**
 * Encode the name to avoid issues with some characters
 *
 * @param string $name
 * @return string
 */
private function encodeName($name)
{
  return "=?UTF-8?B?". base64_encode($name) . '?=';
}
```

If I get a chance, I will try to jump into the code base and create a pull request, but it is daunting at the moment and I have other priorities. 

But if you guys could fix this, it would be awesome!

**Comment by bytestream** [comment]
Came across this issue again, after switching to RFC 2047. This time when using `@` in the display name of From header. Some mail servers seem to misinterpret `INFO@ <address@address.com>` incorrectly (when utf-8 encoded) and give a blank From header

RFC 2047
> Other characters are also illegal in certain contexts.  For example, an 'encoded-word' in a  'phrase' preceding an address in a From header field may not contain any of the "specials" defined in RFC 822.

RFC 822 
>>>
            specials    =  "(" / ")" / "<" / ">" / "@"  ; Must be in quoted-
                        /  "," / ";" / ":" / "\" / <">  ;  string, to use
                        /  "." / "[" / "]"              ;  within a word.
>>>

Seems to me like any `specials` characters in the UTF-8 encoded string need to be stripped out? Or have I misinterpreted that?
