### ISSUE TITLE
Emails never delivered on Gmail or Hotmail, but they are on the same domain

### ISSUE THREAD

**Issue by PLPeeters** [swiftmailer/swiftmailer#358]
The emails I send to Gmail or Hotmail (or others I guess) are not getting delivered. If I send an email to the same address however, this one's received just fine. Basically, what I have is a function whose declaration is `function sendMail($to, $subject, $message)`.

`$to` is a simple email (so, just `email@domain.com`, not something like `Name <email@domain.com>`), `$subject` and `$message` are strings (duh).

I used to have the Mail PEAR package (http://pear.php.net/package/Mail/) handle the email sending, but wanted to switch to Swift Mailer since it's a more recent library.

My code used to be:

```
function sendMail($to, $subject, $message) {
    require_once "Mail.php"

    $from = "admin@domain.com";
    $subject = $subject;
    $body = $message;

    $host = "smtp.domain.com:587";
    $username = "admin@domain.com";
    $password = 'password';

    $headers = array(
        'From' => $from,
        'To' => $to,
        'Subject' => $subject,
        'Content-Type' => 'text/html; charset=UTF-8',
        'MIME-Version' => '1.0');
    $smtp = Mail::factory('smtp', array(
        'host' => $host,
        'auth' => true,
        'username' => $username,
        'password' => $password));

    $mail = $smtp->send($to, $headers, $body);
}
```

It became:

```
function sendMail($to, $subject, $message) {
    require_once '/path/to/swiftmailer/lib/swift_required.php';

    $transport = Swift_SmtpTransport::newInstance('smtp.domain.com', 587)
        ->setUsername('admin@domain.com')
        ->setPassword('password');

    $mailer = Swift_Mailer::newInstance($transport);

    $email = Swift_Message::newInstance($subject)
        ->setFrom('admin@domain.com')
        ->setTo(array($to))
        ->setBody($message);

    $result = $mailer->send($email);
}
```

Since the only thing that changed is the library, this seems to be a bug... Any clues?

**Comment by fnocetti** [comment]
Did you ever solved the problem? I'm having same issue and can't figure out the solution! It's driving me crazy

**Comment by PLPeeters** [comment]
@fnocetti I guess I did since I closed this, but since this is so old I can't really remember how I fixed it, sorry...
