### ISSUE TITLE
StreamBuffer: php error not catchable

### ISSUE THREAD

**Issue by realtebo** [swiftmailer/swiftmailer#359]
This is my init code 

``` php
try {
            $transport = Swift_SmtpTransport::newInstance($this->host, $this->port)
                        ->setUsername($smtp_login)
                        ->setPassword($client->password);

            $transport->stop();
            $transport->start();

        } catch (Swift_TransportException $e) {
            Yii::log("SMTP login fallito su $this->host:$this->port - credenziali $smtp_login / $client->password", CLogger::LEVEL_ERROR, "application");
            return false;
        }


$this->mailer = $this->swift->mailer($transport); 
```

I'm reporting a bug about the **last** line of code. In some cases it break everything down with the following error:

`end of 6 bytes failed with errno=32 Broken pipe (... Swift/Transport/StreamBuffer.php:232)`

This is not an exception, so we cannot handle. 
Please, tell us (or find a way to fix) a workaround to handle this situation in live and mission-critical environment

Follows the stack trace:

```
[error] [php] fwrite(): send of 6 bytes failed with errno=32 Broken pipe (.. Swift/Transport/StreamBuffer.php:232)
Stack trace:
#0 .. Swift/ByteStream/AbstractFilterableInputStream.php(92): Swift_Transport_StreamBuffer->_doWrite()
#1 ... Swift/Transport/AbstractSmtpTransport.php(276): Swift_Transport_StreamBuffer->write()
#2  ... Swift/Transport/EsmtpTransport.php(245): Swift_SmtpTransport->executeCommand()
#3 ... Swift/Transport/AbstractSmtpTransport.php(217): Swift_SmtpTransport->executeCommand()
#4  ... Swift/Transport/AbstractSmtpTransport.php(500): Swift_SmtpTransport->stop()
#5  .. [my php script] Mail.php(814): Swift_SmtpTransport->__destruct()
```

Note: v. 4.0.4 on PHP 5.3.3

**Comment by robcaw** [comment]
Yep this is an issue for me. Running switfmailer in a daemon and after a while it starts failing with: 

` fwrite(): send of 272 bytes failed with errno=32 Broken pipe in ... /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php line 232`

**Comment by yasasn86** [comment]
robcaw, I have the same issue.
Symfony\\Component\\Debug\\Exception\\ContextErrorException: Notice: fwrite(): send of 333 bytes failed with errno=32 Broken pipe  at ........../vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php line 232
