### ISSUE TITLE
Can't catch Swift_RfcComplianceException (5.0.1)

### ISSUE THREAD

**Issue by aquavark** [swiftmailer/swiftmailer#360]
Hi,
Using Swiftmail 5.0.1, and trying to catch invalid email addresses with the following:

try
            {
                $mailer->send($message);
            }
            catch (Swift_RfcComplianceException $e)
            {
                echo "!! Invalid email address : ".$e->getMessage()."\r\n";
            }

But the exception always reports as uncaught 

PHP Fatal error:  Uncaught exception 'Swift_RfcComplianceException' with message 'Address in mailbox given [kai.1.@xxxxxxxxx] does not comply with RFC 2822, 3.6.2.' in /var/www/xxxxxxx/hared/Swift-5.0.1/lib/classes/Swift/Mime/Headers/MailboxHeader.php:352
Stack trace:
#0 /var/www/eroster/shared/Swift-5.0.1/lib/classes/Swift/Mime/Headers/MailboxHeader.php(264): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('kai.1.@xxxxxxx....')
#1 /var/www/eroster/shared/Swift-5.0.1/lib/classes/Swift/Mime/Headers/MailboxHeader.php(108): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)
#2 /var/www/eroster/shared/Swift-5.0.1/lib/classes/Swift/Mime/Headers/MailboxHeader.php(65): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)
#3 /var/www/eroster/shared/Swift-5.0.1/lib/classes/Swift/Mime/SimpleHeaderFactory.php(60): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)
#4 /var/www/eroster/shared/Swift-5.0.1/lib/classes/Swift/Mime/SimpleHeaderSet.php(70): Swift_Mime_SimpleHeaderFactory->createMailboxHeader('To in /var/www/xxxxxxxx/shared/Swift-5.0.1/lib/classes/Swift/Mime/Headers/MailboxHeader.php on line 352

I know that the email address is invalid, I just want to catch that one and go on to the next. It appears that I can neither catch it, nor ignore it (and let it send to the valid email address in the same array of TO addresses). Is this a bug, or am I following the examples (from various places, but same technique) wrongly?

The email has a brief text-only part, and a single PDF attachment, if that is relevant to this issue.

Many thanks

**Comment by fecou** [comment]
So : 
`try {
    $message->setTo($mail_addr);
} catch (\Swift_RfcComplianceException $e) {
    echo("swift exception: " . $e);
}`
