### ISSUE TITLE
Swift_Message as instance of Swift_Mime_MimePart causes type mismatching in IDE parsing

### ISSUE THREAD

**Issue by cautionbug** [swiftmailer/swiftmailer#362]
i'm using PHPStorm 6.0.3, and it's reporting a Class type issue. Maybe it's not an actual problem, but i can see where the conflict is coming from...

_Message.php_:

``` php
class Swift_Message extends Swift_Mime_SimpleMessage {. . .}
```

_SimpleMessage.php_:

``` php
class Swift_SimpleMessage extends Swift_Mime_MimePart 
  implements Swift_Mime_Message {. . .}
```

so...

``` php
$message = Swift_Message::newInstance();
// $message is instance of Swift_Mime_MimePart
```

Whereas the `Swift_Mailer::send()` functions signatures call for:

``` php
public function send(Swift_Mime_Message $message, &$failedRecipients = null){. . .}
```

![2013-08-23_1508](https://f.cloud.github.com/assets/1391849/1018384/beb4fa74-0c27-11e3-86b5-ce4c683bb3a8.png)

The result is confusing the IDE, as it thinks `$Message` is a MimePart instance, so isn't valid for `send()`. On the same token, i should be able to call `->addPart()`, but since `Swift_Message` is a MimePart, the IDE doesn't see it as an available function (even though it's defined in the `Swift_Message` class):
![2013-08-23_1515](https://f.cloud.github.com/assets/1391849/1018410/6810942a-0c28-11e3-92f4-d48aad773cc5.png)

It may just be PHPStorm misinterpreting the class structures, or not a strict problem (PHP is pretty forgiving, after all), but i thought i'd at least bring it to your attention & let you decide if it's worth further examination. If you need any additional info, let me know.

Thanks.

**Comment by johnnypeck** [comment]
As a note to anyone finding this issue add

```php
/**
  * @var \Swift_Mime_Message $myMessage
  */
```

and PHPStorm will stop complaining.

**Comment by hittten** [comment]
The IDE is not wrong this warning appears because it can be an instance of another class by inheritance, so the correct way to solve this is as follows:

```php
$message = \Swift_Message::newInstance()
    ->setSubject($subject)
    ->setFrom($from)
    ->setTo($to)
    ->setBody(
        $body,
        $bodyType
    );

if (!$message instanceof \Swift_Mime_Message) {
    throw new \Exception(sprintf('Expected Swift_Mime_Message, %s given', get_class($message)));
}

return $this->get('mailer')->send($message);
```

And the warning will disappear
