### ISSUE TITLE
DomainKeys Signer - fail (bad sig)

### ISSUE THREAD

**Issue by razvanioan** [swiftmailer/swiftmailer#372]
I'm struggling to understand why I cannot make DomainKeys pass.

I know that's surpassed by DKIM (which is working fine by the way), but Yahoo still checks DomainKeys and I want to implement it.

I'm using same pair of keys (selector) for both DomainKeys and DKIM, but this doesn't have to be an issue (for others where's working I see the same).

I've tested even with a simple message and signed only by DomainKeys.
It always fails (I'm checking directly by sending to Yahoo).

Trying to figure it out what can be wrong but doesn't see anything yet.

Thanks

**Comment by stef157** [comment]
The same error for my part with the latest update.
Any idea how to deal with it ?

Thanks.

**Comment by razvanioan** [comment]
Nope, unfortunately :(

I've droped entirely DomainKey signature, and stick just to DKIM...
