### ISSUE TITLE
No information about Swift_RfcComplianceException if sending fails

### ISSUE THREAD

**Issue by kuborgh-mspindelhirn** [swiftmailer/swiftmailer#386]
The send method of Swift_Mailer cathes Swift_RfcComplianceException and adds the email for which this Exception is thrown to an array of failed adresses.
The exact message why this has happend is not stored anyway.

I think it would be nice to have some kind of logging here.

Maybe just an getter on the mailer class for the last occured error ?

**Comment by michaelhogg** [comment]
Probably a duplicate of #353

**Comment by kuborgh-mspindelhirn** [comment]
Yes. It is
