### ISSUE TITLE
SwiftMailer throws a warning if unable to open default sys_get_temp_dir

### ISSUE THREAD

**Issue by cordoval** [swiftmailer/swiftmailer#398]
"
Hi,

It seems that when swiftmailer initializes it runs the preferences.php file. In this file it sets a cache type to disk if it can access sys_get_temp_dir(). However, when access to this directory happens to be restricted (e.g. open base dir restrictions), it raises a warning, causing Symfony to raise an ErrorException, ultimately causing Symfony to halt. If this library is indeed a Symfony dependency, then it would be ideal to have this cache path configurable through Symfony configuration facilities.

As a dirtier workaround, it'll work to just silence ('@') is_writable().
"
by @feamsr00

**Comment by feamsr00** [comment]
Hi There,

I can confirm this has been fixed for a bit. I'd think this issue could be closed now.

Thanks!
