### ISSUE TITLE
Not working with mailcatcher.me

### ISSUE THREAD

**Issue by RSully** [swiftmailer/swiftmailer#415]
I was directed towards mailcatcher from laravel/framework#1821

When I set Laravel to use smtp with localhost and port 1025 swift throws the following error:

> [Swift_TransportException]
> Expected response code 220 but got code "500", with message "500 Unknown command"

**Comment by MageParts** [comment]
Thanks @RSully for saving a few hours of my life :-)

**Comment by GokulSrinivas** [comment]
Thanks @RSully . You saved my time :+1:

**Comment by twify93** [comment]
Thank you @RSully

**Comment by falnyr** [comment]
@RSully LIFESAVER!

**Comment by fabpot** [comment]
Can anyone send a pull request to add a small note about how to use mailcatcher with Swiftmailer. That would help many other users.
