### ISSUE TITLE
Swift_Transport_SpoolTransport::send() calls beforeSendPerformed & sendPerformed

### ISSUE THREAD

**Issue by leevigraham** [swiftmailer/swiftmailer#433]
Swift_Transport_SpoolTransport::send() method triggers beforeSendPerformed & sendPerformed events even though the Transport itself isn't responsible for sending email only queuing the message.

Plugins using these events fire twice performing actions such as logging etc unreliable as the email is not actually sent.

Is this actually an issue or am I missing something?

**Comment by samdjstevens** [comment]
I think this is a duplicate of #139?

**Comment by leevigraham** [comment]
@samdjstevens seems like it… I'll close this one.
