### ISSUE TITLE
Multipart hierarchy is god damn wrong.

### ISSUE THREAD

**Issue by ghost** [swiftmailer/swiftmailer#434]
Let's say we have an html + text multipart/alternative message.

Let's say we have inline images in the html part.

Using your own tutorials, the resulting structure is this:

```
1. multipart/alternative
        1.1. text/plain
        1.2. multipart/related
                1.2.1. text/html
                1.2.2. inline image 1
                1.2.3. inline image 2
                1.2.4. ...
```

That seems logical right? Wrong. In Outlook Express and a bunch of other clients the above structure produces a mess for the text-only version of the email, and it renders a phantom clip icon for attachments, which shouldn't be there for inline images.

Here's the correct structure: http://msdn.microsoft.com/en-us/library/office/aa563064(v=exchg.140).aspx

Now, achieving this structure in the link is god damn impossible in Swift_Mailer, because the Swift_Mime_SimpleMimeEntity's setChildren() method is trying to be "smart" by doing these among other things:

1) Auto-creating wrapper multipart entities.
2) Taking the $contentType users pass and just assigning some other content type value. Whatever, right?
3) Re-ordering the entities, sometimes doing the right thing (like putting text/plain before text/html) and sometimes the wrong thing (putting attachments before the text/html part, although they were added after the text/html part).

The code in this method has a little comment: "// TODO: Try to refactor this logic". Apparently that wasn't done.

Here's what I had to do to gain some control over the MIME part content types and hierarchy:

``` php
/**
 * Patching Swift Mailer.
 * 
 * Prevents mangling of content-type, reshuffling of children, and appearance of phantom multipart entities.
 */
trait FixSwiftMailerMadness {
    public function setChildren(array $children, $compoundLevel = null) {
        // Setting parent class private properties.
        $set = function ($class, $object, $name, $value) {
            $refl = new \ReflectionProperty($class, $name);
            $refl->setAccessible(true);
            $refl->setValue($object, $value);
        };

        // Calling parent class private methods.
        $call = function ($class, $object, $name, array $args = null) {
            $refl = new \ReflectionMethod($class, $name);
            $refl->setAccessible(true);
            if ($args) return $refl->invokeArgs($object, $args);
            else return $refl->invoke($object);
        };

        $set('Swift_Mime_SimpleMimeEntity', $this, '_immediateChildren', $children);
        $call('Swift_Mime_SimpleMimeEntity', $this, '_fixHeaders');
        return $this;
    }
}

// With this, I'm using "new MimePart()" instead of "\Swift_MimePart::newInstance()".
class MimePart extends \Swift_MimePart {
    use FixSwiftMailerMadness;
}

// With this, I'm using "new Message()" instead of "\Swift_Message::newInstance()".
class Message extends \Swift_Message {
    use FixSwiftMailerMadness;
}
```

And here's a snippet of me using the above patched classes to reproduce the structure from the MSDN article (which works _great_):

``` php
$message = new Message();

$message
    ->setSender('****@****.com', '****')
    ->setSubject($messageData['subject'])
    ->setTo($messageData['to']);

/*
 * Assemble the body hierarchy manually.
 */

$htmlBody = new MimePart($messageData['html'], 'text/html');
$textBody = new MimePart($messageData['text'], 'text/plain');

$alternative = new MimePart(null, 'multipart/alternative');
$alternative->setChildren([$textBody, $htmlBody]);

$related = new MimePart(null, 'multipart/related');
$related->setChildren(\array_merge([$alternative], $inlineImages));

$message->setContentType('multipart/mixed');
$message->setChildren([$related]);

$result = $this->mailer->send($message, $failedRecipients);
```

A note: "$inlineImages" above is an array of Swift_EmbeddedFile instances (for inline images). Since this type of entity has no children, I didn't need to patch that particular class.

Fixing the mess in the original code would require a lot of refactoring, and it should start with cutting setChildren to those two lines I'm emulating above.

So my question is - what's the status among the maintainers, is this going to be refactored, or not.

The entities should be free to assemble without any "magic" going on. The part sorting, wrapping and so on compositing should happen as a _separate step_ in a separate class. 

I may be able to help out, if I have your agreement.

**Comment by rmuktader** [comment]
> Using your own tutorials, the resulting structure is this:

@ghost where are these tutorial that allowed you to create that structure?

**Comment by fabpot** [comment]
I'm closing this issue as it's going to be fixed by Symfony Mailer/Mime, which will replace Swiftmailer eventually.
