### ISSUE TITLE
Cannot use "Name" <address> format for setFrom

### ISSUE THREAD

**Issue by TheCycoONE** [swiftmailer/swiftmailer#437]
In our case our from address is already translated into the header format "Name" &lt;address&gt;, however if we pass that string into setFrom it complains that the address is invalid according to RFC 2822.

Since this was the format PEAR::Mail and other mail clients require, it's the format we use throughout our application.  Obviously we could write a fairly simple regex to grab the name and address separately, but since they are going to end up back in this format, and it's quite common, I think support for it deserves to be in the library.

**Comment by spezialist1** [comment]
Hi all.

Unfortunately, I can confirm that the current swiftmailer version also doesnt support above the stated senders format. Nevertheless, why it is impossible to solve or bypass this problem? To me, for example, is also required for sending mail such format.

Very thanks for the support.
