### ISSUE TITLE
getmypid() has been disabled for security reasons

### ISSUE THREAD

**Issue by adis-io** [swiftmailer/swiftmailer#445]
https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Mime/SimpleMimeEntity.php#L85

https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Mime/SimpleMimeEntity.php#L420

https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Mime/SimpleMimeEntity.php#L689

From php getmypid() function page

> **_Warning**_
> Process IDs are not unique, thus they are a weak entropy source. We recommend against relying on pids in security-dependent contexts.

**Comment by amineameur** [comment]
hello guys first i'am not prof on this things :')
i realy tried to read this shit but i din'tget the joke 
very simple im using password reset to email a link to my users to change there password
so in local everything goes but when i set my app on a server when i send mail i got this error
getmypid() has been disabled for security reasons
tell me what to do without philosophy
