### ISSUE TITLE
Cannot inherit previously-inherited or override constant LEVEL_TOP from interface Swift_Mime_Message

### ISSUE THREAD

**Issue by dryu** [swiftmailer/swiftmailer#477]
Ok, this one has some mentions on the internet related to APC, but I'm at PHP 5.4.22 and do not use APC.

This fatal exception is thrown at:

swiftmailer\swiftmailer\lib\classes\Swift\Mime\SimpleMessage.php

PHP 5.4.22
SwiftMailer 5.2.0 (2014-05-08)

Active PHP extensions:

```
extension=php_curl.dll
extension=php_gd2.dll
extension=php_mbstring.dll
extension=php_openssl.dll
extension=php_pdo_oci.dll
extension=php_pdo_sqlsrv_54_nts.dll
extension=php_wincache.dll
```

The mail is being composed and send from Yii2 wrapper like that:

``` php
Yii::$app->mail->compose('sr-full', ['sr' => $sr])->setFrom(['noreply@domain.com' => 'Mailer'])->setTo($email)->setSubject('subject')->send();
```

The same works sometimes when I restart my development server (PHP in-build web server in 5.4), but after a successful mail submission, all subsequent attempts fail like that.

Please advise.

**Comment by hardsetting** [comment]
I have a similar issue using PHP 5.6 and the SwiftMailer integrated in the framework Yii 2.
Did disabling wincache resolve the problem?
