### ISSUE TITLE
OPENSSL_ALGO_SHA256 only in PHP 5.4

### ISSUE THREAD

**Issue by reedy** [swiftmailer/swiftmailer#486]
swiftmailer requires PHP >= 5.2.4, but seemingly unconditionally allows use of rsa-sha256/OPENSSL_ALGO_SHA256

**Comment by fabpot** [comment]
min version is not 5.2 anymore

**Comment by reedy** [comment]
https://github.com/swiftmailer/swiftmailer/blob/5.x/composer.json#L18 says 5.3.3

https://secure.php.net/manual/en/openssl.signature-algos.php says OPENSSL_ALGO_SHA256 was added in 5.4.8

**Comment by Rotzbua** [comment]
@reedy There is no bug, this is simply a bad issue report. You did not provide any example, reproducible description or affected class. And no swiftmailer version which is affected.
