### ISSUE TITLE
Office 365

### ISSUE THREAD

**Issue by rhodrykorb** [swiftmailer/swiftmailer#497]
A client is now using Office 365 (Exchange Online) for their corporate email system.

This SwiftMailer code seems to work for other SMTP servers, but not Office365:
`Smtp::newInstance('smtp.office365.com', 587, 'tls')->setUsername('username@mydomain.com')->setPassword('Password1');`

The error being outputted is:
`Connection could not be established with host smtp.office365.com [An attempt was made to access a socket in a way forbidden by its access permissions. #10013]`

**Comment by aniruddhaad** [comment]
Here is another observation with swiftmailer 5.3.1.
For me it worked on windows 7 with XAMPP.
Its NOT working on production CENT OS 5.1

Continuously getting error -
Connection could not be established with host smtp.office365.com [Network is unreachable #101]

A little variation in ->setAuthMode()  to NTLM, LOGIN, XOAUTH2, CRAM-MD5...
got one of following (with Swift_Plugins_Loggers_EchoLogger)-
1) Connection could not be established with host smtp.office365.com [Connection timed out #110]
& 
 2) Connection could not be established with host smtp.office365.com [Connection timed out #101]

Even opened port 587 from firewall & encryption to "tls" but no luck.

**Comment by aniruddhaad** [comment]
Another test with Port 25, encryption tls, setAuthMode('LOGIN') works.

**Comment by poul-kg** [comment]
@rhodrykorb Have you found any solution? I have exactly the same issue.

**Comment by aniruddhaad** [comment]
Following thing works :)

->setHost("smtp.office365.com")
->setSourceIp('x.x.x.x') //replace x with your ip address
->setLocalDomain('example.com')
		->setPort(25)
		->setEncryption('tls')
		->setAuthMode('LOGIN');

So port 25 with tls (I thought tls port would be 587 earlier but it works with 25 port with tls)
Hope it helps ;)

**Comment by cordoval** [comment]
you forgot the username and password lines i assume

**Comment by aniruddhaad** [comment]
I didn't wrote... As its standard function call with single value as parameter  I.e. Username &  password

**Comment by aniruddhaad** [comment]
Well... So far office 365 worked OK but few months back we have switch to mandril as we were constantly getting host not found (php_getaddreas not able to.... Bla bla)... 
Mandril or send grid works like charm.. No waiting for establishing connection like office 365...

**Comment by cordoval** [comment]
that is if no hippa requirement is in place. However office 365 is good option for hippa apps. Could this problem you speak of be worked around somehow? any suggestions for those staying with office 365?

**Comment by aniruddhaad** [comment]
Well after using office 365  for couple of years... It did not worked smoothly,  rather had to tweak code few times to get it working again... So its not good option to go with office 365 at least for sending email from php swift mailer. Though It works great with email client like outlook etc. 

Work around could be grab it of smtp.office365.com but the iPhone keeps changing... So using it will brake the code.

**Comment by aniruddhaad** [comment]
Pardon... Auto complete by phone
#grab ip address of smtp.office365.com but the ip keeps changing... So using it will brake the code.

**Comment by cordoval** [comment]
works like a charm thanks! 👍

**Comment by cordoval** [comment]
this issue can be closed i think

**Comment by cordoval** [comment]
For those still with it, port is not 25, it is MAILER_PORT=587
