### ISSUE TITLE
Question about SwiftMailer on WordPress.org vs. GitHub

### ISSUE THREAD

**Issue by davidfavor** [swiftmailer/swiftmailer#523]
The http://WordPress.org version is 4.3.0 for this plugin.

The http://GitHub.com version is 5.2.2 for this plugin.

Also the 4.3.0 version emits broken PHP prior to the <DOCTYPE> tag on all pages.

So I'm imagining the correct way to use this plugin is to do to a clone into wp-content/plugins.

If this is correct, let me know.

Also, I recommend you place a note on http://WordPress.org directing people to your GitHub version.

Thanks.

**Comment by hubdotcom** [comment]
Hello, author of the WP plugin here - this has been updated to the latest stable version of Swift Mailer - please update your plugin and let me know any feedback you have! https://wordpress.org/plugins/swift-mailer
