### ISSUE TITLE
Feature request: create attachment from stream resource

### ISSUE THREAD

**Issue by baohx2000** [swiftmailer/swiftmailer#527]
Some applications may need to create attachments from remote file resources where it's not realistic to pull the entire contents into a string and create an attachment that way.  For example, creating an attachment using a 20M file from S3.  For this use case, I have to create a temp file locally, stream the contents of the s3 file into it, then use the temp file to create the attachment using Swift_Attachment:fromFile.  Of course, I also have to remove the temp file afterwards.
It would be very nice if I could just create an attachment using the s3 stream resource in the first place.

**Comment by Richard87** [comment]
I would also love this (and I think it's getting more and more relevant!)

**Comment by Gemorroj** [comment]
current workaround
```php
$f = fopen('file.txt', 'r'); // <- my stream

$attachment = \Swift_Attachment::newInstance(
    \stream_get_contents($f), // get stream content
    'file.txt'
);
```
