### ISSUE TITLE
RFC 6530

### ISSUE THREAD

**Issue by pmairif** [swiftmailer/swiftmailer#535]
When trying to send a mail to an address that contains international characters (conforming to RFC 6530, e. g. 'john.dö@example.com'), I get a Swift_RfcComplianceException. Are there any plans to extend swift mailer to conform to RFC 6530? Or do I just miss sth.?

**Comment by dstevenson** [comment]
Running into a similar issue here with internationalized emails supported by RFC 6530, any plans or workarounds ?

**Comment by xabbuh** [comment]
#409 would make this work I think.

**Comment by dstevenson** [comment]
@xabbuh You're correct. I'll continue to follow up there.
