### ISSUE TITLE
SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by paulfry** [swiftmailer/swiftmailer#544]
Hello,

We are using Laravel 4.2 on Laravel Forge servers. We are getting the error above when trying to send through SMTP.

Our SSL provider has confirmed the cert is successfully installed. 

Our SMTP provider has confirmed all ok on the server front.

A bit stuck now. Any suggestions would be very helpful.

**Comment by Hikkijp** [comment]
As @if-joerch said, the workaround works and would be great to have it configurable.
:+1:

It may affect many other people as well.

**Comment by iz65535** [comment]
Hi
This topic is important for our projects too.  For now we manually change sources to add self-signed certificates ignore, but it's not a good idea

also i've found this code (sorry if it's obvious) https://github.com/swiftmailer/swiftmailer/issues/571

**Comment by acinelli** [comment]
Code implement here:
https://github.com/acinelli/swiftmailer/tree/topic_571

I've submitted a Pull Request, awaiting...

**Comment by unnaki** [comment]
Any news on this ?

**Comment by ITwrx** [comment]
maybe not pure self signed certs, but you can use certs signed by your own CA without disabling peer checking in swiftmailer. You have to import the signing CA's cert as a trusted CA into the sending server. Then it is treated just like a "normal" cert. The Arch wiki has details for those inclined.

**Comment by BrendonKoz** [comment]
My shared hosting provider's SMTP server has this issue as well and in order to send email via PHP 5.6 I have to disable the security that 5.6 has created for us, which I agree is horrible, but at the moment my only option. I too had to set this workaround to connect to our host's mail server. Until all hosts can catch up and fix this issue, having a workaround -- whether suggested or not -- would be a welcomed thing.

At the very least, an ability to set stream_socket_client $options from code outside the core should work.

**Comment by karborator** [comment]
Ok, it works for me too, but what about that emails are stored into Spam folder ?

**Comment by Shweta-Deodhare** [comment]
Thanks if-joerch, It helped me, i had same issue, and it works on laravel 5 too!

**Comment by premejo** [comment]
Seems there is a way to send those options through without having to add any lines to StreamBuffer.php.
Just create the following $transport instance using the additional ->setStreamOptions() method call.

// Create the Transport
$https['ssl']['verify_peer'] = FALSE;
$https['ssl']['verify_peer_name'] = FALSE;  // seems to work fine without this line so far
$transport = Swift_SmtpTransport::newInstance('smtp.mailserver.net', 587, 'tls')
	->setUsername('username')
	->setPassword('password')
	->setStreamOptions($https)
	;

**Comment by sstok** [comment]
Try setting the `'cafile'` for `$https['ssl']`, eg. 

`$https['ssl']['cafile'] = '/etc/ssl/certs/ca-certificates.crt';`

**Comment by wlepinski** [comment]
@premejo Where did you created those lines?

**Comment by Phil795** [comment]
Something has changed. 

Now you need to add the two lines **before** stream_context_create(...)

$options['ssl']['verify_peer'] = FALSE;
$options['ssl']['verify_peer_name'] = FALSE;

**Comment by speller** [comment]
Same issue...

**Comment by Phil795** [comment]
Here is a complete working code snippet.
Try to overwrite your function

`

    private function _establishSocketConnection()
    {

        $host = $this->_params['host'];
        if (!empty($this->_params['protocol'])) {
            $host = $this->_params['protocol'].'://'.$host;
        }

        $timeout = 15;
        if (!empty($this->_params['timeout'])) {
            $timeout = $this->_params['timeout'];
        }

        $options = array();
        if (!empty($this->_params['sourceIp'])) {
            $options['socket']['bindto'] = $this->_params['sourceIp'].':0';
        }

        if (isset($this->_params['stream_context_options'])) {
            $options = array_merge($options, $this->_params['stream_context_options']);
        }

	$options['ssl']['verify_peer'] = FALSE;
	$options['ssl']['verify_peer_name'] = FALSE;

        $streamContext = stream_context_create($options);

        $this->_stream = @stream_socket_client($host.':'.$this->_params['port'], $errno, $errstr, $timeout, STREAM_CLIENT_CONNECT, $streamContext);
        if (false === $this->_stream) {
            throw new Swift_TransportException(
                'Connection could not be established with host '.$this->_params['host'].
                ' ['.$errstr.' #'.$errno.']'
                );
        }
        if (!empty($this->_params['blocking'])) {
            stream_set_blocking($this->_stream, 1);
        } else {
            stream_set_blocking($this->_stream, 0);
        }
        stream_set_timeout($this->_stream, $timeout);
        $this->_in = &$this->_stream;
        $this->_out = &$this->_stream;
    }`

**Comment by speller** [comment]
This works, but I'm using composer to build dependencies for the project so I have to modify this function manually after each build. Don't understand why developers still did nothing to fix this...

**Comment by lazaro3487** [comment]
Here is a complete solution for this problem. The container is injected throw a service:

    public function sendMail($subject, $template, $to)
    {
        //Estas lineas son para cuando el servidor tiene un certificado no valido
        $https['ssl']['verify_peer'] = FALSE;
        $https['ssl']['verify_peer_name'] = FALSE;

        $transport = \Swift_SmtpTransport::newInstance($this->container->getParameter('mailer_host'), $this->container->getParameter('mailer_port'),  $this->container->getParameter('mailer_encryption'))
            ->setUsername($this->container->getParameter('mailer_user'))
            ->setPassword($this->container->getParameter('mailer_password'))
            ->setStreamOptions($https)
        ;

        $message = \Swift_Message::newInstance()
            ->setSubject($subject)
            ->setFrom($this->container->getParameter('mailer_user'))
            ->setTo($to)
            ->setBody($template,'text/html');

        return $this->mailer->newInstance($transport)->send($message);
    }

**Comment by salvisb** [comment]
@lazaro3487 where to put this code in Laravel?

**Comment by kamleshwebtech** [comment]
> Here is a complete working code snippet.
> Try to overwrite your function
> 
> ```
> private function _establishSocketConnection()
> {
> 
>     $host = $this->_params['host'];
>     if (!empty($this->_params['protocol'])) {
>         $host = $this->_params['protocol'].'://'.$host;
>     }
> 
>     $timeout = 15;
>     if (!empty($this->_params['timeout'])) {
>         $timeout = $this->_params['timeout'];
>     }
> 
>     $options = array();
>     if (!empty($this->_params['sourceIp'])) {
>         $options['socket']['bindto'] = $this->_params['sourceIp'].':0';
>     }
> 
>     if (isset($this->_params['stream_context_options'])) {
>         $options = array_merge($options, $this->_params['stream_context_options']);
>     }
> 
> $options['ssl']['verify_peer'] = FALSE;
> $options['ssl']['verify_peer_name'] = FALSE;
> 
>     $streamContext = stream_context_create($options);
> 
>     $this->_stream = @stream_socket_client($host.':'.$this->_params['port'], $errno, $errstr, $timeout, STREAM_CLIENT_CONNECT, $streamContext);
>     if (false === $this->_stream) {
>         throw new Swift_TransportException(
>             'Connection could not be established with host '.$this->_params['host'].
>             ' ['.$errstr.' #'.$errno.']'
>             );
>     }
>     if (!empty($this->_params['blocking'])) {
>         stream_set_blocking($this->_stream, 1);
>     } else {
>         stream_set_blocking($this->_stream, 0);
>     }
>     stream_set_timeout($this->_stream, $timeout);
>     $this->_in = &$this->_stream;
>     $this->_out = &$this->_stream;
> }
> ```

what is file path?? Please share thanks.

**Comment by Phil795** [comment]
> > Here is a complete working code snippet.
> > Try to overwrite your function
> > ```
> > private function _establishSocketConnection()
> > {
> > 
> >     $host = $this->_params['host'];
> >     if (!empty($this->_params['protocol'])) {
> >         $host = $this->_params['protocol'].'://'.$host;
> >     }
> > 
> >     $timeout = 15;
> >     if (!empty($this->_params['timeout'])) {
> >         $timeout = $this->_params['timeout'];
> >     }
> > 
> >     $options = array();
> >     if (!empty($this->_params['sourceIp'])) {
> >         $options['socket']['bindto'] = $this->_params['sourceIp'].':0';
> >     }
> > 
> >     if (isset($this->_params['stream_context_options'])) {
> >         $options = array_merge($options, $this->_params['stream_context_options']);
> >     }
> > 
> > $options['ssl']['verify_peer'] = FALSE;
> > $options['ssl']['verify_peer_name'] = FALSE;
> > 
> >     $streamContext = stream_context_create($options);
> > 
> >     $this->_stream = @stream_socket_client($host.':'.$this->_params['port'], $errno, $errstr, $timeout, STREAM_CLIENT_CONNECT, $streamContext);
> >     if (false === $this->_stream) {
> >         throw new Swift_TransportException(
> >             'Connection could not be established with host '.$this->_params['host'].
> >             ' ['.$errstr.' #'.$errno.']'
> >             );
> >     }
> >     if (!empty($this->_params['blocking'])) {
> >         stream_set_blocking($this->_stream, 1);
> >     } else {
> >         stream_set_blocking($this->_stream, 0);
> >     }
> >     stream_set_timeout($this->_stream, $timeout);
> >     $this->_in = &$this->_stream;
> >     $this->_out = &$this->_stream;
> > }
> > ```
> 
> what is file path?? Please share thanks.

You can find the function in StreamBuffer.php 

`/vendor/switftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php`
