### ISSUE TITLE
Misleading SSL/TLS option

### ISSUE THREAD

**Issue by dol** [swiftmailer/swiftmailer#545]
The security argument of Swift_SmtpTransport is misleading with the naming.

```
'ssl' => SMTP over SSL/TLS (recommended port: 465)
'tls' => STARTTLS (SSL/TLS) over TCP (recommended port: 587)
```

`'ssl'` can also use the [TLS protocol](https://www.fastmail.fm/help/technical/ssltlsstarttls.html). Since SSLv3 are widely disabled, only the TLS protocol is used. It would be clearer, if the options are called differently.
This is a BC break, if the security options are called differently.

An possible solution to this problem would be to an autodetection of the SSL or STARTTLS. If the argument 'security' is set to 'true', it first tries to establish an SSL connection, if it's not working, try reestablish an 'TCP' connection and look for the Capability of 'STARTTLS'.

**Comment by RealRancor** [comment]
I agree that this should be clarified. Some notes about the difference between the ssl(SSL/TLS) and the tls(STARTTLS) could be also mentioned at the documentation:

http://swiftmailer.org/docs/sending.html#encrypted-smtp

This has also lead to some confusion in https://github.com/owncloud/documentation/issues/1778

**Comment by Sebi94nbg** [comment]
Thanks guys!

Laravel 5.4 uses this PHP libary too and had the problem, that it couldn't send emails due of a SSLv3 handshake failure:
```
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```

After changing the mentioned settings, it worked fine:
```
MAIL_PORT=465 (before '25')
MAIL_ENCRYPTION=ssl (before 'tls')
```

**Comment by Rotzbua** [comment]
@Sebi94nbg ssl3 is broken for years now... better upgrade your mailserver.. this issue is about the naming of the technique

**Comment by Sebi94nbg** [comment]
@Rotzbua the mail server is up2date, not vulnerable and does only allow recommended cipher suites and protocols. That's the reason, why I got this issue.

**Comment by Rotzbua** [comment]
@Sebi94nbg I think that a server environment issue. It seems that php and mail server do not support the equal ciphers. Which cipher does your server (php,curl,openssl) and your mailserver support?

Maybe it is this bug, read first comment:
https://secure.php.net/manual/de/function.stream-socket-enable-crypto.php

**Comment by Sebi94nbg** [comment]
@Rotzbua yeah, maybe.

On both servers is SSLv3 disabled and/or not available.

TLS is available with the following cipher list on both servers:
`ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!SHA:!SHA1;`

**Comment by Rotzbua** [comment]
@Sebi94nbg If you use the website from your website, there is only tls1.2 allowed. The link above describes that the config constant of php has been changed, so that now only tls1.0 is used by default. I guess that's the reason for the error.

**Comment by ITwrx** [comment]
@Sebi94nbg you may want to take a look at #598. especially sstok's comment.
