### ISSUE TITLE
V3->V4/5 slow performance of QpEncoder->_encodeString

### ISSUE THREAD

**Issue by zevnikrok** [swiftmailer/swiftmailer#550]
When migrating from V3 to V4 or V5 library we've encountered a major performance issue, while sending our html newsletter (65kB). Processing of each email jumped from 2 seconds to about 6 seconds.

Profiler took me to the QpEncoder->_encodeString, which reads only 4 bytes by default. Increasing default value from 4 to 1024 (as suggested by some other user) puts this back to normal performance.

Why does it read only 4 bytes by default and if increasing this value to 1024 producess any side effects?

**Comment by zevnikrok** [comment]
Is there any progress on this issue? Or workaround/configuration change to make latest version perform with the same speed as V3?

Any respone would be appreciated.

**Comment by zevnikrok** [comment]
FreeBSD 8.1, PHP 5.3.16
source&destination charsets are both UTF-8
loaded extensions: Core, date, ereg, libxml, pcre, Reflection, SPL, hash, session, apache2handler, bcmath, bz2, ctype, curl, dom, ftp, standard, iconv, json, mbstring, mcrypt, mysqlnd, mysqli, pcntl, PDO, pdo_mysql, posix, mysql, soap, tokenizer, xml, xmlreader, xmlwriter, zlib, filter, gd, openssl, SimpleXML, xmlrpc, zip, fileinfo, memcached, memcache, geoip, imap, Phar, mhasha

**Comment by xdecock** [comment]
if you can move up to php > 5.4.7, the issue is solved (switched to cbased
qpencoder)

Regards

On Tue, May 5, 2015 at 6:49 AM, zevnikrok <notifications@github.com> wrote:

> FreeBSD 8.1, PHP 5.3.16
> source&destination charsets are both UTF-8
> loaded extensions: Core, date, ereg, libxml, pcre, Reflection, SPL, hash,
> session, apache2handler, bcmath, bz2, ctype, curl, dom, ftp, standard,
> iconv, json, mbstring, mcrypt, mysqlnd, mysqli, pcntl, PDO, pdo_mysql,
> posix, mysql, soap, tokenizer, xml, xmlreader, xmlwriter, zlib, filter, gd,
> openssl, SimpleXML, xmlrpc, zip, fileinfo, memcached, memcache, geoip,
> imap, Phar, mhasha
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/550#issuecomment-98948995>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by voku** [comment]
I can also see this problem |  PHP 5.6.13-1 (opcache curl igbinary intl memcache pdo_mysql readline tidy xsl mysqlnd gd imagick mcrypt mysqli pdo_sqlite redis twig blackfire pdo geoip imap memcached mysql pspell sqlite3 xmlrpc)

44567 Calls (QpEncoder->_nextSequence) for 18 e-mails

![mail](https://cloud.githubusercontent.com/assets/264695/9770165/e0f8f898-572e-11e5-928d-943ebe0e6bd9.jpg)

I will try this again with ```$this->message = Swift_Message::newInstance(); $this->message->setEncoder(Swift_Encoding::get8BitEncoding()); ``` ...

**Comment by zevnikrok** [comment]
Unfortunately I still haven't been able to migrate to newer version.

**Comment by voku** [comment]
@zevnikrok maybe you can test my fork https://github.com/voku/swiftmailer so that I know if there is a performance improvment with this changes? thx. 

-> compare -> https://github.com/swiftmailer/swiftmailer/compare/5.x...voku:5.x

**Comment by voku** [comment]
with "Swift_CharacterStream_MbCharacterStream" (https://github.com/giggsey/swiftmailer/commit/30da017ff51eed9f152b765b019693883dd989b4) I could increase the performance about ~60% ...

![swiftmailer](https://cloud.githubusercontent.com/assets/264695/15547120/bd34c0f0-22a2-11e6-8c70-293be070ff89.png)

**Comment by fabpot** [comment]
@voku Can you submit a PR for the changes? I would be much easier to review and test. Thanks.
