### ISSUE TITLE
Old copyright 2009 on website

### ISSUE THREAD

**Issue by gaumondp** [swiftmailer/swiftmailer#552]
This is more than cosmetic it's about perception... 

People landing on swiftmailer.org for the first time see a prominent "© 2009 Chris Corbyn" and can believe the project is old and not maintained anymore.

The year should be removed or changed IMHO.

**Comment by TheDigitalOrchard** [comment]
Not sure if this is relevant anymore? I'm not seeing that. But that said, the latest 5.4.0 release is not promoted through the website's blog, which seems to be an oversight (to me). Maybe people are too busy to manage the website properly? That's life as an open-source dev...
