### ISSUE TITLE
Strange Bcc headers logic

### ISSUE THREAD

**Issue by mastir** [swiftmailer/swiftmailer#554]
I'm tring to add Bcc and Cc headers passed from my CMS, as in documentation i've got 
    $bcc = array(
        array('abc@abc.com'=>'abc'),
        array('cba@cba.com'=>'cba'),
    );

```
$mail->setBcc($bcc)
```

causes ContextErrorException: Warning: Illegal offset type in /var/web/inventure/data/Skynar/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php line 405

```
$mail->setBcc([]);
foreach($bcc as $address)
    $mail->addBcc($address) -> Validation error



$mail->setBcc([]);
foreach($bcc as $addr){
    $name = current($bcc);
    $email = key($bcc);
    $mail->addBcc($email,$name); -> this way it works
} 
```

what am i doing wrong?

**Comment by davedarko** [comment]
I'm getting the same results as posted above "preg_match() expects parameter 2 to be string" for a valid cc array.
