### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by Paradox81ru** [swiftmailer/swiftmailer#555]
Hello. I'm trying to send mail in Yii2. Seems to do everything as written, but instead of sending mail I get the error:
Connection to tcp://smtp.mail.EN:465 Timed Out

My configuration:
'mailer' => [
    'class' => 'yii\swiftmailer\Mailer',
    'useFileTransport' => false,
    'transport' => [
        'class' => 'Swift_SmtpTransport',
        'host' => 'smtp.mail.ru',
        'username' => 'mail@mail.ru',
        'password' => 'password',
        'port' => '465',
        'encryption' => 'tls',
    ],
], 

Send so:
Yii::$app->mailer->compose('confirmEmail', ['user' => $user])
    ->setFrom('mail@mail.ru')
    ->setTo('mail@land.ru')
    ->setSubject('Email confirmation for ... ')
    ->send(); 

In the trace I figured fail after this function:
public function readLine($sequence)
{
    if (isset($this->_out) && !feof($this->_out)) {
        $line = fgets($this->_out);
        if (strlen($line) == 0) {
            $metas = stream_get_meta_data($this->_out);
            if ($metas['timed_out']) {
                throw new Swift_IoException(
                'Connection to '.
                $this->_getReadConnectionDescription().
                 ' Timed Out'
                );
            }
        }
        return $line;
    }
} 

more precisely, after this line:
    $line = fgets($this->_out); 
in file StreamBuffer.php.
After that begins to form the error. Please tell me, what can it be?
Thank you.

**Comment by micik** [comment]
ini_set('max_execution_time', 300);
