### ISSUE TITLE
Encapsulate $swift_mime_types

### ISSUE THREAD

**Issue by dfyx** [swiftmailer/swiftmailer#560]
Making `$swift_mime_types` a global variable and later unsetting it feels very hacky. It would probably be better to encapsulate it as a static member in a class.

The reason I noticed the current solution is because I need to do some lookups in my own project (that uses Swift) and my only good solution was to copy the contents of `mime_types.php` into my own class that looks like the following:

``` php
<?php
class MimeType {
    private static $mimeTypes = array(
        '3dml' => 'text/vnd.in3d.3dml',
        '3ds' => 'image/x-3ds',
        '3g2' => 'video/3gpp2',
        '3gp' => 'video/3gpp',
        '7z' => 'application/x-7z-compressed',
        'aab' => 'application/x-authorware-bin',
        // ...
        'zir' => 'application/vnd.zul',
        'zirz' => 'application/vnd.zul',
        'zmm' => 'application/vnd.handheld-entertainment+xml',
        '123' => 'application/vnd.lotus-1-2-3',
    );

    public static function register($mimeType, $ext) {
        static::$mimeTypes[$ext] = $mimeType;
    }

    public static function lookup($ext) {
        return static::$mimeTypes[$ext];
    }
}
```

**Comment by fabpot** [comment]
I'm closing this issue as it's going to be fixed by Symfony Mailer/Mime, which will replace Swiftmailer eventually.
