### ISSUE TITLE
PSR-4 Autoloading And Namespacing

### ISSUE THREAD

**Issue by GrahamCampbell** [swiftmailer/swiftmailer#566]
In #409 it's been discussed that 6.0 will be needed. Is there any chance we can overhaul the autoloading to PSR-4 and add proper namespacing too?

**Comment by Dygear** [comment]
Dito on the PSR-4 support, sad to see this hasn't been talked about in over a year.

**Comment by dhm80** [comment]
+1 for PSR-4

**Comment by kjdion84** [comment]
+1

**Comment by fabpot** [comment]
Closing as it's not worth it.

**Comment by ConnorVG** [comment]
This is severely disappointing.

**Comment by aat2703** [comment]
Not worth it? Didn't see that coming in 2017...Can this issue be re-considered? This issue would mean an increase in performance for autoloaders at least for PhalconPHP which have autoloaders written in C. Link: https://olddocs.phalconphp.com/en/3.0.0/reference/loader.html

**Comment by tflori** [comment]
@fabpot I see it the same: when using `composer dump-autoload --optimize` a psr-4 would make much more sense.

There are not many good mail client implementations on packagist. PHPMailer with it's strange one class for all principle but namespaces like hell `PHPMailer\PHPMailer\PHPMailer` and several mail libraries from frameworks.. I rather would use swiftmailer but unfortunately  for me this is a no go.

Not the autoloader is the problem - the missing namespaces are. In times of php7 a class name `Swift_StreamFilters_StringReplacementFilter` doesn't fit to any coding style guide.

**Comment by Rotzbua** [comment]
@tflori @kjdion84 Swiftmailer is OSS. So why not fork and fix it?

**Comment by madflow** [comment]
@Rotzbua My guess is - because there are already people offering their help in this thread and they where met with: 
> Closing as it's not worth it.

**Comment by BenMorel** [comment]
> Closing as it's not worth it.

Can hardly believe this comment.

**Comment by fabpot** [comment]
@BenMorel The reality is that nobody forked Swiftmailer to switch to PSR-4.

Instead, I've done all the work with a brand new version that uses modern PHP: Symfony Mailer, which is the successor of Swiftmailer. I can hardly believe that I got no help whatsoever.

**Comment by BenMorel** [comment]
@fabpot Happy to hear that!

I actually totally missed Symfony Mailer:

- I never heard of it until now
- googling for "symfony mailer" actually returns the Swift Mailer docs on the Symfony website first
- there is a small mention of it on the [Swift Mailer](https://symfony.com/doc/current/email.html) page, but small enough to miss it
- installing the latest Symfony version using the `website-skeleton` still installs Swift Mailer

I can understand that it's not more emphasized at the moment, as the docs say it's experimental. Once it becomes stable, it'd deserve a bit more exposure though.

Anyway it's good news, thank you for releasing it, and I'll be happy to test it, and help improve it if I can.

**Is it based on the Swift Mailer codebase?** Is it just Swift Mailer with namespaced classes & renamed methods only, or are there more fundamental changes that make it more *experimental*?
