### ISSUE TITLE
Allow setting ssl connection options, e.g. self-signed certificates

### ISSUE THREAD

**Issue by acinelli** [swiftmailer/swiftmailer#571]
I'm working on a project using swiftmailer and needed to allow use of a self-signed certificate.  I've completed the simple work on this and will be making a pull request shortly.

**Comment by acinelli** [comment]
Code implement here:
https://github.com/acinelli/swiftmailer/tree/topic_571

I've submitted a Pull Request, awaiting...

**Comment by joostfaassen** [comment]
:+1:

**Comment by h-wang** [comment]
:+1:

**Comment by rdpascua** [comment]
:+1:

**Comment by lollypopgr** [comment]
:+1:

**Comment by shulcsm** [comment]
Accept please

**Comment by hcoat** [comment]
:+1: 
This is very needed.

**Comment by sstok** [comment]
@acinelli can you open a pull-request with these changes? Note that you must rebase on the 5.x branch to update your feature branch.

**Comment by deminy** [comment]
:+1: Wish this (or an alternative approach) could be accepted. The fix is very important for using Swift Mailer on PHP 5.6. Thanks

**Comment by aerkanc** [comment]
+1 for me! Please fix!

**Comment by antic-eye** [comment]
:+1:

**Comment by giovkanata** [comment]
:+1:

**Comment by greabock** [comment]
```
Swift_DependencyContainer::getInstance()
            ->register('transport.buffer')
            ->asNewInstanceOf(InsecureStreamBuffer::class)
            ->addConstructorLookup('transport.replacementfactory');
```

where InsecureStreamBuffer extends Swift_Transport_StreamBuffer

**Comment by Braunson** [comment]
:+1:

**Comment by piotrooo** [comment]
:+1:  waiting for release

**Comment by mareckii** [comment]
:+1: waiting for release

**Comment by snwFlake** [comment]
:+1: also waiting for release :)

**Comment by simoncpu** [comment]
It's November 25, 2016, this patch has not yet been merged. :(
