### ISSUE TITLE
Configuration to override message ID generation domain

### ISSUE THREAD

**Issue by dmyers** [swiftmailer/swiftmailer#576]
Could there be an option or some way to override the default way generating message IDs are handled? Many people may not have `$_SERVER['SERVER_NAME']` set and the ability to override would be really helpful.

https://github.com/swiftmailer/swiftmailer/blob/87f0b05a3ebb3cb8e4ea9ca12133ce6f28c7a15e/lib/classes/Swift/Mime/SimpleMimeEntity.php#L686

[Here's an interesting discussion](https://core.trac.wordpress.org/ticket/25239) about this at WordPress.

**Comment by c960657** [comment]
A PR has been created for this feature:
#619 Separate message/content ID generator class

**Comment by dmyers** [comment]
Sweet! Thank you for mentioning! I hope it gets merged in.

**Comment by antongorodezkiy** [comment]
btw, as far as I can see, it's should be already merged.

**Comment by murilozilli** [comment]
Can someone inform what the configuration is? I couldn't find it
