### ISSUE TITLE
Message::addBcc doesn't work

### ISSUE THREAD

**Issue by kelunik** [swiftmailer/swiftmailer#579]
Calling `$message->addBcc("...")` doesn't work and results in:

> Warning:  Illegal offset type in /.../vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php on line 404

**Comment by xabbuh** [comment]
How do you call the method?

**Comment by kelunik** [comment]
```php
$message = \Swift_Message::newInstance()
	->setSubject($subject)
	->setFrom([MAIL_USER => 'User Portal'])
	->setBody($body)
;

foreach($users as $user) {
	$message->addBcc($user->mail);
}
```

**Comment by xabbuh** [comment]
Is the `$mail` property of your `$user` objects a string?

**Comment by kelunik** [comment]
Yes, all works fine using
```php
foreach ($users as $user) {
    $mails[] = $user->mail;
}

$message->setBcc($mails);
```

**Comment by flashek** [comment]
Bump, same problem for me. I think getBcc() should return empty array in case of empty bcc reciepient list rather than null.
