### ISSUE TITLE
Allow to get the filename used in FileSpool

### ISSUE THREAD

**Issue by rvanlaak** [swiftmailer/swiftmailer#586]
When a message is spooled to file, [`FileSpool` generates a random string](https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/FileSpool.php#L92-L112) but it is not possible to reuse it.

If the `SpoolTransport` was able to get the `$fileName` it could also add it to the `SendEvent` [here](https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Transport/SpoolTransport.php#L98-L103).

Any reason why the `$fileName` is not returned? I'd like to use it to allow the user to cancel sending an email. Shouldn't the `FileSpool` make use of the `Mime_Message::generateId()`? That would allow us to locate the spooled email later.

**Comment by Rvanlaak** [comment]
@fabpot seems like I can use the `SendEvent` for this since `5.4.0` if I'm correct? :+1: 

https://github.com/swiftmailer/swiftmailer/search?utf8=%E2%9C%93&q=RESULT_SPOOLED
