### ISSUE TITLE
bug mail

### ISSUE THREAD

**Issue by semiaLi** [swiftmailer/swiftmailer#589]
Hi,
I am using swiftmailer, i want to know if there are somebody who have received the same body mail of two different person with two different object?! In fact, as an administrator of a web application i have receive a mail at 16:00 with a sender X and an object M . But 20minute later, i receive the same mail body with different sender Y and diffrent object.N , knowing that the body sent contained a very personel information that the second one can't know so he can't resent the same body essentially with the same espacement ...

**Comment by xdecock** [comment]
Have you tried disabling the cache?

(just to be 100% sure nothing is involved here)

**Comment by semiaLi** [comment]
But if i disable the cache, if i have many mails sent in the same time and if the swift haven't already sent the first one will be deleted ?

**Comment by xdecock** [comment]
I don't understand the question,

all a disabled cache will do is reduce performance for a mail sent multiple
times, which, from your first explanation is not the case

On Mon, Mar 30, 2015 at 12:02 PM, semiaLi <notifications@github.com> wrote:

> But if i disable the cache, if i have many mails sent in the same time and
> if the swift haven't already sent the first one will be deleted ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/589#issuecomment-87619890>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by semiaLi** [comment]
ok i will try to disable the cache , in fact now i am saving the sent emails in the base so that i can see this bug if it will be reproduced an other time.
Thank you for your answer.
