### ISSUE TITLE
Towards 6.0, the next steps

### ISSUE THREAD

**Issue by fabpot** [swiftmailer/swiftmailer#590]
Next steps:
- [ ] replace the Swiftmailer even dispatcher by the Symfony one.

**Comment by stof** [comment]
@fabpot would it be worth refactoring Swiftmailer to stop using a static service locator in a weird way (look at how arguments are passed to the parent constructor all the time for instance) ?

**Comment by fabpot** [comment]
@stof sure, but we need Pimple first and I will create a PR for that (not finished yet)

**Comment by xdecock** [comment]
Dropping Magic codes? ( automatic text / plain => mixed/alternative when
adding a text/html part ) code

there is probably a few other sections that might benefit from
simplification / transparency and removal of dormant bugs / code messing up
with datas.
