### ISSUE TITLE
IBAction not responding after button align center to image + align bottom to image with compact Height

### ISSUE THREAD

**Issue by rikenmon** [swiftmailer/swiftmailer#595]
I (think) I found a small bug for swift storyboard layout: 
Inside an Image I align a button (center to image and bottom of image). 
I use 2 doc outlines: wAnyhAny and wAnyhCompact. 
Though both orientations work perfect for IBOutlet (in both orientations the button text is OK) IBAction is only working for wAnyhAny, it does not respond to wAnyhC. 

If I align from top + left of superview it all works fine!

I hope this helps someone,
Regards, Erik

**Comment by sstok** [comment]
@rikenmon You are confusing Swift (the language) with Swiftmailer (a PHP library for sending e-mails) :smile:
