### ISSUE TITLE
swiftmailer TLSv1.1 and TLSv1.2 support

### ISSUE THREAD

**Issue by ITwrx** [swiftmailer/swiftmailer#598]
Does swiftmailer currently support tlsv1.1 and tlsv1.2? If not, what is the ETA for this feature? 

Thanks

**Comment by mkaatman** [comment]
PCI compliance is forcing us to turn off TLSv1.0, initially it seems like swiftmailer does not support TLSv1.2 Any confirmation on this?

**Comment by stof** [comment]
Swiftmailer does not implement TLS on its own. So this depends on what your PHP version supports (which actually depends on the openssl version against which PHP is linked AFAIK)

**Comment by mkaatman** [comment]
PHP 5.6.20 (cli) (built: Apr  2 2016 08:28:23)
OpenSSL 1.0.1e-fips 11 Feb 2013

Both PHP and OpenSSL support TLSv1.2

Swiftmailer starts throwing:
`[19-May-2016 08:58:01 America/Chicago] PHP Fatal error:  Uncaught exception 'Swift_TransportException' with message 'Connection could not be established with host localhost [Connection refused #111]' in ...`

I'll see if I can create a complete minimal verifiable example.

**Comment by stof** [comment]
Can you paste the full message, i.e. including the stack trace ?

**Comment by mkaatman** [comment]
```
[19-May-2016 08:56:02 America/Chicago] PHP Fatal error:  Uncaught exception 'Swift_TransportException' with message 'Connection could not be established with host localhost [Connection refused #111]' in /site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:265
Stack trace:
#0 /site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(62): Swift_Transport_StreamBuffer->_establishSocketConnection()
#1 /site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(113): Swift_Transport_StreamBuffer->initialize(Array)
#2 /site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#3 /site/public_html/includes/mail.php(67): Swift_Mailer->send(Object(Swift_Message))
#4 /site/includes/common.php(215): in /site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 265

```

**Comment by ITwrx** [comment]
i had forgotten about this and after forcing tlsv1.2 in postfix config of mailserver, swiftmailer can't send mail. "connection reset by peer" b/c the protocol swiftmailer is trying to use isn't supported on mail server. i had to reduce supported tls version to 1.0 before swiftmailer could mail again. i'm using archlinux with php php 7.0.7-1 and openssl 1.0.2.h-1 on both the web server and mail server so i doubt my php and openssl versions are the issue. i also use tlsv1.2 with my sites' certs on said webserver and have for a while.  My servers supported tlsv1.2 when i posted this issue over a year ago. 

thanks

**Comment by sstok** [comment]
Temporarily try changing https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/Transport/StreamBuffer.php#L95 `STREAM_CRYPTO_METHOD_TLS_CLIENT` to `STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT`.

http://php.net/manual/en/function.stream-socket-enable-crypto.php#119122
`Now, be careful because since PHP 5.6.7, STREAM_CRYPTO_METHOD_TLS_CLIENT (same for _SERVER) no longer means any tls version but tls 1.0 only (for "backward compatibility"...).`

**Comment by ITwrx** [comment]
@sstok thanks a lot! that worked. I guess i'll leave this issue open until this workaraound is not necessary.

**Comment by sstok** [comment]
Great 👍 A simple way to fix this is using `STREAM_CRYPTO_METHOD_SSLv23_CLIENT`. But that will make the system vulnerable for downgrade attacks (forced lower version by a man in the middle).

We can change the `tls` option to accept eg. false (default), true (`STREAM_CRYPTO_METHOD_TLSv1_0_CLIENT|STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT|STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT` when available) or a specific value (the constant value).

**Comment by mkaatman** [comment]
Working here as well. Thank you for the update.

**Comment by ITwrx** [comment]
@sstok the ```STREAM_CRYPTO_METHOD_SSLv23_CLIENT ``` option leaves a bad taste in the mouth, even though sslv2 and 3 are disabled on my mailserver. Being able to choose tls protocol instead of generic "tls" option sounds like the best option (out of the two) to me. A "use highest protocol supported by openssl and lock" option would be future proof, though maybe more difficult to implement.

**Comment by DA40** [comment]
As Swift_Transport_StreamBuffer::startTLS() is hard coded to use STREAM_CRYPTO_METHOD_TLS_CLIENT, can anyone suggest a neat way to override it to use STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT, without editing its source file?  PCI compliance requires that only TLS v1.2 be used from July onwards.

**Comment by mkaatman** [comment]
I couldn't figure out a way to do it. I edited the source. Kind of bad because I have to remember to either not update that package or reapply the fix. IMO, tlsv1_2 should be the new default, there shouldn't be much reason not to use tls v1_2 at this point in time.

I'd love to hear how your PCI 3.1 compliance is going. If you'd be willing to send me an email it's my username at gmail. Ours has been difficult at best.

**Comment by xdecock** [comment]
Overriding the transport, and updating the dependency map

**Comment by DA40** [comment]
Isn't overriding the transport, and updating the dependency map just as bad as editing the source, in the sense that you've still got to manually merge any changes in the master code to yours?  (It's also using a sledgehammer to crack a nut!)

Fortunately, my code is running on the same linux host as the mail server, so I've worked around this problem by switching to the sendmail transport.  The disadvantage, of course, is not getting the same exception feedback.

**Comment by carlaron** [comment]
Any hope of some change on this? Our app needs to be able to make SMTP connections to a wide variety of servers (our clients enter their SMTP connection info, and our app sends mail using their accounts), so we need it to try TLSv1.2, but fall back to TLSv1.0 if that's all the client's SMTP server has. But I can see others wanting to lock in TLSv1.2... so I guess @sstok second idea sounds the best?

**Comment by malikkotob** [comment]
@Rotzbua, @sstok, How will the code in #935 play out? If the server supports `1.2`, it will use that? Else, it will use `1.1`, and if it doesn't support `1.1` it will support `1.0`? Or will it default to `1.0`?

**Comment by Rotzbua** [comment]
>  If the server supports 1.2, it will use that? Else, it will use 1.1, and if it doesn't support 1.1 it will support 1.0?
@malikkotob yes, it would use the highest possible tls version.

**Comment by malikkotob** [comment]
Great, thank you for the clarification @Rotzbua!

**Comment by DA40** [comment]
When will this fix be merged into the master?  Thanks.

**Comment by justinvoelker** [comment]
While we wait for this fix to be merged, is there anyway to explicitly specify TLS version in the config (i.e. I provide host, username, password, TLS version, etc.)? Reading the doc and browsing the code tells me no, but, maybe there is a way that I'm not seeing.

Side note, the manual fix of editing source code isn't really a fix for containerized apps. I have to add custom code that, after composer pulls in the proper packages, edits that source code to make this update. That's just bad.

**Comment by mkaatman** [comment]
@fabpot Thanks for the update! While you're at it, do you want to add TLSv1.3? https://github.com/swiftmailer/swiftmailer/commit/4c4b333c9164b74aaceb7ff9bef2d55f7a5514b8
