### ISSUE TITLE
$SERVER instead of $_SERVER variable used in getRandomId

### ISSUE THREAD

**Issue by dice4x4** [swiftmailer/swiftmailer#600]
After this commit 9950459bdeec4edcf1f13dc32e7afa0fe577284f there is an error: removed extra underscore on $_SERVER variable.
Maybe it happened somewhere else with other variables.
https://github.com/swiftmailer/swiftmailer/blob/9950459bdeec4edcf1f13dc32e7afa0fe577284f/lib/classes/Swift/Mime/SimpleMimeEntity.php#L686

**Comment by fabpot** [comment]
fixed in 28b95d7
