### ISSUE TITLE
Missing space in subject email

### ISSUE THREAD

**Issue by AntoineDeprez** [swiftmailer/swiftmailer#601]
Hi there,

I'm using SwiftMailer (v 4.2.2) to send my emails, and I recently observed that when SwiftMailer construct an email, if it has a long subject, it inserts line breaks into it in the header of the mail.

Subject: Lorem ipsum dolor sit amet =?iso-8859-1?Q?consect=E9tur?=
 adipisicing elit

The original subject was : "Lorem ipsum dolor sit amet consectétur adipisicing elit"

When I send the mail (using Mandrill, or even the php mailer with my local SMTP server), I receive the mail with the subject "Lorem ipsum dolor sit amet consectéturadipisicing elit"

The space is missing, just where the line break was inserted in the header.

I tried the solution on this thread (https://github.com/swiftmailer/swiftmailer/issues/393) : removing the "\r" in the function getTokenAsEncodedWord() in classes/Swift/Mime/Headers/AbstractHeader.php , but it doesn't seem to work.

Does anyone have a solution for this?

Thanks in advance.

**Comment by sstok** [comment]
v4.2.2 is really old, you should upgrade to last version of 5.x (v5.4.0).

**Comment by zaalbarxx** [comment]
I encounter the same problem on 5.4.1 version. I noticed that the issue happens if the last character of word is some special characters so for example "został zmieniony" is converted to "zostałzmieniony" while "zostal zmieniony" is properly encoded to "zostal zmieniony". Is there a fix for this ?

**Comment by xdecock** [comment]
and can you test with zosłat zmieniony ?

checking if it also happens if the quoted-printable sequence is in the
middle of the word.

either way, can you provide the encoded Subject header in both cases?

(or a test case)

thanks,

Xavier

On Wed, Jun 24, 2015 at 10:57 AM, zaalbarxx <notifications@github.com>
wrote:

> I encounter the same problem on 5.4.1 version. I noticed that the issue
> happens if the last character of word is some special characters so for
> example "został zmieniony" is converted to "zostałzmieniony" while "zostal
> zmieniony" is properly encoded to "zostal zmieniony". Is there a fix for
> this ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/601#issuecomment-114792945>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by zaalbarxx** [comment]
For "adres e-mail został zmieniony" (no space)
    Subject: =?utf-8?Q?Tw=C3=B3j?= adres e-mail =?utf-8?Q?zosta=C5=82?= \r\n zmieniony.

For "adres e-mail zołsta zmieniony" (no space)
    Subject: =?utf-8?Q?Tw=C3=B3j?= adres e-mail =?utf-8?Q?zos=C5=82ta?=\r\n zmieniony.\r\n

For "adres e-mail zostal zmieniony" (with space, correct)
    Subject: =?utf-8?Q?Tw=C3=B3j?= adres e-mail zostal zmieniony.\r\n

**Comment by xdecock** [comment]
The issue seems with decoding basically, the line break is causing the
culprit here

Might be usefull to reread the mimespecs to check if we can encode the
space after line breaks

On Wed, Jun 24, 2015 at 11:24 AM, zaalbarxx <notifications@github.com>
wrote:

> For "adres e-mail został zmieniony" (no space)
> Subject: =?utf-8?Q?Tw=C3=B3j?= adres e-mail =?utf-8?Q?zosta=C5=82?= \r\n
> zmieniony.
>
> For "adres e-mail zołsta zmieniony" (no space)
> Subject: =?utf-8?Q?Tw=C3=B3j?= adres e-mail =?utf-8?Q?zos=C5=82ta?=\r\n
> zmieniony.\r\n
>
> For "adres e-mail zostal zmieniony" (with space, correct)
> Subject: =?utf-8?Q?Tw=C3=B3j?= adres e-mail zostal zmieniony.\r\n
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/601#issuecomment-114802802>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by nvvetal** [comment]
This problem occurs when subject have 2 and more different languages, where last word in English lang
Fix (2 languages):
$message->getHeaders()->get('subject')->setLanguage($yourMainLanguage);

**Comment by davidbehler** [comment]
Any idea when this will be fixed? We are using 5.4.6 and still experiencing this issue.

Changing line 303 in Swift/Mime/Headers/AbtractHeader.php from
`$header->setMaxLineLength(76); // Forcefully override`
to
`$header->setMaxLineLength(998); // Forcefully override`
seems to fix the issue for us. But I don't really know what repercussions this might have.

**Comment by meshenka** [comment]
i'm on Swiftmailer 5.4.6  tried both

```php
$message->getHeaders()->get('subject')->setLanguage($yourMainLanguage);
```
and 

```php
$header->setMaxLineLength(998); // Forcefully override
```

Both failed on me :(

(used in Symfony 2.7.15 )

**Comment by nvvetal** [comment]
meshenka

do you have an example?

**Comment by meshenka** [comment]
@nvvetal i tried different sample code base, but in the end it looks to be a mail client specific issue (in my case Zimbra)

**Comment by rimas-kudelis** [comment]
The whitespace goes missing when it coincides with the position at which the hading is being wrapped (folded).

From my understanding of RFC822, part 3.4.2, when folding MIME headers, it is acceptable to have more than one witespace or htab character as a marker that the previously started header field continues. Although the way this is worded could certainly be clearer.

Either way, whether or not this is required, I believe it would simply be safer to encode whitespace characters which coincide with the folding position.

**Comment by MisterGrouik** [comment]
Also have this problem.

setSubject('à é è i ù fin') will give this mail subject : à é èi ùfin
while
setSubject('à é è ù') will give this mail subject : à é è ù

Why does it strips white spaces when there's non accentuated letter after an accentuated letter ?

**Comment by robsch** [comment]
FYI: 

Detected the same with the character ®

However, I assume that it has something to do with the email client as well! I detected this with GroupWise on a Mac (Worst email client ever! I hate it, feels like being in 1995 ...). That program absorbs the blank by default. But when I drag & drop the email on my desktop (eml file) and open it with GroupWise (open with...), the blank is suddenly there! Also with an online email provider that blank gets shown. So the issue may depend on the email client.

**Comment by p1ratrulezzz** [comment]
Solved this problem

Just change here
\Swift_Mime_Headers_AbstractHeader::getEncodableWordTokens
```php
/**
     * Splits a string into tokens in blocks of words which can be encoded quickly.
     *
     * @param string $string
     *
     * @return string[]
     */
    protected function getEncodableWordTokens($string)
    {
        $tokens = array();

        $encodedToken = '';
        // Split at all whitespace boundaries
        //foreach (preg_split('~(?=[\t ])~', $string) as $token) // Old one
        foreach (preg_split('~(?<=[\t ])~', $string) as $token) { // regexp changed
            if ($this->tokenNeedsEncoding($token)) {
                $encodedToken .= $token;
            } else {
                if (strlen($encodedToken) > 0) {
                    $tokens[] = $encodedToken;
                    $encodedToken = '';
                }
                $tokens[] = $token;
            }
        }
        if (strlen($encodedToken)) {
            $tokens[] = $encodedToken;
        }

        return $tokens;
    }

```

in other words - we move the space from first position to last. It will be encoded as "_" in the email.
