### ISSUE TITLE
autoload in tests

### ISSUE THREAD

**Issue by yurii-github** [swiftmailer/swiftmailer#604]
i find it not only here but in other projects - wrong location of autoloader
maybe i don't get something, excuse me then, i haven't used composer and github intensively
but right now to run tests from command, i need to change
$autoloader = require_once dirname(__DIR__).'/vendor/autoload.php';
$autoloader->add('Swift_', __DIR__.'/unit');
to
$autoloader = require_once '../../../vendor/autoload.php';
if($autoloader instanceof \stdClass) {
	$autoloader->add('Swift_', __DIR__.'/unit');
}

regards

**Comment by eclipxe13** [comment]
try this:
```
git clone https://github.com/swiftmailer/swiftmailer.git
cd swiftmailer/
composer update
phpunit tests/
```
It run the tests (a lot failing, btw) but that is another topic

**Comment by yurii-github** [comment]
uh, thanks for reply! i guess i'm getting how it works now. it worked even without  "phpunit tests/" just "phpunit" as it  caught that dir from config.

it looks like it was my mistake to try to test it from my working web application. that way the path to mailer looks like APP/vendor/swiftmailer/swiftmailer/REPOSITORY.

can you advice,
then to test all dependencies under vendor on my web application i have to clone each repository (project)  separately (like you showed) and test it this way in my envorinment? 

thanks in advance

**Comment by fabpot** [comment]
You can also go to each directory and run phpunit.
