### ISSUE TITLE
Swiftmailer cuts subject of message with utf-8

### ISSUE THREAD

**Issue by lzv** [swiftmailer/swiftmailer#605]
Hello.
I use swiftmailer 5.4.0 in Yii 2. My code for creating a message: 

Yii::$app->mailer->compose()
    ->setCharset('utf-8')
    ->setFrom(Yii::$app->params['email_from'])
    ->setTo($email)
    ->setSubject('Восстановление пароля')
    ->setTextBody($message)
    ->send();

But when I opened message in Thunderbird, his subject is "Восстано" only. Raw message:

...
Subject: =?utf-8?Q?=D0=92=D0=BE=D1=81=D1=81=D1=82=D0=B0=D0=BD=D0=BE?=
=?utf-8?Q?=D0=B2=D0=BB=D0=B5=D0=BD=D0=B8=D0=B5_=D0=BF?=
=?utf-8?Q?=D0=B0=D1=80=D0=BE=D0=BB=D1=8F?=
...

Thunderbird reads only first row. Is there a way to solve this problem? How setting swiftmailer to not split subject header?

**Comment by fvosberg** [comment]
I think this is related to my pull request

https://github.com/swiftmailer/swiftmailer/pull/655
