### ISSUE TITLE
compatibility with php >= 5.5

### ISSUE THREAD

**Issue by gbusoni** [swiftmailer/swiftmailer#607]
Is it swiftmailer compatible with php 5.5 and later? I have seen that in the code the preg_replace function that is deprecated in php 5.5 is still used in 4 files. Is it possible to replace this functions with preg_replace_callback to avoid deprecated errors in the error log?

**Comment by fabpot** [comment]
@gbusoni Making it compatible would be fantastic and should not be too complicated. Can you work on this and submit a PR?

**Comment by Koc** [comment]
I don't see any `/e` flag usage in code https://github.com/swiftmailer/swiftmailer/search?utf8=%E2%9C%93&q=preg_replace

**Comment by stof** [comment]
preg_replace is not deprecated at all in PHP 5.5. The only deprecated stuff is the ``e`` modifier for the regex. So this issue is invalid.
