### ISSUE TITLE
Allow uft8 characters in username part of email addresses

### ISSUE THREAD

**Issue by nickvergessen** [swiftmailer/swiftmailer#608]
https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/Validate.php#L30-L41 and https://github.com/swiftmailer/swiftmailer/blob/048be6f7c19944d604e321347990543bc2bbe10b/lib/classes/Swift/Mime/Headers/PathHeader.php#L134-L142 seem to validate RFC 2822.
Would be nice to get it update to [ RFC 6531 ](https://tools.ietf.org/html/rfc6531) which allows utf8 characters in user parts of email adresses, e.g. `täst@localhost`

**Comment by sstok** [comment]
This has been finally fixed in the upcoming 6.0, but note that 6.0 is not backward compatible. #409
