### ISSUE TITLE
Support for group addresses

### ISSUE THREAD

**Issue by matkodjipalo** [swiftmailer/swiftmailer#614]
It would be nice that a user can define a group address in Swifmailer.

Example from RFC 2822 (https://www.ietf.org/rfc/rfc2822.txt)
...
## A.1.3. Group addresses

From: Pete pete@silly.example
To: A Group:Chris Jones c@a.test,joe@where.test,John jdoe@one.test;
Cc: Undisclosed recipients:;
Date: Thu, 13 Feb 1969 23:32:54 -0330
Message-ID: testabcd.1234@silly.example
....

I was trying to make a mail message only with BCCs and 'Undisclosed recipients' in 'TO' field, $address = ['', 'Undisclosed recipients:'];, but Swiftmailer has thrown an exception because empty address isn't allowed.

PHP version is 5.4.40 and swiftmailer version is 5.2

**Comment by dannykopping** [comment]
:+1:
