### ISSUE TITLE
Content-Type: multipart/related not set when needed

### ISSUE THREAD

**Issue by betaglop** [swiftmailer/swiftmailer#615]
When I'm embedding images into the HTML body of an email, the global Content-Type is set to multipart/mixed. This is fine with many email readers (such as Gmail, Zimbra, ...) but it does not display anything with Mozilla Thunderbird for instance.

A workaround consist, at the end of the email composition process, to run:
$message->setContentType('multipart/related');
in the case where embedded images are present.

I'm not sure but I think that the RFC says that the Content-Type needs to be set on multipart/related if any image is embedded into the body of an email... and this is not the default behavior of SwiftMailer (and it took me hours to find this out)

**Comment by betaglop** [comment]
It's possible that it happens if some content is added AFTER embedding the images... but I have no more energy to test it.

**Comment by mbaynton** [comment]
This is well known and well reported.

#56 
#184 

I suggest not embedding images, while I'm not a bulk mail expert, I did a survey of bulk mail I receive after encountering this issue and found that literally none of the experts do embed.

**Comment by fabpot** [comment]
I'm closing this issue as it's going to be fixed by Symfony Mailer/Mime, which will replace Swiftmailer eventually.
