### ISSUE TITLE
PCRE problem with PHP 5.6.10 and Swift

### ISSUE THREAD

**Issue by xkobal** [swiftmailer/swiftmailer#616]
I have freshy installed PHP 5.6.10 from dotdeb (NON-ZTS on Wheezy) and I have now this error that comes from Swiftmailer: 

Jun 12 13:09:03 jfg-stage-front-1 apache2: PHP Warning:  preg_match(): Compilation failed: internal error: previously-checked referenced subpattern not found at offset 4246 in /home/web/OverblogUser-654/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php on line 347

Jun 12 13:09:03 jfg-stage-front-1 apache2: PHP Fatal error:  Uncaught exception 'Swift_RfcComplianceException' with message 'Address in mailbox given [developers@domain-net.net] does not comply with RFC 2822, 3.6.2.' in /home/web/OverblogUser-654/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:348#012Stack trace:#012#0 /home/web/OverblogUser-654/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(263): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('developers@jfg-...')#012#1 /home/web/OverblogUser-654/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(106): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)#012#2 /home/web/OverblogUser-654/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(63): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)#012#3 /home/web/OverblogUser-654/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(602): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)#012#4 /home/web/OverblogUser-65 in /home/web/OverblogUser-654/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php on line 348

It seems to come from the upgrade to pcrelib to 8.37 => http://php.net/ChangeLog-5.php#5.6.10

**Comment by xkobal** [comment]
Seems to be the same with  5.5.26 from dotdeb

**Comment by xdecock** [comment]
Php bug due to incorrect bundled pcre lob allready reported twice we can't
do anything on our level
Le 12 juin 2015 1:45 PM, "Xavier HAUSHERR" <notifications@github.com> a
écrit :

**Comment by xkobal** [comment]
I have seen the other issue, so I close this one. Thanks
