### ISSUE TITLE
Calling Swift_Message::attach() causes fatal error when using setChildren() in 5.4.1

### ISSUE THREAD

**Issue by marcusjfloyd** [swiftmailer/swiftmailer#617]
I'm using swiftmailer inside of one of my classes to send emails with attachments. I call SwiftMessage::attach like so:

```php
$Message = \Swift_Message::newInstance($subject);

$attachment = \Swift_Attachment::newInstance($attachmentData, "attachment.pdf", "application/pdf");

$Message::attach($attachment);
```

and I get the following error:

PHP Fatal error:  Call to undefined method My\Custom\Class::setChildren() in /home/mfloyd/workspace/webtrunk/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php on line 529

It's almost as if SimpleMessage lost its context and is trying to call setChildren() as a method of the class that I'm using swiftmailer in. Is anyone else having this issue?

**Comment by xdecock** [comment]
Strange apc?

On Thu, Jun 18, 2015 at 8:03 PM, Marcus J. Floyd <notifications@github.com>
wrote:

> I'm using swiftmailer inside of one of my classes to send emails with
> attachments. I call SwiftMessage::attach like so:
>
> $Message = \Swift_Message::newInstance($subject);$attachment = \Swift_Attachment::newInstance($ticketAttachment, "tickets_order_".$Order->order_id.".pdf", "application/pdf");$Message::attach($attachment);
>
> and I get the following error:
>
> PHP Fatal error: Call to undefined method My\Custom\Class::setChildren()
> in
> /home/mfloyd/workspace/webtrunk/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php
> on line 529
>
> It's almost as if SimpleMessage lost its context and is trying to call
> setChildren() as a method of the class that I'm using swiftmailer in. Is
> anyone else having this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/617>.
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by marcusjfloyd** [comment]
Sorry guys... I was calling attach statically instead of  as a method of \Swift_Message. Changing it to $Message->attach($attachment) fixed it for me.
