### ISSUE TITLE
Swift Mailer - 500 Internal Server Error

### ISSUE THREAD

**Issue by toddy86** [swiftmailer/swiftmailer#618]
I think I have tried every trick in the book, however no matter what I continue to get a 500 Internal Server Error when I attempt to submit the form. 

I have tried both my iPage and GoDaddy hosting services to hopefully rule out any server related configurations which I may have missed. 

Any help anyone is able to provide would be appreciated - been staring at this for hours (so likely I can't see the forest through the trees by now)

```
require_once 'swift/lib/swift_required.php';


    // grab post data
    $name = filter_var($_POST['name'], FILTER_SANITIZE_STRING)
    $email = filter_var($_POST['email'], FILTER_SANITIZE_EMAIL)
    // $message = filter_var($_POST['message']), $FILTER_SANITIZE_STRING)

    // create our mail body message
    $data = "Name: " . $name . "<br />" . "Email: " . $email;

    // create the transport
    $transport = Swift_SmtpTransport::newInstance('smtp.gmail.com', 465, "ssl")
        ->setUsername('myemailaddress@gmail.com')
        ->setPassword('password');

    // create the mailer
    $mailer = Swift_Mailer::newInstance($transport);
    $message = Swift_Message::newInstance('Web Lead')
        ->setFrom (array('myemailaddress@gmail.com' => 'Web Leads from This is Where'))
        ->setTo (array('myemailaddress@gmail.com' => 'Lead recipients'))
        ->setSubject ('Web Lead from XYZ')
        ->setBody ($data, 'text/html');

    // send the message
    $result = $mailer=>send($message);
```

**Comment by xdecock** [comment]
try a try { ##yourcode## } catch (Exception $e) {
var_dump($e->getMessage(), $e->getTraceAsString()); }

you'll have the info ;)

On Mon, Jun 22, 2015 at 8:19 PM, toddy86 <notifications@github.com> wrote:

> I think I have tried every trick in the book, however no matter what I
> continue to get a 500 Internal Server Error when I attempt to submit the
> form.
>
> I have tried both my iPage and GoDaddy hosting services to hopefully rule
> out any server related configurations which I may have missed.
>
> Any help anyone is able to provide would be appreciated - been staring at
> this for hours (so likely I can't see the forest through the trees by now)
>
> require_once 'swift/lib/swift_required.php';
>
>
>     // grab post data
>     $name = filter_var($_POST['name'], FILTER_SANITIZE_STRING)
>     $email = filter_var($_POST['email'], FILTER_SANITIZE_EMAIL)
>     // $message = filter_var($_POST['message']), $FILTER_SANITIZE_STRING)
>
>     // create our mail body message
>     $data = "Name: " . $name . "<br />" . "Email: " . $email;
>
>     // create the transport
>     $transport = Swift_SmtpTransport::newInstance('smtp.gmail.com', 465, "ssl")
>         ->setUsername('myemailaddress@gmail.com')
>         ->setPassword('password');
>
>     // create the mailer
>     $mailer = Swift_Mailer::newInstance($transport);
>     $message = Swift_Message::newInstance('Web Lead')
>         ->setFrom (array('myemailaddress@gmail.com' => 'Web Leads from This is Where'))
>         ->setTo (array('myemailaddress@gmail.com' => 'Lead recipients'))
>         ->setSubject ('Web Lead from XYZ')
>         ->setBody ($data, 'text/html');
>
>     // send the message
>     $result = $mailer=>send($message);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/618>.
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by thee-killer** [comment]
Hello @xdecock 

Getting similar error, here are the messages as you suggested

**getMessage**

`string(66) "Connection could not be established with host smtp.gmail.com [ #0]"`

**getTraceAsString**

    string(471) "#0 E:\xampp1\htdocs\mail\lib\classes\Swift\Transport\StreamBuffer.php(62): Swift_Transport_StreamBuffer->_establishSocketConnection()
    #1 E:\xampp1\htdocs\mail\lib\classes\Swift\Transport\AbstractSmtpTransport.php(113): Swift_Transport_StreamBuffer->initialize(Array)
    #2 E:\xampp1\htdocs\mail\lib\classes\Swift\Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
    #3 E:\xampp1\htdocs\mail\index.php(25): Swift_Mailer->send(Object(Swift_Message), Array)
    #4 {main}"


when tried [dirty hack](http://stackoverflow.com/a/31245169) its working on local system, but still on server its not working giving me 500 internal server error.

Any idea to help me from this trouble. Thanks in adv. :)

**Comment by xdecock** [comment]
high, either you're being filtered out, or gmail is refusing connection

try a simple telnet to confirm

PS any tls / port?

On Thu, Oct 15, 2015 at 3:34 PM, thee-killer <notifications@github.com>
wrote:

> Hello @xdecock <https://github.com/xdecock>
>
> Getting similar error, here are the messages as you suggested
>
> *getMessage*
>
> string(66) "Connection could not be established with host smtp.gmail.com
> [ #0]"
>
> *getTraceAsString*
>
> string(471) "#0 E:\xampp1\htdocs\mail\lib\classes\Swift\Transport\StreamBuffer.php(62): Swift_Transport_StreamBuffer->_establishSocketConnection()
> #1 E:\xampp1\htdocs\mail\lib\classes\Swift\Transport\AbstractSmtpTransport.php(113): Swift_Transport_StreamBuffer->initialize(Array)
> #2 E:\xampp1\htdocs\mail\lib\classes\Swift\Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
> #3 E:\xampp1\htdocs\mail\index.php(25): Swift_Mailer->send(Object(Swift_Message), Array)
> #4 {main}"
>
> when tried dirty hack <http://stackoverflow.com/a/31245169> its working
> on local system, but still on server its not working giving me 500 internal
> server error.
>
> Any idea to help me from this trouble. Thanks in adv. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/618#issuecomment-148387695>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B
