### ISSUE TITLE
Add IDN (non-ASCII domain names) support 

### ISSUE THREAD

**Issue by swiftmailer** [swiftmailer/swiftmailer#63]
When i use special characters in e-mails which is valid these days you get an error:

Address in mailbox given [Tëst@intermeshdev.nl] does not comply with RFC 2822, 3.6.2.

Original creation date: 2009-05-22T11:56:20Z
Original reporter: Maciej Lisiewski
Original ticket: http://swiftmailer.lighthouseapp.com/projects/21527/tickets/93

**Comment by mvar** [comment]
status update, please

**Comment by dakira** [comment]
@fabpot: let's finally fix this and #541. I propose we *don't* add the intl dependency and use [true/php-punycode](https://github.com/true/php-punycode) instead for IDN/punycode conversion.

The way I see it, the quickest solution would be to generally convert all email addresses containing multibyte chars to punycode (before validation).

Comments?

**Comment by ossinkine** [comment]
I've just published plugin for Swiftmailer which converts domain name to punycode before sending https://github.com/ossinkine/swiftmailer-punycode-plugin. Maybe someone will find it useful while we have no official support.

**Comment by MickL** [comment]
This took only 6 years

**Comment by fabpot** [comment]
@MickL Indeed, you could have contributed that feature 6 years ago, but you did not.

Big thanks to @c960657 who took the time to investigate the issue, worked on the implementation, tested it, submitted a pull request, worked on making it better based on feedback. Thank you @c960657 in the name of all developers out there who will be able to benefit from this important feature for free. Of course, they don't care how and by whom it was implemented. Some won't even realized that you worked on this for free, without being paid, without any incentives. You deserve one more thank you from me, the maintainer who was too lazy to dedicate a few free days to work on this to please developers who are never satisfied with what they get for free.
