### ISSUE TITLE
Expected response code 220 but code "", with message ""

### ISSUE THREAD

**Issue by ShrutiShah2990** [swiftmailer/swiftmailer#633]
I am receiving this error since few days. It was working for an year but now it suddenly pop ups this error.

**Comment by xdecock** [comment]
version of php / ssl?

usually it's an ssl related issue

On Tue, Jul 7, 2015 at 7:13 AM, ShrutiShah2990 <notifications@github.com>
wrote:

> I am receiving this error since few days. It was working for an year but
> now it suddenly it pop ups this error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/633>.
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by ShrutiShah2990** [comment]
PHP version 5.5.9 and we are not using SSL

**Comment by xdecock** [comment]
then you're probably expecting a connection reset, but without a stack
trace or a code example, it's quite complex to be sure.

PS : the ssl part is for the connection to the smtp server, not the
connection to the webserver

On Tue, Jul 7, 2015 at 7:44 AM, ShrutiShah2990 <notifications@github.com>
wrote:

> PHP version 5.5.9 and we are not using SSL
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/633#issuecomment-119079785>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by ShrutiShah2990** [comment]
The same piece of code is working on other server,
In config I have set encryption to ssl, port 25.

**Comment by baptistedonaux** [comment]
I have the same fail, and like @xdecock my code works on dev. I use sendmail without SSL/TLS. Anyone hasn't solution for this problem ?

**Comment by ShrutiShah2990** [comment]
Most probably this issue arises when you face a connection time out. Please check if you have a proper internet and there is no connection time out.

**Comment by xdecock** [comment]
can you connect to the :25 port via telnet?


might happen if the :25 port is filtered by your hosting provider.

On Mon, Aug 10, 2015 at 2:30 PM, Baptiste Donaux <notifications@github.com>
wrote:

> I have the same fail, and like @xdecock <https://github.com/xdecock> my
> code works on dev. I use sendmail without SSL/TLS. Anyone hasn't solution
> for this problem ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/633#issuecomment-129427144>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by baptistedonaux** [comment]
The hosting has specific configuration and I don't check the configuration. In my case, I think it's a configuration problem. I solved my problem using "mail" transport and not "sendmail". (s**t solution).

**Comment by pasnox** [comment]
Same problem, does not seems related to sendmail / ssl from what i can see.
Because it can connect fine and send first command 'MAIL FROM: ...' then get no answer, at this stage the connection is already done ? Maybe some write buffer issues ?

**Comment by amjadsarwar** [comment]
**Expected response code 220 but got code "", with message ""**
.env file
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=25
MAIL_USERNAME=amjad.sarwar23@gmail.com
MAIL_PASSWORD=6868055a
MAIL_ENCRYPTION=null

mail.php
<?php
return [
'driver' => env('MAIL_DRIVER',' smtp'),
'host' => env('MAIL_HOST', 'smtp.gmail.com'),
'port' => env('MAIL_PORT', 25),
'from' => ['address' =>"amjad.sarwar23@gmail.com" , 'name' => "amjad"],

'username' => env('MAIL_USERNAME'),
'password' => env('MAIL_PASSWORD'),
'sendmail' => '/usr/sbin/sendmail -bs',
'pretend' => false,
];

mail code
  Mail::send('email.verify' , ['confirmation_code' => $confirmation_code],  function($message) use ($abc){
            $message->to(Input::get('email'), Input::get('username'))
                ->subject('Verify your email address');
        });

**Comment by YumiAlmero03** [comment]
you were using a gmail account in sending you should change your port to 587 or 465 and your encryption to tls or ssl

**Comment by sstok** [comment]
@m-junaid You properly want to change your password!! As I got the non-edited version in my inbox. And you can't use encryption when using sendmail.

Please don't post Framework specific code, try to make the smallest possible piece of code that produces the problem. Any framework specific code can obscure the actual details and actually be the cause of the problem.

**Comment by hikouki** [comment]
@m-junaid Try to run `php artisan config:clear` command.
It may be looking at cache.

**Comment by jayaswaminathan** [comment]
'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => false,
            'transport' => [
                'class' => 'Swift_SmtpTransport',
                'host' => 'mail.xxxxx.com',
                'username' => 'xxxx@xxxxx.com',
                'password' => 'xxxxx',
                'port' => '26',
                'encryption' => 'tls',
I am receiving a error."Expected response code 220 but got code "", with message "" ".But Gmail is working Fine for me.I am changing our webmail facing a problem.Anyone give a solution for me.thanks in advance.

**Comment by amjadsarwar** [comment]
'mail' => [
        'class' => 'yii\swiftmailer\Mailer',
        'viewPath' => '@frontend/mail',
        'useFileTransport' => false,//set this property to false to send
mails to real email addresses
        //comment the following array to send mail using php's mail function
        'transport' => [
            'class' => 'Swift_SmtpTransport',
            'host' => 'smtp.gmail.com',
            'username' => 'logics.tester@gmail.com',
            'password' => '**************',
            'port' => '587',
            'encryption' => 'tls',
                        ],
    ],

**Comment by amjadsarwar** [comment]
plaease move this config commen to backend or frontend

**Comment by lorenzadamour** [comment]
bonjour j'ai un problème avec mon envoie de mail d'après un formulaire. L'envoie de mail se fait bien, mais lorsque je reçois dans ma boite mail je ne reçois pas l'adresse de l'expéditeur entré dans le formulaire mais je reçois mon adresse même:

Exemple

from: 123@gmail.com
to: 123@gmail.com


Parameters:
parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: ***
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: smtp.gmail.com
    mailer_user: 123@gmail.com
    mailer_password: ***
    mailer_encryption:  ssl
    mailer_auth_mode: login
    mailer_port: 465
    secret: 1f55a0254de4a7699bfd3e5b3296665371ba2033

et ma config:

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    encryption: %mailer_encryption%
    auth_mode: "%mailer_auth_mode%"
    spool:     { type: memory }

**Comment by daanhaitsma** [comment]
@lorenzadamour their message, translated from French to English by Google Translate:

> hello i have a problem with my sending mail from a form. The sending of mail is done well, but when I get in my mailbox I do not get the address of the sender entered in the form but I get my address same:
> 
> Example
> 
> from: 123@gmail.com
> to: 123@gmail.com
> 
> Parameters:
> parameters:
> database_host: 127.0.0.1
> database_port: null
> database_name: ***
> database_user: root
> database_password: null
> mailer_transport: smtp
> mailer_host: smtp.gmail.com
> mailer_user: 123@gmail.com
> mailer_password: ***
> mailer_encryption: ssl
> mailer_auth_mode: login
> mailer_port: 465
> secret: 1f55a0254de4a7699bfd3e5b3296665371ba2033
> 
> and my config:
> 
> swiftmailer:
> transport: "%mailer_transport%"
> host: "%mailer_host%"
> username: "%mailer_user%"
> password: "%mailer_password%"
> port: "%mailer_port%"
> encryption: %mailer_encryption%
> auth_mode: "%mailer_auth_mode%"
> spool: { type: memory }

**Comment by HarisButt91** [comment]
![untitled](https://user-images.githubusercontent.com/33089391/32044820-7bee4258-b9f3-11e7-9176-7d62e5e1635b.png)

what should be fill in these requirments. iam facing this error "Expected response code 220 but got code "", with message ""

**Comment by m-junaid** [comment]
@HarisButt1 

1: Either you must allow less secure apps or use app password by enabling 2 step verification on your gmail acc. 
2: Disable any antivirus on your machine. 
3: Don't forget to clear your cache (sometimes it don't take updated content from .env file) 
4: You don't need to change anything in Mailer inside config directory(not recommended), you should use env variables

**Comment by mjalili27** [comment]
@ShrutiShah2990  Thank you i had this problem for one week it solved by replacing the tls encryption with 
ssl
