### ISSUE TITLE
Switch from mcrypt to more secure implementation

### ISSUE THREAD

**Issue by Hikariii** [swiftmailer/swiftmailer#634]
libmcrypt is a dead project, unmaintained for ~8 years, last version 2.5.8 was released in February 2007!
Various well maintained alternative libraries exist:
- openssl
- nss (Network Security Service)
- etc.

See also http://blog.remirepo.net/post/2015/07/07/About-libmcrypt-and-php-mcrypt

**Comment by xdecock** [comment]
You can probably propose a pull request easily as it's seems to only affect

lib/classes/Swift/Transport/Esmtp/Auth/NTLMAuthenticator.php  and the
related test.

I don't use it so not sure i won't mess up everything.

On Tue, Jul 7, 2015 at 10:11 AM, Sebastiaan de Rooij <
notifications@github.com> wrote:

> libmcrypt is a dead project, unmaintained for ~8 years, last version 2.5.8
> was released in February 2007!
> Various well maintained alternative libraries exist:
>
>    - openssl
>    - nss (Network Security Service)
>    - etc.
>
> See also
> http://blog.remirepo.net/post/2015/07/07/About-libmcrypt-and-php-mcrypt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/634>.
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B
