### ISSUE TITLE
proc_open with sendmail no command line output

### ISSUE THREAD

**Issue by jacob-v-dam** [swiftmailer/swiftmailer#641]
I run Laravel 5.1 with SwiftMailer. There occurs an error when I try to send an e-mail via sendmail with SwiftMailer:

```
exception 'Swift_TransportException' with message 'Expected response code 220 but got code "", with message ""' in
```

SwiftMailer is reading the buffer but the command **/usr/sbin/sendmail -bs** returns no answer. But when I execute the same command via CLI there is a result:

```
220 myhostname ESMTP Postfix
```

Is this an known issue? How can I fix this? I'm running php 5.6.11.

**Comment by justjavac** [comment]
me too

**Comment by pasnox** [comment]
Same here since some linux update my sendmail no longer works - return null reply though manual call of the command show reply.

**Comment by Braunson** [comment]
+1 Getting this with bluehost and various hosts.

**Comment by xdecock** [comment]
Isn't proc_open disabled or messed with on those hosts?
