### ISSUE TITLE
PHP 7 compatability issue

### ISSUE THREAD

**Issue by dvc** [swiftmailer/swiftmailer#643]
$ php bin/php7cc.php ../some_symfony_project
...
File: ../some_symfony_project/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/NTLMAuthenticator.php
Line 62. Function argument(s) returned by "func_get_arg" might have been modified: func_get_arg(3);
Line 63. Function argument(s) returned by "func_get_arg" might have been modified: func_get_arg(4);

File: ../some_symfony_project/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php
Line 276. Possible object property creation during by-reference assignment: $this->_in =& $this->_stream;
Line 277. Possible object property creation during by-reference assignment: $this->_out =& $this->_stream;

File: ../some_symfony_project/vendor/swiftmailer/swiftmailer/tests/unit/Swift/Mime/AbstractMimeEntityTest.php
Line 979. Function argument(s) returned by "func_get_args" might have been modified: func_get_args();

**Comment by stof** [comment]
It looks to be that you ran this on an outdated version of the library, because line numbers don't match the codebase

**Comment by dvc** [comment]
Last tag:

        {
            "name": "swiftmailer/swiftmailer",
            "version": "v5.4.1",
            "source": {
                "type": "git",
                "url": "https://github.com/swiftmailer/swiftmailer.git",
                "reference": "0697e6aa65c83edf97bb0f23d8763f94e3f11421"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/swiftmailer/swiftmailer/zipball/0697e6aa65c83edf97bb0f23d8763f94e3f11421",
                "reference": "0697e6aa65c83edf97bb0f23d8763f94e3f11421",
                "shasum": ""
            },


https://github.com/swiftmailer/swiftmailer/blob/0697e6aa65c83edf97bb0f23d8763f94e3f11421/lib/classes/Swift/Transport/Esmtp/Auth/NTLMAuthenticator.php

https://github.com/swiftmailer/swiftmailer/blob/0697e6aa65c83edf97bb0f23d8763f94e3f11421/lib/classes/Swift/Transport/StreamBuffer.php

https://github.com/swiftmailer/swiftmailer/blob/0697e6aa65c83edf97bb0f23d8763f94e3f11421/tests/unit/Swift/Mime/AbstractMimeEntityTest.php

**Comment by stof** [comment]
The func_get_args reports in NTLMAuthenticator.php are false positives because there is no assignments overwriting the arguments in the method and so it cannot have been modified. and in AbstractMimeEntityTest.php, this is the first statement of the function.

Before opening issues on lots of open-source projects, it would be good to ensure that the tool used to detect compatibility issues actually detects them properly.

**Comment by stof** [comment]
And ``Possible object property creation during by-reference assignment`` does not make sense. These properties are defined in the class. So it will not create properties.

**Comment by dvc** [comment]
I`m sorry :- (
Thank you for detailed answer.
