### ISSUE TITLE
Don't regenerate message-id after sending mail

### ISSUE THREAD

**Issue by tomsommer** [swiftmailer/swiftmailer#648]
All the Swift_Transport handlers regenerate the message-id by calling message->generateId() after a send() is performed. 

Basically $message is modified and so ->toString() and getId() no-longer reflect the actual mail that was sent. This is not okay.

There are multiple GitHub issues that are based on this problem.

**Comment by stof** [comment]
the issue is that Swift messages are mutable, and it is perfectly valid to mutate an instance and send it again without cloning the instance. In this case, a different id is needed

**Comment by tomsommer** [comment]
That should be something the developer should do and be aware of then.

It's not every transport that does a ->generateId() anyway, not to mention 3rd party Transports, so it's very random what's going on.

Suddenly, after send(), your Swift_Message is not what it used to be, and that is not okay if it's needed for logging etc.

See #335 and #198

**Comment by stof** [comment]
@tomsommer generating the id is something that Swift always does internally currently. Forcing to regenerate it manually when reusing the instance would be a big BC break

**Comment by xdecock** [comment]
One thing that might not be a compatibility break (but not sure if it's
doable) is only mark it as "used" on send, and regenerate them on every
"send" event

But, it will probably mess with half the caching layer, so, not a simple
operation

On Thu, Aug 13, 2015 at 2:01 PM, Christophe Coevoet <
notifications@github.com> wrote:

> @tomsommer <https://github.com/tomsommer> generating the id is something
> that Swift always does internally currently. Forcing to regenerate it
> manually when reusing the instance would be a big BC break
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/648#issuecomment-130642427>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by tomsommer** [comment]
That's a good idea. Marking the object as having being sent, and then regenerate if it's used in another send() function with the same ID. After ->send() you still need to account for people being able to set their own message-id for the next message.

So if you store ```$message->getLastIdSent()``` and then do this before every send() ```if ( $message->getLastIdSent() == $message->getid() ) $message->generateId();```

You could also leave it up to the developer to decide on the message-id, some actually might know what they are doing, sending the same message with the same ID.

Currently I'm using this workaround:
```
$_id = $message->getId();
$transport->send($message);
$message->setId($_id);
```
Nasty stuff

**Comment by Yamakasi** [comment]
yes! I just found out the same issue, this should not be the way. I think the "nasty" fix of @tomsommer  is the way for now, thanks!

**Comment by ArondeParon** [comment]
Any news on this? I just wasted quite some time before discovering SwiftMailer does this.
