### ISSUE TITLE
Sending emails in local host

### ISSUE THREAD

**Issue by nasrithamer** [swiftmailer/swiftmailer#649]
In my website the contactbundle work fine but in local doesn't work i don't know why 
i turned off the "Access for less secure apps" in my account gmail but still not working 

my parameters.yml : 
    mailer_transport:  gmail
    mailer_host:       ~
    mailer_user:       nasrithamer.symfony@gmail.com 
    mailer_password:   ****

my config.yml : 
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    #spool:
        #type: file
        #path: "%kernel.root_dir%/spool"

i don't know the bloc is in my windows 7 or antivirus avast , i'm workin with xampp ??

**Comment by fyrye** [comment]
For others interested; Yes Avast (and other Anti-Virus apps that monitor ports) will block communication unless you enable exceptions for it.
