### ISSUE TITLE
SMTP Transport breaks HELO on Mac OS X due to IPv6

### ISSUE THREAD

**Issue by swiftmailer** [swiftmailer/swiftmailer#65]
This is an easy one to fix. :)

When creating an Swift_SmtpTransport it, by default, tries to use the local server name ($_SERVER['SERVER_NAME']). If this server name is "localhost" (which it often is on a developer machine) then it fails the _isFqdn() check (which it rightly should) and the transport then defaults to using $_SERVER['SERVER_ADDR']. It does not, however, check whether this address against _isFqdn which it should. 

On Mac OS X 10.5, SERVER_ADDR will often be ::1 which is an IPv6 address not compatible with (some/all?) SMTP servers resulting in a "501 5.5.4 Invalid Address" response to "HELO [::1]".

The fix would be to additionally check whether SERVER_ADDR is a full qualified domain name (or valid IP) and if not then just default to 127.0.0.1 which would be better than nothing.

Original creation date: 2009-07-22T15:34:22Z
Original reporter: Patrick Hogan
Original ticket: http://swiftmailer.lighthouseapp.com/projects/21527/tickets/98

**Comment by c960657** [comment]
Fixed in #672 and/or #799.
