### ISSUE TITLE
Cannot access content type used in constructor for \Swift_Message after calling addPart()

### ISSUE THREAD

**Issue by Kyoushu** [swiftmailer/swiftmailer#654]
After calling addPart() in the class \Swift_Message, it's no longer possible to access the content type passed to the constructor.

```
$message = new Swift_Message('foo', 'html body', 'text/html');

echo $message->getContentType(); // output: "text/html"

$message->addPart('text body', 'text/plain');

echo $message->getContentType(); // output: "multipart/alternative"
```

This causes problems when implementing a transport for an API which composites multi-part emails itself, such as Mandrill.

As you can see in the example below, Mandrill expects the html and text body in API calls to be added to separate fields.

```
{
    "subject": "foo",
    "to": [
        {
            "email": "to@example.com",
            "type": "to"
        }
    ],
    "from_email": "from@example.com",
    "html": "html body",
    "text": "text body"
}
```

To determine if $message->getBody() should go into the "html" or "text" field, I need to check $message->getContentType(). Because getContentType() now returns "multipart/alternative", I'm unable to do this.

As a result, I have to resort to the following nasty hack.

```
$messageRef = new \ReflectionClass($message);
if($messageRef->hasProperty('_userContentType')){
    $propRef = $messageRef->getProperty('_userContentType');
    $propRef->setAccessible(true);
    $contentType = $propRef->getValue($message);
}
```

Would it be possible to add a method to \Swift_Message to expose the content type passed to the constructor?

**Comment by fabpot** [comment]
If you are using an API like Mandrill, I'm not sure you need to use Swiftmailer. In any case, the Swiftmailer behavior looks good to me. You can as many part as you want, so keeping one of them looks wrong to me.
