### ISSUE TITLE
CWE-327: Use of a Broken or Risky Cryptographic Algorithm

### ISSUE THREAD

**Issue by avardbacon** [swiftmailer/swiftmailer#656]
Our application uses the swiftmailer library. The use of weak md5 were reported by our application security scan.  We are required by them to report an issue here, in order to mitigate this flaw.

instances were found here:
swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php - line 83
swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/NTLMAuthenticator.php - line 596
swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/NTLMAuthenticator.php - line 603

**Comment by xdecock** [comment]
It's not used for any cryptographic purposes.

it's used to generate content-ids...

and for the ntlm, i suspect if you don't authenticate through ntlm you
should be safe,

Can you please not simply report things blindly?

A security scan tool, is as expected a tool, it's output should be
understood, following blindly rules leads also to bugs.

Xavier

On Wed, Aug 26, 2015 at 7:17 PM, avardbacon <notifications@github.com>
wrote:

> Our application uses the swiftmailer library. The use of weak md5 were
> reported by our application security scan. We are required by them to
> report an issue here, in order to mitigate this flaw.
>
> instances were found here:
> swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php - line 83
> swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/NTLMAuthenticator.php -
> line 596
> swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/NTLMAuthenticator.php -
> line 603
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/656>.
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by xdecock** [comment]
I confirm, we can remove the MD5 in NTLM as soon as Microsoft fixes his protocol (and all implementations are replaced), or, we stop supporting the ntlm auth so you can fix you security scan problem.

So, Not a bug, not a security risks by itselfs, won'tfix

**Comment by avardbacon** [comment]
I don't need you to do anything. I know this is not risky, I just had to officially report an issue here. I aplogize at the same time.
thanks

**Comment by stof** [comment]
Well, why do you have to report an issue here if you know it is invalid ? this is what was meant by @xdecock in

> Can you please not simply report things blindly?
