### ISSUE TITLE
Exclude unnecessary files from git archive

### ISSUE THREAD

**Issue by fbm-static** [swiftmailer/swiftmailer#657]
Hello,

Could it be considered to add `export-ignore`  to files not required for production when installing or requiring this package to composer?

Example of these are:
- tests
- docs
  - phpunit.xml.dist
  - .travis.yml
  - CHANGES
  - README

Thank you.

**Comment by replete** [comment]
i++;

**Comment by fabpot** [comment]
Already discussed (on some of my other projects) and rejected. See the discussion in symfony/symfony#17749 for instance.
