### ISSUE TITLE
swiftmailer: getting error "expected...code 220 but got code 451"

### ISSUE THREAD

**Issue by scwGit** [swiftmailer/swiftmailer#658]
Hi - 
I have a couple of php scripts where the script uses swiftmailer to send an email with a couple of attachments.

The script has worked fine as recently as a couple days ago. Then last night, I started getting this error:

"Fatal error: Uncaught exception 'Swift_TransportException' with message 'Expected response code 220 but got code "451", with message "451-The server has reached its limit for processing requests from your host. 451 Please try again later. "

I talked with my web host (GoDaddy)...they see no problems on their end and have been able to successfully send test messages from my directory using php mail and smtp mail.

Using the script, I have tried sending the messages to email accounts on 3 different email services (gmail, godaddy, cox) and gotten the same error each time.

I have not touched any of the swiftmailer code.

Any assistance appreciated. Steve

**Comment by Braunson** [comment]
@scwGit You will have to increase your SMTP relays on GoDaddy.
