### ISSUE TITLE
Swift_SmtpTransport - Wrong parameters Sending Email

### ISSUE THREAD

**Issue by sminath33** [swiftmailer/swiftmailer#659]
Anytime I switch from using Swift_MailTransport to Swiftmailer Smtp Transport I receive wrong parameters exception. It appears that the version of Swiftmailer I am using is not compatible with Smtp Transport.  

I am simply taking form values from a page and calling the below php class. Here is the code: 

<!DOCTYPE HTML>

<html lang='en'>
    <head>
        <meta charset='utf-8' />
        <title>Success!</title>
    </head>

```
<body>
```

<?php
$from = $_POST['email22'];
$name = $_POST['name'];
$stringName = (string)$name;
$stringFrom = (string)$from;
$body = "Beth, You have a work request from: "."\n"."Name: ".$_POST['email22']."\n"."Phone Number: ";
$body2 = "Name: ".$_POST['name']."\n"."Email Address: ".$_POST['email22']."\n"."Phone Number: ".$_POST['phone']."\n"."Subject: ".$_POST['subject']."\n"."Message Details: ".$_POST['message'];

//echo "From is  ".$from;
//echo "From String is ".$stringFrom;
        require_once 'lib/swift_required.php';
// Create the mail transport configuration
//$transport = Swift_MailTransport::newInstance();

//trying to send via Smtp Google
$transport = Swift_SmtpTransport::newInstance('smtp.gmail.com', 465, "ssl");
$transport->setUsername('xxxxx@gmail.com');
$transport->setPassword('xxxxxxxx');

// Create the message
$message = Swift_Message::newInstance();
$message->setTo(array(
  "sminath3@aol.com" => "Nate Smith",
  "beth.snider.art@gmail.com" => "Beth Snider"
));
$message->setSubject("Work Request From Your Website");
//$message->setBody("You're our best client ever.");
$message->setBody($body2);
$message->setFrom("$stringFrom", "$stringName");

// Send the email
$mailer = Swift_Mailer::newInstance($transport);
$result = $mailer->send($message);

//$xportlist = stream_get_transports();
//echo "The transport value is ".$xportlist;
//echo "The result is ".$result;
//print_r($xportlist);

?>

```
</body>
```

</html>

Here is the error message received:
Fatal error: Wrong parameters for Exception([string $exception [, long $code ]]) in /home/content/62/7295662/html/php/lib/classes/Swift/SwiftException.php on line 27

**Comment by sminath33** [comment]
There haven't been any updates for this issue in over a week. Could someone take a look and provide some feedback?? Thanks!!! ~Nate

**Comment by malditologin** [comment]
I have the same problem, any ideas?

**Comment by xdecock** [comment]
Version of PHP?



On Mon, Dec 21, 2015 at 6:09 PM, malditologin <notifications@github.com>
wrote:

> I have the same problem, any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/659#issuecomment-166361820>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by malditologin** [comment]
PHP v5.2.5, Windows Server 2003

**Comment by GrahamCampbell** [comment]
Swiftmailer for PHP 5.2 isn;t supported anymore.

**Comment by GrahamCampbell** [comment]
The currently supported version requires php 5.3.3: https://github.com/swiftmailer/swiftmailer/blob/5.x/composer.json#L18.

**Comment by malditologin** [comment]
Thank you, I have to update but I have no time.

**Comment by sminath33** [comment]
Will php 5.3 work or does it need to be 5.3.3? Will php 5.4 work instead?

**Comment by GrahamCampbell** [comment]
5.3.3 or greater

**Comment by GrahamCampbell** [comment]
7.0.1 is the latest

**Comment by sminath33** [comment]
Great, I've updated to use 5.4. Let's see if this will resolve the issue. Thanks!
