### ISSUE TITLE
escapeshellarg() has been disabled for security reasons

### ISSUE THREAD

**Issue by platx** [swiftmailer/swiftmailer#662]
When i try to send message via swift mailer, get this error: escapeshellarg() has been disabled for security reasons.
Hosting provider said, that this function cannot be enabled. Is the other way to send mail messages withaout this function?
![yiibaseerrorexception - google chrome](https://cloud.githubusercontent.com/assets/5385861/9706458/007ab38e-54ee-11e5-8d92-f79556083b92.jpg)

**Comment by xdecock** [comment]
Not a bug, your hosting provider disabled shell related functions, use
another transport.

On Sun, Sep 6, 2015 at 10:21 PM, Vladyslav <notifications@github.com> wrote:

> When i try to send message via swift mailer, get this error:
> escapeshellarg() has been disabled for security reasons.
> Hosting provider said, that this function cannot be enabled. Is the other
> way to send mail messages withaout this function?
> [image: yiibaseerrorexception - google chrome]
> <https://cloud.githubusercontent.com/assets/5385861/9706458/007ab38e-54ee-11e5-8d92-f79556083b92.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/662>.
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by sstok** [comment]
The recommended transporter is SMTP (which works also better with big e-mails and bulk).
