### ISSUE TITLE
Quoted-printable subject (header) encoding bug

### ISSUE THREAD

**Issue by vizzah** [swiftmailer/swiftmailer#665]
When encoding headers and subject in particular, Swiftmailer tries to 'tokenize' (split into words) subject apparently trying to detect whether it should be encoded (Unicode) or left intact (ASCII).

There are bugs, however, which result in spaces between words being stripped and other encoding oddities.

Spaces between words are sometimes lost when subject is a mix of unicode and ASCII and encoding is quoted-printable:
Subject 'Добро пожаловать на Site.ru' encoded in quoted-printable:
Subject: =?utf-8?Q?=D0=94=D0=BE=D0=B1=D1=80=D0=BE_=D0=BF=D0=BE?=
 =?utf-8?Q?=D0=B6=D0=B0=D0=BB=D0=BE=D0=B2=D0=B0=D1=82=D1=8C_=D0=BD=D0=B0?=
 Site.ru

Missing space before 'Site.ru'. Some e-mail clients show space correctly, but some doesn't.

Subject encoded in base64 also looks strange:
Subject: =?utf-8?B?0JTQvtCx0YDQvg==?=
 =?utf-8?B??=  =?utf-8?B?0L/QvtC20LDQu9C+0LLQsNGC0Yw=?=

Should encoding prefix '=?utf-8?' be prefixing each word?

Also, If two spaces are inserted between words, mail clients are not seeing them at all after tokenized encoding.

There was no configurable way to set header encoding to Base64, requiring hacks to 'mime_deps.php'. 

I also had to patch /swiftmailer/lib/classes/Swift/Mime/Headers/AbstractHeader.php
to make function tokenNeedsEncoding($token) always return false, to prevent encoding of subject and then in the client doing it yourself:
    ->setSubject('=?utf-8?B?'.base64_encode($subj).'?=')

This makes subject encoded as one b64 string (with one prefix), which is perfectly recognized by webmail and email clients which didn't show it correctly before. No issues with lost spaces or incorrect token encodings. Not sure why this "tokenization" is required at all for base64 encoded data.

**Comment by dmaicher** [comment]
Maybe related to an issue I created a while ago regarding encoding problems in the To-Header: https://github.com/swiftmailer/swiftmailer/issues/650

**Comment by borkor** [comment]
This is still an open issue 

For example I have issues with this subject:

Original
Vaš kolega je naručio oglas

Encoded
Subject: =?utf-8?Q?Va=C5=A1?= kolega je =?utf-8?Q?naru=C4=8Dio?= oglas

Viewable subject in YahooMail
Vašnaručiooglas

**Comment by dmaicher** [comment]
In Thunderbird the subject shows fine as "Vaš kolega je naručio oglas" :yum: 
Did you try some other email clients?

**Comment by borkor** [comment]
@dmaicher I tried Zimbra web mail client. It strips spaces. 

I quickly looked up the code and I think this could be an issue with using strlen instead of mb_strlen.

**Comment by dmaicher** [comment]
But as said `Subject: =?utf-8?Q?Va=C5=A1?= kolega je =?utf-8?Q?naru=C4=8Dio?= oglas` shows up just fine in thunderbird :wink: 

So not sure but seems to me this encoding is valid?

**Comment by borkor** [comment]
@dmaicher It is definitely valid, but the YahooMail and [Zimbra](https://www.zimbra.com/) has the issue with it.

**Comment by Rotzbua** [comment]
Test with yahoo web mailer: send a mail with subject: ` Vaš kolega je naručio oglas`
Is encoded by yahoo as:
`Subject: =?UTF-8?Q?Va=C5=A1_kolega_je_naru=C4=8Dio_oglas?=`
Seems to be different with the header from @borkor:
`Subject: =?utf-8?Q?Va=C5=A1?= kolega je =?utf-8?Q?naru=C4=8Dio?= oglas`

Difference is, that yahoo encodes the complete subject and swiftmailer every single utf8 char.
Is there a standard how it is done right? Complete or partial encoding?

**Comment by borkor** [comment]
@Rotzbua I meant that mail header generated by swiftmailer is as it is, but the preview of those received headers is not interpreted very well by YahooMail or the Zimbra webmail client. 

Nevertheless, that seems to be a bug in those webmail readers.

**Comment by borkor** [comment]
what I would do to resolve this issue is move away from tokenization and encode the whole subject as one to make it more compatible with existing webmail clients.

**Comment by ampaze** [comment]
In my opinion this is definitely a bug in Yahoo Mail that we encountered too, they decode the parts that where encoded but throw away the unencoded parts between encoded parts. 

Having said that, the option to encode the whole subject line and use the underscore for space would be good to have. Then at least some readability is retained, which is the whole purpose of this encoding scheme.

Does yahoo have a bugtracker?

**Comment by Rotzbua** [comment]
I think the according rfc is rfc2047.
So it seems that yahoo do not correctly handle example 2 ( https://tools.ietf.org/html/rfc2047#section-8 ).
```
 encoded form                                displayed as
   ---------------------------------------------------------------------
   (=?ISO-8859-1?Q?a?=)                        (a)

   (=?ISO-8859-1?Q?a?= b)                      (a b)

           Within a 'comment', white space MUST appear between an
           'encoded-word' and surrounding text.  [Section 5,
           paragraph (2)].  However, white space is not needed between
           the initial "(" that begins the 'comment', and the
           'encoded-word'.


   (=?ISO-8859-1?Q?a?= =?ISO-8859-1?Q?b?=)     (ab)

           White space between adjacent 'encoded-word's is not
           displayed.

   (=?ISO-8859-1?Q?a?=  =?ISO-8859-1?Q?b?=)    (ab)

        Even multiple SPACEs between 'encoded-word's are ignored
        for the purpose of display.
```
But is this particular encoding really required today? I mean, if we use utf8 it would be better to encode de complete subject instead of encode every non ascii char. Also encoding every single non ascii char increase the subject.

@borkor Btw. for zimbra is a issue opened: https://bugzilla.zimbra.com/show_bug.cgi?id=107700

**Comment by ampaze** [comment]
I tested some more and Yahoo only has a problem when the last word in the subject is encoded. Unfortunately adding an extra space to the end of the subject didn't fix it.

**Comment by ampaze** [comment]
I tried to change the way the Subject is encoded inside of Swiftmailer, but that is way to involved. But I found another solution, just pre-encode the subject.

`$subject = str_replace('=20', '_', mb_encode_mimeheader($subject, 'UTF-8', 'Q', ' '));`

Swiftmailer seems apply the header folding correctly so all is good.
Disclaimer: I have not yet tested this very much.

**Comment by Lyrdow** [comment]
@ampaze this can actually be a very bad solution. Because il solves the display problem but can break emails signature (tested on our emails with either older and most recent version (6.0.2) of swiftmailer). With this pre-encoding, we have a clear dkim=fail in the header on gmail and others. Everything come back ok if we remove this pre-encoding.
