### ISSUE TITLE
Email "szymon10@yahoo.com" will not pass validation.

### ISSUE THREAD

**Issue by borzy** [swiftmailer/swiftmailer#668]
\Swift_Mime_Headers_MailboxHeader::_assertValidAddress("szymon10@yahoo.com")
throws exception:

> 'Swift_RfcComplianceException' with message 'Address in mailbox given [szymon10@yahoo.com‎] does not comply with RFC 2822, 3.6.2.' in /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:348

Grammar used: Swift_Mime_Grammar.

I've found this code uses ridiculously complex regex. Why not use PHPs filter_var('bob@example.com', FILTER_VALIDATE_EMAIL) ?

**Comment by stof** [comment]
Because ``filter_var`` does not validate things properly either. It accepts some invalid emails, and it rejects valid ones.

The dev version of Swiftmailer 6 (not ready for production use yet though) relies on https://github.com/egulias/EmailValidator/ for the email validation
