### ISSUE TITLE
html parts not being parsed when embedded images are included

### ISSUE THREAD

**Issue by swiftmailer** [swiftmailer/swiftmailer#67]
We are sending an email in text, HTML, and also embedding some images in the HTML part.

The problem is some email clients like thunderbird are not parsing these properly and only show the text part.

The content type in the headers shows:
Content-Type: multipart/related;

Does it need text/html added in there somewhere?

Original creation date: 2009-07-29T15:03:50Z
Original reporter: Ben
Original ticket: http://swiftmailer.lighthouseapp.com/projects/21527/tickets/102

**Comment by fabpot** [comment]
I'm closing this issue as it's going to be fixed by Symfony Mailer/Mime, which will replace Swiftmailer eventually.
