### ISSUE TITLE
Accept "@" as begin of mail password

### ISSUE THREAD

**Issue by karousn** [swiftmailer/swiftmailer#676]
Swiftmailer considered any password beging with "@" as Object.
I got this message error: 
```Invalid type for path "swiftmailer.mailers.default.password". Expected scalar, but got object.```

**Comment by xdecock** [comment]
probably more a problem on the config syntax, as this is not a message
emited by swift itself. (and swiftmailer.mailers.default.password is not
defined by swiftmailer.

what framework is used?

On Wed, Oct 7, 2015 at 12:24 PM, Nabil Karous <notifications@github.com>
wrote:

> Swiftmailer considered any password beging with "@" as Object.
> I got this message erreur :
> Invalid type for path "swiftmailer.mailers.default.password". Expected
> scalar, but got object.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/676>.
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by fabpot** [comment]
Probably comes from a Symfony configuration written in YAML.

**Comment by karousn** [comment]
@xdecock : symfony v2.3.*

**Comment by xdecock** [comment]
not sure of the yaml syntax, but i suspect @XXX is a special syntax,
there's probably a "@XXX" syntax to allow @startedStrings

http://www.yaml.org/spec/1.2/spec.html#id2802842

I recommend this reading

On Wed, Oct 7, 2015 at 1:10 PM, Nabil Karous <notifications@github.com>
wrote:

> @xdecock <https://github.com/xdecock> : symfony v2.3.*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/676#issuecomment-146157417>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by karousn** [comment]
in the same link "@" was reserved for *Indicator Characters*  may be that is way, but , is they anyway how using some reserved character without having error for example by adding another special character.

**Comment by xdecock** [comment]
I'm not using yaml, so probably the worst person to ask, so i recommend
checking on a symfony forum (or in yaml doc)

but the example seems to work

On Wed, Oct 7, 2015 at 3:28 PM, Nabil Karous <notifications@github.com>
wrote:

> in the same link "@" was reserved for *Indicator Characters* may be that
> is way, but , is they anyway how using some reserved character without
> having error for example by adding another special character.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/676#issuecomment-146196282>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by sstok** [comment]
In Symfony using `@password` references a service when used in a YAML the service definition.
Double the `@`-sign to mark the value as raw/literal.
