### ISSUE TITLE
user-10@corsecureemail.com; on behalf of; Sourabh [sourabhj@neuronsolutions.com]

### ISSUE THREAD

**Issue by sourabhcodiant** [swiftmailer/swiftmailer#678]
We have receive in the from section of the mail "user-10@corsecureemail.com; on behalf of; Sourabh [sourabhj@neuronsolutions.com]" , We dont want "on behalf of" we just want from mail i.e. sourabhj@neuronsolutions.com . Please reply me the solution ASAP

Thanks

**Comment by xdecock** [comment]
Based on the sender header added by your mailung provider

Le ven. 9 oct. 2015 12:39, sourabhcodiant <notifications@github.com> a
écrit :

**Comment by sourabhcodiant** [comment]
can i set the sender header in our php code.
I have creating the following class. Please let me know if found any thing wrong in this class
<?php
require_once(dirname(__FILE__).'/vendor/autoload.php');
class MyMailer {
    public $transport;
    public $message;
    public $mailer;
    public $server;
    public $userName;
    public $password;
    public $port;
    public function __construct()
    {
        global $AI;
        $this->server   = $AI->get_setting("SMTP_SERVER");
        $this->userName = $AI->get_setting("SMTP_USER");
        $this->password = $AI->get_setting("SMTP_PASSWORD");
        $this->port     = $AI->get_setting("SMTP_PORT");
        $this->transport = Swift_SmtpTransport::newInstance($this->server,$this->port)
          ->setUsername($this->userName)
          ->setPassword($this->password);
        $this->mailer = Swift_Mailer::newInstance($this->transport);
        $this->message = Swift_Message::newInstance();
    }
    public function sendEmail($param)
    {
        $this->message
          ->setSubject($param['subject'])
          ->setFrom($param['from'])
          ->setTo($param['to'])
          ->setBody($param['body'], 'text/html');
          if(!empty($param['attachment']))
          {
              $this->message->attach(Swift_Attachment::fromPath($param['attachment']));
          }      
        return  $this->mailer->send($this->message);
    }
}

**Comment by xdecock** [comment]
No, this is probably injected by interspire, but this is not a bug, it's a
problem of software interractions further down the chain, github is not
there for that, sorry

I recommend reading about email, smtp, dkim, spf, dmarc, ... if you want to
understand what is going on.

regards,

Xavier

On Fri, Oct 9, 2015 at 1:27 PM, sourabhcodiant <notifications@github.com>
wrote:

> can i set the sender header in our php code.
> I have creating the following class. Please let me know if found any thing
> wrong in this class
> <?php
> require_once(dirname(*FILE*).'/vendor/autoload.php');
> class MyMailer {
> public $transport;
> public $message;
> public $mailer;
> public $server;
> public $userName;
> public $password;
> public $port;
> public function __construct()
> {
> global $AI;
> $this->server = $AI->get_setting("SMTP_SERVER");
> $this->userName = $AI->get_setting("SMTP_USER");
> $this->password = $AI->get_setting("SMTP_PASSWORD");
> $this->port = $AI->get_setting("SMTP_PORT");
> $this->transport =
> Swift_SmtpTransport::newInstance($this->server,$this->port)
> ->setUsername($this->userName)
> ->setPassword($this->password);
> $this->mailer = Swift_Mailer::newInstance($this->transport);
> $this->message = Swift_Message::newInstance();
> }
> public function sendEmail($param)
> {
> $this->message
> ->setSubject($param['subject'])
> ->setFrom($param['from'])
> ->setTo($param['to'])
> ->setBody($param['body'], 'text/html');
> if(!empty($param['attachment']))
> {
> $this->message->attach(Swift_Attachment::fromPath($param['attachment']));
> }
>
> return $this->mailer->send($this->message);
> }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/678#issuecomment-146838815>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B
