### ISSUE TITLE
http://swiftmailer.org/ website issue

### ISSUE THREAD

**Issue by mickadoo** [swiftmailer/swiftmailer#681]
I couldn't find an e-mail to send issues with the website to, so I'm writing it here.

I'm using chrome on ubuntu 14.10. The sidepanel on the website does not allow me to click through the documentation. I think it's because of the minus margins

```
#container {
    float: left;
    width: 100%;
   margin-right: -390px;
}
```

---

Changing this to:

```
#container {
    float: left;
    width: 77%;
}
```

```
#content { 
    padding: 15px;
    color: #222;
    line-height: 1.4em;
    font-size: 0.8em;
}
```

```
#sidepanel {
    float: right;
    width: 23%;
}
```

fixed it for me

**Comment by emielmolenaar** [comment]
Same issue here, Chrome on Ubuntu 15.10.

**Comment by TomOne** [comment]
Same issue here. The navigation sidebar is accessible in Firefox and MS Edge, but not Chrome.

**Comment by JSchwehn** [comment]
I can confirm that behavior on Chrome (Version 46.0.2490.80) running under windows 7.
