### ISSUE TITLE
Calling Message::toString() twice with S/MIME-Signing does not return same result

### ISSUE THREAD

**Issue by jannschu** [swiftmailer/swiftmailer#684]
Hi,

thanks for swiftmailer! :-)

The issue is, that saveMessage() and restoreMessage() in the Message class do not restore/save the encoding. So the signer will change that and it is not restored.

Example:

``` php
<?php 
require_once 'swiftmailer/lib/swift_required.php';
$dir = 'swiftmailer/tests/_samples/';
$message = Swift_SignedMessage::newInstance('Wonderful Subject')
  ->setFrom(array('john@doe.com' => 'John Doe'))
  ->setTo(array('receiver@domain.org', 'other@domain.org' => 'A name'))
  ->setBody('Here is the message itself');

$signer = new Swift_Signers_SMimeSigner();
$signer->setSignCertificate($dir.'smime/sign.crt', $dir.'smime/sign.key');
$message->attachSigner($signer);
assert($message->toString() == $message->toString());
?>
```

**Comment by sstok** [comment]
Calling toString() will regenerate the entire message (including signing), I think the `Swift_Mime_SimpleMessage` (or parent classes) should keep a cached version and clear this when something changes.

@xdecock What do you think?

**Comment by jannschu** [comment]
What will happen if I call toString(), then send it. I guess it will be signed twice?
