### ISSUE TITLE
Class Swift_CharacterReaderFactory_SimpleCharacterReaderFactory does not exist

### ISSUE THREAD

**Issue by Ataurr** [swiftmailer/swiftmailer#685]
hello i have just transfer our site one server to another server and now i am getting a error. i am now trying to use smtp

PHP Fatal error: Uncaught exception ‘ReflectionException’ with message ‘Class Swift_CharacterReaderFactory_SimpleCharacterReaderFactory does not exist’ in /assets/php/vendor/swiftmailer/swiftmailer/lib/classes/Swift/DependencyContainer.php:308

am i missing something ??

Thanks

**Comment by artemalexpetrov** [comment]
Hi! I have the same problem with Swift_Encoder_Rfc2231Encoder
