### ISSUE TITLE
TLS 2.0

### ISSUE THREAD

**Issue by phpgraphics** [swiftmailer/swiftmailer#689]
Hi guys,
I need to increase security on my server so i need to use TLS 2.0. After i do that i get 
Warning: stream_socket_enable_crypto(): SSL: Connection reset by peer in swift/classes/Swift/Transport/StreamBuffer.php on line 95 Fatal error: Uncaught exception 'Swift_TransportException' with message 'Unable to connect with TLS encryption' 

Could you please tell me how i could possibly sort this?

Regards,
George

**Comment by stof** [comment]
Well, swiftmailer relies on http://php.net/stream_socket_enable_crypto

So your issue looks like PHP itself does not yet support TLS 2.0 (at least in the version you are using). note that it is also related to the version of openssl you are using

**Comment by xdecock** [comment]
Mmmmh, TLS 2.0 doesn't exists at all

https://fr.wikipedia.org/wiki/Transport_Layer_Security Max version is  1.3 and is in final drafts stages
