### ISSUE TITLE
addPart() does not inherit encoding

### ISSUE THREAD

**Issue by swiftmailer** [swiftmailer/swiftmailer#69]
Consider:

$this->message->setCharset('iso-8859-1');
$message->setEncoder(Swift_Encoding::get8BitEncoding());
$message->setBody('foo æøå bar', 'text/html');
$message->addPart('foo æøå bar', 'text/plain');

The body correctly gets the right encoding and charset, however the alternative body (set by addPart) gets this:

Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

clearly ->addPart() does not correctly inherit the encoding and charset set in the $message class, and there is no other way to assign charset or encoding to the added part.

Thanks.

Original creation date: 2009-08-20T10:43:20Z
Original reporter: MichaelL
Original ticket: http://swiftmailer.lighthouseapp.com/projects/21527/tickets/107

**Comment by fyrye** [comment]
A workaround for others until the issue is resolved is to manually define and attach the mime part rather than using the addPart.
```php
$message = \Swift_Message::newInstance();
$message->setEncoder(\Swift_Encoding::getBase64Encoding());
$message->setFrom('name@example.com')
    ->setTo('user@example.com')
    ->setSubject('Test')
    ->setBody('This is an html message', 'text/html');
$part = \Swift_MimePart::newInstance();
$part->setEncoder($message->getEncoder());
$part->setBody('This is a text message', 'text/plain');
$message->attach($part);
var_dump($message->toString());
```

Outputs:
```
string 'Message-ID: <4264df3ba4621e4ec0ea963f21ccca77@example.com>
Date: Thu, 14 Jan 2016 20:10:42 +0000
Subject: Test
From: name@example.com
To: user@example.com
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="_=_swift_v4_1452802242_e202ee1b9d03205d6d3e09b55539203f_=_"


--_=_swift_v4_1452802242_e202ee1b9d03205d6d3e09b55539203f_=_
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: base64

VGhpcyBpcyBhIHRleHQgbWVzc2FnZQ==

--_=_swift_v4_1452802242_e202ee1b9d03205d6d3e09b55539203f_=_
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: base64

VGhpcyBpcyBhbiBodG1sIG1lc3NhZ2U=

--_=_swift_v4_1452802242_e202ee1b9d03205d6d3e09b55539203f_=_--
```

**Comment by Sapistudio** [comment]
https://github.com/swiftmailer/swiftmailer/pull/889
