### ISSUE TITLE
Failed to authenticate with 1 authenticator on Server

### ISSUE THREAD

**Issue by CoteViande** [swiftmailer/swiftmailer#692]
Hi!

Mails get sent wonderfully from my local machine but fail on the online server. They had worked up until now and I'm at a loss as to why it is not authenticating even though I provide the correct password.

On my online server, I get the following error: `Failed to authenticate on SMTP server with username '<email>' using 1 possible authenticators`

I have been diving into Swiftmailer's code and if I understand properly, this error means that inside the `AuthHandler`, in the `doEhlo` function, the `$authenticator->authenticate` returned false. I assume this means that one of the `executeCommand` did not execute properly.

I find it fishy that it can authenticate on my local machine but not on the server, with the exact same credentials.
But I cannot figure out how to debug this. So any kind of help would be greatly appreciated.

Side note: I use Symfony2.3 on a shared hosting account.

**Comment by alexmck** [comment]
Any chance you've just enabled DNSSEC on your domain? I've just done the same and have suddenly run into this same problem.

**Comment by CoteViande** [comment]
Unfortunately, it seems to be turned off on my server.
