### ISSUE TITLE
[5.X] BUG - Return types for getTo(), getCc() and getBcc() 

### ISSUE THREAD

**Issue by lucasmichot** [swiftmailer/swiftmailer#693]
`\Swift_Mime_SimpleMessage` implements the `\Swift_Mime_Message` interface, which states the following functions should return `string[]` arrays only:
- `\Swift_Mime_Message::getTo()`
- `\Swift_Mime_Message::getCc()`
- `\Swift_Mime_Message::getBcc()`

But these functions may return `null` instead of empty arrays. The interface is thus not respected and a bug can occur.

@fabpot @xdecock , I am willing to provide a PR to fix that, but which way round ?
- Shall the interface be updated to indicate these functions can also return `null` ?
- OR Shall the concrete implementations be updated so that they only return `string[]` arrays ?

**Comment by sstok** [comment]
I would say always return an array, an empty array is technically the same as null for this case but less error prone. Similar to a function that returns a boolean value doesn't return null.

But lets wait what the others have to say ;)

**Comment by fabpot** [comment]
I agree with @sstok, we sholud always return an array.
