### ISSUE TITLE
RFC 2822, 3.6.2. exception

### ISSUE THREAD

**Issue by Poloko** [swiftmailer/swiftmailer#698]
I am contantly getting an error and I dont get why. I went through as much web documentation as I could but I cant solve it. I keep getting this error.

atal error: Uncaught exception 'Swift_RfcComplianceException' with message 'Address in mailbox given [] does not comply with RFC 2822, 3.6.2.' in /home/simplysocialdanc/public_html/wp-content/themes/aperture/lib/classes/Swift/Mime/Headers/MailboxHeader.php:308 Stack trace: #0 /home/simplysocialdanc/public_html/wp-content/themes/aperture/lib/classes/Swift/Mime/Headers/MailboxHeader.php(238): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('') #1 /home/simplysocialdanc/public_html/wp-content/themes/aperture/lib/classes/Swift/Mime/Headers/MailboxHeader.php(96): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array) #2 /home/simplysocialdanc/public_html/wp-content/themes/aperture/lib/classes/Swift/Mime/Headers/MailboxHeader.php(60): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array) #3 /home/simplysocialdanc/public_html/wp-content/themes/aperture/lib/classes/Swift/Mime/SimpleMimeEntity.php(581): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array) #4 /home/simplysocialdanc/public_html/wp-content/theme in /home/simplysocialdanc/public_html/wp-content/themes/aperture/lib/classes/Swift/Mime/Headers/MailboxHeader.php on line 308

here is my code

   $msg = "Dear domain <br><br>";
   $msg .= $name;
   $msg .= "<br> sent you the following message:";
   $msg .= $comment;
   $msg .= "<br>";
   $msg .= $name;
   $msg .= "'s email address is ";
   $msg .= $email;
   $msg .= " and would like your assistance. <br>";
   $msg .= "<br> From Webmaster";

   $msg1 = "Dear ";
   $msg1 .= $name;
   $msg1 .= "<br><br> Thank you for query.<br> Someone from Host with get back to you very soon! <br>THIS MESSAGE IS AN AUTOMATIC RESPONSE, <font color='#FF0000'>DO NOT RESPOND TO THIS MESSAGE</font><br><br>Kind Regards<br><img src='http://domain.co.za/wp-content/uploads/2015/11/logoe.jpg' style='width:40%; float:left' /><br>Host<br><br><a href='http://www.domain.co.za' target='blank'>domain.co.za</a>";
   // Create the mail transport configuration
   $transport = Swift_MailTransport::newInstance();

   // Create the message
   $message = Swift_Message::newInstance();

   //create the message
   $message = Swift_Message::newInstance($subject)
     ->setFrom(array($email => $fullname))
     ->setTo(array($hoste => $host))
     ->setReplyTo(array($email => $fullname))
     ->setContentType("text/html")
     ->setBody($msg)
     ;

   // Send the email
   $mailer = Swift_Mailer::newInstance($transport);
  
   $result = $mailer->send($message);
   // Create the mail transport configuration
   $transport1 = Swift_MailTransport::newInstance();

   // Create the message
   $message1 = Swift_Message::newInstance();

  //create the message
   $message1 = Swift_Message::newInstance($subject1)
     ->setFrom(array($hoste => $host))
     ->setTo(array($email => $fullname))
     ->setReplyTo(array($hoste => $host))
     ->setContentType("text/html")
     ->setBody($msg1)
     ;
  
   // Send the email
   $mailer1 = Swift_Mailer::newInstance($transport1);
   $result1 = $mailer1->send($message1);
   if($result1 && $result1){
   	header("Location: http://domain.co.za/success/");
   } else {
   	header("Location: http://domain.co.za/failed/");
   }

All the variable are set before this code what is wrong please help.

I checked the RFC 2822, 3.6.2. and I dont see how it doesn't meet it

**Comment by sstok** [comment]
`'Address in mailbox given [] does not comply with RFC 2822, 3.6.2.'` your `$email` is empty (or you removed it). SwiftMailer 5.x doesn't yet fully support all e-mail addresses, 6.0 will solve this but also introduces some (minor) BC breaks and is not released yet.

**Comment by Poloko** [comment]
Thank you so much you made me realize my mistake!!

**Comment by sstok** [comment]
@Poloko Can you close this one? ;)
