### ISSUE TITLE
When setting up  a Cc-receiver:   the Cc-receiver get one mail for each regular-receiver

### ISSUE THREAD

**Issue by estebu** [swiftmailer/swiftmailer#702]
When I setting up  a Bcc- or Cc-receiver:   this Bcc- or Cc-receiver gets the same number of emails as recipients are included in the "sentTo - Array".

For instance:

I have 4 recipients -> 

$message->setTo(array
    ('address1@domain.com' => 'Name One'),
    ('address2@domain.com' => 'Name Two'),
    ('address3@domain.com' => 'Name Three'),
    ('address4@domain.com' => 'Name Four')
);

and one reciepent in Cc ->

$message->setCc(array('address5@domain.com' => 'Name Cc'));

Now in the Mailbox of  'address5@domain.com' are 5 times the same email. 
All other reciepents (1-4) get one email only (that should be very ok). 

Can You imagine why??

here is the code:

//Mailfunction
		require_once 'swiftmail/swift_required.php';

// Create the Transport
$transport = Swift_SmtpTransport::newInstance('mail.server.net', 465, 'ssl')
	->setUsername('username')
	->setPassword('********************')
  ;

// Create the Mailer using your created Transport
$mailer = Swift_Mailer::newInstance($transport);

// Create a message
$message= Swift_Message::newInstance();
$message->setSubject($subject);
$from_sender = array($mail_sender_email => $mail_sender_name);
$message->setFrom($from_sender);
$message->setReturnPath($mail_sender_email);
$message->setCc(array('address5@domain.com' => 'Address Cc'));
$message->setBody($text,'text/html');
$message->addPart('
	Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. 
	<img src="http://www.imageserver.com/image.jpg" width="527" height="377" />
	', 'text/plain');

// Send the message
$failedRecipients = array();
$numSent = 0;
$to = $receiver;
foreach ($to as $address => $receiver_name)
{
  if (is_int($address)) {
    $message->setTo($receiver_name);
  } else {
    $message->setTo(array($address => $receiver_name));
  }
  $numSent += $mailer->send($message, $failedRecipients);
}

printf(" %d Emails sent.\n", $numSent);

**Comment by estebu** [comment]
PHP Version 5.6.13-0+deb8u1

**Comment by xdecock** [comment]
Your bug  : 

foreach ($to as $address => $receiver_name)
{
if (is_int($address)) {
$message->setTo($receiver_name);
} else {
$message->setTo(array($address => $receiver_name));
}
$numSent += $mailer->send($message, $failedRecipients);
}

A foreach loop
