### ISSUE TITLE
Issues with Gmail authentication

### ISSUE THREAD

**Issue by fernandosoares** [swiftmailer/swiftmailer#703]
Hey everybody.

I can't connect with Gmail SMTP server.

Look:

 $transport = Swift_SmtpTransport::newInstance()
            ->setHost('smtp.gmail.com')
            ->setPort(465)
            ->setEncryption('ssl')
            ->setUsername('email@gmail.com')
            ->setPassword('mypasss');

```
$mailer = Swift_Mailer::newInstance($transport);

$message = Swift_Message::newInstance('Contato via Site')
        ->setFrom(array($email => $de))
        ->setTo(array($destinatario => 'Agência Linka'))
        ->setBody($corpo_mensagem, 'text/html')
        ->setCharset('UTF-8');

$mailer->send($message);
```

And then I get this:

Fatal error: Uncaught exception 'Swift_TransportException' with message 'Connection could not be established with host smtp.gmail.com [ #0]' in ...

Anyone has experienced this?

**Comment by sstok** [comment]
Check if you can reach the host from your system, and make sure the firewall doesn't block out-going port 465.
