### ISSUE TITLE
For how long should I watch this space?

### ISSUE THREAD

**Issue by guidogam** [swiftmailer/swiftmailer#706]
Seriously, when used with a database, the Decorator and Logger don't cut it.
What's wrong with the (obvious) implementation $mailer->send($message, $failedRecipients, $failureMessages, array($template=>$value)) ?

Other than that, especially after years spent dabbling with mail(), SwiftMailer and its documentation are simply great!

**Comment by xdecock** [comment]
I usually recommend building each mail in your own loop, as it'll be way faster and easier to debug for you, and will avoid the complex "change email and restore the original status" part of the code in the plugin which is tricky as it should work for overly complex hierarchy of mime content, so, it's reccursive, ... and in the end, altough it's probably correct it's a tricky part of the code and you might easily hit a bug hidden in there somewhere.

**Comment by guidogam** [comment]
I did exactly that, but I'm used to 8-bit microcontrollers running at 8 MHz with 1KB of RAM, so I'm pretty stingy with resources.
Given what you wrote and that the program runs beautifully as it is now, I will be more generous with the resources and forget optimizations which are not such. Thanks and congratulations again.

**Comment by guidogam** [comment]
Just one extra thing. What about an horrible hack? (yes, I do use GOTOs,
and I'm proud of it)

While the actual message is telnetted to the SMTP server all instances of
{*{*{<varname>}*}*} are substituted with <varname> contents.
I only need to put a number which is the encryped ID of the recipient, to
complete the unsubscribe link. And this is a practice that should be
encouraged.


Cordiali saluti

Guido Gambardella

Tel. +39 010 218842

 TDD Tecnologie Digitali
 Corso Magenta 27/3
 16125 Genova ITALY
 e-mail info@tdd.it

2016-01-05 12:56 GMT+01:00 De Cock Xavier <notifications@github.com>:

**Comment by xdecock** [comment]
you can then check for a stream filter in php ;)

Probably a way uglier hack than any else i can think of, it will become a
nightmare for the person trying to maintain the code if you do the hack in
an obscure config file

http://php.net/manual/en/function.stream-filter-register.php

But hey, it can be done to work

Out of scope but imho one of the most beautifull misuse of wrappers
https://github.com/scottmac/php-function-rename

On a more serious note, i usually implement a template engine for the text
/ html and let them "generate and send.

On Tue, Jan 5, 2016 at 1:32 PM, guidogam <notifications@github.com> wrote:

> Just one extra thing. What about an horrible hack? (yes, I do use GOTOs,
> and I'm proud of it)
>
> While the actual message is telnetted to the SMTP server all instances of
> {*{*{<varname>}*}*} are substituted with <varname> contents.
> I only need to put a number which is the encryped ID of the recipient, to
> complete the unsubscribe link. And this is a practice that should be
> encouraged.
>
>
> Cordiali saluti
>
> Guido Gambardella
>
> Tel. +39 010 218842
>
> TDD Tecnologie Digitali
> Corso Magenta 27/3
> 16125 Genova ITALY
> e-mail info@tdd.it
>
> 2016-01-05 12:56 GMT+01:00 De Cock Xavier <notifications@github.com>:
>
> > I usually recommend building each mail in your own loop, as it'll be way
> > faster and easier to debug for you, and will avoid the complex "change
> > email and restore the original status" part of the code in the plugin
> which
> > is tricky as it should work for overly complex hierarchy of mime content,
> > so, it's reccursive, ... and in the end, altough it's probably correct
> it's
> > a tricky part of the code and you might easily hit a bug hidden in there
> > somewhere.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/swiftmailer/swiftmailer/issues/706#issuecomment-168981000
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/706#issuecomment-168987380>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by guidogam** [comment]
Don't prod me with ugly hacks, I may do it!
The only problem is that the person that will maintain the code is me, but another me, after some more months of C and assembly.

Beautiful? That rename_function scares even me, that once used to do weird stuff with the C preprocessor.
