### ISSUE TITLE
How to change message encoder from qp to base64?

### ISSUE THREAD

**Issue by SonkoDmitry** [swiftmailer/swiftmailer#707]
I set it by

```
->setEncoder(\Swift_Encoding::getBase64Encoding())
```

after test it by

```
->getEncoder()
```

but all mails recieve with Content-Transfer-Encoding: quoted-printable anyway

**Comment by ruden** [comment]
https://github.com/swiftmailer/swiftmailer/issues/69#issuecomment-171771123
https://gist.github.com/tanakahisateru/8337701#file-perfect-mail-php
