### ISSUE TITLE
not working when integrated with WP Plugin 

### ISSUE THREAD

**Issue by heshamfathi** [swiftmailer/swiftmailer#709]
i have integrated swiftmailer with a plugin i have made which is called using POST and adding a route to WP , the plugin works perfectly , however the Swiftmailer doesn't , as i call it from inside a function of a class but the $message->toString(), but $mailer->send() always returns 0 not matter what the email is , i have made sure that the swiftmailer loaded correctly and there is no error or not found file at all, but when i loaded swiftmailer alone as a separate plugin it works and it seems like the problem at this part :  
1. my plugin index has to call a request handler to handle requests for the website at this link : example.com/someRoute with this action hook :
add_action('parse_request', array( 'RequestsHandler', 'processRequests' ));

the requests handler calls a datahandler which calls swiftmail inside a fuction with this code : 
public function sendEmails()
    {
        $this->prepareRequestDataToSendEmail();
        require_once plugin_dir_path(plugin_dir_path(__FILE__)) . 'senders/swiftmailer/swift_required.php';
        $transport = Swift_MailTransport::newInstance();
        $mailer = Swift_Mailer::newInstance($transport);
        $message = Swift_Message::newInstance();
        $message->setSubject($this->senderSubject);
        $message->setFrom(array($this->senderFromEmail => $this->senderFromName));
        $message ->setTo(array($this->senderReceiverEmail));
        $message ->setBody($this->senderContent, 'text/html');
        echo $message->toString();
        echo $result = $mailer->send($message, $failures) ;
        var_dump( $failures );
    }

**Comment by xdecock** [comment]
What is your os ?  Do you have a mail server available ?  Does the mail()
function work on your system ?  What is the php version ?

Thanx

**Comment by heshamfathi** [comment]
Issues Fixed , it was a server error, i found a php.ini file in the folder however it had only the config for showing errors but when i deleted it everything worked, the thin is swiftmailer worked even when this file was there but not inside the wp plugin , anyway it works now
