### ISSUE TITLE
Switfmailer removes dot in number

### ISSUE THREAD

**Issue by wouterverstuyf** [swiftmailer/swiftmailer#714]
Hello

I use swiftmailer to send emails when an order is being submitted. The email is the most of the time okay, but sometimes the dot in the amount is deleted.

Example : total price = 123.45 €
Sometimes the amount is 12345 in the email. The strange about this is that it occurs randomly.

Any ideas? I cannot find the issue ...

Thx!
Wouter

**Comment by xdecock** [comment]
the dot is probably the first character on a line and is stripped by some
element through the chain.

Can you tell us which transport you're using?

and what filter are on your mail chain?

Thx,

Xavier

On Tue, Jan 12, 2016 at 6:47 PM, Wouter Verstuyf <notifications@github.com>
wrote:

> Hello
>
> I use swiftmailer to send emails when an order is being submitted The
> email is the most of the time okay, but sometimes the dot in the amount is
> deleted
>
> Example : total price = 12345 €
> Sometimes the amount is 12345 in the email The strange about this is that
> it occurs randomly
>
> Any ideas? I cannot find the issue
>
> Thx!
> Wouter
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/714>.
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by wouterverstuyf** [comment]
Hi Xavier

Thx for the reply.
The dot is not at the beginning of a line, sometimes it the dot from the amount is being stripped, sometimes it's the dot in an URL.

This is the code:

$content = 'Thank you for you order at website.be. The total price is 124.45€';

        $message = \Swift_Message::newInstance('New order')
            ->setFrom(array('info@...' => 'info@...'))
            ->setTo(array('info@...' => 'info@...'))
            ->setBody($content, 'text/html');

        $transport =
          \Swift_MailTransport::newInstance(
            FrontendModel::getModuleSetting('core', 'mailer_type'),
            FrontendModel::getModuleSetting('core', 'smtp_server'),
            FrontendModel::getModuleSetting('core', 'smtp_port'),
            FrontendModel::getModuleSetting('core', 'smtp_username'),
            FrontendModel::getModuleSetting('core', 'smtp_password'),
            FrontendModel::getModuleSetting('core', 'smtp_secure_layer')
        );
        $mailer = \Swift_Mailer::newInstance($transport);
        $mailer->send($message);

As mailer_type is use "mail", so the smtp settings can be ignored.
In the message, sometimes the dot of website.be is removed, and some times the dot in the number.

Hope this will give more info...
Thx!

**Comment by xdecock** [comment]
;) the position in the line is asked at the smtp level which will be
splitted on 62 or 72 characters (i don't remember)

On Wed, Jan 13, 2016 at 8:01 AM, Wouter Verstuyf <notifications@github.com>
wrote:

> Hi Xavier
>
> Thx for the reply.
> The dot is not at the beginning of a line, sometimes it the dot from the
> amount is being stripped, sometimes it's the dot in an URL.
>
> This is the code:
>
> $content = 'Thank you for you order at website.be. The total price is
> 124.45€';
>
>     $message = \Swift_Message::newInstance('New order')
>         ->setFrom(array('info@...' => 'info@...'))
>         ->setTo(array('info@...' => 'info@...'))
>         ->setBody($content, 'text/html');
>
>     $transport =
>       \Swift_MailTransport::newInstance(
>         FrontendModel::getModuleSetting('core', 'mailer_type'),
>         FrontendModel::getModuleSetting('core', 'smtp_server'),
>         FrontendModel::getModuleSetting('core', 'smtp_port'),
>         FrontendModel::getModuleSetting('core', 'smtp_username'),
>         FrontendModel::getModuleSetting('core', 'smtp_password'),
>         FrontendModel::getModuleSetting('core', 'smtp_secure_layer')
>     );
>     $mailer = \Swift_Mailer::newInstance($transport);
>     $mailer->send($message);
>
> As mailer_type is use "mail", so the smtp settings can be ignored.
> In the message, sometimes the dot of website.be is removed, and some
> times the dot in the number.
>
> Hope this will give more info...
> Thx!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/714#issuecomment-171197293>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by wouterverstuyf** [comment]
@xdecock Hmz, I think I'm not seeing it... :)

The $content (content of the mail) is actually a lot bigger, above is just a part of the mail as an example.

Do you mean I can remove the smtp lines, cause I'm using mail() to send the emails. Is this causing the issue?

Thx

**Comment by xdecock** [comment]
yes,

but basically, in smtp

to send
"Hello ABCDER ~
. Line with dot as first caracter

we need to implement dot stuffing (doubling up the dot)

It's implemented, however if you have some proxies in the path it might be
the culprit

So what's your smtp server?

On Wed, Jan 13, 2016 at 11:56 AM, Wouter Verstuyf <notifications@github.com>
wrote:

> @xdecock <https://github.com/xdecock> Hmz, I think I'm not seeing it... :)
>
> The $content (content of the mail) is actually a lot bigger, above is just
> a part of the mail as an example.
>
> Do you mean I can remove the smtp lines, cause I'm using mail() to send
> the emails. Is this causing the issue?
>
> Thx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/714#issuecomment-171253818>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by wouterverstuyf** [comment]
Hmz, but on the website I don't use a SMTP server, but simple the mail() function.
I've adjusted the code as follows:

        $transport = \Swift_MailTransport::newInstance();
        $mailer = \Swift_Mailer::newInstance($transport);
        $mailer->send($message);

I have read in the docs, that if you want to use mail() you can leave the transport instance empty. Should this make any difference?

btw, it's a FORK CMS website, if that info might help.

**Comment by xdecock** [comment]
you always use an smtp server otherwise the mail won't get anywhere

On Wed, Jan 13, 2016 at 12:15 PM, Wouter Verstuyf <notifications@github.com>
wrote:

> Hmz, but on the website I don't use a SMTP server, but simple the mail()
> function.
> I've adjusted the code as follows:
>
>     $transport = \Swift_MailTransport::newInstance();
>     $mailer = \Swift_Mailer::newInstance($transport);
>     $mailer->send($message);
>
> I have read in the docs, that if you want to use mail() you can leave the
> transport instance empty. Should this make any difference?
>
> btw, it's a FORK CMS website, if that info might help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/714#issuecomment-171257296>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by wouterverstuyf** [comment]
Right... stupid!
Then I suppose the script will use the default smtp server of the Combell hosting. This should be smtp.mailprotect.be

**Comment by xdecock** [comment]
If you check the email received and look received headers you'll find your
answer
Le 13 janv. 2016 12:36 PM, "Wouter Verstuyf" <notifications@github.com> a
écrit :

**Comment by wouterverstuyf** [comment]
Okey, thx, I will search for it tomorrow and if I get this server...
What should I do with it to fix the removing dot problem? Change the transport object?
