### ISSUE TITLE
yii\base\UnknownPropertyException

### ISSUE THREAD

**Issue by Alexandr10** [swiftmailer/swiftmailer#715]
Exception (Unknown Property) 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\swiftmailer\Mailer::0' 

in D:\USR\www\basic\vendor\yiisoft\yii2\base\Component.php:197

Stack trace:
#0 D:\USR\www\basic\vendor\yiisoft\yii2\BaseYii.php(518): yii\base\Component->__set('0', Array)
#1 D:\USR\www\basic\vendor\yiisoft\yii2\base\Object.php(105): yii\BaseYii::configure(Object(yii\swiftmailer\Mailer), Array)
#2 [internal function]: yii\base\Object->__construct(Array)
#3 D:\USR\www\basic\vendor\yiisoft\yii2\di\Container.php(372): ReflectionClass->newInstanceArgs(Array)
#4 D:\USR\www\basic\vendor\yiisoft\yii2\di\Container.php(151): yii\di\Container->build('yii\\swiftmailer...', Array, Array)
#5 D:\USR\www\basic\vendor\yiisoft\yii2\BaseYii.php(344): yii\di\Container->get('yii\\swiftmailer...', Array, Array)
#6 D:\USR\www\basic\vendor\yiisoft\yii2\di\ServiceLocator.php(133): yii\BaseYii::createObject(Array)
#7 D:\USR\www\basic\vendor\yiisoft\yii2\di\ServiceLocator.php(71): yii\di\ServiceLocator->get('mailer')
#8 D:\USR\www\basic\controllers\TestController.php(11): yii\di\ServiceLocator->__get('mailer')
#9 [internal function]: app\controllers\TestController->actionLala()
#10 D:\USR\www\basic\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#11 D:\USR\www\basic\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#12 D:\USR\www\basic\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('lala', Array)
#13 D:\USR\www\basic\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('test/lala', Array)
#14 D:\USR\www\basic\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#15 D:\USR\www\basic\web\index.php(12): yii\base\Application->run()
#16 {main}
web.php:inside components:

 'mailer' => [
        [
            'class' => 'yii\swiftmailer\Mailer',
            'viewPath' => '@app/mail',
            'useFileTransport' => false, //I tried true too
            'transport' => [
                'class' => 'Swift_SmtpTransport',
                'host' => 'smtp.gmail.com', 
                'username' => 'ibondariev@gmail.com', 
                'password' => '***', 
                'port' => '587', 
                'encryption' => 'tls',
            ],
        ],
    ],
and in controller:

  \Yii::$app->mailer->compose()
                ->setFrom('ibondariev@gmail.com')
                ->setTo('bondsasha@ua.fm')
                ->setSubject('This is a test mail')
                ->send();
any ideas.what is wrong?

**Comment by GrahamCampbell** [comment]
This is totally unrelated to swiftmailer.
