### ISSUE TITLE
is there a way to handle a timeout as an error

### ISSUE THREAD

**Issue by stccorp** [swiftmailer/swiftmailer#716]
Hello,
I got the case with a couple of emails that swift will NOT return an error. It will said 

Connection to mydomain.com:25 Timed Out (code: 0)<br />

But it will not return as an error.  So how can I catch this case?

Thank you

**Comment by brutto** [comment]
+1

**Comment by brutto** [comment]
For my case found workaround to use FailoverTransport with 2 instances of same Transports:

Example:
```
$failoverTransport = new Swift_FailoverTransport([
  new Swift_SmtpTransport(),
  new Swift_SmtpTransport()
]);
```

It allows use same transport untill it timeouted and again after that. =)
