### ISSUE TITLE
Swiftmailer 1and1.com time out

### ISSUE THREAD

**Issue by rretzko** [swiftmailer/swiftmailer#718]
All - Any help troubleshooting is appreciated; 1and1 help desk was unable to help.

I'm working on Windows 10 trying to run a short Swiftmailer test as follows: 
$transport = \Swift_SmtpTransport::newInstance('smtp.1and1.com', '587', 'tls')
                ->setUsername('rick@auditionforms.com')
                ->setPassword('************') 
                ->setAuthMode('login'); 

and am getting an error message "Connection could not be established with host smtp.1and1.com [Connection timed out #110]"

I've tried: 
  $server names = smtp.1and1.com, mrvnet.kundenserver.de, mrelat.perfora.net and 74.208.5.2
  $ports  = 25 and 587 (25 hits an 'Internal Server Error')
  $authModes = PLAIN, crammd5, login, LOGIN

All produce the same time out state.

Thanks for your assistance.

**Comment by xdecock** [comment]
have you tried with telnet to exclude a network filter?

**Comment by rretzko** [comment]
Hi - Thanks for the response; I am able to telnet into the server.  I've moved to plan b: Mailchimp/Mandrillapp which is working fine through their API with the exception of some issues regarding the PDF attachment.  The 1and1.com problem remains unsolved, but my application moves forward.

**Comment by BDN001** [comment]
Hi, been stuck with this for days, but managed to get it working... checked Swiftmailer v6 installed for latest Laravel 5.5... checked port (25/587), host (local or auth.smtp.1and1.co.uk), with and without auth. Tried TLS and SSL and null. None of these worked, but when I switched off -bs flag in /usr/sbin/sendmail it works. Have to use -t flag instead. But (for no good reason) it works.

**Comment by adhn** [comment]
I was only lost for 3 hours with this problem untill I found this thread :)

**Comment by MrDarpan** [comment]
@BDN001 How to switch off -bs flag in /user/sbin/sendmail ?
