### ISSUE TITLE
Attachments content corrupted

### ISSUE THREAD

**Issue by mastir** [swiftmailer/swiftmailer#719]
$mail = $this->getService('mail')->create(); //new Swift_message
$mail->setTo($email);
$mail->setCharset('utf-8');
$mail->setBody($body, 'text/html');
$mail->attach(new \Swift_Attchment($html_page, 'attach.html', 'plain/text'));
$this->getService('mail')->send($mail);

expected result: html page attached
result: 2 exact messages with headers in attachment file and invalid encoding.
Message-ID: <896ea0b4e3a1sdfsd1c756164cde0b47@aaa.bb>
Date: Mon, 25 Jan 2016 11:17:00 +0000
Subject: = SSSSS
From: AAA BBB<ccc@aaa.bb>
To: AAA BBB <ddd@eee.ddd>
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
...

affects 5.4.1, 5.4.0, 5.3.1, 5.3.0,5.2.2, 5.0.3, 4.3.1

**Comment by xdecock** [comment]
Can you provide the source you receive?

are you sure you're providing utf8 html?

**Comment by mastir** [comment]
[email.eml.txt](https://github.com/swiftmailer/swiftmailer/files/103204/email.eml.txt)

**Comment by mastir** [comment]
and why do i have mail  2 times? without attachment i've got only 1 letter sent.

**Comment by mastir** [comment]
oh sorry, found bug in template system that cases Swift_message to string conversion in output buffer and breaking whole message on send.
