### ISSUE TITLE
SSL Operation failed with code 1 (0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length error)

### ISSUE THREAD

**Issue by Braunson** [swiftmailer/swiftmailer#720]
Receiving this sending through various SMTP hosts, seems like an issue with their mail server's certs but want to confirm. Any suggested fixes for their side?

```
Warning: fgets(): SSL operation failed with code 1. OpenSSL Error messages: error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length in /var/www/vhosts/site/lib/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 163
```

**Comment by saidbakr** [comment]
I have like too but with Roundcube mail.

**Comment by aldos84** [comment]
I've the same issue in my current project. I use Amazon SES.
But I not always get this error, only time by time. Don't know how to fix it.

**Comment by Rotzbua** [comment]
Bug reports without any information are useless.

**Comment by rajasekaranka** [comment]
Hi All,
   am using opensssl 1.0.2 n version for TLS1.2 - TCP/IP,
  when using to connect socket by calling - SSL_connect , am getting below error 
error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length
 am using the ca/pem certificate with Key length  - 2048 , Please help me to understand this issue
