### ISSUE TITLE
Compatibility PHP 7

### ISSUE THREAD

**Issue by quentincurtet** [swiftmailer/swiftmailer#730]
Hi,

I saw on travis that https://travis-ci.org/swiftmailer/swiftmailer encountered failures for PHP7.
 Does Swiftmailer is compatible with PHP7 ?

Thanks for your answer.

Cordially.

**Comment by cerlestes** [comment]
We're running SwiftMailer 5.4.1 on a PHP 7.0.3 production machine and haven't encountered any errors so far. But then we're only using the basics, no attachments or other fancy stuff.

**Comment by quentincurtet** [comment]
Sorry i should close this issue, it was a problem made by another developer.

Sorry for the inconvenience.
