### ISSUE TITLE
Expose _userContentType

### ISSUE THREAD

**Issue by tremby** [swiftmailer/swiftmailer#736]
I need a way to get the content type of the message body after a part has been added. After such a part has been added, `$message->getContentType()` changes to `multipart/alternative`, and even though I can get the body with `getBody()` I can't get its type.

Am I missing something, or is it impossible to get this at the moment?

It seems to me either the type should be set to `multipart/alternative` at send time rather than earlier, so a user can still get at the body and its type. Or when a part is added the existing body should immediately become a child and be accessed as such, and then the message's type can change. But perhaps there are good design decisions for the way things currently work which I'm missing.

(I posted on Stackoverflow with [a question about how to retrieve this value](http://stackoverflow.com/questions/36025109/swiftmailer-get-body-contenttype-after-a-part-has-been-added) before digging into the code and finding this.)

**Comment by thomasbilk** [comment]
The information is still there in the protected property `_userContentType`. Maybe this could be solved with another method like `->getBodyContentType()` or something like that?

**Comment by tremby** [comment]
That sounds good to me.

**Comment by yareckon** [comment]
Made a pull request to simply return that value on ->getBodyContentType()

**Comment by TerjeBr** [comment]
Any updates on this?

Why has this not been merged yet?

**Comment by TerjeBr** [comment]
@fabpot or any other maintainer? This is ready to be merged.

**Comment by jbondhus** [comment]
Is anyone going to merge this? I could use this as well.

**Comment by TerjeBr** [comment]
@xdecock Could you merge this please?

**Comment by lambjs** [comment]
@xdecock Need this too. Can you please merge?

**Comment by TerjeBr** [comment]
This seems to have been merged 26th Aug. 2018 in https://github.com/swiftmailer/swiftmailer/pull/939
@fabpot could you please confirm this?

Seems like all that is left to do is to mark this PR as merged and closed.

**Comment by fabpot** [comment]
Yep, fixed.
