### ISSUE TITLE
offering openpgp plugin for swiftmailer 

### ISSUE THREAD

**Issue by postme** [swiftmailer/swiftmailer#737]
[OpenPGPSigner.zip](https://github.com/swiftmailer/swiftmailer/files/181227/OpenPGPSigner.zip)

Hi there,
for one of my projects I needed an OpenPGP signing/encrypting solution for Swiftmailer. I have the code available and am happy to donate it to Swiftmailer. Its a standard Signer, implementing  Swift_Signers_BodySigner. Are you interested in receiving the code and making it part of Swiftmailer?
Kind regards
Meint

**Comment by rubiodamian** [comment]
+1

**Comment by fritzmg** [comment]
This signer should definitely be integrated. Any updates on this? No comments from Swiftmailer devs?

**Comment by pavarnos** [comment]
See also https://github.com/Mailgarant/switfmailer-openpgp
