### ISSUE TITLE
Attachment order is not kept

### ISSUE THREAD

**Issue by Congelli501** [swiftmailer/swiftmailer#744]
I'm using swiftmailer to send an offer email: a PDF document and some photos.

I want the PDF document to be the first attachment and then the photos. To do that, I insert the attachment (using `$message->attach(...)`) in the right order, but swiftmailer reorder my attachments before sending the mail.

The attachment are ordered by mimetype (_childSortAlgorithm, Swift_Mime_SimpleMimeEntity, l. 793).

Why are the files ordered by mimetypes instead of keeping the user order ?
I don't see any use case where this reorder is awaited by the user, and this behaviour is not documented anywhere.

Version:
5.x-dev
fffbc0e2a7e376dbb0a4b5f2ff6847330f20ccf9

**Comment by it-can** [comment]
Is there a way to fix this?

**Comment by fabpot** [comment]
This is indeed a limitation of Swiftmailer, which would require a major refactoring to fix. The good news is that Symfony Mailer does behave correctly.
