### ISSUE TITLE
getmypid() has been disabled for security reasons

### ISSUE THREAD

**Issue by bastos71** [swiftmailer/swiftmailer#745]
hi ! 

I was looking at #445 but I still have a problem with this function.
When I look at the sources, this function is still used 3 times in https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/Mime/SimpleMimeEntity.php

Could this be fixed or am I doing it wrong ?

**Comment by yaazkal** [comment]
Hi. I'm having the same issue. Any short term fix?

**Comment by yambug** [comment]
Me too.
ERROR: exception 'ErrorException' with message 'getmypid() has been disabled for security reasons' in /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php:83
