### ISSUE TITLE
Can't use Swift_Transport_FailoverTransport because it no longer has a constructor.

### ISSUE THREAD

**Issue by BrunoDeBarros** [swiftmailer/swiftmailer#746]
When using `Swift_FailoverTransport::newInstance($transports);`, it no longer works because the failover transport no longer has a __construct, and Swift_FailoverTransport [tries to call it](https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/FailoverTransport.php#L26).

This happened in the ["[Swift] various dead code cleanups, simplifications and phpdoc fixes"](https://github.com/swiftmailer/swiftmailer/commit/dae3bc6c530b86bcaca97ff2cf171b43328d569d) commit.

**Comment by fabpot** [comment]
fixed in 13d4a53
