### ISSUE TITLE
Can't switch between text and html formats in Thunderbird when using embed

### ISSUE THREAD

**Issue by swiftmailer** [swiftmailer/swiftmailer#75]
This bug is related to ticket #34 and #77.

I am trying to create a multipart/alternative email with Swift 4.0.5 with a text section and html section with embedded images.

My code looks similar to:

@@@
$message = Swift_Message::newInstance();

$message->addPart("Test text body", 'text/plain');
$cid = $message->embed(Swift_Image::fromPath("test.jpg"));
$message->addPart("Html body <img src=\"$cid\" />", 'text/html');
@@@

When viewing the sent message in Thunderbird 3, I see the HTML version with embedded images.  However if I change Thunderbird to view the plain text version, I see a Thunderbird-gernerated plain text version of the HTML, not the plain text part I added.

In Swift 3, I was able to use Thunderbird to view the html and plaintext versions.

In Swift 4.0.5, the message source looks like:

@@@
Content-Type: multipart/alternative;
 boundary="a"

--a
Content-Type: text/plain

Test text body

--a
Content-Type: multipart/related
 boundary="b"

--b
Content-Type: text/html

...HTML...

--b
Content-Type: image/jpeg

...JPEG...

--b

--a
@@@

In Swift 3.3.3, the message source looked like:

@@@
Content-Type: multipart/related;
 boundary="a"

--a
Content-Type: multipart/alternative;
 boundary="b"

--b
Content-Type: text/plain

...PLAINTEXT...

--b
Content-Type: text/html

...HTML...

--b

--a
Content-Type: image/jpeg

...JPG...

--a
@@@

Original creation date: 2009-12-31T21:44:39Z
Original reporter: Brandon
Original ticket: http://swiftmailer.lighthouseapp.com/projects/21527/tickets/119

**Comment by fabpot** [comment]
I'm closing this issue as it's going to be fixed by Symfony Mailer/Mime, which will replace Swiftmailer eventually.
