### ISSUE TITLE
SMimeSigner.php add headers

### ISSUE THREAD

**Issue by Manium** [swiftmailer/swiftmailer#758]
Hi,
is it possible to pass custom headers to messageStreamToSignedByteStream method in order to fill the 5th parameter of openssl_pkcs7_sign ? It is useful to get this headers for the openssl_pkcs7_verify to do his job.
Thxs a lot

**Comment by sstok** [comment]
It's not supported at the moment, but it should be possible to add support for this. I don't have time to work on this at the moment, but if you can provide a patch I'm happy to review it 👍
