### ISSUE TITLE
strpos(): Empty needle in Swift/StreamFilters/StringReplacementFilter.php:47

### ISSUE THREAD

**Issue by umairyounus** [swiftmailer/swiftmailer#762]
`2016-05-17 11:10:32] production.ERROR: ErrorException: strpos(): Empty needle in /var/www/releases/20160517150023/vendor/swiftmailer/swiftmailer/lib/classes/Swift/StreamFilters/StringReplacementFilter.php:47
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'strpos(): Empty...', '/var/www/releas...', 47, Array)
#1 /var/www/releases/20160517150023/vendor/swiftmailer/swiftmailer/lib/classes/Swift/StreamFilters/StringReplacementFilter.php(47): strpos('\r\n.', '')
#2 /var/www/releases/20160517150023/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php(86): Swift_StreamFilters_StringReplacementFilter->shouldBuffer('')
#3 /var/www/releases/20160517150023/vendor/swiftmailer/swiftmailer/lib/classes/Swift/KeyCache/DiskKeyCache.php(210): Swift_ByteStream_AbstractFilterableInputStream->write('')
#4 /var/www/releases/20160517150023/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(545): Swift_KeyCache_DiskKeyCache->exportToByteStream('20412f94866388f...', 'body', Object(Swift_Transport_StreamBuffer))
#5 /var/www/releases/20160517150023/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(532): Swift_Mime_SimpleMimeEntity->_bodyToByteStream(Object(Swift_Transport_StreamBuffer))
#6 /var/www/releases/20160517150023/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(611): Swift_Mime_SimpleMimeEntity->toByteStream(Object(Swift_Transport_StreamBuffer))
#7 /var/www/releases/20160517150023/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Message.php(172): Swift_Mime_SimpleMessage->toByteStream(Object(Swift_Transport_StreamBuffer))
#8 /var/www/releases/20160517150023/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(327): Swift_Message->toByteStream(Object(Swift_Transport_StreamBuffer))
#9 /var/www/releases/20160517150023/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(428): Swift_Transport_AbstractSmtpTransport->_streamMessage(Object(Swift_Message))
#10 /var/www/releases/20160517150023/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(454): Swift_Transport_`

**Comment by xdecock** [comment]
StringReplacementFilter

Can you paste you settings on the replacment filter ?

**Comment by umairyounus** [comment]
We are not putting anything in replace, this is automatically called when sending email with bcc on. When using bcc it is trying to store data in cache and this is error is getting triggered.

**Comment by digilist** [comment]
I am having the same issue here. I did not configure anything special and use create a simple message with a recipient, a BCC and a html body.  Any idea why this is happening?

**Comment by digilist** [comment]
We got this reproduced. It happens, when the full message length is a multiple of 8192. I am not exactly sure, why, but SwiftMailer writes the mail into a file on disk and then reads it again into a stream. This is, where the error happens (see here: https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/KeyCache/DiskKeyCache.php#L210)

When reading a file that has a length of exactly n*8192 bytes (n >= 1), the last value of $bytes is an empty string which triggers the error. You can use the following snippet, to validate this behavior in PHP:

```php
$fp = fopen('demo', 'r');
while (!feof($fp) && false !== $bytes = fread($fp, 4)) {
    var_dump($bytes);
}
```

Just create a file with 8 (or similar) bytes (`echo -n "abcdefgh" > demo`) and see what happens:
```
string(4) "abcd"
string(4) "efgh"
string(0) ""
```

This behavior is the same with PHP 5.6 and PHP 7.

I am not exactly sure, what's the best way to fix this, as I haven't fully understood the Swift Mailer internals yet. A simple fix would be to ignore any empty value of $bytes in the linked code snippet.

Thanks @raffomania for helping to find the cause of this bug.

**Comment by xdecock** [comment]
It's quite logical but nice catch.

The last call will give 0 bytes and an empty string. And toggle the eof
(end of file) flag.

To be honnest the bug seems more to be in the inputStream which should
accept empty string

Le mer. 9 nov. 2016 15:11, Markus Fasselt <notifications@github.com> a
écrit :

**Comment by raffomania** [comment]
@xdecock exactly, we found that the following adaption of `AbstractFilterableInputStream.write` would fix the problem for us:

    public function write($bytes)
    {
        $this->_writeBuffer .= $bytes;
        if (empty($this->_writeBuffer)) {
            return;
        }
        foreach ($this->_filters as $filter) {
            if ($filter->shouldBuffer($this->_writeBuffer)) {
                return;
            }
        }
        $this->_doWrite($this->_writeBuffer);

        return ++$this->_sequence;
    }

The alternative would be to allow an empty string in `StringReplacementFilter.shouldBuffer`.

**Comment by digilist** [comment]
Which solution do you prefer? I'd like to submit a PR to fix this issue

**Comment by fabpot** [comment]
@digilist Thanks a lot for investing this issue. I prefer the other alternative. I've submitted a PR with some tests to avoid any regressions in #879.
