### ISSUE TITLE
Address with unicode chars combined with a colon broke header

### ISSUE THREAD

**Issue by OliverFriedrich** [swiftmailer/swiftmailer#763]
Somthing like 
`$message->setFrom(['test@test.com' => ':Test with unicode ÖÄÜ']);`
becomes 
`From: :Test with unicode =?utf-8?Q?=C3=96=C3=84=C3=9C?= <test@test.com>` 
and breaks the mail header, as there is the unquoted colon in the resulting header field. If the unicode chars ÖÄÜ are omitted the result is quoted and functional:
`From: ":Test with unicode" <test@test.com>`

Tested version: current download from github.

**Comment by dmaicher** [comment]
Maybe related to an issue I posted a while ago :cry: 

https://github.com/swiftmailer/swiftmailer/issues/650

**Comment by dmaicher** [comment]
I proposed a fix here https://github.com/swiftmailer/swiftmailer/pull/774
