### ISSUE TITLE
Message-ID reveals admin panel location

### ISSUE THREAD

**Issue by PELock** [swiftmailer/swiftmailer#764]
Swiftmailer reveals admin panel location in Message-ID (domain part after the @), I've tried to add Message-ID manually but it just adds second Message-ID

```
	$message = Yii::$app->mailer->compose();

	$message->setTo(...);
        ...
	$headers = $message->getSwiftMessage()->getHeaders();

	// message ID header (hide admin panel location)
	$headers->addIdHeader('Message-ID', md5(time()) . "@example.com");

```
(it's Yii2 app with Swiftmailer)

**Comment by voku** [comment]
I think you can change it via "setId()" | http://swiftmailer.org/docs/headers.html#id-headers

**Comment by PELock** [comment]
@voku thank you buddy, it works fine!
