### ISSUE TITLE
PHP 7.x support?

### ISSUE THREAD

**Issue by jbouse** [swiftmailer/swiftmailer#765]
Debian is currently in transition from PHP 5.x to PHP 7.x ... Looking to determine if Swift will still work or if it should be removed from the distribution when PHP 5.x is removed.

**Comment by fabpot** [comment]
Yes, Swiftmailer works with PHP7.

**Comment by GrahamCampbell** [comment]
https://github.com/swiftmailer/swiftmailer/blob/5.x/.travis.yml#L23

**Comment by jbouse** [comment]
Thanks for the quick response. I hadn't thought to check the .travis.yaml file and was just looking for confirmation since all the docs seem to only mention "PHP 5".
