### ISSUE TITLE
Duplicate emails sent

### ISSUE THREAD

**Issue by barbmc** [swiftmailer/swiftmailer#766]
I am using the code below to send an email, and every time two identical emails are sent out.

`require_once 'swift/lib/swift_required.php';
            $starpath='../images/';
		    if ($eauthreq=='yes') {
			      $transport = Swift_SmtpTransport::newInstance("$eserver","$eport")
                  ->setusername($euser)
                  ->setPassword($epass);
		    } else {
			      $transport = Swift_SmtpTransport::newInstance("$eserver","$eport");
		    }
		    $mailer = Swift_Mailer::newInstance($transport);
            $message = Swift_Message::newInstance();
		    $message->setSubject("$clientname Account Information");
	    
            if ($client=='wrm') {
                require_once('email-header.php');
                $body .= "<br>Hi $fname,<br><br>Your account at $clientname has been created.<br>You can now log in at <a href='http://webrecipemanager.com'>Web Recipe Manager</a><br><br> Below is your user name for future reference.<br><br><hr>";
            } else {
                $body = "<br>Hi $fname,<br><br>Your account at $clientname has been created.<br>You will be able to log in when an administrator has approved your account.<br><br> Below is your user name for future reference.<br><br><hr>";
            }
            
            $body .= "User: $user<hr><br>";
		    $body .= "Regards,<br>$clientname Administration.";
            
            if ($client=='wrm') {
                require_once('email-footer.php');
            }
            $message->setBody(
                '<html>' .
                ' <head></head>' .
                ' <body>' .
                $body .
                ' </body>' .
                '</html>',
                  'text/html'
            );
            if($lname) {
                $toname=$fname.' '.$lname;
            } else {
                $toname=$fname;
            }
            $message->setTo(array(
              $email => $toname,
              $csuppemail => $clientname
            ));
		    $message->setFrom(array($csuppemail => $clientname));

            if ($mailer->send($message)){
               echo 'yes';
            } else {
               echo "Message failed to send";
            }`

**Comment by barbmc** [comment]
It's OK I worked it out.

**Comment by q-sol** [comment]
Apologies, how did you fixed this?

**Comment by barbmc** [comment]
It was my error.

**Comment by q-sol** [comment]
ah yes, I am having a similar error so i am trying to figure out if maybe what you found would help me.
