### ISSUE TITLE
Issue with SSL / TLS and self-signed server certificates

### ISSUE THREAD

**Issue by Ziggizag** [swiftmailer/swiftmailer#768]
Hi,

Sending encrypted messages on servers presenting self-signed certificates or on shared environment where server certificate does not match domain name results in exception like the following one:

> exception 'ErrorException' with message 'stream_socket_enable_crypto(): Peer certificate CN=`*.servername.com' did not match expected CN=`mail.domain.com'' in \home\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php:95

I sugggest adding configuration parameter "Skip certificate validation", so method **_establishSocketConnection** of the **Swift_Transport_StreamBuffer** class could add the following in case this parameter is set to true:

`$options['ssl'] = ['allow_self_signed' => true, 'verify_peer' => false, 'verify_peer_name' => false];`

That would effectively prevent the above mentioned exception from occurrence.

**Comment by mihai-mocanu** [comment]
+1 having same issue

**Comment by matteomoretti** [comment]
+1 same issue

**Comment by mtarvainen** [comment]
First of all, thanks for your great library!

As far as I can see lack of this feature blocks upgrade away from PHP 5.5 (EOL) if self-signed certificate is in use. See upgrade note in http://php.net/manual/en/migration56.openssl.php

**Comment by fabpot** [comment]
Anyone willing to submit a PR?
