### ISSUE TITLE
No exception handling for Swift_RfcCompliance Exception

### ISSUE THREAD

**Issue by crmpicco** [swiftmailer/swiftmailer#773]
I have found an issue with the exception handling in `MailboxHeader`. When a non RFC-compliant email address is passed in it throws a Swift_RfcCompliance exception, however this is not handled within the SwiftMailer code that I can see.

```
    /**
     * Throws an Exception if the address passed does not comply with RFC 2822.
     *
     * @param string $address
     *
     * @throws Swift_RfcComplianceException If invalid.
     */
    private function _assertValidAddress($address)
    {
        if (!preg_match('/^'.$this->getGrammar()->getDefinition('addr-spec').'$/D',
            $address)) {
            throw new Swift_RfcComplianceException(
                'Address in mailbox given ['.$address.
                '] does not comply with RFC 2822, 3.6.2.'
                );
        }
    }
```

It would seem that SwiftMailer should handle this exception here (maybe?)

```
    /**
     * Set the to addresses of this message.
     *
     * If multiple recipients will receive the message an array should be used.
     * Example: array('receiver@domain.org', 'other@domain.org' => 'A name')
     *
     * If $name is passed and the first parameter is a string, this name will be
     * associated with the address.
     *
     * @param mixed  $addresses
     * @param string $name      optional
     *
     * @return Swift_Mime_SimpleMessage
     */
    public function setTo($addresses, $name = null)
    {
        if (!is_array($addresses) && isset($name)) {
            $addresses = array($addresses => $name);
        }

        if (!$this->_setHeaderFieldModel('To', (array) $addresses)) {
            $this->getHeaders()->addMailboxHeader('To', (array) $addresses);
        }

        return $this;
    }
```

I can of course catch this exception in my application, but this seems sub-optimal as I believe this should be handled within Swiftmailer at a lower level.

Do you accept pull requests as I believe this issue could be resolved fairly easily?

I have seen "answers" on StackOverflow like this (http://stackoverflow.com/a/9094044/691505) however commenting out the exception doesn't seem right.

**Comment by xdecock** [comment]
why should swiftmailer handle it you probably want to know the mail won't
be sent?

On Wed, Jul 6, 2016 at 7:50 AM, Craig R Morton <notifications@github.com>
wrote:

> I have found an issue with the exception handling in MailboxHeader. When
> a non RFC-compliant email address is passed in it throws a
> Swift_RfcCompliance exception, however this is not handled within the
> SwiftMailer code that I can see.
>
>     /**
>      * Throws an Exception if the address passed does not comply with RFC 2822.
>      *
>      * @param string $address
>      *
>      * @throws Swift_RfcComplianceException If invalid.
>      */
>     private function _assertValidAddress($address)
>     {
>         if (!preg_match('/^'.$this->getGrammar()->getDefinition('addr-spec').'$/D',
>             $address)) {
>             throw new Swift_RfcComplianceException(
>                 'Address in mailbox given ['.$address.
>                 '] does not comply with RFC 2822, 3.6.2.'
>                 );
>         }
>     }
>
> It would seem that SwiftMailer should handle this exception here (maybe?)
>
>     /**
>      * Set the to addresses of this message.
>      *
>      * If multiple recipients will receive the message an array should be used.
>      * Example: array('receiver@domain.org', 'other@domain.org' => 'A name')
>      *
>      * If $name is passed and the first parameter is a string, this name will be
>      * associated with the address.
>      *
>      * @param mixed  $addresses
>      * @param string $name      optional
>      *
>      * @return Swift_Mime_SimpleMessage
>      */
>     public function setTo($addresses, $name = null)
>     {
>         if (!is_array($addresses) && isset($name)) {
>             $addresses = array($addresses => $name);
>         }
>
>         if (!$this->_setHeaderFieldModel('To', (array) $addresses)) {
>             $this->getHeaders()->addMailboxHeader('To', (array) $addresses);
>         }
>
>         return $this;
>     }
>
> I can of course catch this exception in my application, but this seems
> sub-optimal as I believe this should be handled within Swiftmailer at a
> lower level.
>
> Do you accept pull requests as I believe this issue could be resolved
> fairly easily?
>
> I have seen "answers" on StackOverflow like this (
> http://stackoverflow.com/a/9094044/691505) however commenting out the
> exception doesn't seem right.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/773>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AADCfTfFQYJuDz09bnfzDoDiSOiTfbFeks5qS0IegaJpZM4JFxgu>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by crmpicco** [comment]
@xdecock Yes, I would like to know the mail won't be sent however it would be nice if there was a way that this was handled a bit more gracefully rather than having to catch a `Swift_RfcComplianceException` everywhere I call `setTo`. An option to fail silently would be nice as it's not always necessary to know that an email won't be sent and I don't always want to have to either do something with the exception or end up with this uglyness:

```
} catch (Swift_RfcComplianceException $e) { 
// do nothing 
}
```

**Comment by ChristianTheMinery** [comment]
What I don't personally understand, is why Swiftmailer has this check so... hardcoded, into it. It clearly blocks perfectly valid emails and has done so for years, which is a HUGE problem. Disabling this check ought to be something that can be passed from the send function itself, if so desired. As it stands, without modifying the source code of the mailer itself, there is NO way to bypass the exception and send to a valid email address anyway. The most one can do is catch the exception and do nothing or log the error. The option to bypass the overly-strict check entirely needs to be there.
