### ISSUE TITLE
prevent fatal error in FileSpool.php when unserializing of message fails

### ISSUE THREAD

**Issue by sneakyvv** [swiftmailer/swiftmailer#782]
FileSpool.php line 166-172:

`if (rename($file, $file.'.sending')) {
    $message = unserialize(file_get_contents($file.'.sending'));

```
$count += $transport->send($message, $failedRecipients);

unlink($file.'.sending');
```

  } else {`

When the unserialize fails $message becomes FALSE. If this is passed to the send() of a 
SendmailTransport.php which expects a Swift_Mime_Message, then a fatal error is thrown

> Catchable Fatal Error: Argument 1 passed to Swift_Transport_AbstractSmtpTransport::send() must be an instance of Swift_Mime_Message, boolean given [...]

This can be avoided by checking if the message is not FALSE before calling send (and deleting the '.sending'-file).

**Comment by JHGitty** [comment]
Can somebody review this? My logs are full of this error and I have no idea how I can prevent it. Is there a workaround?

**Comment by NathanVss** [comment]
I'm facing the same error, and I don't know why ..
