### ISSUE TITLE
V3 Documentation

### ISSUE THREAD

**Issue by wayneljw** [swiftmailer/swiftmailer#796]
Dear Developer,

I am still using the old SwiftMailer v3.3.1
May I know where I can find the documentation for the old version?

http://swiftmailer.org/wikidocs/v3 seems inaccessible now.

thanks.

**Comment by sstok** [comment]
Swiftmailer v3.3.3 was released, 26th March 2008. That's 8 years ago! In the meantime many improvements have been made and a ton of (security) bugs have been fixed.

Swiftmailer v5 is much more easy to use and provides the latest security fixes.
Using software this old yields a number of problems, I even believe v3 used PHP 4 😅 which means you are using a version that is end of maintenance, and has not been updated with security fixes for over 3 years.

Please upgrade to the latest version, supporting versions this old is just not worth it.

**Comment by jslegers** [comment]
What about version v5.0.0?

Is the documentation for v5.4.9 still available somewhere? I can't find it anywhere.

v5.4.9 is the latest version of SwiftMailer that still supports PHP 5, so at least that version is still relevant for projects where PHP 7 is not an option.
