### ISSUE TITLE
Type hinting in phpdoc @returns is too strict

### ISSUE THREAD

**Issue by ABM-Dan** [swiftmailer/swiftmailer#801]
Example:

``` php
$message = new \Swift_Message();
// setSender method defined in \Swift_Mime_SimpleMessage,
$message->setSender('foo@example.com')
// the addPart method won't be hintable,
// because the previous method claims to be returning a \Swift_Mime_SimpleMessage, object
   ->addPart('<p>html content<p>');
```

This gets even worse if someone extends \Swift_Message.

Created a PR https://github.com/swiftmailer/swiftmailer/pull/800

(Don't know why the code is failing, I didn't touch anything near those files)

**Comment by fabpot** [comment]
Closing as the PR was merged a long time ago.
