### ISSUE TITLE
introduce a way to programatically disable the check _assertValidAddress in 

### ISSUE THREAD

**Issue by domnulnopcea** [swiftmailer/swiftmailer#810]
Hi,

we have to introduce a way to disable the valid address check.

now what we do is to comment the code in the composer package. every update of swiftmailer will overwrite that 

gitlab.com is doing this also
https://gitlab.talview.com/resources/swiftmailer/commit/15b9ca896a2b4efb72cf0e7a9cead3a09536f3c7?view=parallel

thanks

**Comment by voku** [comment]
Why do you need to comment out this check? Can't we fix this?

-> I also had problems with IDN domains and emoji in e-mail addresses, so I implemented a simple non RFC-valid check for this via https://github.com/voku/email-check/ with this commit https://github.com/voku/swiftmailer/commit/9be14951f638558a36c269b80da7bc9d187eae4d#diff-42584800e90c6d14774ed317b27bd069R346

**Comment by domnulnopcea** [comment]
I need to comment it in order to send the email to addresses that do not pass the validation check

**Comment by domnulnopcea** [comment]
any news here?

**Comment by fabpot** [comment]
fixed in master

**Comment by domnulnopcea** [comment]
Hi,
this https://github.com/swiftmailer/swiftmailer/pull/815/files is not fixing the issue.

it just removes a preg_match call with the Egulias\EmailValidator\EmailValidator implementation.

There should be provided a way to configure swiftmailer to skip this check all together.

big projects like gitlab are doing this but it prevents us from easily upgrading swiftmailer!
