### ISSUE TITLE
System Requirements should list "PHP 5.3 or higher" instead of "PHP 5.2 or higher"

### ISSUE THREAD

**Issue by drbraden** [swiftmailer/swiftmailer#811]
The web page at "http://swiftmailer.org/docs/overview.html" should list PHP 5.3 as a requirement (currently says 5.2).  Issue #771 replaced "`dirname(__FILE__)`" with "`__DIR__`", which wasn't introduced until version 5.3.

**Comment by fabpot** [comment]
fixed
