### ISSUE TITLE
Email body repeating since release 4.0.6

### ISSUE THREAD

**Issue by swiftmailer** [swiftmailer/swiftmailer#82]
Let me start by saying I love SwiftMailer.  Awesome product.  Have used this now for years.  We have sent millions of messages using SwiftMailer.

Problem:  We send out over 20,000 HTML messages per day using SwiftMailer using two different servers.  One server (Mail1) has been upgraded to 4.0.6 the other (Mail0) is on the prior release.  In some cases, instances of a message are received with part of the message body repeating after the "end" of the original message body.

In all cases with repeating content the final HTML tag is not closed and the repeating content begins after that.  The additional content is a repeat of the original content split  just after an MS Word character like a Smart quote or a curly apostrophe.  Imagine using the result from list($junk,$repeatingcontent)=explode('microsoft smart quote',$messagebody,2) .  The $repeatingcontent is then added to the end of the document.  The final HTML tag is not closed and the same explode is done on $repeatingcontent until nothing is left and the message finally ends.

MS Word characters in the message body appear to be the cause however, this has been a tough bug to track down as it is not happening in all messages.  I receive many of the messages myself and have only one instance of such a message arriving in my inbox whilst other recipients of the same message have the problem occuring in their copy

Originally I suspected email client problems and badly formed HTML tables in the message.  I have eliminated all of these possibilities over a period of several weeks.

I started logging every message body after we had loaded it into SwiftMailer with the personalisation all in place to ensure it was nothing I was doing in my loop.  There was not one instance at my end.

After logging enough of these events I could compare the original HTML, my log of what was loaded into swift and check which server was used.  This is when I noticed that the old version on Mail0 was not causing the issue.

With more substantial series of tests I confirmed this and finally received a copy of a message with the issue from an email message I had instigated.  The issue was repeatable and identical and only accured when using SwiftMailer 4.0.6.

Once I had a copy that I could repeat the bug (sending one proof message at a time) that came to my inbox I could look at the received code and find the MS Word character link.

I will make these characters safe as a probable workaround however it might be something to look at at your end also.

I would have attached the files however they are too large for this service.  I can provide if required.

Thanks in advance.

Mark

Original creation date: 2010-03-07T13:19:58Z
Original reporter: Mark
Original ticket: http://swiftmailer.lighthouseapp.com/projects/21527/tickets/139

**Comment by vidilab** [comment]
The problem of duplication of content seems to be still present in the current version. Short example to reproduce:

$body = "<p>Anything<p>2\xB0C<p>1\xB0C<p>5\xC2\xB0C";
$msg->setBody($body,'text/html');

This produces the following (note the duplication).

<p>Anything<p>2?C<p>1=B0C<p>5=C2=B0C<p>1?C<p>5=C2=B0C

I've seen it only happen for invalid UTF-8 characters. Setting a character set ($msg->setCharset('iso-8859-1');) fixes the duplication, but then UTF-8 characters of course do not display anymore.
