### ISSUE TITLE
Settings Content-Transfer-Encoding multiple times during S/MIME encryption

### ISSUE THREAD

**Issue by func0der** [swiftmailer/swiftmailer#822]
I have a multipart message with a simple plain text part and an attachment, which is base64 encoded.

In the SMimeSigner::signMessage() the encoder for raw encoding is added.

The resulting headers contain three "Content-Transfer-Encoding" entries:

```
Content-Type: application/x-pkcs7-mime; smime-type=enveloped-data;
 name="smime.p7m"; charset=utf-8
Content-Transfer-Encoding: raw
Content-Transfer-Encoding: raw
Content-Transfer-Encoding: base64
```

I could not find anything prohibited about the three time usage of "Content-Transfer-Encoding", but it says `Unlike Content-Types, a proliferation of Content-Transfer-Encoding values is undesirable and unnecessary.` (http://www.freesoft.org/CIE/RFC/1521/5.htm)
Also that might be the reason PXI firewalls with deep inspection do reject sending those emails (not proven to be a valid statement, but the only thing we could come up with, since the unencrypted email had only one per part).

Is this a known bug or maybe even intended behavior?

**Comment by liberpater** [comment]
I encountered the same bug, though i found it in a round-about way.  #834
