### ISSUE TITLE
Issue with single quotes/apostrophes on Exim4/Debian when escaping arguments for extraParams

### ISSUE THREAD

**Issue by jamesggordon** [swiftmailer/swiftmailer#824]
SwiftMailer correctly identifies email addresses with single quote/apostrophes in the local part as valid email addresses (eg. paul.o'brien@example.com) and allows them as "To" addresses and "From" addresses.

However, if I set the from address to an address that has a single quote/apostrophe in the local part of the "From" address when using Exim4 as my MTA, I get an error (exim: bad -f address... malformed address). The problem does not occur on OS X (postfix) but does occur on Debian with Exim4. (The reason I want to set the from address is because I'm using VERP to encode the recipient address into the from address so that I can handle bounces in an automated fashion.)

The problem is that the `_formatExtraParams()` method in the `MailTransport` class escapes the arguments to prevent a potential security issue. Full details can be found in issue #520.

However, the escaped output, which looks something like this, causes the malformed address error with Exim4:

    -f'paul.o'\''brien@example.com'

Interestingly, if you remove the call to `escapeshellarg()` you get this, which works:

    -fpaul.o'brien@example.com

I am at a bit of a loss as to how to resolve this issue. Although I have 99% control over the email addresses in the database, I still don't want to remove the call to `escapeshellarg()` due to the security risks, but I'm unsure as to how I can convince it to produce output that is compatible with Exim4.

**Comment by jamesggordon** [comment]
**UPDATE**

I have triple-checked the code and it turns out that regardless of how you set the return path (`setFrom()`, `setSender()` or `setReturnPath()`), it is not actually possible to provide a malformed address, because SwiftMailer validates all relevant headers. So the two calls to `escapeshellargs()` will *never actually be invoked with the kind of input that they are defending against*, since it is impossible to set a return path that has an invalid address. The space character alone is enough to render the address invalid and as soon as you remove the spaces the string no longer works as a valid command line argument.

If you would like to test this hypothesis, try this code:

    require_once 'vendor/swiftmailer/swiftmailer/lib/swift_required.php';
    
    $from1 = 'testing@gmail.com';
    $from2 = 'testing@gmail.com -OQueueDirectory=/tmp -X /var/www/html/malicious.php';
    
    $message = Swift_Message::newInstance()
                            ->setSubject('Test email')
                            ->setFrom($from1)
                            ->setSender($from1)
                            ->setReturnPath($from2)
                            ->setTo(['support@genos.net'])
                            ->setBody('Here is the message itself');
    
    Swift_Mailer::newInstance(Swift_MailTransport::newInstance())->send($message);

All three methods that set the `from` address will cause the message construction to fail if you use `$from2`.

So adding the calls to `escapeshellarg()` has effectively achieved no increase in security whatsoever but has degraded the functionality, as you can no longer set a `from` address using any of the methods above if that address contains a single quote/apostrophe, which is a **valid** character in the local part of an email address.

The original impetus for adding `escapeshellarg()` came from the OP of #520, who said "I think the MailTransport is vulnerable to this issue" and "As far as i can see, calls to `setFrom()` are not validated for correct RFC email format." It is unfortunate that nobody took the time to test the assertion in the second statement, as that assertion is, at least in the current version of the code, false.

@fabpot Would you be happy for me to create a PR to remove the calls to `escapeshellarg()` as long as I add some tests for the malicious `from` address shown above?

**Comment by jamesggordon** [comment]
Having posted that long-winded comment, I'm now thinking that the real culprit is somewhere between PHP and Exim4. It should be completely valid to pass a quote-escaped parameter to `mail()` and one should be able to assume that `mail()` will then dutifully pass this parameter to the underlying mail transport, which should be capable of picking up the quote-escaped argument and dealing with it properly. So after all that, I have decided to close this issue.

**Comment by jamesggordon** [comment]
OK, I have more information about this issue!

Whilst it is correct that `SwiftMailer` escapes the arguments when invoking `sendmail` (ie. in `SendmailTransport.php`), it should **not** escape the arguments when calling PHP's `mail()` function in `MailTransport.php` because the `mail()` function is already escaping the arguments. This explains why Exim4 complains when using a `from` address with a single quote - because `SwiftMailer` is escaping the arguments and then the arguments are getting escaped *again* by the `mail()` function.

For proof that the PHP interpreter is escaping the arguments see: https://github.com/php/php-src/blob/master/ext/standard/mail.c#L369

The solution to resolve this issue is to reverse this change: https://github.com/c960657/swiftmailer/commit/3d374ac67cea4bde2f071bd663b97cfe6d7c4fb2

@fabpot Would you like me to make that change or are you happy to do it yourself?

**Comment by fabpot** [comment]
@jamesggordon Thank you so much for your work on this one. I have just opened a PR to fix this (#829).

**Comment by jamesggordon** [comment]
You are a legend! I tested the change and it works perfectly. Thanks for looking after the PR.

**Comment by fabpot** [comment]
Just released a new version with the fix.
