### ISSUE TITLE
501 HELO requires valid address

### ISSUE THREAD

**Issue by ashishrawat417** [swiftmailer/swiftmailer#836]
Started this issue few days back. I don't see any good documentation to debug this issue. 
I am using yii2-swiftmailer.
![2016-12-07_1209](https://cloud.githubusercontent.com/assets/2182791/20957499/36c71c48-bc76-11e6-8105-9e24f6c55a1b.png)

**Comment by arturmamedov** [comment]
How to solve? I get this with Laravel 5.5 and PHP 7.3
