### ISSUE TITLE
header encoding problem

### ISSUE THREAD

**Issue by swiftmailer** [swiftmailer/swiftmailer#84]
Add the following e-mail address to a message (the utf-8 char is important!):

"Berntsen, Pål" Berntsen@intermesh.dev

Swift will create the following header string:

To: Berntsen, =?utf-8?Q?P=C3=A5l?= Berntsen@intermesh.dev

Now if you send this with postfix it will rewrite this header to:

To: Berntsen@Intermesh-1, =?utf-8?Q?P=C3=A5l?= test@intermesh.dev

The problem lies in the comma and the separated encoded string. I fixed this by always encode the entire name when encoding is needed in any part of the string.

I changed this function in Mime/Headers/AbstractHeaders.php:

protected function getEncodableWordTokens($string)
  {
    $tokens = array();

```
$encodedToken = '';
//Split at all whitespace boundaries
```

//Fix: don't split the string for this bug.

```
//foreach (preg_split('~(?=[\t ])~', $string) as $token)
    $token=$string;
{
  if ($this->tokenNeedsEncoding($token))
  {
    $encodedToken .= $token;
  }
  else
  {
    if (strlen($encodedToken) > 0)
    {
      $tokens[] = $encodedToken;
      $encodedToken = '';
    }
    $tokens[] = $token;
  }
}
if (strlen($encodedToken))
{
  $tokens[] = $encodedToken;
}

return $tokens;
```

  }

I hope you'll fix this problem too!

Original creation date: 2010-06-14T13:47:31Z
Original reporter: aleksblendwerk
Original ticket: http://swiftmailer.lighthouseapp.com/projects/21527/tickets/150

**Comment by bytestream** [comment]
Came across this issue again, after switching to RFC 2047. This time when using `@` in the display name of From header.

RFC 2047
> Other characters are also illegal in certain contexts.  For example, an 'encoded-word' in a  'phrase' preceding an address in a From header field may not contain any of the "specials" defined in RFC 822.

RFC 822 
>>>
            specials    =  "(" / ")" / "<" / ">" / "@"  ; Must be in quoted-
                        /  "," / ";" / ":" / "\" / <">  ;  string, to use
                        /  "." / "[" / "]"              ;  within a word.
>>>

Seems to me like any `specials` characters in the UTF-8 encoded string need to be stripped out? Or have I misinterpreted that?
