### ISSUE TITLE
Any idea what causes this error:

### ISSUE THREAD

**Issue by cretace** [swiftmailer/swiftmailer#849]
PHP Fatal error:  Uncaught exception 'Swift_TransportException' with 
message 'Expected response code 250 but got code "550", with message "550 
5.7.1 Command rejected

It's triggered from a cron script.  
The site moved to a new server about one month ago but the cron email was all ok up till now.
Other emails got sent correctly from the same cron, directly after this error message, so PHP cannot have suffered a "fatal errror". 
Any ideas what this might indicate?
Thanks

**Comment by ponasromas** [comment]
Update to latest SM version and provide code piece witch sends email.
