### ISSUE TITLE
Gmail tags messages sent via SwiftMailer as Spam/ Hotmail completely rejects mail

### ISSUE THREAD

**Issue by arturroesch** [swiftmailer/swiftmailer#852]
Hey folks,
i have trouble getting SwiftMailer to work properly. Even though DKIM and SPF are configured correctly, Gmail always tags mails sent via SwiftMailer as Spam. The only (probably) anomaly I detected is the following line in the mail header:
`Received: from [127.0.0.1] (www.mydomain.de [12.51.163.193])
	by mydomain.de (Postfix) with ESMTPA id 8E72E60D42
	for <mymail@googlemail.com>; Fri, 30 Dec 2016 21:03:23 +0100 (CET)`

Any ideas, help or hints from similar problems are appreciated. 
Cheers!

**Comment by StudioMaX** [comment]
Try to test your message here: https://www.mail-tester.com/
