### ISSUE TITLE
have error in new 

### ISSUE THREAD

**Issue by vahidalvandi** [swiftmailer/swiftmailer#854]
installed swiftmailer with composer and call it with 
	$mailer = new \Swift_Mailer();

but i have bellow error

 Argument 1 passed to Swift_Mailer::__construct() must be an instance of Swift_Transport, none given,

**Comment by sstok** [comment]
http://swiftmailer.org/docs/messages.html
http://swiftmailer.org/docs/sending.html

The documentation should be updated to give example directly as currently there is no direct "Call to action" for the visitor.

**Comment by vahidalvandi** [comment]
i use composer and autoload

i fixed it


    //Create the Transport.
	$transport = \Swift_SmtpTransport::newInstance('smtp.dsdsddsd.ir', 587, 'tls')
		->setUsername('noreply@dddddd.ir')
		->setPassword('iFv0(dsd=r')
		->setStreamOptions(array(
			'ssl' => array(
				'verify_peer' => false,
				'verify_peer_name' => false,
				'allow_self_signed' => true
			)
		)
		);

**Comment by sstok** [comment]
If it's fixed please close this issue then 👍
