### ISSUE TITLE
Fixing typos in documentation

### ISSUE THREAD

**Issue by noplanman** [swiftmailer/swiftmailer#858]
What is the best way to submit typo corrections for the documentation?

I hope typos don't have to be reported 1 by 1...

`When using OpenSSL this can done by the including the -addtrust emailProtection parameter when creating the certificate.`
should be
`When using OpenSSL this can be done by including the -addtrust emailProtection parameter when creating the certificate.`

**Comment by fabpot** [comment]
The best way is to submit a pull request on the 5.x branch with all typos you found fixed.

**Comment by noplanman** [comment]
Right!

(How blind of me to miss the `doc` folder... :grin:)
