### ISSUE TITLE
Adding sign and encrypt certificates by text

### ISSUE THREAD

**Issue by noplanman** [swiftmailer/swiftmailer#859]
Is it possible to set the sign and encrypt certificates by text input instead of just the path to a key file?

I have the situation where the keys are stored in the database and would like to make use of that, instead of having to save them to some temporary folder first and removing them again afterwards.

For that I'd also have to make sure to write into a safe folder where the private keys can't be leaked in some way.

Any suggestions?

I was thinking `setSignCertificateFromText` and `setEncryptCertificateFromText` or something like that.

**Comment by sstok** [comment]
The current implementation relies heavily on `file://`, it should be possible to make this work.
But I know from experience OpenSSL can be very picky on what's accepted, and not helping you on why it's not accepted...

https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/Signers/SMimeSigner.php would have to be rewritten to accept strings (which I remember is not supported) or use a `memory` stream http://php.net/manual/en/wrappers.php.php, although I'm not aware of how deep this is implemented (properly not as this API is anything but developer friendly 😑).

If this is not possible you can choose to encrypt the private key and pass a password with the method call https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/Signers/SMimeSigner.php#L90

**Comment by noplanman** [comment]
Ok, since it isn't possible to sign/encrypt with PGP keys, I'll close off here, as that's what I'm looking for.

@sstok Thanks for your reply and explanation!
