### ISSUE TITLE
PGP encrypting emails (feature request)

### ISSUE THREAD

**Issue by noplanman** [swiftmailer/swiftmailer#861]
How does PGP encryption work?

I have my public key saved on the server, the path is in the variable `$pubkey_file`.

This is what I have:
```php
$signer = Swift_Signers_SMimeSigner::newInstance();
$signer->setEncryptCertificate( $pubkey_file );
$message->attachSigner( $signer );
```

But when I try this I get the error below.
```
ERROR: Swift Mailer: Failed to encrypt S/Mime message. Error: "error:0906D066:PEM routines:PEM_read_bio:bad end line".
ERROR: Error while sending email!
```
The key I'm using is my PGP public key which can be found here: https://noplanman.ch/pgp.asc

Am I doing something wrong or did I misunderstand the `setEncryptCertificate` method?

**Comment by quantumpacket** [comment]
> The certificate and private key must be PEM encoded, and can be either created using for example OpenSSL or obtained at an official Certificate Authority (CA).

Someone correct me if I am wrong, but it doesn't appear to be for PGP keys, but for SSL certificates. If you want PGP encrypted messages I'd check out using https://github.com/pear/Crypt_GPG in conjunction with Swiftmailer.

**Comment by noplanman** [comment]
Oh, well that makes sense then.

In which case this issue has now been converted into a feature request 😃

**Comment by Rotzbua** [comment]
Well there is a request already: #737

And here another:
https://github.com/Mailgarant/switfmailer-openpgp

**Comment by noplanman** [comment]
@Rotzbua Awesome, thanks! Will have a look at that 👍
