### ISSUE TITLE
problem sending large mails (>1200000bytes)

### ISSUE THREAD

**Issue by swiftmailer** [swiftmailer/swiftmailer#88]
Sending one mail with no attaches, only one html part, to only one recipient fails if mail has more than 1.2mbytes (aproximate numbers). It fails when using sendmail or smtp transport.

I'm getting memory exhaustion (after tracing for an hour) in the following trace:

CharacterReader/Utf8Reader.php:function getCharPositions:line 136
 /\* Ok we got a complete char here */
$lastChar=$currentMap['p'][$charPos+$foundChars]=$startOffset+$i+$size;

Called from:

CharacterStream/NgCharacterStream.php:function write

$this->_charCount += $this->_charReader->getCharPositions(substr($this->_datas, $this->_datasSize), $this->_datasSize, $this->_map, $ignored);

Looks like getCharPositions is requesting more than 128mb (the memory limit) when parsing a 1.2mb html mail.

Is this correct? Is there any solution? 

Thanks in advance!

Original creation date: 2010-11-27T19:17:31Z
Original reporter: diego
Original ticket: http://swiftmailer.lighthouseapp.com/projects/21527/tickets/168

**Comment by amirshakya2010** [comment]
Any update in this issue ?
