### ISSUE TITLE
Message: Class 'Swift_SmtpTransport' not found [COMPOSER]

### ISSUE THREAD

**Issue by quentingosset** [swiftmailer/swiftmailer#887]
After download  swiftmail with composer, i include my vendor/autoload.php and when i launch my script i have this message : Message: Class 'Swift_SmtpTransport' not found

**Comment by leavasco** [comment]
Same here.

SwiftMailer doesn't has a namespace, so you should instantiate your SmtpTransport like if it were in the global space.
So, just add '\' in the beginning of the name class.
Ex: $transport = \Swift_SmtpTransport::newInstance('smtp.example.org', 25);

You can read more in http://php.net/manual/en/language.namespaces.global.php
