### ISSUE TITLE
How to get fail reason for a mail?

### ISSUE THREAD

**Issue by karpy47** [swiftmailer/swiftmailer#891]
I need to understand the failure reason and not just what email addresses that failed.
Couldn't find any info how so I'm using this hack:

In file: swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:422

Uncomment a line and add as below:

    // $failedRecipients[] = $forwardPath;
    $failedRecipients[] = ['email' => $forwardPath, 'code' => $e->getCode(), 'message' => $e->getMessage()];  

Now when sending a mail:
 
    $mailer->send($message, $failures);

The variable $failure will contain more info than just the email. Even though it solves my problem temporarily, it's not a good solution. I would really like to see a better way to get that failure info .

**Comment by jstanden** [comment]
`$mailer->send()` throws `Swift_TransportException` or `Swift_RfcComplianceException` when the message fails to send for either reason.

In the `catch($e) {...}` block you can use `$e->getMessage()` to get the error message.

**Comment by JorisVanEijden** [comment]
> `$mailer->send()` throws `Swift_TransportException` or `Swift_RfcComplianceException` when the message fails to send for either reason.

No it does not. It just provides a list of addresses that failed.
Exceptions are swallowed silently in \Swift_Transport_AbstractSmtpTransport::_doMailTransaction()
