### ISSUE TITLE
Swiftmailer and php7 full support ?

### ISSUE THREAD

**Issue by arena94** [swiftmailer/swiftmailer#892]
hereattached warnings / errors i got from last ver (5.4.5 i guess)  with a php compatibility checker

[swiftmailer php 7 check.txt](https://github.com/swiftmailer/swiftmailer/files/835376/swiftmailer.php.7.check.txt)

thank you for your answers

**Comment by arena94** [comment]
Not sure scan was complete, found another one

[clone.txt](https://github.com/swiftmailer/swiftmailer/files/835383/clone.txt)

**Comment by Rotzbua** [comment]
Look at: https://github.com/swiftmailer/swiftmailer/blob/5.x/composer.json
The minimum required php version is 5.3.3. So of course there are a lot of deprecated stuff is used.

Is there a bug you found with php7? I want to migrate soon to php7.x..

**Comment by arena94** [comment]
Thank you for your answer,

I am developping plugins for WordPress but i am new to github so forgive me any misunderstanding or mistake.

I just updated my dev environnement to php 7.0.16 yesterday and try to migrate my plugins to php 7.

May be it could be a good idea to create a fork, something like Swiftmailer ver 7.x for php 7.x .

Do we have to ask to @fabpot ?

**Comment by arena94** [comment]
apparently not so much to do ... 

INI directives 'magic_quotes_runtime' & 'safe_mode' are deprecated in PHP 5.3 so i just commented them

[php7_INI_directives.txt](https://github.com/swiftmailer/swiftmailer/files/836207/php7_INI_directives.txt)

But for this error : 
FILE: classes/Swift/Transport/Esmtp/Auth/NTLMAuthenticator.php
 528 | ERROR | Bitwise shifts by negative number will throw an ArithmeticError in PHP 7.0

the code is 
<
    protected function uRShift($a, $b)
    {
        if ($b == 0) {
            return $a;
        }

        return ($a >> $b) & ~(1 << (8 * PHP_INT_SIZE - 1) >> ($b - 1));
    }
>
may be just testing <if ($b <= 1)> but not an expert !

**Comment by arena94** [comment]
so far, so good

first simple test is ok !

**Comment by arena94** [comment]
So here are the issues detected :

[PHP 7 Compatibility Checker.txt](https://github.com/swiftmailer/swiftmailer/files/840731/PHP.7.Compatibility.Checker.txt)

and here are the modif i made

[old_new_diff.txt](https://github.com/swiftmailer/swiftmailer/files/840733/old_new_diff.txt)

i send about ten mails right now and have no notable issues ... still testing

**Comment by Rotzbua** [comment]
@arena94 Just informational: If you make an pull request, do it to branch `master`. `master` would be the next release 6.x which target php >=5.5 (according to composer.json). Then it would be suitable to drop the deprecated functions you mentioned above.

**Comment by arena94** [comment]
ok
