### ISSUE TITLE
[Question] Can we add custom email address to setFrom() function?

### ISSUE THREAD

**Issue by Zuhayer** [swiftmailer/swiftmailer#895]
Can we set the setFrom() email address to some custom email address, but still be able to recieve email to the email address defined in config.yml?

`    mailer_transport: gmail`
   ` mailer_host: 127.0.0.1`
  **`  mailer_user: devclan@gmail.com`**
`    mailer_password: ~`

`$message = \Swift_Message::newInstance()`
                   `      ->setSubject('test')`
**`->setFrom('hello@new-email.com')`**
                   `      ->setTo('user@gmail.com')`
                       `  ->setBody($this->renderView('email.html.twig'), 'text/html')`
`;`

**Comment by jamesggordon** [comment]
I can't see any reason why you wouldn't be able to call setFrom() and set the "from" address to anything you like.

**Comment by Zuhayer** [comment]
setFrom() is working fine in my project with Synfony 3.1 .. but is not working for me in an older project with Symfony 2.3 :( ..

In the older project it shows the email which I have sent un mailer_user param, instead of the one in setFrom().

**Comment by jamesggordon** [comment]
Sounds like it isn't a SwiftMailer issue - more like a question for the Symfony folks.

You could always try stepping through your code with a debugger to find out what part of Symfony is hijacking the email and/or you could temporarily alter SwiftMailer's setFrom() method to throw an exception if it gets called with the address from the config. That way you can trace back up the call stack and find out where in Symfony it is being overridden.

**Comment by Zuhayer** [comment]
@jamesggordon Thanks. I will do that.

**Comment by NadaBen** [comment]
@Zuhayer I have the same problem here, did you find exactly where is the issue ?

**Comment by Zuhayer** [comment]
@NadaBen I found that it can be done using domain emails. If i have email@mywebsite.com configured, I can set the value of setFrom() to {anyother-email}@mywebsite.com. But it can't be done using Gmail.

This is what I remember finding out.
