### ISSUE TITLE
Function Overloading DEPRECATED - consequences?

### ISSUE THREAD

**Issue by Hellek** [swiftmailer/swiftmailer#896]
Hi! Thanks for this great lib! I just started to use it and i really like it. But i have a problem with file attachments which have cyrillic names. (cyrillic setBody() works fine).

This http://swiftmailer.org/docs/installing.html#troubleshooting isn't help.

But the main question in this:
http://php.net/manual/en/mbstring.overload.php
"Warning This feature has been DEPRECATED as of PHP 7.2.0. Relying on this feature is highly discouraged."

You writing "Swift Mailer does not work when used with function overloading as implemented by mbstring (mbstring.func_overload set to 2). A workaround is to temporarily change the internal encoding to ASCII when sending an email"

What are the consequences for the Swiftmailer when this feature will be removed in next PHP versions?
Especially for non-latin languages ()

**Comment by Rotzbua** [comment]
Swiftmailer does not use the overloading function. It has problems with the function. It is positive that this feature is deprecated and removed.

**Comment by Hellek** [comment]
@Rotzbua Tnx for answer. Great!

**Comment by Hellek** [comment]
If someone interested how i solve the problem with cyrillic symbols - i transliterate file names on loading, before attaching.
As i find out this a problem of PHP, espeshially on windows. For examlpe file_exists() wont to see existed file. After some magic with iconv(), file_exists() works fine, but the name of the file, after move_uploaded_file() was tomething like ???.txt
So i prefer transliteration, then magic))
