### ISSUE TITLE
username and password not accepted

### ISSUE THREAD

**Issue by kandrejevs** [swiftmailer/swiftmailer#899]
I'm using google business account with 2-factor authentification. Created app password to use with swiftmailer and it returns

```
exception 'Swift_TransportException' with message 'Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials l132sm18098495wmd.10 - gsmtp
```

configration in laravel: 
```
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=info@me.com
MAIL_PASSWORD=qwertyuio
MAIL_ENCRYPTION=tls
```
I have tried to unlock captcha, create new password, change settings directly in mail.php configuration file, everything fails.

I also want to point out that it was working previously, it stopped at some point recently without me changing anything in configuration. Don't know exact time, issue was raised only today.

**Comment by cjburkey01** [comment]
Same issue, tried same steps to fix.

**Comment by sstok** [comment]
Unless you can provide a Swiftmailer only script it's impossible to say whats going on.
Laravel uses a special system for Swiftmailer which could cause problems with usage.
Something as shown on http://swiftmailer.org/docs/sending.html without any framework details.

Make sure your root CA file loading works properly (PHP <5.6 has know problems with this) and check if. The error may provide you with more information: https://productforums.google.com/forum/#!topic/gmail/zXfsoqWa7E8;context-place=topicsearchin/gmail/authorid$3AAPn2wQcrnE0AVT3b0g2x9_eQwtmwc-shSsDGPWohmKkVQ7AVrl9Sr-R9tY0AmDm1vQU7PIBVWEeg%7Csort:date%7Cspell:false

**Comment by vysakhcs1** [comment]
Try composer update. It may help you.

**Comment by vysakhcs1** [comment]
Try composer update. It may help you.

**Comment by Bast1onCZ** [comment]
Solved. You have to enable less secure apps in your google account settings.
