### ISSUE TITLE
How to use swiftmailer to send mail without SMTP authentication?

### ISSUE THREAD

**Issue by larryu** [swiftmailer/swiftmailer#914]
I use Laravel5.4 to send email via swiftmailer.
And my mail server seems that does not use auth.
How do I configure my smtp settings in Laravel?
Does swiftmailer support sending email without SMTP authentication?

**Comment by dmaicher** [comment]
Did you check http://swiftmailer.org/docs/sending.html ?
Simply not setting any username & password (or using `null`) should work.

**Comment by larryu** [comment]
@dmaicher Thanks. Yep, I have already figured it out. But thanks again for your reply.

**Comment by Mushood** [comment]
Commenting since this is first result from google:

In my case, I had to send an email to a local SMTP server

```
                $message = (new \Swift_Message)
                    ->setSubject('Report ')
                    ->setFrom(Your_email)
                    ->setTo(Your_destination)
                    ->setBody($body, 'text/html');
                $this->container->get('mailer')->send($message);

                $transport = $this->container->get('mailer')->getTransport();
                $spool = $transport->getSpool();
                $realTransport = new \Swift_SmtpTransport(host_of_local_smtp, port_of_smtp);
                $spool->flushQueue($realTransport);
```
Also the client smtp server was only able to send internal emails. When testing, make sure you have an internal email inbox otherwise, you can lose time trying to send an email to an external mailbox

**Comment by justnixx** [comment]
> @dmaicher Thanks. Yep, I have already figured it out. But thanks again for your reply.

How did you do it?
