### ISSUE TITLE
Create Attachment from Raw MIME Part

### ISSUE THREAD

**Issue by ThomasLandauer** [swiftmailer/swiftmailer#915]
Please include a method to add an already mime-encoded attachment to a message. The string holding the raw attachment would look like this:
````
Content-Type: image/png; name="abc.png"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="abc.png"

iVBORw0KGgoAAAANSUhEUgAABq0AAAOMCAIAAABYYG5ZAAAAAXNSR0IArs4c6QAAAARnQU1B
AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhe7P1n3L9bVd/7nsenmROS
...
````
So essentially, just bypass the magic of `Swift_Attachment`, which automatically encodes its input and adds MIME headers.

Related, but different issues:
* https://github.com/swiftmailer/swiftmailer/issues/258 wants to attach an entire raw email.
* https://github.com/swiftmailer/swiftmailer/issues/456 wants to send an entire raw email.

So, again, what I'm looking for would be something like this:
````php
$message = new \Swift_Message();
$message->setFrom(...)
  ->setTo(...)
  ->setSubject(...)
  ->setBody(...)
  ->**addRawAttachment($rawAttachment)** // with $rawAttachment being the string from above

**Comment by dmaicher** [comment]
I do something similar in my app and use this without any issues to attach an already encoded original email using the `Swift_Mime_ContentEncoder_RawContentEncoder`:

```php
$attach = \Swift_Attachment::newInstance($rawEmail, 'original.eml', 'message/rfc822');
$attach->setEncoder(new \Swift_Mime_ContentEncoder_RawContentEncoder());
