### ISSUE TITLE
501 mail from address must be same as authorization user 

### ISSUE THREAD

**Issue by swiftmailer** [swiftmailer/swiftmailer#92]
hi,
  when I used the following code to send mail via SMTP, it said '501 mail from address must be same as authorization user
'.how to send mail using different user via SMTP?

<?php

require_once 'lib/swift_required.php';

//Create the Transport the call setUsername() and setPassword()
$transport = Swift_SmtpTransport::newInstance('smtp.example.org', 25)
  ->setUsername('username')
  ->setPassword('password')
  ;

//Create the Mailer using your created Transport
$mailer = Swift_Mailer::newInstance($transport);

?>

Original creation date: 2011-03-24T01:58:18Z
Original reporter: Maciej Lisiewski
Original ticket: http://swiftmailer.lighthouseapp.com/projects/21527/tickets/189

**Comment by mckelvin** [comment]
I find this issue in google and I also find the answer to this issue in https://wiki.archlinux.org/index.php/SSMTP .

Create aliases for local usernames (optional)

```
/etc/ssmtp/revaliases
root:username@gmail.com:smtp.gmail.com:587
```

It's a solution to `ssmtp`. I guess there's a similar way for swiftmailer.
