### ISSUE TITLE
Send mail with msmtp 

### ISSUE THREAD

**Issue by rsantellan** [swiftmailer/swiftmailer#921]
I have an few installation using the php mail through msmtp to sending the emails. This a good way to always use the mail transport and don't worry about setting the credentials for each project.
But now that the Swift_Transport_MailTransport is deprecated and will be removed is there an easy way to include the msmtp program on Swiftmailer?

Regrads.

**Comment by sstok** [comment]
> Msmtp is an SMTP client with a sendmail compatible interface.

May you can use the SendmailTransport? (use `setCommand` to change the to be executed command).

**Comment by rsantellan** [comment]
@sstok That work really well! Now I have to figure it out how to use it on Symfony with the mail queue.!
Thanks a lot!
