### ISSUE TITLE
 Argument 1 passed to Swift_Transport_EsmtpTransport::__construct()

### ISSUE THREAD

**Issue by CihanAksoy** [swiftmailer/swiftmailer#932]
Hi, i getting this error with swiftmailer 6.0

I using PHP Version 7.0.15-0ubuntu0.16.04.4
 
**Argument 1 passed to Swift_Transport_EsmtpTransport::__construct() must implement interface Swift_Transport_IoBuffer, none given**

What can i do ?

**Comment by Rotzbua** [comment]
Seems to be #905 ? Provide some sample code...

**Comment by CihanAksoy** [comment]
My codes is same [this](http://swiftmailer.org/docs/introduction.html)

        ```
$transport = (new \Swift_SmtpTransport('smtp.gmail.com', 587, 'tls'))
            ->setUsername('xxx@gmail.com')
            ->setPassword('xxxx');

        $mailer = new \Swift_Mailer($transport);

        $message = new \Swift_Message('Wonderful Subject');
        $message->setFrom(['john@doe.com' => 'John Doe'])
        ->setTo(['xxxx@gmail.com'])
        ->setBody('Here is the message itself');

        $result = $mailer->send($message);
```

**Comment by CihanAksoy** [comment]
no one knows ?

**Comment by sarelvdm** [comment]
Im also getting this error. Using Swiftmailer 6 on Slim3 Framework. If I change back to version 5 then everything 100%
