### ISSUE TITLE
[Bug] Swiftm. 6.x only support tls 1.0

### ISSUE THREAD

**Issue by Rotzbua** [swiftmailer/swiftmailer#933]
### PHP constant change
STREAM_CRYPTO_METHOD_TLS_CLIENT changed from tls1.x to only tls1.0
Reference: https://secure.php.net/manual/de/function.stream-socket-enable-crypto.php#119122

### Line of code
https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Transport/StreamBuffer.php#L94

### Solution
Set option to `STREAM_CRYPTO_METHOD_TLSv1_0_CLIENT|STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT|STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT`

Better: make it changeable than hard coded

**Comment by sstok** [comment]
Related to #598 this should be configurable and I favor `STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT` as being to default (for security reasons).

**Comment by linuxonlinehelp** [comment]
1000.. Thanks, fixed my LATEST GROUPOFFICE SETUP!
