### ISSUE TITLE
SMTP transport over SOCKS5

### ISSUE THREAD

**Issue by swiftmailer** [swiftmailer/swiftmailer#94]
Would be nice to support sending emails using SMTP over a SOCKS5 proxy, just as Thunderbird does:

https://trac.torproject.org/projects/tor/wiki/TheOnionRouter/TorifyHOWTO/EMail

Original creation date: 2011-06-11T11:11:31Z
Original reporter: k.andris (at gmail)
Original ticket: http://swiftmailer.lighthouseapp.com/projects/21527/tickets/196

**Comment by atlanticmanagement** [comment]
> A socks-URL can be: {socks4|socks5}://[user[:pass]@][host[:port]]
Is there still no implemented way to use swiftmailer with a socks proxy?

How to use this?

I try to do this:
My Server -> Socks Proxy (with username & password) -> Gmail
