### ISSUE TITLE
Having a strange error "unexpected '->' (T_OBJECT_OPERATOR)"

### ISSUE THREAD

**Issue by TimurGumarov** [swiftmailer/swiftmailer#940]
Hi! Help me please with this strange thing.

Using this code:
```
require_once __DIR__.'/lib/swift_required.php';

$transport = new Swift_SmtpTransport('localhost', 25);

$mailer = new Swift_Mailer($transport);

$message = new Swift_Message("Обратная связь с сайта ManeQuest! $language")
	->setFrom(['info@timlion.ru' => 'ManeQuest'])
	->setTo(['tim@timlion.ru'])
	->setBody("Тема: $theme<br>e-mail: $email<br>Текст: $text<br>Имя/ник: $nickname")
	->setContentType('text/html');
```

End server respondes an error to me:
> Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in ... on line 45

This line is 
`->setFrom(['info@timlion.ru' => 'ManeQuest'])`

I'm looking to this and i don't know how to fix it for 4 hours. My brains are hot.

**Comment by TimurGumarov** [comment]
Sorry for my imperfect English.

**Comment by Rotzbua** [comment]
Hi, brackets are missing, already fixed in doc e.g. #929
```php
$message = (new Swift_Message("Обратная связь с сайта ManeQuest! $language"))
	->setFrom(['info@timlion.ru' => 'ManeQuest'])
	->setTo(['tim@timlion.ru'])
	->setBody("Тема: $theme<br>e-mail: $email<br>Текст: $text<br>Имя/ник: $nickname")
	->setContentType('text/html');

**Comment by TimurGumarov** [comment]
It was no brackets here too:
http://swiftmailer.org/docs/sending.html#using-the-send-method

Now I catched another error:
> Fatal error:  Uncaught ReflectionException: Class Egulias\EmailValidator\EmailValidator does not exist in /home/users/9/9175388788/domains/timlion.ru/manequest/lib/classes/Swift/DependencyContainer.php:309 Stack trace: #0 /home/users/9/9175388788/domains/timlion.ru/manequest/lib/classes/Swift/DependencyContainer.php(309): ReflectionClass-&gt;__construct('Egulias\\EmailVa...') #1 /home/users/9/9175388788/domains/timlion.ru/manequest/lib/classes/Swift/DependencyContainer.php(323): Swift_DependencyContainer-&gt;createNewInstance('email.validator') #2 /home/users/9/9175388788/domains/timlion.ru/manequest/lib/classes/Swift/DependencyContainer.php(114): Swift_DependencyContainer-&gt;createSharedInstance('email.validator') #3 /home/users/9/9175388788/domains/timlion.ru/manequest/lib/classes/Swift/DependencyContainer.php(371): Swift_DependencyContainer-&gt;lookup('email.validator') #4 /home/users/9/9175388788/domains/timlion.ru/manequest/lib/classes/Swift/DependencyContainer.php(348): Swift_DependencyContainer-&gt;lookupRecursive('email.validato in  /home/users/9/9175388788/domains/timlion.ru/manequest/lib/classes/Swift/DependencyContainer.php  on line  309

I saw en error like this here:
https://github.com/Respect/Validation/issues/390

I must write in that thread?

**Comment by Rotzbua** [comment]
Close this and open a new issue, because now we have swiftmailer v6. Don't forget to post your environment: php version, swiftmailer version, EmailValidator version and a code example. Best.
