### ISSUE TITLE
Having "Fatal error: Uncaught ReflectionException"

### ISSUE THREAD

**Issue by TimurGumarov** [swiftmailer/swiftmailer#943]
Hi! Catched this:
>Fatal error: Uncaught ReflectionException: Class Egulias\EmailValidator\EmailValidator does not exist in /.../lib/classes/Swift/DependencyContainer.php:309 Stack trace: #0 /.../lib/classes/Swift/DependencyContainer.php(309): ReflectionClass->__construct('Egulias\EmailVa...') #1 /.../lib/classes/Swift/DependencyContainer.php(323): Swift_DependencyContainer->createNewInstance('email.validator') #2 /.../lib/classes/Swift/DependencyContainer.php(114): Swift_DependencyContainer->createSharedInstance('email.validator') #3 /.../lib/classes/Swift/DependencyContainer.php(371): Swift_DependencyContainer->lookup('email.validator') #4 /.../lib/classes/Swift/DependencyContainer.php(348): Swift_DependencyContainer->lookupRecursive('email.validato in /.../lib/classes/Swift/DependencyContainer.php on line 309

My code:
```
require_once __DIR__.'/lib/swift_required.php';

$transport = new Swift_SmtpTransport('localhost', 25);

$mailer = new Swift_Mailer($transport);

$message = ( new Swift_Message("...!"))
->setFrom(['...@...' => '...'])
->setTo(['...@...'])
->setBody("...")
->setContentType('text/html') ;
```

Php version: 7.0
Swiftmailer: 6.0.2 (downloaded master-version in oficial site)
Have no EmailValidator (At least I think so. And I don't know how to check it if I have it. I installed nothing.)

**Comment by voku** [comment]
have you installed swiftmailer via composer? If not, have you installed the vendors, too?

**Comment by TimurGumarov** [comment]
Nothing more, only swiftmailer from oficial site.

**Comment by TimurGumarov** [comment]
Somebody helps me?)

**Comment by xabbuh** [comment]
How exactly did you install Swiftmailer?

**Comment by jmorales2718** [comment]
I am getting the same issue. Using swiftmailer installed through github with v7 php. It's a strange error because even when you copy the example code from [the swiftmailer documentation](http://swiftmailer.org/docs/messages.html) you still get the same error.

**Comment by Rotzbua** [comment]
http://swiftmailer.org/docs/introduction.html#installation

**Comment by AerWyn81** [comment]
Hi, seems having the same issue too.

Current version of Switmailer : 6.0.0
-> `composer require "swiftmailer/swiftmailer:^6.0"`

Current version of php : 7.0

Mail transport : 
![image](https://user-images.githubusercontent.com/22222045/26951641-35ccb84a-4ca2-11e7-83d8-a18919f01c6f.png)

Mailer : 
![image](https://user-images.githubusercontent.com/22222045/26951653-43d97d6a-4ca2-11e7-97f4-abc2f59da0c1.png)

Send message : 
![image](https://user-images.githubusercontent.com/22222045/26951692-6379f226-4ca2-11e7-9176-54ba42183fc5.png)

And the error : 

> PHP Fatal error:  Uncaught ReflectionException: Class Egulias\\EmailValidator\\EmailValidator does not exist in /home/snir/vendor/swiftmailer/swiftmailer/lib/classes/Swift/DependencyContainer.php:309\nStack trace:\n#0 /home/snir/vendor/swiftmailer/swiftmailer/lib/classes/Swift/DependencyContainer.php(309): ReflectionClass->__construct('Egulias\\\\EmailVa...')\n#1 /home/snir/vendor/swiftmailer/swiftmailer/lib/classes/Swift/DependencyContainer.php(323): Swift_DependencyContainer->createNewInstance('email.validator')\n#2 /home/snir/vendor/swiftmailer/swiftmailer/lib/classes/Swift/DependencyContainer.php(114): Swift_DependencyContainer->createSharedInstance('email.validator')\n#3 /home/snir/vendor/swiftmailer/swiftmailer/lib/classes/Swift/DependencyContainer.php(371): Swift_DependencyContainer->lookup('email.validator')\n#4 /home/snir/vendor/swiftmailer/swiftmailer/lib/classes/Swift/DependencyContainer.php(348): Swift_DependencyContainer->lookupRecursive('email.validator')\n#5 /home/snir/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Depen in /home/snir/vendor/swiftmailer/swiftmailer/lib/classes/Swift/DependencyContainer.php on line 309

AerWyn81

**Comment by jmorales2718** [comment]
@AerWyn81 

Apparently, you need the [EmailValidator](https://github.com/egulias/EmailValidator). You need composer for it, but if you are already using it then there should be no problems.

**Comment by AerWyn81** [comment]
Hi,

I'm already using it : 
![image](https://user-images.githubusercontent.com/22222045/26974570-3ee99040-4d1c-11e7-9daf-2091409adc3f.png)

And still having issue : 
![image](https://user-images.githubusercontent.com/22222045/26974616-6b561d9c-4d1c-11e7-9863-0c020bbed5a5.png)

AerWyn81

**Comment by xabbuh** [comment]
Do you use Composer's autoloader?

**Comment by AerWyn81** [comment]
How can I know if i'm using Composer's autoloader ? 

I just installed swiftmailer thanks to : `composer require "swiftmailer/swiftmailer:^6.0"`, create the php script for send email as writed in the http://swiftmailer.org/docs and it's all I think?

**Comment by jmorales2718** [comment]
You need your require path to be to the composer autoloader.php

**Comment by AerWyn81** [comment]
Like : ?
![image](https://user-images.githubusercontent.com/22222045/26975597-be39dfe0-4d20-11e7-8ea1-d00a1496d4ef.png)
Yep I don't use relative path, I know, I know..

**Comment by AerWyn81** [comment]
Ooook, so, I found a half solution.

After did my last modification, I saw this error : 
![image](https://user-images.githubusercontent.com/22222045/26976178-fb91a56a-4d22-11e7-8ae3-aa40a579557c.png)

After that, I enable `allow less secure apps access` to my gmail account and after that worked for me.
The last problem is the sender adress on the mail, it diplay the gmail account but I want to customize the sender email like "no-reply@mydomain.com" but I don't know if that is possible.

**Comment by Rotzbua** [comment]
@AerWyn81 You use a not encrypted connection to google. Your password is sent plain, so better use tls/ssl and change it.

**Comment by AerWyn81** [comment]
Mh, seems to be ok : 
![image](https://user-images.githubusercontent.com/22222045/26978446-d92efe4c-4d2b-11e7-84a2-011f6bd5fe59.png)
no?

**Comment by TimurGumarov** [comment]
Hi all.
I just downloaded from github latest master version and include it in my project.
I already used 5.0.1 version like this, it worked.

**Comment by TimurGumarov** [comment]
I used no connections to smtp in transport, i'm using "send()" method like here:
http://swiftmailer.org/docs/sending.html#using-the-send-method

**Comment by ssantu** [comment]
PHP Fatal error:  Uncaught ReflectionException: Class Egulias\\EmailValidator\\EmailValidator does not exist

I am also getting this error, and could resolved yet. I don't want  to use composer here.

After this **git clone https://github.com/swiftmailer/swiftmailer.git**, I got a folder **swiftmailer**, now I want to do "**git clone https://github.com/egulias/EmailValidator.git**". Shall I install this EmailValidator in swiftmailer folder? Please help me out. I've installed EmailValidator in swiftmailer folder but could that could not resolved  this error. Thanks

My swiftmailer folder structure is,
![screenshot from 2017-08-25 12-47-40](https://user-images.githubusercontent.com/31346079/29713013-922a4a9c-8994-11e7-83e1-0bb3f355ac5f.png)

**Comment by fabpot** [comment]
@ssnatu After cloning, you need to run `composer install` to get the dependencies.

**Comment by ssnatu** [comment]
@fabpot Thanks for the reply. I did composer install, but still error is coming.

[Fri Aug 25 14:07:29.660545 2017] [:error] [pid 12485] [client 127.0.0.1:46008] PHP Fatal error:  Uncaught ReflectionException: Class Egulias\\EmailValidator\\EmailValidator does not exist in /var/www/html/new/swift/swiftmailer/lib/classes/Swift/DependencyContainer.php:309\nStack trace:\n#0 /var/www/html/new/swift/swiftmailer/lib/classes/Swift/DependencyContainer.php(309): ReflectionClass->__construct('Egulias\\\\EmailVa...')\n#1 /var/www/html/new/swift/swiftmailer/lib/classes/Swift/DependencyContainer.php(323): Swift_DependencyContainer->createNewInstance('email.validator')\n#2 /var/www/html/new/swift/swiftmailer/lib/classes/Swift/DependencyContainer.php(114): Swift_DependencyContainer->createSharedInstance('email.validator')\n#3 /var/www/html/new/swift/swiftmailer/lib/classes/Swift/DependencyContainer.php(371): Swift_DependencyContainer->lookup('email.validator')\n#4 /var/www/html/new/swift/swiftmailer/lib/classes/Swift/DependencyContainer.php(348): Swift_DependencyContainer->lookupRecursive('email.validator')\n#5 /var/www/html/new/swift/swiftmailer/lib/classes/Swift/DependencyContainer.php(129): Swift_DependencyC in /var/www/html/new/swift/swiftmailer/lib/classes/Swift/DependencyContainer.php on line 309, referer: http://localhost/new/swift/

**Comment by xabbuh** [comment]
@ssnatu Do you use Composer's autoloader?

**Comment by ssnatu** [comment]
@xabbuh Thanks, for the reply, I am not using composer's autoloader. I'd tried using composer's autoloader (require_once 'vendor/autoload.php;) and it works fine. But I want to use swiftmailer w/o composer, Can we do that?

**Comment by xabbuh** [comment]
Yes, though I don't see why you would want to do that. Anyway, you will then need to configure your own autoloader to find the Swiftmailer classes.

**Comment by ssnatu** [comment]
@xabbuh Thanks for the reply. I'm in the middle of this and now I'm getting an errror, 

PHP Fatal error:  Class 'Doctrine\\Common\\Lexer\\AbstractLexer' not found in /EmailValidator/EmailValidator/EmailLexer.php on line 7

I've installed **lexer** (git clone https://github.com/doctrine/lexer.git) to solve this error in /EmailValidator/EmailValidator/ path but it didn't helped me.

Thanks in advance.

**Comment by xabbuh** [comment]
Well, you need to configure your autoloader for every single package that you install by cloning their git repository. Again, I don't see why you would want to do that instead of just letting Composer do that job for you.

**Comment by ssnatu** [comment]
@xabbuh In my project it is not suggested to use Composer. For that reason I've to use swiftmailer only w/o Composer. Thanks

**Comment by ssnatu** [comment]
When you are not using composer, that time you have to include the files before **swift_required.php** to solve the dependency issue.
e.g My sendemail.php file

![screenshot from 2017-09-05 10-17-54](https://user-images.githubusercontent.com/31346079/30054300-8f89d9e6-9223-11e7-9bb7-260674a878a4.png)

And my folder structure is,

![screenshot from 2017-09-05 10-19-12](https://user-images.githubusercontent.com/31346079/30054346-ba448e10-9223-11e7-90bf-b4924331f960.png)

Hope, this will help. Thanks.
