### ISSUE TITLE
How to implement a single use button for sending emails with Swiftmailer

### ISSUE THREAD

**Issue by ghost** [swiftmailer/swiftmailer#945]
I am using Symfony 2.8 and Swiftmailer 2.3 to send messages. In my Web application, there is a button used by the users to send emails (for sending requests). But I have noticed that sometimes the users clicked several times on the button during the loading of the page and it sends consequently the emails twice or more. That is why I would like to know 2 things:

- Is there a way to do a "single use button" or equivalent to avoid sending emails twice or more by clicking twice or more during the loading of the page? If I must send 4 emails by clicking on the button, I do not want to allow users to send 8 emails (4 original emails + 1 copy of each emails) or 12 emails (4 original emails + 2 copies of each emails) for example.

- If I use a "single use button" or equivalent, I would like to be sure that the emails were well sent by Swiftmailers in order not to block the sending of emails if they were not sent. It would be a problem if a user interrupts for example the loading of the page which could cancel the sending of emails and if he cannot send these emails anymore...

What is the best and most appropriate way to do that?

**Comment by Rotzbua** [comment]
Hi, github issues are used to report issues or feature requests. Please use a forum for your question or https://stackoverflow.com/ . BTW swiftmailer is a backend and has nothing to do with buttons. Best.
