### ISSUE TITLE
Archives of very old versions are unavailable.

### ISSUE THREAD

**Issue by bangpound** [swiftmailer/swiftmailer#947]
I'm looking for version 3.3.2 of Swift, which is listed [at the official web site](http://swiftmailer.org/downloads/archive) but the link target no longer exists.

I'm trying to identify what changes might have been made to this library in an application I support. If I can see the differences between the committed version and official release, I can more confidently propose an upgrade.

Is there anyway these very old versions can be acquired?

**Comment by fabpot** [comment]
Unfortunately, I'm not sure where you can get it. But you can probably get the code directly from Github.

**Comment by fabpot** [comment]
Closing as version 3 is now very old. I've just removed the archive page as all versions are now available on Github.

**Comment by fabpot** [comment]
You can get 3.3.3 here: http://swiftmailer.org/get/Swift-3.3.3-php5.tar.gz

**Comment by bangpound** [comment]
Thank you for your help!

**Comment by Flurrywinde** [comment]
This file is now zero length when I try to download it. I'm currently using 3.3.2-php4, which then broke (a long time ago) when my host upgraded to php5. Are there upgrade instructions anywhere? Much seems to have changed, and unfortunately, my health issues make it hard to devote a lot of time to programming. If there aren't, I will try to upgrade when I can, but in the meantime, is there a php5 version of the code that's compatible with my code written for the 3.3.2-php4 version?
