### ISSUE TITLE
duplicate setReturnPath in mail header

### ISSUE THREAD

**Issue by raghubirthakur** [swiftmailer/swiftmailer#949]
I am sending mail setting setReturnPath but its sending Return-Path two times.

Code snippet is pasted below

```
<?php

$transport = (new Swift_SmtpTransport('mail1.example.com', 25));
$mailer = new Swift_Mailer($transport);
$message = new Swift_Message();

$message->setReturnPath('bounceinfo@mail1.example.com');
$message->setReplyTo('noreply@sendingdomain.com');
$message->setFrom(['noreply@sendingdomain.com' => 'No Reply']);
$message->setTo(['to@email.com' => 'To']);
$message->setSubject('My amazing subject');
$message->setBody('Here is the message itself');

$result = $mailer->send($message);

?>
```

Please help me in setting return path correctly. When I am checking message headers, its coming correct. When email is sent, its headers contains two return path.

Thanks in advance.

**Comment by Rotzbua** [comment]
Maybe the additional return path is set by the smtp server? Try a different return path to check.

**Comment by raghubirthakur** [comment]
I have cross checked the similar code with phpmailer and only one return-path is added. So smtp is not adding return path.

I am using swift-mailer because its giving me power to sign dual dkim keys.

**Comment by Rotzbua** [comment]
I think you are wrong. As I can see phpmailer do not use `return-path`? And according to #384 the smtp-server should set `return-path` and not swiftmailer.

**Comment by jeetusb** [comment]
In Swiftmailer, If we use "Return-Path" explicitly as follows:

`$message->setReturnPath('return@example.com');`

it will set "Return-Path" twice else it will set one "Return-Path" derived from "From:" header.

Swiftmailer derives best return path itself. It is written in following file:

```
File Path: /swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php 
Line No: 174
```

Below is code snippet for the same.

   ```
 public function send(Swift_Mime_SimpleMessage $message, &$failedRecipients = null)
    {
      .
      .
      .

        if (!$reversePath = $this->getReversePath($message)) {
            $this->throwException(new Swift_TransportException(
                'Cannot send message without a sender address'
                )
            );
        }
```

**Comment by Rotzbua** [comment]
@jeetusb Thanks for the line of code. But this is variable is used in the end to call `$this->doMailFromCommand($reversePath);` which is a smtp command and not a swiftmailer header.

@raghubirthakur I think your receiving stmp server adds an additional `Return-Path` according to the smtp comminication `MAIL FROM:`
So you got a mail with 2 `Return-Path`:
```
Return-Path: <bounceinfo@mail1.example.com> (Generated by smtp server)
Return-Path: <bounceinfo@mail1.example.com> (Transferred by swiftmailer, because header is set manually)
```

I could not observe this behavior at my system. So it seems mail server depended.

**Comment by raghubirthakur** [comment]
Hi Rotzbua,

Have you sent a mail to you in following case as mentioned in my code.

```
$message->setReturnPath('bounceinfo@mail1.example.com');
$message->setFrom(['noreply@sendingdomain.com' => 'No Reply']);
```

return path is different and from address is different. I am trying to send Type 2 mail where sender is different but "FROM" will show sender domain address.

If I remove setReturnPath from my code, only one return-path is set and that is "sendingdomain.com".

Please try to identify from where its added automatically and how can one change it.

I appreciate for your time, and its helpful for swift-mailer community if we answer here a good solution.

Thanks.

**Comment by Rotzbua** [comment]
A good testing tool: https://www.mail-tester.com

**Comment by raghubirthakur** [comment]
Rotzbua,

Have you tried sending an email with setReturnPath?

**Comment by sneakyx** [comment]
should be updated in docu: https://swiftmailer.symfony.com/docs/messages.html#setting-the-return-path-bounce-address
See also: https://stackoverflow.com/questions/5980381/bounce-support-for-swiftmailer
