### ISSUE TITLE
6.0 is slow to send

### ISSUE THREAD

**Issue by tomsommer** [swiftmailer/swiftmailer#950]
Using the SMTP transport and localhost, Swiftmailer 6.0 starting hanging when sending mail to some addresses. It seems to be related to some DNS timeout or command sent through SMTP?

**Comment by tomsommer** [comment]
Solved, was related to DomainKeySigner and wrong \r\n

**Comment by Rotzbua** [comment]
@tomsommer You still use DomainKeySigner? I thought DKIM obsoletes the DomainKey-stuff?

**Comment by tomsommer** [comment]
I use both Swift_Signers_DKIMSigner and Swift_Signers_DomainKeySigner

**Comment by Rotzbua** [comment]
Ok, but that's not the answer for my question. I asked why you use domainkey, because dkim replaces domainkey.
I think the domainkeysigner should be removed from swiftmailer. Also it is marked officially as historic and obsolete https://www.ietf.org/rfc/rfc4870.txt.

**Comment by tomsommer** [comment]
Because some foolish recipients still use Domainkey as a validator :)

**Comment by tomsommer** [comment]
I will however say, that the \r\n check is ludicrous, because obviously this _can_ happen a lot, despite what the code indicates.
