### ISSUE TITLE
Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR)

### ISSUE THREAD

**Issue by PerfectNarcissism** [swiftmailer/swiftmailer#954]
Hi, I have this problem Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR)

My code is:

````
<?php

require_once 'core/swiftmailer/vendor/autoload.php';

try {
	// Create the Transport
	$transport = (new Swift_SmtpTransport('smtp.gmail.com', 587))
		->setUsername('andriu0901@gmail.com')
		->setPassword('123')
	;

	// Create the Mailer using your created Transport
	$mailer = new Swift_Mailer($transport);

	// Create a message
	$message = new Swift_Message('Wonderful Subject')
		->setFrom(['andriu0901@gmail.com' => 'John Doe'])
		->setTo(['danierick207@gmail.com' => 'A name'])
		->setBody('Here is the message itself')
		;

	// Send the message
	$result = $mailer->send($message);
	if($result){
			echo "Enviado";
	}else{
		echo "error";
	}

} catch (Exception $e) {
	echo $e;
}

 ?>
```
Someone who can help me please

**Comment by xabbuh** [comment]
You are missing a pair of parentheses when creating the `Swift_Message` object:

```php
// Create a message
$message = (new Swift_Message('Wonderful Subject'))
        ->setFrom(['andriu0901@gmail.com' => 'John Doe'])
        ->setTo(['danierick207@gmail.com' => 'A name'])
        ->setBody('Here is the message itself')
    ;
```

**Comment by PerfectNarcissism** [comment]
Thank you so much...
But I have another problem now
 Swift_TransportException: Expected response code 250 but got code "..."

**Comment by Rotzbua** [comment]
I think encryption is not set?
If there is still a wrong documentation, please correct it in the folder https://github.com/swiftmailer/swiftmailer/tree/master/doc  and make a pull request. thanks.

**Comment by rmbl** [comment]
The parentheses are also missing in the documentation at http://swiftmailer.org/docs/introduction.html#basic-usage. That should probably be fixed.

**Comment by rmbl** [comment]
It's correct in the doc folder, but still wrong on the homepage at http://swiftmailer.org/docs/introduction.html#basic-usage
