### ISSUE TITLE
SpoolTransport method send shouldn't return the boolean instead of integer ?

### ISSUE THREAD

**Issue by apodgorbunschih** [swiftmailer/swiftmailer#956]
https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Transport/SpoolTransport.php

The method send, shouldn't return boolean instead of integer? and also the phpdoc says that it returns "The number of sent e-mail's" but in reality it returns or 1 or 0.

**Comment by Rotzbua** [comment]
Please notify the `implements Swift_Transport` and the interface mention `int` as return type.
