### ISSUE TITLE
Swiftmailer wont install

### ISSUE THREAD

**Issue by StaringSnake** [swiftmailer/swiftmailer#961]
Everytime I run `$ composer require "swiftmailer/swiftmailer:^6.0"` or `$ composer require swiftmailer/swiftmailer` I get the following result:

> Using version ^6.0 for swiftmailer/swiftmailer
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - laravel/framework v5.4.27 requires swiftmailer/swiftmailer ~5.4 -> satisfiable by swiftmailer/swiftmailer[5.x-dev, v5.4.0, v5.4.1, v5.4.2, v5.4.3, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8] but these conflict with your requirements or minimum-stability.
>     - laravel/framework v5.4.27 requires swiftmailer/swiftmailer ~5.4 -> satisfiable by swiftmailer/swiftmailer[5.x-dev, v5.4.0, v5.4.1, v5.4.2, v5.4.3, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8] but these conflict with your requirements or minimum-stability.
>     - laravel/framework v5.4.27 requires swiftmailer/swiftmailer ~5.4 -> satisfiable by swiftmailer/swiftmailer[5.x-dev, v5.4.0, v5.4.1, v5.4.2, v5.4.3, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8] but these conflict with your requirements or minimum-stability.
>     - Installation request for laravel/framework (locked at v5.4.27, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.27].
> 
> 
> Installation failed, reverting ./composer.json to its original content.
> 

I have looked for hours and didnt found a single solution to my problem, do you guys now what triggers this?

**Comment by xabbuh** [comment]
Laravel does not allow to install Swiftmailer 6, you need to stick with 5.x for now.

**Comment by StaringSnake** [comment]
Thank you for clearing up the question! I was going mad about this. Well, if possible someone can close the thread. The question is solved.

**Comment by xabbuh** [comment]
As the reporter you can close it yourself. :)
