### ISSUE TITLE
Ongoing support for 5.x

### ISSUE THREAD

**Issue by jmaybury** [swiftmailer/swiftmailer#962]
First off, my apologies of there's already an answer to this somewhere, but I couldn't find it.

I see that SwiftMailer 6.0 now requires PHP 7. My question is, is there any intention to maintain the 5.x branch with critical bug fixes and security patches going forward, for lingering PHP 5 users? If so, has an end-of-life date been set? If not, are you aware of a fork or third-party distribution taking this on?

**Comment by fabpot** [comment]
We've just released new versions of the 5.x for a critical bug with recent versions of PHP. But apart from these issues, 5.x is not maintained aymore.
