### ISSUE TITLE
Got Expected response code 354 but got code "503", with message "503 Bad sequence of commands [@sm190202] " when sending emails in a loop

### ISSUE THREAD

**Issue by Andrew-Wang** [swiftmailer/swiftmailer#966]
When I send emails in a loop, I got the exception: Expected response code 354 but got code "503", with message "503 Bad sequence of commands [@sm190202]", I found there's a fix fixed this error in [mustafaileri/swiftmailer commit d289295](https://github.com/mustafaileri/swiftmailer/commit/d289295235488cdc79473260e04e3dabd2dac3ef) , could you please merge the changes in the commit?

**Comment by SamAriafar** [comment]
This issue still exists. Any explaination?!

**Comment by pcool** [comment]
I have the same issue with office365 since a few days.
The code worked perfectly before and suddenly I'm getting this error. 
Any ideas what Microsoft could have changed that causes this error?

**Comment by andreasmatu** [comment]
I am sending within a loop and get this error as well since some days.

**Comment by fidding** [comment]
I have this error because the recipient email cannot be found

**Comment by pedroresende** [comment]
Any news on this ?

**Comment by BasvanH** [comment]
We've got this because of a relaying problem, I presume it's not a code problem. Check your smtp servers logs.
