### ISSUE TITLE
DecoratorPlugin: PHP Recoverable fatal error:  Object of class DateTimeImmutable could not be converted to string

### ISSUE THREAD

**Issue by SkunkyDu52** [swiftmailer/swiftmailer#967]
Hi,
I've got an issue with the decoration of a date. I dont know if it is intentionnal or not (that i could understand because of local date  format...)
In fact, i try to decorate an element whose value is an instance of DateTime. This snippet generate the error:

```
foreach ($message->getHeaders()->getAll() as $header) {
          $body = $header->getFieldBodyModel();
                $count = 0;
                if (is_array($body)) {
                    $bodyReplaced = array();
                    foreach ($body as $key => $value) {
                        $count1 = 0;
                        $count2 = 0;
                        $key = is_string($key) ? str_replace($search, $replace,
                                        $key, $count1) : $key;
                        $value = is_string($value) ? str_replace($search,
                                        $replace, $value, $count2) : $value;
                        $bodyReplaced[$key] = $value;

                        if (!$count && ($count1 || $count2)) {
                            $count = 1;
                        }
                    }
                } else {
                    $bodyReplaced = str_replace($search, $replace, $body, $count);
                }
```

In my case, $body isnt an array then pass in the str_replace. As it is not a string but an object, i got the following error:
 PHP Recoverable fatal error:  Object of class DateTimeImmutable could not be converted to string in ...\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Plugins\DecoratorPlugin.php

Will you do something about that? I corrected it like that:
```
foreach ($message->getHeaders()->getAll() as $header) {
                $body = $header->getFieldBodyModel();
                if ($body instanceof \DateTimeImmutable) {
                    $body = $body->format('Y-m-d H:i');
                }
```

But, as you can expect, i dislike to change things in vendor...
Thanks in advance for you repply,

Maxime

**Comment by HanXHX** [comment]
I confirm this issue. PHP version: 7.0.19 and and swiftmailer: 6.0.1


```php
        $replacements = [
            'blah@bloh.com' => [
                '{firstname}' => 'Foo',
                '{link}' => 'http://bar.com'
            ]
        ];

        $emailer->registerPlugin( new \Swift_Plugins_DecoratorPlugin($replacements));
        $emailer->send($message); // crash
```

**Comment by pbarney** [comment]
I'm having the same problem. Has anyone come up with a solution?

As far as I can tell, the decorator is jumping through each line of the headers looking for strings to replace but is failing when it comes to this DateTimeImmutable object because it's not a string.

**Comment by pbarney** [comment]
Can someone Replace line 114 of `lib\classes\Swift\Plugins\DecoratorPlugin.php` with:

`                } elseif (is_string($body) || (is_object($body) && method_exists($body, '__toString' ))) {`

**Comment by Rotzbua** [comment]
@pbarney Is this a fix? If yes can you make a pull request?
