### ISSUE TITLE
Having "Fatal error: Uncaught ReflectionException"

### ISSUE THREAD

**Issue by kevindavis338** [swiftmailer/swiftmailer#968]
Hi there,

I'm getting the following error:

PHP Fatal error:  Uncaught ReflectionException: Class Egulias\\EmailValidator\\EmailValidator does not exist in /var/www/html/mailer/swift/lib/classes/Swift/DependencyContainer.php:309\nStack trace:\n#0 /var/www/html/mailer/swift/lib/classes/Swift/DependencyContainer.php(309): ReflectionClass->__construct('Egulias\\\\EmailVa...')\n#1 /var/www/html/mailer/swift/lib/classes/Swift/DependencyContainer.php(323): Swift_DependencyContainer->createNewInstance('email.validator')\n#2 /var/www/html/mailer/swift/lib/classes/Swift/DependencyContainer.php(114): Swift_DependencyContainer->createSharedInstance('email.validator')\n#3 /var/www/html/mailer/swift/lib/classes/Swift/DependencyContainer.php(371): Swift_DependencyContainer->lookup('email.validator')\n#4 /var/www/html/mailer/swift/lib/classes/Swift/DependencyContainer.php(348): Swift_DependencyContainer->lookupRecursive('email.validator')\n#5 /var/www/html/mailer/swift/lib/classes/Swift/DependencyContainer.php(129): Swift_DependencyContainer->resolveArgs(Array)\n#6 /var/www/html/mailer/swift/lib/ in /var/www/html/mailer/swift/lib/classes/Swift/DependencyContainer.php on line 309

Here is my code:

     require_once 'swift/lib/swift_required.php';
     $transport = new Swift_SmtpTransport('smtp.gmail.com', ***, 'ssl');
     $transport->setUsername("email@gmail.com");
     $transport->setPassword("Password");

     $mailer = new Swift_Mailer($transport);

     $message = new Swift_Message('Weekly Hours');
     $message->setTo("email@test.com" ,"To");
     $message->setFrom("email@gmail.com", From");
     $message->setSubject("Hello Joe!");
     $message->setBody ('Test Message', 'text/html');

     $result = $mailer->send($message);    

Php version: 7.0
Swiftmailer: 6.0.2 (downloaded via composer)

**Comment by Rotzbua** [comment]
The error tells you that a class is missing from:
https://github.com/egulias/EmailValidator/

**Comment by kevindavis338** [comment]
Well, I did install it and there is my composer file:

{
    "require": {
        "egulias/email-validator": "~2.0",
        "swiftmailer/swiftmailer": "^6.0"
    }
}


So even I do have have the validator installed, I'm still getting the above error.

**Comment by naumanahmad17** [comment]
@kevindavis338  i am having the same issue any solution :)

**Comment by xdecock** [comment]
Vendor/autoload.php ?

Le 22 juil. 2017 1:22 AM, "kevindavis338" <notifications@github.com> a
écrit :

**Comment by smouheb** [comment]
@kevindavis338 for me also, while it's clearly installed in the vendor folder and the composer.json  shows the same version as above... really lost for the moment

**Comment by sstok** [comment]
` require_once 'swift/lib/swift_required.php';` is not enough you need to require the `vendor/autoload.php` file also else only Swift Mailer classes can be auto-loaded.

**Comment by fabpot** [comment]
Closing as there is no more feedback from the reporter.
