### ISSUE TITLE
add  3D  every time after equal sign

### ISSUE THREAD

**Issue by swiftmailer** [swiftmailer/swiftmailer#97]
Hi there,
I saw that this problem is reported more as 1 year ago.

This error comes up in V 4.07 and V4.10Rc2

If I use 
$message->setBody($html, text/plain');  instead of $message->setBody($html, 'text/html');  
the html content is correct!

I added: Swift_Preferences::getInstance()->setCacheType('null');  
but the problem is the same.

<table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" width=3D"750" =align=3D"center">
 <tr>
   <td align=3D"right" colspan=3D"2">

Any idead how to fix?

Regards,
Uwe

Original creation date: 2011-06-24T22:33:06Z
Original reporter: inthanet
Original ticket: http://swiftmailer.lighthouseapp.com/projects/21527/tickets/200

**Comment by cassianotartari** [comment]
Thanks @ShawnKuan, it works!

Maybe @swiftmailer can clouse the issue now
