### ISSUE TITLE
PHP Namespaces usage

### ISSUE THREAD

**Issue by klimov-paul** [swiftmailer/swiftmailer#971]
Library class names should be refactored to use PHP namespaces.

Namespaces were introduced at PHP 5.3.
Swiftmailer 5.x requires PHP >= 5.3:
https://github.com/swiftmailer/swiftmailer/blob/v5.4.8/composer.json#L18 
Swiftmailer 6.x requires PHP >= 7.0:
https://github.com/swiftmailer/swiftmailer/blob/v6.0.0/composer.json#L18 

Pros:
- a PHP library without namespaces looks outdated as namespace usage considered a practice, which good library should follow
- using namespaces you can rely on Composer autoloader like ‘PSR-4’, making such files as `swift_required.php` to be redundant
- using namespaced based class autoloading (e.g. ‘PSR-4’) will increase performance comparing with current custom autoload implementation.

For the namespace root `swiftmailer` or `swift` can be used. Thus definition of class `Swift` will look like following:

```php
namespace swiftmailer;

abstract class Swift
{
    // …
}
```

Definition of `Swift_Transport_SendmailTransport` will look like:

```php

namespace swiftmailer\transport;

class Sendmail extends AbstractSmtp
{
    // …
}
```

To keep BC and support migration to the namespace usage, you can create aliases for the old class names for the most-used classes. For example:

```php
class Swift_Transport_SendmailTransport extends \swiftmailer\transport\Sendmail
{
}
```

Even one of the most conservative libraries – PHPUnit – has already migrated to namespaces usage.
It would be a shameful if swiftmailer 7.x will not.

**Comment by Rotzbua** [comment]
This was mentioned in #566 and was rejected by owner see https://github.com/swiftmailer/swiftmailer/issues/566#issuecomment-302747726 .

**Comment by klimov-paul** [comment]
Shameful...
:disappointed:

**Comment by sstok** [comment]
@fabpot as this was done for Twig can we reconsider this for SwiftMailer?

**Comment by jaikdean** [comment]
Since SwiftMailer is often used in Symfony projects, there is a tangible benefit of adding namespaces. It enables autowiring without specifying service classes in the Symfony DI container.

**Comment by Soullivaneuh** [comment]
I think it worth it. Plus, it will fix bench of weird issue with custom auto-loading such as this one: https://github.com/maglnet/ComposerRequireChecker/issues/55#issuecomment-370135553

**Comment by razvanioan** [comment]
This is frustrating !

How can I use SwiftMailer from a custom class which is namespaced (like entire project) ?
I cannot make it recognize the class / methods from Swift

**Comment by fabpot** [comment]
Closing as the namespaced version of Swiftmailer is now available... as Symfony Mailer.
