### ISSUE TITLE
Array short syntax usage for >= 6.0

### ISSUE THREAD

**Issue by klimov-paul** [swiftmailer/swiftmailer#972]
Swiftmailer 6.x requires PHP >= 7.0:
https://github.com/swiftmailer/swiftmailer/blob/v6.0.0/composer.json#L18

It would be nice if you switch to array short syntax all over the code for new versions.
Array short syntax has been introduced at PHP 5.4.

Compare:

```php
$buffer->initialize(array_merge($this->params, array('command' => $command)));

if (false === strpos($command, ' -i') && false === strpos($command, ' -oi')) {
    $buffer->setWriteTranslations(array("\r\n" => "\n", "\n." => "\n.."));
} else {
    $buffer->setWriteTranslations(array("\r\n" => "\n"));
}
```

with:

```php
$buffer->initialize(array_merge($this->params, ['command' => $command]));

if (false === strpos($command, ' -i') && false === strpos($command, ' -oi')) {
    $buffer->setWriteTranslations(["\r\n" => "\n", "\n." => "\n.."]);
} else {
    $buffer->setWriteTranslations(["\r\n" => "\n"]);
}
```

Usage of the array shot syntax make source code much more readable.

**Comment by Rotzbua** [comment]
I personally do not see a big readability advantage for short syntax but feel free to make a pull request. 👍

**Comment by klimov-paul** [comment]
I can do this, but you should aware that such PR will affect almost all source files, so the result diff will be hard to navigate and review. Such kind of changes usually better to be performed by someone with direct commit priviledges.
I can open a PR, but I need a confirmation from core team until I begin.

**Comment by sstok** [comment]
The problem with this type of changes is dealing with merge conflicts, Symfony for example decided to not use the new short-array language until 2.8 becomes end of life.

I'm not aware of the BC policy of Swift Mailer, but if 5.x is not not maintained anymore this change should be possible.

**Comment by fabpot** [comment]
Done now that the 5.x branch is not maintained anymore.
