### ISSUE TITLE
Wrongly documented return types for header info related methods

### ISSUE THREAD

**Issue by akeeman** [swiftmailer/swiftmailer#976]
It looks like the documented return types for header related methods are getting messy. For instance [Swift_Mime_SimpleMessage::getReplyTo](https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Mime/SimpleMessage.php#L285) should [return a string](https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Mime/SimpleMessage.php#L283) according to the documentation, while it does return an array or null (and maybe a string, I haven't checked).

**Comment by Rotzbua** [comment]
@akeeman Can you make a pull request?
