### ISSUE TITLE
Version 5.x documentation download as PDF

### ISSUE THREAD

**Issue by shoulders** [swiftmailer/swiftmailer#978]
Hi

I would like to get a copy of the version 5.x documentation as a PDF but there is no where to download it. 

You can get the latest version but that covers only the 6.x range which is only for php 7.0 which a lot of people do not have.

thanks

**Comment by Rotzbua** [comment]
Just use the amazing Wayback Machine of archive.org ;-)
https://web.archive.org/web/20161119020136/http://swiftmailer.org:80/pdf/Swiftmailer.pdf

**Comment by shoulders** [comment]
@Rotzbua 

Thanks, just what i was looking for.
