### ISSUE TITLE
addIdHeader() produces duplicate Message-ID header

### ISSUE THREAD

**Issue by ThomasLandauer** [swiftmailer/swiftmailer#984]
When adding a `Message-ID` header with `$message->getHeaders()->addIdHeader('Message-ID', 'foo@example.com');` the resulting email has two (!) `Message-ID`s:
* the one automatically created by Swift Mailer
* the one being passed into `addIdHeader()`

**Comment by Rotzbua** [comment]
Swiftmailer version?
PHP version?

**Comment by ThomasLandauer** [comment]
swiftmailer/swiftmailer v6.0.1
PHP Version 7.0.14
