### ISSUE TITLE
Documentation: ID Header section is confusing

### ISSUE THREAD

**Issue by ThomasLandauer** [swiftmailer/swiftmailer#985]
First: Is this the right place to report errors in the docs https://swiftmailer.symfony.com/docs/introduction.html ? No repo to submit a PR?

It's about https://swiftmailer.symfony.com/docs/headers.html#id-headers

* Minor typo: "Changing the value of an existing date header is done by calling its setId() method" => "of an existing **ID** header"
* Major: IMO, The entire section is overly complicated. Most people probably just want to set the `Message-ID` header, nothing else. I mean: Who uses a custom ID header? What for?  
Also the text keeps switching between talking about the "official" `Message-ID` and those custom ID-headers. When following the examples, it can lead to this issue: https://github.com/swiftmailer/swiftmailer/issues/984  
So I think the entire section should be re-written completely.

**Comment by Rotzbua** [comment]
Documentation path to make a pr: https://github.com/swiftmailer/swiftmailer/tree/master/doc

**Comment by ThomasLandauer** [comment]
I'm closing this, since Swift Mailer is going to be replaced by [Symfony Mailer](https://symfony.com/doc/master/mailer.html).
