### ISSUE TITLE
Expected response code 250 but got code "552"

### ISSUE THREAD

**Issue by wout** [swiftmailer/swiftmailer#989]
| Q                   | A
| ------------------- | -----
| Bug report?         | ~~yes~~/no
| Feature request?    | ~~yes~~/no
| RFC?                | ~~yes~~/no
| How used?           | Standalone/~~Symfony~~/~~3party~~
| Swiftmailer version | 5.4.8
| PHP version         | 5.6.25

### Observed behaviour
I am using Expected response code 250 but got code "552", with message "552 message line is too long "

### Question
I was just wondering where this error comes from. Is it straight from the mail server? Or is this a SwiftMailer error? Also, is this related to a body parameter that's too big?

**Comment by Rotzbua** [comment]
It comes from the mail server. So yes your mail is too big. Did you attached a lot?

**Comment by muhammadtaqi** [comment]
I face similer issue when attached file size of Bigger then the limit like 

`->attach(\Swift_Attachment::fromPath($this->get('kernel')->getRootDir(). "/../web/".'invoice.pdf'))`

> got code "552", with message "552-5.2.3 Your message exceeded Google's message size limits. Please visit 552-5.2.3  https://support.google.com/mail/?p=MaxSizeError to view our size 552 5.2.3 guidelines.

**Comment by fabpot** [comment]
Closing, as there is no bug in Swiftmailer.
