### ISSUE TITLE
[Doc] `mysql_*` functions are mentioned in Decorator plugin

### ISSUE THREAD

**Issue by Oire** [swiftmailer/swiftmailer#994]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Standalone
| Swiftmailer version | 6.0
| PHP version         | 7.1

### Observed behaviour

Steps to reproduce:

1. Open the [plugin docs](https://swiftmailer.symfony.com/docs/plugins.html) page.
2. Go to the Decorator plugin section. Note that there a bunch of `mysql_*` calls are quoted in the examples.

### Expected behaviour

As `mysql_*` functions are removed from PHP 7, the docs should be rewritten to use, e.g., PDO (much better) or `mysqli_*` (worse, as for me).

### Example

See above.

**Comment by fabpot** [comment]
Can you propose a pull request with the needed changes?

**Comment by Oire** [comment]
@fabpot, yes, sure, I will :). Just thought it would be better to open an issue beforehand.
