### ISSUE TITLE
Swift_TransportException: Process could not be started

### ISSUE THREAD

**Issue by parovchenkos** [swiftmailer/swiftmailer#997]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Standalone
| Swiftmailer version | 6.0.2
| PHP version         | 7.1.8

### Observed behaviour
The letter was supposed to go to the post office...

### Expected behaviour
The letter did not go

### Example
Stack trace:
#0 C:\OpenServer\domains\yii2-enjoy\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php(58): Swift_Transport_StreamBuffer->establishProcessConnection()
#1 C:\OpenServer\domains\yii2-enjoy\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(126): Swift_Transport_StreamBuffer->initialize(Array)
#2 C:\OpenServer\domains\yii2-enjoy\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\SendmailTransport.php(52): Swift_Transport_AbstractSmtpTransport->start()
#3 C:\OpenServer\domains\yii2-enjoy\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mailer.php(67): Swift_Transport_SendmailTransport->start()
#4 C:\OpenServer\domains\yii2-enjoy\vendor\yiisoft\yii2-swiftmailer\Mailer.php(150): Swift_Mailer->send(Object(Swift_Message))
#5 C:\OpenServer\domains\yii2-enjoy\vendor\yiisoft\yii2\mail\BaseMailer.php(263): yii\swiftmailer\Mailer->sendMessage(Object(yii\swiftmailer\Message))
#6 C:\OpenServer\domains\yii2-enjoy\vendor\yiisoft\yii2\mail\BaseMessage.php(49): yii\mail\BaseMailer->send(Object(yii\swiftmailer\Message))
#7 C:\OpenServer\domains\yii2-enjoy\vendor\dektrium\yii2-user\Mailer.php(281): yii\mail\BaseMessage->send()
#8 C:\OpenServer\domains\yii2-enjoy\vendor\dektrium\yii2-user\Mailer.php(175): dektrium\user\Mailer->sendMessage('parovchenkos+1@...', '\xD0\x94\xD0\xBE\xD0\xB1\xD1\x80\xD0\xBE \xD0\xBF\xD0\xBE...', 'welcome', Array)
#9 C:\OpenServer\domains\yii2-enjoy\vendor\dektrium\yii2-user\models\User.php(329): dektrium\user\Mailer->sendWelcomeMessage(Object(dektrium\user\models\User), Object(dektrium\user\models\Token))
#10 C:\OpenServer\domains\yii2-enjoy\vendor\dektrium\yii2-user\models\RegistrationForm.php(112): dektrium\user\models\User->register()
#11 C:\OpenServer\domains\yii2-enjoy\vendor\dektrium\yii2-user\controllers\RegistrationController.php(136): dektrium\user\models\RegistrationForm->register()
#12 [internal function]: dektrium\user\controllers\RegistrationController->actionRegister()
#13 C:\OpenServer\domains\yii2-enjoy\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#14 C:\OpenServer\domains\yii2-enjoy\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 C:\OpenServer\domains\yii2-enjoy\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('register', Array)
#16 C:\OpenServer\domains\yii2-enjoy\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('user/registrati...', Array)
#17 C:\OpenServer\domains\yii2-enjoy\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#18 C:\OpenServer\domains\yii2-enjoy\frontend\web\index.php(15): yii\base\Application->run()
#19 {main}

**Comment by sstok** [comment]
It seems you are not using Swiftmailer as a standalone but as part of the Yii2 framework.

You provided the stack trace but not the actual error message.
Please provide more information including which transporter you are using, and what exact error message you get.

**Comment by fabpot** [comment]
Closing as there is no more feedback from the reporter.
