### ISSUE TITLE
addpart() strtolower() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by MordiSacks** [swiftmailer/swiftmailer#998]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | yes/no
| How used?           | Standalone within laravel 5.4
| Swiftmailer version | 5.4.8
| PHP version         | 7.1.6

### Observed behaviour
`$swiftMsg->addPart($plainText);`
throws error 
> strtolower() expects parameter 1 to be string, array given

> vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php line 746

### Expected behaviour
add a part to the message

### Example
`$swiftMsg->addPart($plainText);`

**Comment by xabbuh** [comment]
Well, `addPart()` is documented to expect a string or an instance of `Swift_OutputByteStream` as the first argument:

```php
/**
     * Add a MimePart to this Message.
     *
     * @param string|Swift_OutputByteStream $body
     * @param string                        $contentType
     * @param string                        $charset
     *
     * @return $this
     */
```

Thus, you will need to check why `$plainText` is an array in your code and fix that accordingly.

**Comment by MordiSacks** [comment]
@xabbuh `$plainText` is string verified, I noticed that if I don't use `$swiftMsg->embed()` in my body, it does work, 
in xdebug I can see that I have 4 mimes 
* text/html
* text/plain
* image/jpeg
* image/jpeg, but when `$child->getContentType()` is called (\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mime\SimpleMimeEntity.php:746) it returns an array of the from address `'sample@example.com' = null`

**Comment by xabbuh** [comment]
Can you provide a small example project that allows to reproduce your issue?

**Comment by MordiSacks** [comment]
@xabbuh 
composer.json
```json
{
    "require": {
        "swiftmailer/swiftmailer": "^6.0",
        "myclabs/deep-copy": "^1.6"
    }
}

```

index.php
```php
<?php
/**
 * Swiftmailer issue reproduce
 *
 * @link https://github.com/swiftmailer/swiftmailer/issues/998
 */
require_once('vendor/autoload.php');

$htmlMessage = file_get_contents('https://pastebin.com/raw/22YYxVe0');

/** Create the message */
$swiftMsg = new \Swift_Message();

$swiftMsg->setFrom('foo@example.com', '')
         ->setSubject('Nebucadnezar II');

// if this section is cemented out and setBody (line 23) uses $htmlMessage, then the message is sent
$embeddedHTML = preg_replace_callback('/(<img.*src=["\'])(.+)(["\'].*>)/Uis', function ($matches) use ($swiftMsg) {
    return $matches[1] . $swiftMsg->embed(\Swift_Image::fromPath($matches[2])) . $matches[3];
}, $htmlMessage);


$swiftMsg->setBody($embeddedHTML, 'text/html');

$tos = [
    'a@example.com',
    'b@example.com',
    'c@example.com',
];

$dp = new \DeepCopy\DeepCopy();

foreach ($tos as $to) {
    $msgObj = $dp->copy($swiftMsg);

    $msgObj->addTo('bar@example.com');

    /**
     * Mailhog
     * @link https://github.com/mailhog/MailHog
     */
    $transport = (new Swift_SmtpTransport())->setHost('127.0.0.1')->setPort(1025);

    $mailer = new Swift_Mailer($transport);

    $mailer->send($msgObj);
}

```
this is the minimal code needed to reproduce the issue, I think now that the issue is related to DeepCopy, and not swiftmailer.
